import type { CourseDefinition } from '../../registry';
import { marketBasicsGlossary } from './glossary';

export const marketBasicsDefinition: CourseDefinition = {
  info: {
    id: 'how-exchanges-work',
    eyebrow: 'Trading von null · Kapitel 1–11 verfügbar',
    title: 'Wie Börsen funktionieren',
    subtitle: 'Ein Einführungskurs ohne vorausgesetztes Tradingwissen. Verstehe Produkte, Marktteilnehmer, Handelsplätze, Auktionen, Orderbuch, Liquidität, Preisbewegungen, Handelszeiten, besondere Handelsphasen und Abwicklung; weitere Kapitel folgen.',
    sourceOrderNotice: 'Lerne die Grundlagen schrittweise. Aktuell sind Kapitel 1 bis 11 verfügbar; der Kurs wird weiter aufgebaut.',
  },
  units: [{
    id: 'how-exchanges-work.chapter-01',
    order: 1,
    kind: 'chapter',
    label: 'Kapitel 1',
    title: 'Handel, Preise und Teilnehmer',
    description: 'Was gehandelt wird, warum Menschen handeln und wie Angebote, Preise und verfügbare Menge zusammenhängen.',
    estimatedLessonCount: 12,
    load: () => import('./chapter-01').then((m) => m.marketBasicsChapterOneLessons),
  }, {
    id: 'how-exchanges-work.chapter-02',
    order: 2,
    kind: 'chapter',
    label: 'Kapitel 2',
    title: 'Was genau wird gehandelt?',
    description: 'Aktien, Anleihen, Fonds und ETFs, Währungen sowie Derivate von Grund auf: Rechte, Pflichten, Preisbezug und eigene Rechenbeispiele.',
    estimatedLessonCount: 24,
    load: () => import('./chapter-02').then((m) => m.marketBasicsChapterTwoLessons),
  }, {
    id: 'how-exchanges-work.chapter-03',
    order: 3,
    kind: 'chapter',
    label: 'Kapitel 3',
    title: 'Wer handelt und warum?',
    description: 'Privatanleger, Fonds, Unternehmen, Banken, Market Maker und weitere Rollen: Handelsmotive, Zeithorizonte und eigene Fallbeispiele.',
    estimatedLessonCount: 22,
    load: () => import('./chapter-03').then((m) => m.marketBasicsChapterThreeLessons),
  }, {
    id: 'how-exchanges-work.chapter-04',
    order: 4,
    kind: 'chapter',
    label: 'Kapitel 4',
    title: 'Wo findet Handel statt?',
    description: 'Börsen, außerbörslicher Handel und verschiedene Ausführungswege: Zugang, Datenquelle, Angebote, Mengen und Kosten richtig unterscheiden.',
    estimatedLessonCount: 21,
    load: () => import('./chapter-04').then((m) => m.marketBasicsChapterFourLessons),
  }, {
    id: 'how-exchanges-work.chapter-05',
    order: 5,
    kind: 'chapter',
    label: 'Kapitel 5',
    title: 'Der Markt als Auktion',
    description: 'Handelswünsche, Preisgrenzen, verfügbare Mengen und Ausführungen: fortlaufender Handel und eine eigene Sammelauktion Schritt für Schritt.',
    estimatedLessonCount: 20,
    load: () => import('./chapter-05').then((m) => m.marketBasicsChapterFiveLessons),
  }, {
    id: 'how-exchanges-work.chapter-06',
    order: 6,
    kind: 'chapter',
    label: 'Kapitel 6',
    title: 'Das Orderbuch verstehen',
    description: 'Kauf- und Verkaufsseite, Markttiefe und Warteschlange: eigene Mengenrechnungen, Buchänderungen und die Grenzen sichtbarer Daten.',
    estimatedLessonCount: 24,
    load: () => import('./chapter-06').then((m) => m.marketBasicsChapterSixLessons),
  }, {
    id: 'how-exchanges-work.chapter-07',
    order: 7,
    kind: 'chapter',
    label: 'Kapitel 7',
    title: 'Liquidität und Markttiefe',
    description: 'Handelbarkeit für eine konkrete Menge: Spread, Tiefe, Preisabweichungen und Kosten mit eigenen Rechnungen und klaren Grenzen der Daten.',
    estimatedLessonCount: 22,
    load: () => import('./chapter-07').then((m) => m.marketBasicsChapterSevenLessons),
  }, {
    id: 'how-exchanges-work.chapter-08',
    order: 8,
    kind: 'chapter',
    label: 'Kapitel 8',
    title: 'Warum bewegen sich Preise?',
    description: 'Aufträge, Nachrichten und Erwartungen: Preisarten, Rechenfälle und Zeitfolgen unterscheiden, ohne unbekannte Motive oder sichere Kursrichtungen zu erfinden.',
    estimatedLessonCount: 24,
    load: () => import('./chapter-08').then((m) => m.marketBasicsChapterEightLessons),
  }, {
    id: 'how-exchanges-work.chapter-09',
    order: 9,
    kind: 'chapter',
    label: 'Kapitel 9',
    title: 'Handelszeiten und Sessions',
    description: 'Kalender, Zeitzonen und Sommerzeit: eigene Zeitrechnungen, Sessiongrenzen und die Unterschiede zwischen App-Zugang, Auftragsannahme und Ausführung.',
    estimatedLessonCount: 24,
    load: () => import('./chapter-09').then((m) => m.marketBasicsChapterNineLessons),
  }, {
    id: 'how-exchanges-work.chapter-10',
    order: 10,
    kind: 'chapter',
    label: 'Kapitel 10',
    title: 'Besondere Handelsphasen',
    description: 'Eröffnungs- und Schlussauktion, Schutzphasen und Wiederaufnahme: eigene Preis- und Mengenrechnungen, vorläufige Anzeigen, Zuteilung und bestätigten Auftragsstatus unterscheiden.',
    estimatedLessonCount: 22,
    load: () => import('./chapter-10').then((m) => m.marketBasicsChapterTenLessons),
  }, {
    id: 'how-exchanges-work.chapter-11',
    order: 11,
    kind: 'chapter',
    label: 'Kapitel 11',
    title: 'Was passiert nach dem Trade?',
    description: 'Ausführungsbericht, Clearing, Verrechnung und Settlement: eigene Mengen-, Geld- und Kalenderrechnungen, Verwahrung, Sicherheiten und bestätigte Abwicklungszustände.',
    estimatedLessonCount: 24,
    load: () => import('./chapter-11').then((m) => m.marketBasicsChapterElevenLessons),
  }],
  glossary: { title: 'Marktgrundlagen-Glossar', entries: marketBasicsGlossary },
};
