import { chapterSevenLesson, type ChapterSevenDraft } from './chapter-07-model';

// Figure references identify the discussion, not a reproduction of its chart.
const drafts: ChapterSevenDraft[] = [
  {
    number: 12, title: 'Fall 7.1: Outside-Up im starken Bärentrend',
    summary: 'Eine auffällige Gegenkerze bleibt ohne tragfähigen Käuferanschluss.',
    section: 'Chartfall 7.1',
    anchors: ['Abbildung 7.1 · Outside-Bars im Bärentrend', 'Bar 1 · erster Rücklauf nach dem Open', 'Starker Bärenbar nach Outside-Up'],
    scenario: 'c07-figure-71-trend',
    paragraphs: [
      'Der Tag beginnt mit einem Bruch unter das Vortagestief und einem deutlichen Bärenbar. In dieser Lage schafft der erste kleine Rücklauf noch keine Umkehr. Der folgende Outside-Up-Bar sieht zwar bullisch aus, steht aber gegen die gerade etablierte Richtung.',
      'Statt ihn über seinem Hoch zu kaufen, kann man prüfen, ob der Markt unter seiner unteren Grenze weiterverkauft wird. Im besprochenen Fall schließt der nächste Bar stark bärisch. Erst dieser Folgeschritt macht sichtbar, dass die Verkäufer den Gegenversuch zurückgewiesen haben.',
      'Ein späterer zweibeiniger Rücklauf zum gleitenden Durchschnitt liefert einen anderen Short-Kontext. Der Fall verbindet damit zwei Gedanken: Ein einzelner Outside-Up-Bar neutralisiert keinen starken Trend, und eine spätere Korrektur kann eine deutlich bessere Informationslage schaffen.',
    ],
    callout: 'Der erste Gegenbar im neuen Trend braucht Belege, bevor er als Wende gilt.',
    diagramTitle: 'Außenbar gegen frischen Abwärtsdruck',
    caption: 'Eigenes Schema: starker Bärenstart, kurzer Outside-Up-Rücklauf und erneuter Verkauf mit Folgebalken.',
    observations: ['Vor dem Outside-Bar ist bereits Verkaufsdruck sichtbar.', 'Der Käuferbruch oben erhält keinen Anschluss.', 'Der nächste starke Bärenbar bestätigt zunächst die Trendseite.'],
    prompt: 'Ein Outside-Up-Bar ist der erste Rücklauf nach einem kräftigen Bärenstart. Der nächste Bar schließt tief. Welche Lesart gewinnt?',
    answers: [['Die Käufer haben nun sicher einen neuen Trend.', 'Der Anschluss spricht gerade nicht dafür.'], ['Der Gegenversuch war schwach; die Bärenfortsetzung bleibt zu prüfen.', 'Richtig. Die Folge ordnet den Outside-Bar ein.'], ['Jeder Outside-Bar verlangt einen Kauf über seinem Hoch.', 'Der Marktort widerspricht dem Automatismus.']], correct: 1,
    takeaways: ['Trendkontext wiegt mehr als die Kerzenfarbe.', 'Der nächste Bar kann den Gegenversuch entkräften.', 'Spätere Pullbacks sind eigene Setups.'],
  },
  {
    number: 13, title: 'Fall 7.1: Großes ioi in seitlicher Bewegung',
    summary: 'Die innere Folgekerze bleibt zu breit für einen guten Ausbruch nahe der Range-Grenze.',
    section: 'Chartfall 7.1',
    anchors: ['Abbildung 7.1 · Bar 5 Outside-Down', 'Große Inside-Folgekerze · ioi', 'Seitliche Überlappung nach Trendphase'],
    scenario: 'c07-figure-71-range',
    paragraphs: [
      'Später im selben Chart überlappen mehrere Bars. Bar 5 erweitert die Spanne nach unten, doch sein Auftreten verwandelt die seitliche Phase nicht automatisch in einen neuen Bärenspike. Die anschließende Inside-Kerze vervollständigt eine ioi-Folge.',
      'Weil dieser letzte Innenbar selbst relativ groß ist, liegen seine Ausbruchsmarken ungünstig: Ein Verkauf darunter kann schon nahe am unteren Ende der Gesamtzone stattfinden; ein Kauf darüber nahe am oberen Ende. Die sichtbare Form liefert hier wenig Raum bis zur jeweiligen Gegenseite.',
      'Der richtige Vergleich gilt nicht „ioi gegen kein ioi“, sondern „Auslösung mit Platz und Anschluss gegen Auslösung an einer alten Range-Grenze“. Ohne besseren Ort kann man auf einen kleineren Randtest, einen Fehlausbruch oder eine neue gerichtete Folge warten.',
    ],
    callout: 'Ein großes ioi innerhalb der Range macht beide Einstiegspreise unbequem.',
    diagramTitle: 'Außen nach unten, innen in der Mitte',
    caption: 'Die selbst entworfene Spannenfolge bleibt in einer größeren seitlichen Zone; der letzte Inside-Bar ist breit.',
    observations: ['Der Outside-Bar entsteht nach Überlappung.', 'Der letzte Innenbar verengt die Gesamtzone nur wenig.', 'Ein Bruch kann am entgegengesetzten Range-Rand starten.'],
    prompt: 'Warum ist der Ausbruch aus einem großen Inside-Bar nach Outside-Down mitten in der Range problematisch?',
    answers: [['Weil Inside-Bars nie auslösen.', 'Auch sie können Auslöser sein, aber der Ort zählt.'], ['Weil beide Trigger nah an äußeren Range-Zonen liegen können.', 'Richtig. Zielraum und Risiko sind ungünstig.'], ['Weil die vorherige Trendrichtung keinen Einfluss haben darf.', 'Die Vorgeschichte bleibt relevant.']], correct: 1,
    takeaways: ['Die Marktphase kann sich innerhalb eines Charts ändern.', 'ioi ist ohne Ort und Größe unvollständig beurteilt.', 'Warten schützt vor Ausbrüchen am falschen Range-Ende.'],
  },
  {
    number: 14, title: 'Fall 7.2: Der erste ioi-Ausbruch scheitert',
    summary: 'Ein Long nahe der oberen Range-Grenze wird von einer kleinen Gegenkerze entkräftet.',
    section: 'Chartfall 7.2',
    anchors: ['Abbildung 7.2 · ioi nach Bar 1', 'Fehlgeschlagener Long-Ausbruch an Bar 2', 'Kleiner Signal-Bar am Range-Hoch'],
    scenario: 'c07-figure-72-failed-ioi',
    paragraphs: [
      'Der Auftakt versucht zunächst, über ein altes Hoch auszubrechen, kehrt aber zurück und zeigt Verkäufer. Eine große Outside-Spanne und der folgende Innenbar bilden anschließend ioi. Der Käuferbruch über die kleine Innengrenze erscheint in dieser Lage verführerisch, beginnt jedoch hoch in einer unruhigen Zone.',
      'Der Bruch hält nicht. Ein kleiner Bar nahe dem oberen Bereich wird zum konkreten Gegenpunkt: Unter ihm müssen enttäuschte Käufer ihre Position neu prüfen, während Verkäufer einen Fehlausbruch am Range-Rand sehen. Anders als beim großen ioi-Bar ist die Risikostrecke des kleinen Bars leichter zu beurteilen.',
      'Ein Short ist damit eine Reaktion auf den gescheiterten Long und den guten Ort des späteren Bars, nicht eine Wette allein auf das Kürzel ioi. Auch hier muss die Bewegung nach unten tatsächlich Raum und Anschluss haben.',
    ],
    callout: 'Der gescheiterte erste Bruch und ein kleiner Bar am Rand sind mehr Information als die ioi-Form allein.',
    diagramTitle: 'Käuferbruch am oberen Rand fällt zurück',
    caption: 'Eigenes Schema: ein breites ioi führt kurz nach oben; ein kleiner Bar am Rand bietet den späteren Gegen-Trigger.',
    observations: ['Der erste Long entsteht nahe der oberen Zone.', 'Die neue Höhe wird nicht gehalten.', 'Der kleinere Folgebar markiert eine präzisere Gegenentscheidung.'],
    prompt: 'Ein ioi-Long oberhalb einer großen Range-Spanne fällt sofort zurück. Ein kleiner Bar liegt am oberen Rand. Was ist die neue Information?',
    answers: [['Das ioi garantiert noch einen zweiten Long.', 'Der erste Bruch ist bereits gescheitert.'], ['Es gibt einen erkennbaren Fehlausbruch und eine engere mögliche Short-Grenze.', 'Richtig. Reihenfolge und Ort tragen die These.'], ['Die Range-Unterkante liegt zwingend nur einen Tick entfernt.', 'Die tatsächliche Strecke muss im Chart geprüft werden.']], correct: 1,
    takeaways: ['Ein ioi-Ausbruch kann sofort scheitern.', 'Kleine Folgekerzen am Rand können klarere Grenzen bieten.', 'Nicht gegen den sichtbaren Rückfall am Hoch an der Form festhalten.'],
  },
  {
    number: 15, title: 'Fall 7.2: Zwei Outside-ähnliche Bars, andere Aufgaben',
    summary: 'Der erste zeigt zunehmenden Käuferdruck; der zweite eine kleine Gegenchance am Rand.',
    section: 'Chartfall 7.2',
    anchors: ['Abbildung 7.2 · Bar 4 nach drittem Tiefschub', 'Bar 5 und kleiner bärischer Inside-Bar', 'Unterschied zwischen Umkehrkraft und Rand-Short'],
    scenario: 'c07-figure-72-upper-edge',
    paragraphs: [
      'Nach mehreren Abwärtsschüben werden bullische Bars kräftiger. Ein fast außerhalb des Vorbars liegender Bar mit großem Körper und kleinen Schatten kann anzeigen, dass der jüngste Verkaufsversuch Käufer gefunden hat. Das Etikett „fast outside“ ist weniger wichtig als die sichtbare Folge zunehmender Stärke.',
      'Später steht ein tatsächlicher Outside-Bar in einer seitlichen Zone. Der nächste kleine Inside-Bar sitzt nahe dem oberen Rand und schließt bärisch. Hier lässt sich eine Gegenbewegung nach unten aus dem Ort und der kleinen Auslösungsgrenze ableiten, obwohl die vorherige Außenform keine Richtung vorgibt.',
      'Die beiden Stellen gehören nicht zu einem einzigen Dauersignal. Nach jeder Bewegung muss neu geprüft werden, welche Seite zuletzt Initiative hatte, wo der nächste Bar liegt und wie viel Strecke bis zur anderen Range-Grenze bleibt.',
    ],
    callout: 'Ähnliche Außenformen können nacheinander Käuferreaktion und Rand-Short begleiten.',
    diagramTitle: 'Starker Gegenschub und späterer oberer Rand',
    caption: 'Zwei unabhängige Lehrsequenzen zeigen eine bullische Reaktion nach drittem Tiefschub und einen kleinen Bärenbar am oberen Range-Rand.',
    observations: ['Die erste Sequenz folgt wiederholtem Verkaufsdruck.', 'Die zweite steht in seitlicher Balance.', 'Der kleine bärische Innenbar liefert die präzisere Short-Grenze.'],
    prompt: 'Warum kann der kleine Innenbar nach dem späteren Outside-Bar wichtiger für einen Short sein als der Outside-Bar selbst?',
    answers: [['Er steht am oberen Rand und bietet eine engere, gerichtete Grenze.', 'Richtig. Ort und Größe verbessern die Lesbarkeit.'], ['Weil Outside-Bars grundsätzlich keinen Schluss haben.', 'Sie besitzen wie alle Bars einen Schluss.'], ['Weil die frühere bullische Stärke nie mehr relevant ist.', 'Sie bleibt Teil des Hintergrunds.']], correct: 0,
    takeaways: ['Stärkeverhältnisse ändern sich über den Tag.', 'Ein fast passendes Muster braucht keine Sonderregel.', 'Kleiner Bar am Rand kann die größere Spanne präzisieren.'],
  },
  {
    number: 16, title: 'Fall 7.2: Der erwartete Verkaufsdruck bleibt aus',
    summary: 'Doppeltest, Trendlinienbruch und höheres Tief verändern die spätere Lage.',
    section: 'Chartfall 7.2',
    anchors: ['Abbildung 7.2 · Bars 7 bis 10', 'Kleines Doppeltief nach Bärenausbruch', 'High 2 und höheres Tief nach Trendlinienbruch'],
    scenario: 'c07-figure-72-later-bottom',
    paragraphs: [
      'Nach einem kräftigen bärischen Ausbruchsbar erwartet man gewöhnlich wenigstens einen gewissen Anschluss. Stattdessen entstehen zwei nahe Tiefs, ohne dass der Verkaufsdruck zunimmt. Diese Abweichung von der Erwartung ist aussagekräftiger als die vorherige Außenform.',
      'Ein späterer Rücklauf hält erneut über dem alten Tief. In der größeren Struktur war die fallende Trendlinie zuvor gebrochen; nun entsteht ein höheres Tief. Ein High-2-Versuch innerhalb des zweibeinigen Pullbacks kann dadurch als weitere Käuferchance beurteilt werden.',
      'Das spätere Setup soll den früheren Short nicht nachträglich „falsch“ machen. Im Moment des früheren Fehlausbruchs galten andere Daten. Der Fall trainiert, den Markt nach neuen Belegen neu zu lesen und nicht die erste These bis zum Tagesende festzuhalten.',
    ],
    callout: 'Fehlender Anschluss nach einem Bärenbar ist selbst eine neue Information.',
    diagramTitle: 'Ausbruch verliert Tempo, höheres Tief entsteht',
    caption: 'Das eigene Schema zeigt einen starken Bruch, zwei nahe Tiefs und eine spätere Pullback-Basis oberhalb davon.',
    observations: ['Der Ausbruchsbar erhält keinen tieferen Schub.', 'Der Doppeltest hält die Tiefzone.', 'Nach Strukturbruch erscheint ein höheres Tief.'],
    prompt: 'Was sollte eine spätere Kaufthese nach einem starken Bärenbar zuerst stützen?',
    answers: [['Nur die alte ioi-Bezeichnung.', 'Die frühere Form sagt wenig über die neue Lage.'], ['Ein neues Tief mit immer größeren Bärenbars.', 'Das würde eher den Verkauf stärken.'], ['Fehlender Verkaufsanschluss und ein verteidigtes höheres Tief.', 'Richtig. Neue Bars ändern die Beweislast.']], correct: 2,
    takeaways: ['Erwarteten und tatsächlichen Anschluss vergleichen.', 'Ein Doppeltief allein bleibt kontextabhängig.', 'Ein höheres Tief nach Linienbruch schafft einen neuen Plan.'],
  },
  {
    number: 17, title: 'Fall 7.3: Gap-Down kehrt über Outside-Up',
    summary: 'Der neue Bar löst die alte Long-These trotz kurzem Tiefbruch aus.',
    section: 'Chartfall 7.3',
    anchors: ['Abbildung 7.3 · Eröffnung mit Gap nach unten', 'Bar 1 bullische Umkehr und Inside-Pause', 'Bar 2 Outside-Up als Einstieg'],
    scenario: 'c07-figure-73-open',
    paragraphs: [
      'Ein großer Eröffnungsabstand nach unten wirkt zunächst bärisch. Der erste Abschnitt weist die tieferen Preise aber zurück und dreht aufwärts. Nach einer kurzen Inside-Pause steht die Frage, ob die Käufer diese neue Richtung fortsetzen können.',
      'Der Folgebalken handelt zuerst unter der Pause. Ein Short an dieser schwachen Grenze findet jedoch keinen Anschluss. Als derselbe Bar über das alte Hoch läuft, löst er den schon zuvor begründeten Long aus und wird zum Outside-Up-Entry-Bar. Verkäufer unter der Pause müssen ihre Idee neu prüfen.',
      'Der gültige Grund für den Long ist die misslungene Abwärtsfortsetzung nach dem Gap samt vorheriger Käuferreaktion. Ein Outside-Bar mitten in einem beliebigen Seitwärtsmarkt hätte diese Vorgeschichte nicht. Die nächste Hürde oberhalb und die Größe des Schutzabstands bleiben zu berücksichtigen.',
    ],
    callout: 'Der Outside-Bar setzt die frühere Umkehrthese um; er erschafft sie nicht allein.',
    diagramTitle: 'Öffnungsbruch scheitert, Entry-Bar wird outside',
    caption: 'Eigenes Schema: Nach tiefer Eröffnung hält ein kleiner Rücklauf, und ein Folgebalken durchläuft beide Seiten der Pause.',
    observations: ['Das Gap erhält keinen Verkaufsanschluss.', 'Der Inside-Bar hält nach der Käuferreaktion inne.', 'Der Outside-Up-Bar löst am alten Hoch aus.'],
    prompt: 'Warum ist der Long über dem Hoch der Inside-Pause trotz kurzem Tiefbruch nachvollziehbar?',
    answers: [['Weil der Gap-Down-Versuch scheiterte und der vorherige bullische Kontext bestehen blieb.', 'Richtig. Der neue Bar bestätigt eine bestehende These.'], ['Weil jeder Inside-Bar nach einem Gap Kaufpflicht bedeutet.', 'Die Richtung ergibt sich nicht aus der Form allein.'], ['Weil der endgültige Tagestrend schon beim Open bekannt war.', 'Die weitere Tagesentwicklung war offen.']], correct: 0,
    takeaways: ['Ein Gap kann unmittelbar scheitern.', 'Ein schwacher Short-Trigger kann Käufer zusätzlich stärken.', 'Outside-Entry-Bar und ursprünglicher Signal-Bar trennen.'],
  },
  {
    number: 18, title: 'Fall 7.3: Der erste Rücklauf ist noch keine Bärenwende',
    summary: 'Ein kleiner Gegenbar an der Durchschnittslinie kann nach starker Käuferreaktion nur ein höheres Tief vorbereiten.',
    section: 'Chartfall 7.3',
    anchors: ['Abbildung 7.3 · Bar 3 am gleitenden Durchschnitt', 'Kleine bärische Umkehr gegenüber starken Bullenbars', 'Höheres Tief und bullisches ii'],
    scenario: 'c07-figure-73-higher-low',
    paragraphs: [
      'Nach dem Outside-Up-Bar steigt der Markt zum gleitenden Durchschnitt. Dort erscheint ein kleiner bärischer Umkehr-Bar. Er kann einen Short vorbereiten, aber seine geringe Größe steht neben den zuvor deutlich stärkeren Käuferkörpern.',
      'Der erste Rücklauf des neuen Aufwärtsversuchs kann deshalb eher ein höheres Tief bilden, als den ganzen Kaufimpuls zu löschen. Kurz darauf verdichten zwei Innenbars den Pullback. Ein bullischer Ausbruch daraus erhält Unterstützung durch die zuvor gewonnene Struktur.',
      'Selbst wenn jemand den frühen Short handelt, muss er den höheren Tiefversuch als Gegenargument beobachten. Die wichtigere Frage ist, ob die Käufer die Korrektur oberhalb des alten Tiefs halten und wieder Anschluss schaffen.',
    ],
    callout: 'Ein kleiner erster Gegenbar wiegt weniger, wenn die neue Käuferstruktur stark bleibt.',
    diagramTitle: 'Kleiner Short-Versuch, höheres Tief',
    caption: 'Ein unabhängiger Anstieg wird am Durchschnitt getestet und korrigiert nur bis zu einem höheren Tief mit enger Innenbar-Folge.',
    observations: ['Die jüngsten Bullenbars sind kräftig.', 'Der erste Bärenbar am Durchschnitt bleibt klein.', 'Der folgende Pullback hält oberhalb des Ausgangstiefs.'],
    prompt: 'Ein kleiner bärischer Bar folgt auf zwei starke Bullenbars der Umkehr. Was muss die Short-These mitbedenken?',
    answers: [['Die Möglichkeit, dass nur ein höheres Tief entsteht.', 'Richtig. Der erste Rücklauf ist noch kein neuer Bärentrend.'], ['Dass alle früheren Bullenbars unsichtbar werden.', 'Ihre Stärke bleibt Teil der Lage.'], ['Dass der gleitende Durchschnitt immer eine Wende erzwingt.', 'Ein Durchschnitt ist nur ein möglicher Testort.']], correct: 0,
    takeaways: ['Relative Barstärke zählt.', 'Ein erster Rücklauf kann Fortsetzung vorbereiten.', 'ii erhält Bedeutung aus der höheren Tiefstruktur.'],
  },
  {
    number: 19, title: 'Fall 7.3: oo vergrößert die Barbwire-Zone',
    summary: 'Zwei aufeinanderfolgende Outside-Bars in starker Überlappung geben nicht automatisch Richtung.',
    section: 'Chartfall 7.3',
    anchors: ['Abbildung 7.3 · Bars 4 und 5', 'Outside–Outside in Barbwire', 'Fehlgeschlagener Bruch aus enger Überlappung'],
    scenario: 'c07-figure-73-oo',
    paragraphs: [
      'Nach mehreren seitlichen Bars umschließt ein Outside-Bar seinen Vorgänger. Der nächste erweitert die Spanne abermals: oo, also outside–outside. Die zweite Kerze kann einen großen bärischen Körper besitzen und kurz unter der ersten schließen, ohne dass die gesamte überlappende Zone bereits verlassen ist.',
      'Diese dichte, wechselhafte Folge wird oft Barbwire genannt. Ein Short unter dem ersten Outside-Bar kann in der gemeinsamen Spanne gefüllt werden und dann in eine Gegenreaktion laufen. Erst ein gehaltener Bruch samt Folgebars würde zeigen, dass eine Seite aus der Balance herauskommt.',
      'Ein kleiner bullischer Folgebar nach dem gescheiterten Tiefbruch kann eine Rückkehr in die Zone signalisieren. Das ist eine neue, spezifische Beobachtung – keine Behauptung, dass jede Barbwire-Grenze immer scheitert. Später kann ein echter Ausbruch durchaus entstehen.',
    ],
    callout: 'Noch größere Außenbars können eine Range vergrößern, ohne sie zu beenden.',
    diagramTitle: 'Zwei Erweiterungen, dann Rückkehr',
    caption: 'Eigenes oo-Schema: beide großen Bars überlappen stark, ein kurzer Tiefbruch kehrt in die gemeinsame Zone zurück.',
    observations: ['Die zweite Spanne ist breiter als die erste.', 'Ein innerer Short-Trigger bedeutet noch keinen Range-Ausbruch.', 'Der kleine Folgebalken prüft die Rückkehr.'],
    prompt: 'Ein oo entsteht nach mehreren Bars mit langen Schatten und überlappenden Bereichen. Was ist die erste Einordnung?',
    answers: [['Zwei Outside-Bars garantieren einen Bärentrend.', 'Die Folge kann weiter zweiseitig bleiben.'], ['Eine vergrößerte Trading Range, bis ein Bruch hält.', 'Richtig. Überlappung dominiert zunächst.'], ['Der erste Outside-Bar muss aus dem Chart entfernt werden.', 'Beide Bars sind Teil der Struktur.']], correct: 1,
    takeaways: ['oo ist oft nur eine erweiterte Balance.', 'Inneren Trigger und äußere Range-Grenze trennen.', 'Ein Fehlausbruch erhält Gewicht durch die Rückkehr.'],
  },
  {
    number: 20, title: 'Fall 7.3: Oberer Rand und Charakter des Tages',
    summary: 'Ein später Outside-Down-Bar passt zu den vielen frühen Richtungswechseln.',
    section: 'Chartfall 7.3',
    anchors: ['Abbildung 7.3 · Bars 6 und 7', 'Swinghoch und Outside-Down-Schluss', 'Frühe Umkehrfolge als Hinweis auf Range-Tag'],
    scenario: 'c07-figure-73-day-type',
    paragraphs: [
      'Der Tag hatte bereits am Anfang mehrere Wechsel: tiefer Start, Gegenbewegung, Inside-Pause, Outside-Up und erneuter kleiner Gegenbar. Später kommen lange Schatten und wiederholte Überlappung hinzu. Diese frühe Unentschiedenheit kann auf einen Tag hindeuten, an dem beide Seiten an äußeren Grenzen handeln.',
      'Ein späterer Aufwärtsschub erreicht ein neues Swinghoch und wird in einem Outside-Down-Bar kräftig zurückgewiesen. Ein Short kann auf dem Bruch des kleinen bärischen Vorbars beginnen; wer erst den Schluss nahe dem Tief des großen Outside-Bars sieht, erhält einen stärkeren Beleg, aber möglicherweise einen weiter entfernten Schutzpunkt.',
      'Zwischen diesen Varianten liegen unterschiedliche Ausführung und Risiko. Die sinnvolle These bleibt die Zurückweisung am oberen Rand einer zweiseitigen Tagesstruktur, nicht eine allgemeine Regel, bei jedem Outside-Down-Bar zu verkaufen. Auch eine zwischenzeitliche kleine Doppeltief-Kaufchance passt zu einem solchen Tag.',
    ],
    callout: 'Die Eröffnungsstruktur kann den späteren Outside-Bar in ein zweiseitiges Tagesbild einordnen.',
    diagramTitle: 'Viele Wechsel, dann Zurückweisung am Hoch',
    caption: 'Eigene Tagesminiatur mit frühem Hin und Her und einem späteren Außenbar, der nach Hochbruch nahe dem Tief schließt.',
    observations: ['Der frühe Handel wechselt mehrfach die Richtung.', 'Der späte Anstieg trifft auf einen oberen Testbereich.', 'Der Outside-Down-Schluss zeigt dort neue Verkäuferinitiative.'],
    prompt: 'Was macht den späteren Outside-Down-Bar am Swinghoch aussagekräftiger als denselben Bar in der Range-Mitte?',
    answers: [['Die Zurückweisung eines neuen Hochs am oberen Rand der zweiseitigen Struktur.', 'Richtig. Der Ort erklärt die Gegenbewegung.'], ['Die bloße Tatsache, dass er größer als der Vorbar ist.', 'Größe ohne Ort reicht nicht.'], ['Eine sichere Prognose für den gesamten nächsten Tag.', 'Eine einzelne Kerze kann das nicht garantieren.']], correct: 0,
    takeaways: ['Frühe Richtungswechsel warnen vor einem einseitigen Tagesplan.', 'Outside-Down am Hoch kann Zurückweisung zeigen.', 'Früher Einstieg und späterer Bestätigungs-Trigger haben anderes Risiko.'],
  },
  {
    number: 21, title: 'Fall 7.4: Outside-Up als Einstieg nach zweibeinigem Pullback',
    summary: 'Vorherige Käuferkraft und ein geordneter Rücklauf begründen den Entry-Bar.',
    section: 'Chartfall 7.4',
    anchors: ['Abbildung 7.4 · Bar 3 Outside-Up', 'Zweibeiniger Pullback im Bullenlauf', 'Vorheriger bullischer Trend-Bar als Referenz'],
    scenario: 'c07-figure-74-bull-entry',
    paragraphs: [
      'Nach einem starken Bullenabschnitt korrigiert der Markt in zwei Etappen. Ein früherer kräftiger Bullenbar zeigt, dass Kaufinteresse noch nicht verschwunden ist. Wird der letzte Pullback zunächst unterboten und dreht dann über sein Hoch, kann der entstehende Outside-Up-Bar die geplante Long-Auslösung liefern.',
      'Es gibt mehr als eine Ausführung: früh über dem direkten Vorbar, vorsichtiger erst über dem Hoch des früheren starken Bullenbars oder später nach dem Schluss des Outside-Bars und dessen eigenem Hoch. Jede Variante verändert Einstiegspreis, Schutzdistanz und Sicherheit der sichtbaren Belege.',
      'Im Fall schließt der Outside-Up-Bar hoch. Das bestätigt zunächst die Käuferreaktion, macht aber die späteren Varianten nicht automatisch besser. Die Frage bleibt, wie weit ein sinnvoller Schutzpunkt entfernt ist und ob der Ausbruch noch genug freien Raum hat.',
    ],
    callout: 'Der Outside-Bar ist hier ein möglicher Einstieg nach Struktur, kein isolierter Kaufbefehl.',
    diagramTitle: 'Zwei Rücklaufbeine, drei mögliche Long-Marken',
    caption: 'Eigenes Schema markiert Vorbarhoch, früheres Bullenhoch und späteres Outside-Hoch als unterschiedliche Auslösepunkte.',
    observations: ['Ein früher starker Bullenbar bleibt im Hintergrund.', 'Der Pullback verläuft in zwei Etappen.', 'Der Outside-Up-Bar schließt hoch, aber spätere Trigger liegen weiter entfernt.'],
    prompt: 'Was ist der Unterschied zwischen Kauf über dem Vorbar und Kauf erst über dem Outside-Hoch?',
    answers: [['Keiner; beide haben denselben Einstiegspreis.', 'Die Outside-Spanne entsteht erst danach.'], ['Der spätere Trigger sieht mehr Stärke, kann aber ein größeres Preis- und Risikointervall verlangen.', 'Richtig. Das ist ein bewusster Trade-off.'], ['Der frühere Einstieg ist immer sicher.', 'Frühe Ausführung besitzt weniger Bestätigung.']], correct: 1,
    takeaways: ['Vorherige Käuferkraft stützt den Entry-Bar.', 'Mehr Bestätigung kann einen teureren Einstieg bedeuten.', 'Der Schutzort bleibt Teil jeder Variante.'],
  },
  {
    number: 22, title: 'Fall 7.4: Outside-Down fängt den High-2-Long',
    summary: 'Mehrere Bärenbars machen den Kaufversuch schwach, bevor sein Entry-Bar umschlägt.',
    section: 'Chartfall 7.4',
    anchors: ['Abbildung 7.4 · Bar 6 Outside-Down', 'Fünf bärische Körper in sechs Vorbars', 'Gescheiterter High 2 als Bullenfalle'],
    scenario: 'c07-figure-74-bear-trap',
    paragraphs: [
      'Später im selben Chart hat sich die Lage verändert: Fast alle unmittelbar vorherigen Bars schließen bärisch. Ein High-2-Zählpunkt mag optisch vorhanden sein, doch ohne vorherige Käuferstärke ist er kein guter Kaufgrund.',
      'Ein erster kleiner Anstieg kann Longs auslösen. Noch innerhalb des Entry-Bars kippt der Kurs, unterschreitet den Vorbar und schließt als Outside-Down-Bar nahe seinem Tief. Der Kauf-Einstiegsbar und der Fehlschlag liegen dicht beieinander; die gefangenen Longs müssen reagieren.',
      'Der Bar wirkt in dieser Folge eher wie ein starker bärischer Trend-Bar als wie eine harmlose Ein-Bar-Range. Das liegt an der bereits sichtbaren Bärenserie und dem gescheiterten Long, nicht daran, dass jede Outside-Down-Form automatisch Verkauf bedeutet.',
    ],
    callout: 'Eine High-2-Zählung ist ohne vorangegangene Bullenstärke kein vollständiges Setup.',
    diagramTitle: 'Long-Auslösung kippt im selben Bar',
    caption: 'Eigener Verlauf: Nach mehreren Bärenbars lockt ein kleiner Hochbruch Käufer an und schließt als kräftiger Outside-Down-Bar.',
    observations: ['Vor dem Kaufversuch dominieren bärische Schlüsse.', 'Der kleine Hochbruch erhält keinen Anschluss.', 'Der Schluss nahe dem Tief bestätigt den Fehlschlag.'],
    prompt: 'Warum ist ein High-2-Long nach fünf Bärenbars und einem Doji besonders schwach?',
    answers: [['Weil die Zahl zwei nie für Longs verwendet werden darf.', 'Die Zählung kann relevant sein, braucht aber Kontext.'], ['Weil der Markt zuvor kaum Käuferstärke für die Trendlinie oder ein erstes Bein gezeigt hat.', 'Richtig. Die notwendige Vorgeschichte fehlt.'], ['Weil ein Outside-Bar keine Short-Falle bilden kann.', 'Die Form lässt verschiedene Ausgänge zu.']], correct: 1,
    takeaways: ['Zählung allein ersetzt keinen Kaufdruck.', 'Ein Entry-Bar kann sofort zur Falle werden.', 'Bärenserie und tiefer Outside-Schluss gehören zusammen.'],
  },
  {
    number: 23, title: 'Fall 7.4: Erst zweites Signal nach Verkaufsklimax',
    summary: 'Ein frühes mögliches Tief braucht nach starkem Verkauf zusätzliche Bestätigung.',
    section: 'Chartfall 7.4',
    anchors: ['Abbildung 7.4 · früher Verkaufsklimax', 'Höheres Tief als späteres Kaufsignal', 'Trendlinienbruch und Test des alten Hochs'],
    scenario: 'c07-figure-74-second-signal',
    paragraphs: [
      'Der frühe Markt unterschreitet eine alte Seitwärtszone. Trotz eines anfänglichen Bullenbars mit oberem Schatten setzen sich Verkäufer durch, und ein beschleunigter Abverkauf erreicht ein mögliches Extrem. Das erste Zeichen eines Tiefs ist in einem so kräftigen Verkauf noch wenig belastbar.',
      'Erst nach weiterem Verlauf entsteht ein höheres Tief, während ein erneuter Short-Versuch keine neue Verkaufswelle erzeugt. Dieser zweite Test bietet mehr Gründe für einen Kauf. Der spätere Outside-Up-Entry-Bar bei Bar 3 steht in einer inzwischen geänderten Struktur.',
      'Der vorherige Abwärtsschub hatte zudem eine wichtige Trendlinie durchbrochen. Ein kräftiger Anstieg von einem späteren Kauf-Setup kann zum Test des alten Hochs führen; dort wird erneut zu prüfen sein, ob Verkäufer zurückkehren. Ein guter Long an einem höheren Tief sagt nichts über einen dauerhaften Bullenmarkt aus.',
    ],
    callout: 'Bei starkem Verkaufsdruck ist ein zweites, höheres Tief oft informativer als das erste Gegensignal.',
    diagramTitle: 'Klimax, zweiter Tief-Test, späterer Hochtest',
    caption: 'Eine eigenständig gezeichnete Folge trennt das erste mögliche Tief vom höheren Tief und dem anschließenden Test des alten Hochs.',
    observations: ['Früher Verkaufsdruck hält zunächst an.', 'Das spätere Tief liegt höher und ohne neuen Abwärtsschub.', 'Ein Hochtest nach Aufwärtsreaktion ist ein neuer Entscheidungspunkt.'],
    prompt: 'Was verbessert nach starkem frühem Verkauf den späteren Long-Versuch?',
    answers: [['Dass der allererste Gegenbar ohne Prüfung gekauft wird.', 'Die Verkaufskraft spricht für zusätzliche Belege.'], ['Ein höheres Tief und ein erneut scheiternder Short-Versuch.', 'Richtig. Der zweite Test verändert die Information.'], ['Dass ein Hochtest jede spätere Korrektur ausschließt.', 'Ein Test kann auch scheitern.']], correct: 1,
    takeaways: ['Ein Klimax ist nur eine mögliche Extremphase.', 'Zweites Signal und höheres Tief verbessern den Kontext.', 'Der spätere Hochtest braucht eine eigene Bewertung.'],
  },
  {
    number: 24, title: 'Fall 7.4: Gescheiterte High-1- und High-2-Käufe',
    summary: 'Nach einem späten Hoch kippt die Struktur durch wiederholte Käuferfehler.',
    section: 'Chartfall 7.4',
    anchors: ['Abbildung 7.4 · Bar 4 Hochtest und bärischer Inside-Bar', 'Bar 5 gescheiterter High 1', 'Bar 6 gescheiterter High 2 und Outside-Down'],
    scenario: 'c07-figure-74-failed-highs',
    paragraphs: [
      'Nach dem Anstieg erreicht ein großer Bullenbar ein neues Hoch. Er kann bereits eine späte Überdehnung anzeigen. Der nächste starke bärische Innenbar liefert Verkäufern erstmals eine deutlichere Gegenstruktur, aus der ein mehrteiliges Abwärtsbein plausibel wird.',
      'Der erste kleine Käuferwiederaufnahmeversuch verliert rasch Wirkung. Ein späterer High-2-Versuch trifft auf noch mehr bärische Vorbars und endet im Outside-Down-Bar. Damit werden Käufer, die auf eine einfache Fortsetzung des alten Aufwärtstrends gesetzt hatten, nacheinander zurückgewiesen.',
      'Wer nur die High-1/High-2-Zahlen liest, übersieht die Richtung und Stärke zwischen ihnen. Entscheidend sind der große späte Hochtest, der bärische Innenbar, ausbleibende Käuferkraft und der schnelle Schluss nach unten. Erst die ganze Sequenz begründet einen möglichen Wechsel der Trendseite.',
    ],
    callout: 'Wiederholte Käuferfehler nach einem Hochtest sind mehr als zwei bloße Zählmarken.',
    diagramTitle: 'Zwei Long-Versuche gegen wachsenden Verkaufsdruck',
    caption: 'Eigenes Schema markiert einen späten Hochtest, bärischen Inside-Bar und zwei gescheiterte Käuferauslösungen.',
    observations: ['Der große Bullenbar steht spät im Anstieg.', 'Der bärische Innenbar liefert erstmals deutliche Gegeninitiative.', 'Der zweite Long-Versuch kippt im Outside-Down-Bar.'],
    prompt: 'Welche Beobachtung wiegt nach dem Hochtest stärker als das High-2-Etikett?',
    answers: [['Die Serie bärischer Bars und das schnelle Scheitern beider Käuferauslösungen.', 'Richtig. Die Folge erklärt die neue Verkäuferkontrolle.'], ['Die Annahme, dass jedes High 2 automatisch steigt.', 'Eine Zählung allein schafft keine Käuferstärke.'], ['Der Name der gleitenden Durchschnittslinie.', 'Der Name ersetzt keine Preisreaktion.']], correct: 0,
    takeaways: ['Ein später großer Bullenbar kann Klimax sein.', 'Ein bärischer Innenbar verändert die Beweislage.', 'Gescheiterte High-1-/High-2-Versuche sind im Kontext zu lesen.'],
  },
];

export const chapterSevenCaseLessons = drafts.map(chapterSevenLesson);
