import { chapterEightLesson, type ChapterEightDraft } from './chapter-08-model';

// Die Diagramme hierzu sind neue Lehrschemata, keine Nachzeichnung von 8.1.
const drafts: ChapterEightDraft[] = [
  {
    number: 8, title: 'Fall 8.1: Zwei Zeitebenen, zwei verschiedene Risiken',
    summary: 'Kürzere Bars ermöglichen engere Stops, aber mehr Auslösungen gegen die größere Struktur.',
    section: 'Chartfall 8.1 · Rahmen',
    anchors: ['Abbildung 8.1 · Drei- und Fünf-Minuten-Blick', 'Längerer Bärentrend mit größeren Pullbacks', 'Kleinerer Stop und häufigere Ausstopper'],
    scenario: 'c08-figure-context',
    paragraphs: [
      'Der Buchfall zeigt eine Umkehrsituation nach einer längeren bärischen Phase. Neue Tiefs werden häufiger gekauft; die Rückläufe nach oben werden größer. Das ist noch keine fertige Bullenwende, aber eine veränderte Vorgeschichte vor dem nächsten Tief-Test.',
      'Eine kürzere Zeitebene zerlegt dieselbe Bewegung in mehr Bars. Sie bietet oft einen näheren technischen Stop, zeigt aber auch zusätzliche Gegenbars und Tiefstiche. Auf der längeren Arbeitszeitebene kann ein solcher Stich innerhalb eines noch intakten Signalbereichs bleiben.',
      'Ein engerer Stop verkleinert den Verlust pro Einheit, erhöht jedoch unter Umständen die Häufigkeit unnötiger Ausstiege. Die geeignete Zeitebene hängt deshalb nicht allein von der Stop-Distanz ab, sondern auch davon, ob die Person ihre Signale konsistent lesen kann.',
    ],
    callout: 'Kleinerer Stop bedeutet nicht automatisch bessere Gesamtqualität.',
    diagramTitle: 'Eine Bewegung, unterschiedlich zerlegt',
    caption: 'Eigenes abstraktes Schema: Links mehr kurze Bars mit Zwischentief, rechts dieselbe Idee in größeren Bars und breiterer Struktur.',
    observations: ['Beide Ansichten können dieselbe Marktphase meinen.', 'Kürzere Bars liefern mehr einzelne Gegensignale.', 'Risikostrecke und Ausstopphäufigkeit zusammen betrachten.'],
    prompt: 'Was ist der mögliche Nachteil, wenn du für eine größere Umkehr nur wegen des kleineren Stops auf eine kürzere Zeitebene wechselst?',
    answers: [['Der Stop kann häufiger getroffen werden, obwohl die größere Struktur noch hält.', 'Richtig. Das kleinere Risiko je Trade kann mit mehr Fehlausstiegen einhergehen.'], ['Es gibt auf kürzeren Charts keine bullischen Signale.', 'Signale gibt es dort ebenfalls, aber ihre Zuverlässigkeit und Menge ändern sich.'], ['Die größere Zeitebene liefert dann keine Information mehr.', 'Sie bleibt für die ursprüngliche These relevant.']], correct: 0,
    takeaways: ['Zeitebene vor dem Trade festlegen.', 'Stop-Distanz und Trefferwahrscheinlichkeit gemeinsam sehen.', 'Änderung der Marktphase im größeren Kontext beachten.'],
  },
  {
    number: 9, title: 'Fall 8.1: Der Schutz gehört unter die Struktur',
    summary: 'Ein überzeugender zweiter Umkehrversuch kann einen größeren sachlichen Stop brauchen.',
    section: 'Chartfall 8.1 · zweiter Versuch',
    anchors: ['Abbildung 8.1 · Signal um Bar 11', 'Zweiter Versuch nach tieferem Tief', 'Struktureller Stop und kleinere Positionsgröße'],
    scenario: 'c08-figure-stop-distance',
    paragraphs: [
      'Im Buchbeispiel erhält ein späterer bullischer Umkehrversuch mehr Gewicht: Es gab bereits einen früheren misslungenen Versuch, mehrere Abwärtsschübe und nun eine deutlichere Käuferreaktion. Der einzelne Reversal-Bar ist damit Teil einer größeren Folge.',
      'Ein Long-Plan muss das Tief dieser relevanten Struktur als möglichen Ungültigkeitspunkt berücksichtigen. Liegt dieser Stop weiter entfernt als bequem erscheint, wird die Umkehridee durch einen willkürlich engen Stop nicht besser. Der Chart zeigt, welches Risiko die These verlangt.',
      'Wer das Geldrisiko begrenzen will, kann die Positionsgröße passend verkleinern oder den Trade auslassen. Eine kleinere Kontraktzahl verändert nicht die fachliche Bedeutung des Tiefs; sie verändert nur die finanzielle Wirkung der Distanz.',
    ],
    callout: 'Schutzort aus der These ableiten, Größe aus dem Risikobudget.',
    diagramTitle: 'Strukturtief und zu enger Zwischen-Stop',
    caption: 'Eigenes Schema zeigt zwei frei gewählte Schutzlinien unter einer bullischen Reaktion; nur eine liegt jenseits des relevanten Tiefs.',
    observations: ['Das zweite Signal hat eine Vorgeschichte.', 'Ein enger Zwischen-Stop kann mitten in der Idee liegen.', 'Positionsgröße begrenzt Geldrisiko ohne Änderung der Struktur.'],
    prompt: 'Ein gutes Long-Setup benötigt einen weiter entfernten Stop unter dem wichtigen Tief. Was ist die saubere Anpassung bei gleichem Geldrisiko?',
    answers: [['Den Stop ohne Chartgrund näher heranrücken.', 'Damit wird der Schutzpunkt von der These abgekoppelt.'], ['Die Position verkleinern oder auslassen.', 'Richtig. Der strukturelle Stop bleibt dort, wo die Idee invalidiert wäre.'], ['Den Stop ganz entfernen.', 'Das würde das Risiko unbestimmt machen.']], correct: 1,
    takeaways: ['Mehrere Versuche verändern die Signalqualität.', 'Stop unter relevante Struktur statt unter zufälligen Mini-Bar.', 'Geldrisiko über Positionsgröße oder Verzicht steuern.'],
  },
  {
    number: 10, title: 'Fall 8.1: Nur der kürzere Chart stoppt aus',
    summary: 'Ein kräftiger Gegenbar der kleinen Zeitebene kann innerhalb des größeren Long-Plans bleiben.',
    section: 'Chartfall 8.1 · Ausstopper',
    anchors: ['Abbildung 8.1 · Stop der Drei-Minuten-Ansicht', 'Fünf-Minuten-Tief bleibt bestehen', 'Konflikt der beiden Signale'],
    scenario: 'c08-figure-stopout',
    paragraphs: [
      'Nach dem Umkehrsignal entsteht im kürzeren Blick ein bärischer Bar mit starkem Schluss. Sein Tief löst den Schutz unter dem kleinen Entry-Bar aus. In dieser Zeitebene sieht das wie eine klare Verkäuferreaktion aus.',
      'Die größere Arbeitszeitebene zeigt gleichzeitig ein anderes Bild: Ihr relevantes Signaltief bleibt unberührt. Wer auf Grundlage des größeren Setups eingestiegen ist, kann nicht unbemerkt den kleineren Stop und die kleinere Signalbewertung zum neuen Plan machen.',
      'Im Nachhinein wirkt der kurze Stich offensichtlich. Während er entsteht, sind die widersprüchlichen Signale aber schwer zu ordnen. Vorher gewählte Zeitebene und Stop-Regel verhindern, dass die Entscheidung mitten im schnellen Gegenbar wechselt.',
    ],
    callout: 'Nicht nach dem Einstieg heimlich die Zeitebene des Schutzplans tauschen.',
    diagramTitle: 'Kleiner Stop berührt, größeres Tief hält',
    caption: 'Zwei unabhängige Lehrschemata markieren jeweils den Schutzort der gewählten Zeitebene; nur die nähere Linie wird geschnitten.',
    observations: ['Ein bärischer Klein-Bar kann stark aussehen.', 'Der weiter entfernte Strukturpunkt bleibt unangetastet.', 'Das Mischen zweier Pläne verändert den Trade.'],
    prompt: 'Ein Long aus dem größeren Chart ist offen; nur der Stop unter einem Bar des kleineren Charts wird erreicht. Welche Aussage ist korrekt?',
    answers: [['Das größere Setup ist damit zwangsläufig ungültig.', 'Sein eigenes relevantes Tief wurde gerade nicht erreicht.'], ['Der kleinere Stich beweist eine sofortige Bärenphase.', 'Ein starker kurzer Gegenbar kann in einer größeren Bewegung aufgefangen werden.'], ['Die beiden Schutzpläne sind verschieden und müssen vorab getrennt werden.', 'Richtig. Ein kleiner Ausstopper invalidiert nicht automatisch die größere These.']], correct: 2,
    takeaways: ['Starke Gegensignale auf kleiner Ebene richtig einordnen.', 'Invalidation auf der geplanten Ebene prüfen.', 'Nicht nachträglich einen anderen Stop übernehmen.'],
  },
  {
    number: 11, title: 'Fall 8.1: Nach dem kurzen Stich übernehmen Käufer',
    summary: 'Ein zurückgekaufter Tiefbruch kann Ausgestoppte an der Rückkehr hindern.',
    section: 'Chartfall 8.1 · Rückeroberung',
    anchors: ['Abbildung 8.1 · bullischer Outside-Folgebar', 'Höheres Tief nach kurzzeitigem Stop-Lauf', 'Ein Chart als Arbeitsgrundlage'],
    scenario: 'c08-figure-recovery',
    paragraphs: [
      'Auf den starken kleinen Bärenbar folgt im Buchfall eine energische Käuferreaktion. Der nächste Bar umfasst den vorherigen und schließt hoch. Das kurze Tief wird zum Teil eines höheren Tiefbereichs statt zum Beginn einer neuen dauerhaften Abwärtsbewegung.',
      'Wer am engen Stop ausgestiegen ist, muss jetzt in sehr kurzer Zeit einen Fehlausbruch erkennen und einen neuen Einstieg planen. Häufig wird aus Vorsicht auf einen späteren Pullback gewartet, während die ursprüngliche Bewegung ohne diese Position weiterläuft.',
      'Die Lehre ist kein Aufruf, Stop-Läufe grundsätzlich zu kaufen. Sie erklärt, weshalb zwei gleichzeitig beobachtete Zeitebenen im schnellen Umschlag handlungsunfähig machen können. Ein fest gewählter Arbeitschart liefert eine konsistentere Entscheidungsfolge.',
    ],
    callout: 'Ein zurückerobertes Tief ist neue Information, kein Beweis für jedes künftige Signal.',
    diagramTitle: 'Stich unter das Tief und bullische Rückkehr',
    caption: 'Eigenes Schema stellt den engen Ausstopper und die anschließende Outside-Up-Reaktion einem ruhigeren Blick auf den größeren Plan gegenüber.',
    observations: ['Der kurzfristige Bärenbar verliert sofort Anschluss.', 'Ein Outside-Up-Bar kann den Tiefbereich zurückerobern.', 'Ein Plan darf nicht bei jedem Gegensignal die Zeitebene wechseln.'],
    prompt: 'Warum ist ein Wiedereinstieg nach dem kurzen Ausstopper psychologisch und praktisch schwer?',
    answers: [['Weil ein einmaliger Stop jeden späteren Einstieg verbietet.', 'Eine erneute Entscheidung ist möglich, aber schwerer unter Zeitdruck.'], ['Weil der Trader einen starken kleinen Bärenbar und seine schnelle Rücknahme neu einordnen muss.', 'Richtig. Angst und widersprüchliche Zeitebenen können den Plan verzögern.'], ['Weil ein Outside-Bar immer eine Trading Range beendet.', 'Die Form allein sagt das nicht.']], correct: 1,
    takeaways: ['Gegenbar und seine Folgereaktion gemeinsam lesen.', 'Kurzer Tiefbruch kann Käufer anziehen.', 'Einen Arbeitschart und seinen Schutzplan konsistent nutzen.'],
  },
  {
    number: 12, title: 'Fall 8.1: Frühe Gegenbrüche scheitern noch',
    summary: 'Kleine Brüche einer fallenden Linie ändern den Trend nicht ohne Anschluss.',
    section: 'Chartfall 8.1 · vertiefter Rückblick',
    anchors: ['Abbildung 8.1 · vertiefte Diskussion', 'Frühe Brüche über fallende Trendlinie', 'Mit-Trend-Short nach ausbleibendem Anschluss'],
    scenario: 'c08-figure-failed-breaks',
    paragraphs: [
      'Vor der späteren bullischen Umkehr beschreibt Brooks im selben Chart frühere Versuche, eine fallende Trendlinie zu überschreiten. Beide bleiben knapp oder kurz und erhalten keine tragfähige Käuferfolge. Ein Linienbruch allein kippt die bisherige Bärenstruktur nicht.',
      'Nach einem misslungenen Gegenbruch kann der Markt wieder in die alte Richtung drehen. Das bereitet einen Mit-Trend-Short vor, solange die weitere Folge den Abwärtstrend stützt. Erst später verändern größere Rückläufe, wiederholte Tief-Tests und stärkere Käuferreaktionen die Ausgangslage.',
      'Diese zeitliche Reihenfolge verhindert Rückschaufehler: Man darf die späte Umkehr nicht in frühere Bars hineinlesen. Am jeweiligen Bar-Schluss lagen erst die damaligen Informationen vor; die spätere Käuferstärke war noch unbekannt.',
    ],
    callout: 'Ein erster Gegenbruch ist ein Test; erst die Folge zeigt den Regimewechsel.',
    diagramTitle: 'Zwei kurze Brüche und die alte Richtung',
    caption: 'Ein frei konstruiertes Schema zeigt zwei nicht gehaltene Tests einer fallenden Referenzlinie; es bildet keine Buchabbildung nach.',
    observations: ['Beide Hochstiche verlieren die neue Zone.', 'Die Bären erhalten danach erneut Schlusskontrolle.', 'Der spätere Umkehrfall darf nicht rückwirkend unterstellt werden.'],
    prompt: 'Warum war ein kurzer Bruch über die fallende Linie im früheren Abschnitt noch keine sichere Bullenwende?',
    answers: [['Weil der Bruch keinen tragfähigen bullischen Anschluss erhielt.', 'Richtig. Der Markt kehrte in die alte Richtung zurück.'], ['Weil Trendlinien nie Informationen liefern.', 'Sie zeigen einen Test, dessen Folge beurteilt werden muss.'], ['Weil die spätere Umkehr schon feststand.', 'Am früheren Entscheidungspunkt war sie nicht bekannt.']], correct: 0,
    takeaways: ['Linienbruch und Anschluss getrennt prüfen.', 'Frühere Entscheidungen nur mit damaligem Wissen beurteilen.', 'Der Bar-Schluss macht die Folge schrittweise sichtbar.'],
  },
];

export const chapterEightCaseLessons = drafts.map(chapterEightLesson);
