import { chapterTenLesson, type ChapterTenDraft } from './chapter-10-model';

const drafts: ChapterTenDraft[] = [
  {
    number: 6, title: 'Fall 10.1: Die meisten zweiten Entries kosten Preis',
    summary: 'Im Buchchart zeigen fast alle erneuten Auslösungen keinen günstigen Rabatt.',
    section: 'Abbildung 10.1 · Überblick',
    anchors: ['Abbildung 10.1 · Tagesübersicht', 'Mehrere zweite Entries', 'Auslösung meist gleich oder ungünstiger'],
    scenario: 'c10-101-price-map',
    paragraphs: [
      'Brooks markiert in Abbildung 10.1 über einen ganzen Handelstag viele zweite Einstiegsmöglichkeiten. Für die Beurteilung zählt nicht, ob jede markierte Stelle später Gewinn brachte. Er vergleicht zunächst, welchen Preis die Wartenden gegenüber dem ersten Versuch bekamen.',
      'In diesem historischen Chart liegt fast jeder zweite Auslösungspreis für die jeweilige Richtung auf demselben Niveau oder etwas ungünstiger. Das passt zur Idee, dass mehr Bestätigung meistens etwas Preis kostet. Der einzelne abweichende Kaufversuch wird im nächsten Schritt gesondert geprüft.',
      'Beim Nacharbeiten zeichne für jeden Kandidaten Versuch eins, Reaktion und Versuch zwei ein. Trenne Longs und Shorts: Für Long ist höher ungünstiger, für Short tiefer. So lässt sich die zentrale Beobachtung des Buchfalls prüfen, ohne aus einer pauschalen Regel ein Handelssignal zu machen.',
    ],
    callout: 'Erst die zwei Auslösungspreise vergleichen, dann die Marktstärke beurteilen.',
    diagramTitle: 'Zweite Auslösung ohne Rabatt',
    caption: 'Eigenes Preisschema mit zwei frei erfundenen Kaufversuchen auf ähnlichem oder etwas höherem Niveau; keine Buchkursreihe.',
    observations: ['Zwei Versuche haben zwei Auslösungspunkte.', 'Mehr Information kann einen späteren Preis erfordern.', 'Der Vergleich sagt allein noch nichts über den Gewinn.'],
    prompt: 'Welche Preisbeziehung findet Brooks im Buchfall 10.1 bei den meisten zweiten Entries?',
    answers: [['Der zweite Entry liegt für die jeweilige Seite gleich oder etwas ungünstiger.', 'Richtig. Der auffällig billigere Long ist die Ausnahme, die er untersucht.'], ['Alle zweiten Longs werden deutlich unter dem ersten ausgeführt.', 'Das entspricht gerade nicht seiner Beobachtung in diesem Chart.'], ['Der Ausführungspreis ist für die Fallbesprechung bedeutungslos.', 'Der Preisvergleich ist das Ausgangsthema des Falls.']], correct: 0,
    takeaways: ['Long und Short beim Preisvergleich spiegeln.', 'Auslösung und späteres Ergebnis nicht vermischen.', 'Abweichungen vom Muster eigens prüfen.'],
  },
  {
    number: 7, title: 'Fall 10.1: Der Long bei Bar 10 wirkt zu billig',
    summary: 'Ein Tick Vorteil gegenüber Bar 9 ist im engen Bärenkanal ein Warnzeichen.',
    section: 'Abbildung 10.1 · Bars 9 und 10',
    anchors: ['Abbildung 10.1 · Long bei Bar 9', 'Bar 10 · ein Tick günstigerer Versuch', 'Enger Bärenkanal ab Bar 8'],
    scenario: 'c10-101-bargain-trap',
    paragraphs: [
      'Im Buchbeispiel folgt auf den Long bei Bar 9 ein erneuter Kaufversuch bei Bar 10. Dieser zweite Versuch bietet sogar einen Tick besseren Preis. Das klingt attraktiv, obwohl ein späterer Trader üblicherweise für zusätzliche Bestätigung mehr bezahlt.',
      'Der umgebende Chart liefert den Gegenbeweis zur Bargain-Idee: Seit Bar 8 läuft ein enger Bärenkanal abwärts. Die Verkäufer schaffen fortlaufend neue Tiefs, und die Gegenversuche sind klein. Das günstigere Angebot ist deshalb plausibel, weil Kaufkraft fehlt, nicht weil der Einstieg plötzlich großzügig geworden wäre.',
      'Brooks behandelt den Preisvorteil als Anlass, die Long-These zu stoppen und den Druck neu zu lesen. Er sagt damit nicht, dass jeder preiswertere zweite Entry verliert. Im konkreten Kontext wäre ein sofortiger Gegentrend-Kauf trotz des Tick-Vorteils eine schwache Entscheidung.',
    ],
    callout: 'Der billige zweite Long verdient Misstrauen, wenn der Bärenkanal eng bleibt.',
    diagramTitle: 'Billigerer Kauf innerhalb des Bärendrucks',
    caption: 'Ein eigener schematischer Abwärtspfad zeigt zwei markierte Kaufversuche; der spätere liegt tiefer, während der Kanal nicht gebrochen ist.',
    observations: ['Der zweite Kaufpunkt liegt etwas tiefer.', 'Die fallende Folge bleibt eng.', 'Der Rabatt kann aus anhaltendem Verkaufsdruck stammen.'],
    prompt: 'Was macht Bar 10 trotz seines günstigeren Long-Preises problematisch?',
    answers: [['Der Long liegt deutlich über dem ersten Auslösungspreis.', 'Im Beispiel liegt er gerade etwas tiefer; das Problem ist der anhaltende Verkaufsdruck.'], ['Der enge Bärenkanal zeigt weiterhin zu viel Verkaufsdruck.', 'Richtig. Der Preisvorteil passt zur Schwäche der Gegenseite.'], ['Ein zweiter Entry darf nie tiefer liegen.', 'Er kann tiefer liegen, muss dann aber besonders kritisch gelesen werden.']], correct: 1,
    takeaways: ['Bar 9 und 10 nur mit dem vorangehenden Kanal vergleichen.', 'Ein Tick Preisvorteil beweist keine bessere Qualität.', 'Gegentrend nur bei erkennbarer Gegenkraft erwägen.'],
  },
  {
    number: 8, title: 'Fall 10.1: Vor dem Long Käuferkraft suchen',
    summary: 'Einzelne minimale Hochstiche reichen nicht als Beleg für eine Umkehr gegen den Bärenkanal.',
    section: 'Abbildung 10.1 · Vorbedingungen',
    anchors: ['Abbildung 10.1 · Erläuterung zu Bar 10', 'Mehrere Bars vor dem Signal', 'Ausmaß bullischer Gegenbewegungen'],
    scenario: 'c10-101-bull-evidence',
    paragraphs: [
      'Bevor Brooks einen Kauf gegen den Bärenkanal erwägt, schaut er einige Bars zurück. Konnten Käufer die Hochs der Vorgängerbars überhaupt deutlich überwinden? Kleine Stiche von wenigen Ticks, die sofort wieder verkauft werden, sind noch keine tragfähige Gegenbewegung.',
      'Diese Prüfung unterscheidet einen echten zweiten Versuch von einer bloßen neuen Zahl auf einer weiter fallenden Kurve. In einem engen Kanal kann ein „High 2“ formal erkennbar sein, während die Käufer weder Raum noch Folgebars gewinnen. Ein sauberer Name für das Muster hebt den Druck nicht auf.',
      'Die Übung ist konkret: Markiere bei den Bars vor deinem geplanten Long, wie weit die Aufwärtsversuche kamen und ob sie oben schlossen. Bleiben sie winzig und ohne Anschluss, ist das Abwarten oder Auslassen besser begründbar als der Kauf eines scheinbar billigen Signals.',
    ],
    callout: 'Vor einem zweiten Long muss die Gegenseite im Chart bereits etwas erreicht haben.',
    diagramTitle: 'Schwache Hochstiche und tragfähige Gegenbewegung',
    caption: 'Zwei selbst konstruierte Abwärtsfolgen zeigen links nur winzige bullische Stiche und rechts einen sichtbaren Gegenstoß vor einem erneuten Tief-Test.',
    observations: ['Kleine Hochstiche ändern den Bärendruck kaum.', 'Ein Gegenstoß zeigt erstmals Raum für Käufer.', 'Die letzten Bars zählen mehr als das Etikett „zweiter“.'],
    prompt: 'Welche Beobachtung würde einen zweiten Long gegen einen engen Bärenkanal eher stützen?',
    answers: [['Dass der Einstieg einen Tick billiger geworden ist.', 'Der Preisvorteil kann aus weiterem Verkaufsdruck stammen.'], ['Dass kein Bar der letzten Folge über sein Vorhoch kam.', 'Dann fehlt sichtbare Käuferkraft.'], ['Dass einige vorangehende Bars bereits deutlich über vorherige Hochs vorstießen.', 'Richtig. Das wäre konkrete bullische Gegenreaktion.']], correct: 2,
    takeaways: ['Vorbars auf echte Gegenbewegung prüfen.', 'Formale Zählung nicht über Momentum stellen.', 'Fehlende Stärke kann ein Auslassen begründen.'],
  },
  {
    number: 9, title: 'Fall 10.1: Kleine Doppeltests markieren Umkehrversuche',
    summary: 'Die Nähe zweier Hochs oder Tiefs kann den zweiten Angriff sichtbar machen.',
    section: 'Abbildung 10.1 · Mikro-Doppel',
    anchors: ['Abbildung 10.1 · Bar 1 und früherer Reversal-Bar', 'Bar 18 und Tief vor Bar 17', 'Mikro-Doppeltop und Mikro-Doppeltief'],
    scenario: 'c10-101-micro-doubles',
    paragraphs: [
      'Im oberen Bereich des Buchcharts lässt sich Bar 1 zusammen mit dem bärischen Reversal-Bar zwei Bars zuvor als enger zweiter Hochtest lesen. Brooks nennt das Mikro-Doppeltop. Die Bars müssen weder direkt nebeneinanderliegen noch exakt dasselbe Hoch erreichen.',
      'Später am unteren Ende bildet Bar 18 mit dem Tief des Bars unmittelbar vor Bar 17 eine entsprechende zweite Prüfung der Käuferseite: ein Mikro-Doppeltief. Diese kurzen Muster zeigen, wie erneute Versuche auf kleinem Raum auch ohne eine große, perfekte Doppel-Formation entstehen können.',
      'Das Kapitel verweist an dieser Stelle auf die ausführlichere Behandlung in einem späteren Buch. Hier genügt die Buchfunktion: zwei nahe Extremtests können einen zweiten Entry vorbereiten. Ob er tragfähig ist, zeigt erst die Richtung der Auslösung und der Folgebars.',
    ],
    callout: 'Zwei nahe Extremtests sind ein Hinweis auf einen erneuten Versuch, kein Umkehrbeweis.',
    diagramTitle: 'Mikro-Doppeltop und Mikro-Doppeltief',
    caption: 'Zwei frei erfundene kleine Folgen zeigen einen wiederholten Hochtest und einen wiederholten Tieftest; keine Nachzeichnung von Abbildung 10.1.',
    observations: ['Die Extremzonen liegen nahe beieinander.', 'Ein Zwischenbar kann die zwei Tests trennen.', 'Die Folge nach dem zweiten Test entscheidet.'],
    prompt: 'Was haben Bar 1 und Bar 18 im Kapitel gemeinsam?',
    answers: [['Sie dienen jeweils als Beispiel für einen zweiten Test einer nahen Extremzone.', 'Richtig. Oben entsteht ein Mikro-Doppeltop, unten ein Mikro-Doppeltief.'], ['Beide müssen exakt denselben absoluten Kurs erreichen.', 'Eine nahe Zone reicht für die strukturelle Deutung.'], ['Beide sind sichere Signale in die gleiche Richtung.', 'Die Richtungen sind verschieden und beide Muster können scheitern.']], correct: 0,
    takeaways: ['Zweite Hoch- und Tieftests auch auf engem Raum erkennen.', 'Form und Auslösung voneinander trennen.', 'Keine Details eines anderen Brooks-Bandes voraussetzen.'],
  },
];

export const chapterTenFigure101Lessons = drafts.map(chapterTenLesson);
