import { chapterSixLesson, type ChapterSixDraft } from './chapter-06-model';

// The book's figures are source anchors, not artwork to reproduce. Each
// diagram below is a separate, constructed example of the teaching point.
const drafts: ChapterSixDraft[] = [
  {
    number: 20, title: 'Fall 6.1: Schwache kleine Bars im starken Bärentrend',
    summary: 'Mehrere unscheinbare Pullbacks bieten eher Shorts; erst ein Strukturbruch ändert die Lage.',
    section: 'Chartfall 6.1', anchors: ['Abbildung 6.1 · kleine Signal-Bars', 'Kurze Pullbacks unter dem Durchschnitt', 'Erst Bruch und zweiter Test für Gegenrichtung'],
    scenario: 'c06-case-01',
    paragraphs: [
      'In einem zügigen Abwärtstrend können kleine Dojis und Inside-Bars an jedem flachen Rücklauf auftreten. Isoliert sehen sie nach Unentschlossenheit aus; im Gesamtbild drücken die Verkäufer den Markt aber immer wieder unter den letzten Pullback. Damit erhalten die kleinen Bars vor allem eine Mit-Trend-Rolle.',
      'Ein frühes bullisches Gegensignal am Tief verdient noch nicht dieselbe Aufmerksamkeit. Erst nachdem der Kurs den fallenden Kanal aufbricht und ein zweiter Tiefversuch keine neue Verkaufsdynamik erzeugt, lässt sich eine größere Korrektur nach oben plausibel begründen.',
      'Der tiefere Fall zeigt zudem, wie ein Fehlversuch nach einer Eröffnungslücke zuerst Käufer anzieht und anschließend neue Shorts schafft. Entscheidend ist nicht die perfekte Einzelkerze, sondern die Reihe aus Fehlausbruch, Bärenspike, schwachen Rückläufen und späterem Test des Trendkanals.',
    ], callout: 'Im starken Trend können gerade schwach aussehende Signal-Bars die Fortsetzung tragen.',
    diagramTitle: 'Kleine Pausen unter einer fallenden Struktur',
    caption: 'Eigenes Schema zu den Lernpunkten von Fall 6.1: mehrere flache Rückläufe und ein späterer Kanalbruch.',
    observations: ['Die frühen Gegenbars verändern den Trend nicht.', 'Wiederholte kleine Pullbacks geben neue Mit-Trend-Punkte.', 'Ein späterer Strukturbruch erhöht die Bedeutung des Tief-Tests.'],
    prompt: 'Ein kleiner Doji steht nach dem vierten flachen Pullback unter fallenden Swinghochs. Was ist zuerst zu prüfen?',
    answers: [['Ob die Bärenseite ihre Reihe von tieferen Fortsetzungen noch hält.', 'Richtig. Der Trendkontext trägt den kleinen Bar.'], ['Ob ein Doji grundsätzlich Long bedeutet.', 'Ein Doji besitzt keine feste Gegenrichtung.'], ['Ob der Markt exakt am Tagestief schließen muss.', 'Der spätere Tagesschluss ist hier noch unbekannt.']], correct: 0,
    takeaways: ['Kleine Bars sind im Trend oft Mit-Trend-Signale.', 'Ein Einzelbar am Tief bestätigt keinen Wechsel.', 'Kanalbruch und weiterer Test ändern die Beweislast.'],
  },
  {
    number: 21, title: 'Fall 6.2: Die schöne Umkehr löst auf der falschen Seite aus',
    summary: 'Frühe Gegen-Trend-Positionen können den bestehenden Trend verstärken.',
    section: 'Chartfall 6.2', anchors: ['Abbildung 6.2 · Reversal-Bar als Fortsetzungssetup', 'Bullisches Signal im Bärentrend scheitert', 'Bärisches Signal im Bullenlauf scheitert'],
    scenario: 'c06-case-02',
    paragraphs: [
      'Stell dir einen starken bullischen Reversal-Bar nach mehreren Abwärtsbars vor. Wer schon innerhalb dieses Bars kauft, setzt auf eine Auslösung über seinem Hoch. Kommt dieser Ausbruch nicht und wird stattdessen sein Tief unterboten, verändert sich der Fall vollständig.',
      'Die enttäuschten Käufer verkaufen beim Bruch unten, während Trendfolger denselben Preis als neue Short-Möglichkeit lesen. Eine auffällige Umkehrform kann so im nächsten Moment eine Fortsetzungsflag gewesen sein. Im Aufwärtstrend funktioniert das Spiegelbild mit einem nicht ausgelösten bärischen Reversal-Bar.',
      'Der Lernpunkt des Chartfalls ist die zeitliche Reihenfolge. Zuerst gibt es nur eine Hypothese, dann eine mögliche Auslösung und schließlich eine Reaktion. Wer die Folge überspringt und die Kerze bereits als bestätigte Wende verbucht, kann in die falsche Seite gedrängt werden.',
    ], callout: 'Eine gute Form verliert an Bedeutung, wenn der Markt nur ihre Gegenseite durchbricht.',
    diagramTitle: 'Reversal-Bar scheitert vor der erwarteten Auslösung',
    caption: 'Im eigenen Beispiel wird das Hoch des bullischen Bars nie erreicht, sein Tief aber gebrochen.',
    observations: ['Frühe Käufer sind vor der Auslösung engagiert.', 'Der geplante Long-Trigger bleibt unberührt.', 'Der Bruch unten verbindet Ausstiege und neue Shorts.'],
    prompt: 'Was unterscheidet einen ausgelösten Long vom frühen Kauf innerhalb eines Reversal-Bars?',
    answers: [['Nichts; die Farbe reicht.', 'Der geplante Trigger ist ein eigener Schritt.'], ['Der Long-Trigger oberhalb des Bars muss tatsächlich gehandelt werden.', 'Richtig. Sonst bleibt das Signal unausgelöst.'], ['Nur die Anzahl der Minuten auf der Uhr.', 'Die Uhr allein ersetzt die Auslösung nicht.']], correct: 1,
    takeaways: ['Erst Auslösung, dann Signal-Bar.', 'Ein Fehlschlag kann Positionen in Trendrichtung zwingen.', 'Dasselbe Muster gilt spiegelbildlich im Bullenmarkt.'],
  },
  {
    number: 22, title: 'Fall 6.3: Der größte Bärenbar kommt spät',
    summary: 'Nach langem Abverkauf kann der größte Bar ein Klimax statt eines frischen Beginns sein.',
    section: 'Chartfall 6.3', anchors: ['Abbildung 6.3 · großer Trend-Bar und Erschöpfung', 'Kanalüberschuss und bullische Inside-Reaktion', 'Gegen-Short ohne vorherige Schwäche'],
    scenario: 'c06-case-03',
    paragraphs: [
      'Nach einer langen Reihe fallender Bars beschleunigt ein besonders großer Bärenbar bis unter die bisherige Kanalbegrenzung. Er zeigt echten Verkaufsdruck und zugleich ein mögliches Erschöpfungsstadium. Die nächste Kerze muss entscheiden helfen, ob Verkäufer weiter kontrollieren.',
      'Ein kleiner bullischer Inside-Bar, der nahe seinem Hoch schließt, verändert die Ausgangslage. Er zeigt Käufer direkt nach dem Übertreiben nach unten. Daraus kann zunächst eine längere Seitwärts- bis Aufwärtskorrektur werden; eine vollständige Trendwende ist eine stärkere These und braucht mehr Anschluss.',
      'Nach mehreren kräftigen Bullenbars wäre ein einzelner bärischer Reversal-Bar wiederum kein überzeugender Short. Ohne erkennbaren Verlust der neuen Aufwärtskraft kann er nur der erste kleine Rücklauf sein. Der Chartfall zwingt zu zwei getrennten Bewertungen derselben großen Bewegungsfolge.',
    ], callout: 'Klimax, Korrektur und Trendwechsel sind drei verschiedene Behauptungen.',
    diagramTitle: 'Später Sell-Climax und erste Gegenreaktion',
    caption: 'Eigenes Schema: ein großer Schluss unter der Kanalzone, gefolgt von einem kleinen bullischen Inside-Bar.',
    observations: ['Die Bärenbewegung ist bereits weit fortgeschritten.', 'Der große Bar überdehnt die bisherige Struktur.', 'Erst die Folgekerze zeigt Kaufbereitschaft.'],
    prompt: 'Nach einem langen Bärentrend folgt auf den größten Bärenbar ein kräftiger bullischer Inside-Bar. Was darfst du zunächst erwarten?',
    answers: [['Eine mögliche Korrektur mit weiteren Tests.', 'Richtig. Ein neuer Bullenmarkt wäre eine weitergehende Behauptung.'], ['Garantiert sofort einen neuen Aufwärtstrend.', 'Der Wechsel ist noch nicht bestätigt.'], ['Der Bärenbar kann niemals ein Klimax sein.', 'Späte ungewöhnliche Größe kann genau darauf hinweisen.']], correct: 0,
    takeaways: ['Großer Spätbar kann Druck und Erschöpfung vereinen.', 'Käuferreaktion muss sichtbar werden.', 'Die erste Gegenbewegung ist nicht automatisch ein neuer Trend.'],
  },
  {
    number: 23, title: 'Fall 6.4: Drei kleine Bars und eine größere Umkehr',
    summary: 'Wie kleinere Bars eine höhere Zeitebene formen, ohne dass ihre Grenzen immer exakt passen.',
    section: 'Chartfall 6.4', anchors: ['Abbildung 6.4 · höhere Zeitebene', 'Drei Fünf-Minuten-Bars', 'Trendumkehr nach Durchschnittstest'],
    scenario: 'c06-case-04',
    paragraphs: [
      'Eine Fünfzehn-Minuten-Umkehr kann aus drei aufeinanderfolgenden Fünf-Minuten-Bars bestehen: zunächst Druck in alter Richtung, dann Pause und schließlich Gegeninitiative. Im kleineren Chart sieht man dabei mehr Entscheidungen als in der zusammengefassten Kerze.',
      'Wichtig ist der zeitliche Abschluss. Nur wenn die drei Bars tatsächlich in dieselbe größere Zeiteinheit fallen, bilden sie dort genau den sichtbaren Umkehr-Bar. Andernfalls kann die kleinere Folge trotzdem ein sinnvoller Test mit Anschluss sein, aber die zusätzliche Aussage einer klaren größeren Kerze fällt weg.',
      'Im Fall des Buches kommt ein Bruch unter den Durchschnitt hinzu, der nicht gehalten wird. Die größere Trendstruktur und der anschließende Gegenmove erklären die Relevanz besser als das bloße Zählen von drei Bars.',
    ], callout: 'Größere und kleinere Bars zeigen denselben Markt mit unterschiedlicher Bündelung.',
    diagramTitle: 'Drei Fünf-Minuten-Abschnitte als Gesamtbar',
    caption: 'Das eigene Lehrbild zeigt drei Teilbars und ihren gemeinsamen Eröffnungs- und Schlussbereich.',
    observations: ['Die kleinere Folge zeigt den Weg der Umkehr.', 'Der größere Bar fasst diesen Weg zusammen.', 'Zeitgrenzen und Marktort bleiben entscheidend.'],
    prompt: 'Warum ist nicht jede schöne Drei-Bar-Folge automatisch eine klare Fünfzehn-Minuten-Umkehr?',
    answers: [['Weil die Zeitfenster unterschiedlich abschließen können.', 'Richtig. Die Bars müssen im selben größeren Fenster liegen.'], ['Weil größere Zeitebenen keine Hochs und Tiefs haben.', 'Auch dort entstehen vollständige Bars.'], ['Weil die erste kleine Kerze immer grün sein muss.', 'Die Form hängt von der Bewegungsrichtung ab.']], correct: 0,
    takeaways: ['Drei kleinere Bars können einen größeren Umkehr-Bar formen.', 'Die Zeitbündelung bestimmt die sichtbare größere Kerze.', 'Kontext bleibt auch bei Zeitebenenwechsel wichtiger als die Form.'],
  },
  {
    number: 24, title: 'Fall 6.5: Gute Dreierfolge ohne perfekte Zeitbündelung',
    summary: 'Ein plausibles kleineres Setup bleibt zu prüfen, auch wenn der größere Chart anders schließt.',
    section: 'Chartfall 6.5', anchors: ['Abbildung 6.5 · Drei-Bar-Reversals', 'Nicht deckungsgleiche größere Kerze', 'Zwei-Bar-Einstieg innerhalb der Folge'],
    scenario: 'c06-case-05',
    paragraphs: [
      'Im Lehrfall sieht die Dreierfolge auf dem kleineren Chart wie eine klare Umkehr aus. Weil der dritte Bar vor dem Abschluss der größeren Kerze endet, ist dieselbe Stärke dort aber weniger deutlich. Das ist ein gutes Beispiel dafür, warum ein höherer Zeitrahmen nicht nachträglich als Beweis erfunden werden sollte.',
      'Zwei der drei kleinen Bars können bereits selbst ein brauchbares Gegenpaar bilden. Wer ein solches Setup bewertet, braucht nicht zwingend noch ein höheres Hoch über alle drei Bars. Gleichzeitig darf der etwas frühere Einstieg die bisherige Abwärtskraft und die Lage zu einer Range nicht ausblenden.',
      'Der tiefergehende Fall zeigt eine Eröffnung unter dem Vortagestief und einen kleinen schwankenden Anfang. Erst der Bruch der Eröffnungszone und später eine deutliche Gegeninitiative liefern jeweils nachvollziehbare Entscheidungen. Viele Bars existieren; nicht jeder Dreierblock verdient Aufmerksamkeit.',
    ], callout: 'Nutze die tatsächliche kleinere Folge; erfinde keine Bestätigung aus dem größeren Chart.',
    diagramTitle: 'Signalfolge neben einer verschobenen Zeitgrenze',
    caption: 'Eigene drei Bars stehen teilweise außerhalb der gezeigten größeren Kerzenperiode.',
    observations: ['Die kleinere Folge zeigt einen Wechsel.', 'Die größere Zeiteinheit schließt zu einem anderen Zeitpunkt.', 'Ein Zwei-Bar-Teilsignal kann trotzdem eine eigene Auslösung besitzen.'],
    prompt: 'Drei Fünf-Minuten-Bars ergeben auf dem Fünfzehn-Minuten-Chart keinen perfekten Umkehr-Bar. Welche Aussage bleibt möglich?',
    answers: [['Der kleinere Verlauf kann mit Kontext dennoch ein Setup sein.', 'Richtig. Sichtbare kleine Struktur und größerer Bar sind getrennt zu prüfen.'], ['Die drei Bars sind automatisch ungültig.', 'Das folgt aus der Bündelung nicht.'], ['Die Zeitgrenze darf für ein besseres Signal verschoben werden.', 'Rückblickende Anpassung wäre irreführend.']], correct: 0,
    takeaways: ['Zeitgrenzen sind echte Chartdaten.', 'Ein kleineres Setup braucht keine erfundene größere Bestätigung.', 'Konzentriere dich auf klare, häufigere Entscheidungen.'],
  },
  {
    number: 25, title: 'Fall 6.6: Der zweite Bar täuscht den Short an',
    summary: 'Große Überlappung verlangt den Bruch der Grenze beider Bars.',
    section: 'Chartfall 6.6', anchors: ['Abbildung 6.6 · Zwei-Bar-Reversal', 'Tief des zweiten Bars innen', 'Ein-Tick-Double-Bottom-Falle'],
    scenario: 'c06-case-06',
    paragraphs: [
      'Ein großer bärischer Bar kann wie ein einfacher Short-Auslöser aussehen. Liegt sein Tief jedoch knapp über dem Tief des bullischen Vorgängers und überlappt er diesen fast vollständig, bilden beide eine kleine gemeinsame Range. Der Bruch nur des jüngeren Tiefs ist noch kein Ausbruch aus dem Paar.',
      'Genau an dieser inneren Grenze können frühe Shorts gefüllt werden und sofort einen Rücklauf erleben. Der Kurs testet das alte Tief, hält dort und zieht wieder an. Wer das gesamte Paar markierte, erkennt den fehlenden Bruch der äußeren Linie.',
      'Im Hintergrund des Chartfalls steht zudem ein vorheriger kräftiger Aufwärtsabschnitt. Dessen erster kleiner Gegenbar muss nicht verkauft werden. Ein späterer Pullback mit bullischer Folge kann die bessere Mit-Trend-Lesart sein.',
    ], callout: 'Nicht unter dem letzten Bar short sein, wenn sein Tief noch innerhalb des Paars liegt.',
    diagramTitle: 'Inneres Tief bricht, äußeres hält',
    caption: 'Das selbst konstruierte Paar markiert zwei nahe, aber unterschiedliche Tiefs.',
    observations: ['Der jüngere Bar überlappt den älteren fast vollständig.', 'Der erste Short-Trigger liegt noch innerhalb des Paars.', 'Die äußere Tiefzone bleibt verteidigt.'],
    prompt: 'Ein Bärenbar im Zwei-Bar-Paar hat ein höheres Tief als der Vorbar. Der Kurs fällt knapp unter den jüngeren Bar und dreht. Was wurde nicht gebrochen?',
    answers: [['Das tiefere Tief des gesamten Paars.', 'Richtig. Es ist die äußere Grenze des Setups.'], ['Die Eröffnung des letzten Bars.', 'Das ist nicht die entscheidende Paargrenze.'], ['Der gleitende Durchschnitt auf jedem Chart.', 'Dazu gibt es keine Information.']], correct: 0,
    takeaways: ['Starke Überlappung macht aus zwei Bars eine Einheit.', 'Innere und äußere Grenze trennen.', 'Vorherigen Trend beim Gegensignal berücksichtigen.'],
  },
  {
    number: 26, title: 'Fall 6.7: Nach dem unsicheren Open wird der zweite Boden wichtiger',
    summary: 'Zwei gescheiterte Ausbrüche und ein höheres Tief helfen, den Anfang neu zu lesen.',
    section: 'Chartfall 6.7', anchors: ['Abbildung 6.7 · erste Stunde', 'Doppelboden und höheres Tief', 'ii als später Einstieg'],
    scenario: 'c06-case-07',
    paragraphs: [
      'In der ersten Stunde können Ausbrüche über und unter eine enge Eröffnungszone nacheinander scheitern. Der erste Gegenschlag mag interessant aussehen, doch solange beide Seiten sofort zurückkehren, ist die Lage unklar. Warten schützt vor einer voreiligen Festlegung.',
      'Der Markt testet danach den unteren Bereich erneut und schafft kein deutlich tieferes Tief. Eine weitere Korrektur hält höher. Diese Folge aus Doppeltest und höherem Tief liefert mehr Belege für Käufer als der erste starke Eröffnungsbar allein.',
      'Ein ii oberhalb des höheren Tiefs kann nun eine genaue Auslösung bieten. Die kleine Form steht hier nicht isoliert, sondern ist das letzte Glied einer Reihe gescheiterter Verkaufsversuche. Scheitert auch der ii-Ausbruch, muss die These wieder geprüft werden.',
    ], callout: 'Im unruhigen Open ist der zweite klare Test oft wertvoller als der erste Impuls.',
    diagramTitle: 'Doppeltest, höheres Tief und ii',
    caption: 'Ein eigener Kursverlauf zeigt erst zweiseitige Fehlausbrüche und später eine geordnete Käuferstruktur.',
    observations: ['Frühe Brüche beider Grenzen halten nicht.', 'Der zweite Test findet Käufer.', 'Der spätere ii bietet erst jetzt einen klareren Auslöser.'],
    prompt: 'Nach widersprüchlichen Eröffnungsbars hält ein zweiter Tief-Test, danach bildet sich ein höheres Tief mit ii. Was macht den Long nachvollziehbarer?',
    answers: [['Allein die zwei winzigen Inside-Bars.', 'Sie sind nur die letzte Strukturstufe.'], ['Die Folge aus fehlenden neuen Tiefs und einem späteren Einstiegspunkt.', 'Richtig. Mehrere Ereignisse tragen die These.'], ['Ein beliebiger erster grüner Bar am Open.', 'Der allein war im unklaren Open zu wenig.']], correct: 1,
    takeaways: ['Doppelte Fehlausbrüche signalisieren Unklarheit.', 'Doppeltest und höheres Tief geben Struktur.', 'Ein ii kann den späteren Einstieg präzisieren.'],
  },
  {
    number: 27, title: 'Fall 6.8: Ein winziger Bar kann die Struktur markieren',
    summary: 'Die absolute Spanne ist kleiner als seine Bedeutung als höheres Tief.',
    section: 'Chartfall 6.8', anchors: ['Abbildung 6.8 · winziger Signal-Bar', 'Höheres Tief nach Kanalbruch', 'Erste und zweite Umkehr'],
    scenario: 'c06-case-08',
    paragraphs: [
      'Ein sehr kleiner Bar wirkt auf einem breiten Tageschart fast wie ein Punkt. Betrachtet man jedoch die Reihe der Tiefs und Schlüsse, kann er genau das höhere Tief markieren, an dem Verkäufer ihren nächsten Versuch aufgeben.',
      'Im vorherigen Bärenkanal war der erste Gegenversuch schwach und fand noch keine Folge. Nach einem Bruch der engen Struktur und einem erneuten, weniger tiefen Rücklauf hat derselbe kleine Bar eine andere Funktion: Er setzt eine Grenze unter einen zweiten Versuch der Käufer.',
      'Der Fall lehrt, nicht nach optischer Größe zu sortieren. Entscheidend sind die Reihenfolge von Verkaufsdruck, erster Gegenreaktion, fehlendem Anschluss nach unten und dem späteren höheren Tief. Ohne diese Schritte wäre der winzige Bar tatsächlich wenig aussagekräftig.',
    ], callout: 'Die Rolle eines Bars entsteht aus seiner Stellung in der Folge, nicht aus Pixelgröße.',
    diagramTitle: 'Kanalbruch und kleines höheres Tief',
    caption: 'Das eigene Schema hebt einen winzigen Bar nach einem früheren, gescheiterten Umkehrversuch hervor.',
    observations: ['Vorher dominiert ein enger Bärenkanal.', 'Der erste Gegenschlag reicht nicht.', 'Das spätere höhere Tief verändert die Struktur.'],
    prompt: 'Warum ist der zweite winzige Bar nach einem gebrochenen Bärenkanal wichtiger als ein ähnlicher früherer Bar?',
    answers: [['Weil seine Spanne größer geworden ist.', 'Die Größe ist gerade nicht der Punkt.'], ['Weil er nach früherer Kaufreaktion ein höheres Tief markiert.', 'Richtig. Die neue Struktur gibt ihm Bedeutung.'], ['Weil winzige Bars immer einen Trend starten.', 'Ohne Kontext gilt das nicht.']], correct: 1,
    takeaways: ['Absolute Bargröße kann täuschen.', 'Ein zweiter Versuch trägt andere Information als der erste.', 'Höhere Tiefs nach Strukturbruch verdienen Aufmerksamkeit.'],
  },
  {
    number: 28, title: 'Fall 6.9: ii auf fünf Minuten, Doppeltest auf einer Minute',
    summary: 'Ein kleines Kompressionsmuster kann eine geordnete Umkehr verbergen.',
    section: 'Chartfall 6.9', anchors: ['Abbildung 6.9 · ii und kleinere Zeitebene', 'Wiederholte Tief-Tests', 'Gerichteter letzter Inside-Bar'],
    scenario: 'c06-case-09',
    paragraphs: [
      'Zwei ineinanderliegende Bars auf dem Fünf-Minuten-Chart verdichten viele einzelne Käufe und Verkäufe. In einer kleineren Zeitebene kann man sehen, dass die Tiefzone mehrmals getestet und dabei immer wieder gehalten wurde.',
      'Diese Detailansicht hilft beim Verständnis, ist aber nicht zwingend nötig, um den größeren ii zu beurteilen. Steht er als höheres Tief nach einer deutlichen Gegenbewegung und schließt der letzte kleine Bar bullisch, haben Käufer mehr Argumente als bei einer körperlosen Kompression in der Range-Mitte.',
      'Im Fall des Buches zeigen zwei solcher Formationen nacheinander eine aufsteigende Tiefstruktur. Ein isolierter Blick auf ein einziges Muster hätte diese Entwicklung verschleiert. Die Auslösung muss dennoch außerhalb der kleinen Spanne erfolgen.',
    ], callout: 'Ein ii kann eine Reihe kleiner verteidigter Tiefs zusammenfassen.',
    diagramTitle: 'Kompression im großen, wiederholter Test im kleinen Bild',
    caption: 'Eigene Panels zeigen dieselbe Idee als verschachtelte Bars und als mehrere Mikrotests.',
    observations: ['Die größere Spanne wird enger.', 'Mehrere kleine Rückläufe halten oberhalb des alten Tiefs.', 'Der bullische Schluss des letzten Bars passt zur Long-These.'],
    prompt: 'Was verbessert ein ii-Long nach einem höheren Tief?',
    answers: [['Ein letzter kleiner Bullenbar und vorher verteidigte Tiefs.', 'Richtig. Form und Struktur stützen sich gegenseitig.'], ['Ein großer Doji mitten in einer Range.', 'Er zeigt eher Balance ohne Vorteil.'], ['Die Behauptung, der nächste Bar könne nicht fallen.', 'Jede Auslösung bleibt unsicher.']], correct: 0,
    takeaways: ['Kompression fasst Detailbewegungen zusammen.', 'Ein höheres Tief gibt dem ii Richtungskontext.', 'Kleinere Zeitebenen dürfen erklären, aber nicht nachträglich Bestätigung erfinden.'],
  },
  {
    number: 29, title: 'Fall 6.10: Ein Mikro-Doppel ist manchmal eine Flag',
    summary: 'Gleiche Tiefs im Abwärtsspike und gleiche Hochs im Aufwärtsspike können Fortsetzung vorbereiten.',
    section: 'Chartfall 6.10', anchors: ['Abbildung 6.10 · Mikro-Doppel', 'Ein-Bar-Bärenflag', 'Ein-Bar-Bullenflag'],
    scenario: 'c06-case-10',
    paragraphs: [
      'Ein fast identisches Tief zweier benachbarter Bars klingt nach Doppeltief. Wenn der Markt gerade steil fällt und die bullische Zwischenkerze nur kurz pausiert, steht das Paar aber weiterhin unter Verkäuferkontrolle. Unter den gemeinsamen Tiefs kann die Abwärtsbewegung wieder einsetzen.',
      'Spiegelbildlich kann ein kleiner Bärenbar nach einem kräftigen Bullenbar mit nahezu gleichem Hoch eher eine ein-Bars-Bullenflag als ein ernsthafter Gipfel sein. Ein Bruch über die Hochzone zwingt frühe Gegenspieler zum Ausstieg.',
      'Die Zusatzdiskussion erinnert an einen wichtigen Vorbehalt: Größere, sich stark überlappende Bars nach einem Ausbruch können den Anfang einer neuen Range markieren. Der Mikro-Doppelname allein rechtfertigt weder einen schlechten Preis noch einen Einstieg direkt in Widerstand.',
    ], callout: 'Zwei gleiche Extreme zeigen eine Grenze; der Spike entscheidet über ihre Rolle.',
    diagramTitle: 'Mikro-Doppel als Fortsetzungsgrenze',
    caption: 'Eigene Bären- und Bullenbeispiele mit jeweils zwei nahe gleichen Extrempunkten.',
    observations: ['Im steilen Trend ist die Pause kurz.', 'Gleiche Extrempunkte bilden eine sichtbare Triggerzone.', 'Starke Überlappung kann die Fortsetzungsthese schwächen.'],
    prompt: 'Zwei fast gleiche Tiefs entstehen direkt in einem Bärenspike. Was ist neben einer Umkehr ausdrücklich möglich?',
    answers: [['Eine ein-Bars-Bärenflag mit Fortsetzung unter den Tiefs.', 'Richtig. Der starke Trend verändert die Doppelform.'], ['Ein garantierter Bullen-Ausbruch.', 'Dafür fehlt Kaufkontrolle.'], ['Dass Hochs und Tiefs irrelevant werden.', 'Die gemeinsame Grenze bleibt gerade relevant.']], correct: 0,
    takeaways: ['Mikro-Doppel sind klein, aber als Grenze klar.', 'Im Spike können sie Fortsetzungsflags sein.', 'Überlappung und nächster Preisbereich verhindern blindes Folgen.'],
  },
  {
    number: 30, title: 'Fall 6.11: Zwei-Bar-Umkehr nach wiederholtem Sell-Climax',
    summary: 'Eine starke Gegenkerze wird erst durch Ort und erschöpften Verkaufsverlauf interessant.',
    section: 'Chartfall 6.11', anchors: ['Abbildung 6.11 · starkes Paar', 'Wiederholte Sell-Climaxes', 'Test der Kanalunterkante'],
    scenario: 'c06-case-11',
    paragraphs: [
      'Ein erster Long gegen einen intakten Bärentrend ist oft heikel. Nach zahlreichen immer tieferen Bars und mehreren außergewöhnlichen Verkaufsschüben ändert sich das Verhältnis: Die Bewegung wirkt schwer fortsetzbar, besonders an der Unterseite eines Kanals.',
      'Folgt auf einen letzten großen Bärenbar ein kräftiger Bullenbar mit hohem Schluss, entsteht ein deutliches Zwei-Bar-Gegensignal. Es begründet zunächst eine Korrektur in mehreren Abschnitten und über mehrere Bars. Ob der Markt daraus einen neuen Bullenmarkt macht, bleibt offen.',
      'Die tiefere Fallbesprechung verbindet den anfänglichen Spike mit einem anschließenden Bärenkanal. Bei sehr starker Verkaufsdynamik kann die Korrektur trotzdem flach bleiben oder erst auf einer größeren Zeitebene sichtbar werden. Ein statistischer Erwartungsbereich ist kein Anspruch auf eine bestimmte Strecke.',
    ], callout: 'Der erste Gegenversuch gewinnt erst durch Klimax-Folge, Testzone und kräftiges Paar an Gewicht.',
    diagramTitle: 'Mehrfacher Sell-Climax und Gegenpaar',
    caption: 'Das eigene Beispiel zeigt drei anwachsende Verkaufsschübe und einen entschlossenen Gegenbar.',
    observations: ['Der Verkaufsverlauf ist bereits ausgedehnt.', 'Ein weiteres Tief liegt am Kanalrand.', 'Das Paar zeigt erstmals deutliche Gegenseite.'],
    prompt: 'Welche Erwartung ist nach einer starken Zwei-Bar-Umkehr am Ende mehrerer Sell-Climaxes angemessen?',
    answers: [['Mindestens eine mögliche mehrteilige Korrektur prüfen.', 'Richtig. Die volle Trendwende wäre eine stärkere, noch offene These.'], ['Sofortigen neuen Bullenmarkt als Tatsache behandeln.', 'Das geht über die beobachteten Bars hinaus.'], ['Den letzten Verkauf ignorieren, weil er groß war.', 'Die große Kerze ist ein zentraler Teil des Klimax-Kontexts.']], correct: 0,
    takeaways: ['Wiederholte Klimaxe verändern die Gegen-Trend-Chance.', 'Ein kräftiges Paar liefert die sichtbare Gegeninitiative.', 'Korrektur und dauerhafte Wende getrennt halten.'],
  },
  {
    number: 31, title: 'Fall 6.12: Das bärische Paar nach einem Buy-Climax',
    summary: 'Die äußere Paargrenze und der vorherige Übertreibungsschub zählen gemeinsam.',
    section: 'Chartfall 6.12', anchors: ['Abbildung 6.12 · Buy-Climax', 'Bruch über Vortageshoch und Kanal', 'Zwei-Bar-Top nach letzter Flag'],
    scenario: 'c06-case-12',
    paragraphs: [
      'Nach einem Aufwärts-Spike und mehreren weiteren Schüben kann ein kleiner letzter Ausbruch über eine alte Hochzone entstehen. Direkt darauf nimmt ein großer Bärenbar einen bullischen Vorgänger zurück. Der Ort nach der überdehnten Bewegung gibt dem Zwei-Bar-Top mehr Sinn als seine Kerzenfarben allein.',
      'Wenn die beiden Bars stark überlappen, liegt die saubere Short-Schwelle unter dem tieferen Tief beider Bars. Ein Bruch nur des zweiten Bars kann die gemeinsame Range intakt lassen. Die größere Triggerdistanz verändert allerdings auch Stop und Verhältnis zum nächsten Ziel.',
      'Andere schöne Gegenpaare innerhalb der vorherigen Abwärtskorrektur waren weniger überzeugend: Dort dominierten noch Bären, und mehrere große Bars überlappten am Durchschnitt. Der Fall zeigt, dass ein Zwei-Bar-Muster je nach Platz einen Klimax beenden oder eine kurze Range-Pause sein kann.',
    ], callout: 'Ein starkes Top-Paar braucht den richtigen Ort und den Bruch seiner gesamten Spanne.',
    diagramTitle: 'Letzter Hoch-Ausbruch und bärisches Paar',
    caption: 'Ein eigenes Schema verbindet drei Aufwärtsschübe, überlappende Top-Bars und das tiefere Paar-Tief.',
    observations: ['Die Aufwärtsbewegung hat bereits mehrere Schübe.', 'Der Bruch über das alte Hoch hält nicht.', 'Die äußere Untergrenze beider Bars ist der klarere Test.'],
    prompt: 'Zwei stark überlappende Bars kehren einen späten Ausbruch über ein altes Hoch um. Was muss der Short-Plan beachten?',
    answers: [['Nur das Tief des jüngeren Bars.', 'Das kann innerhalb des Paars liegen.'], ['Das tiefere Paar-Tief und den Platz bis zur nächsten Unterstützung.', 'Richtig. Auslösung und Risiko gehören zusammen.'], ['Nur, dass der zweite Bar rot ist.', 'Die Farbe ersetzt weder Ort noch Trigger.']], correct: 1,
    takeaways: ['Klimax-Ort verstärkt das Gegenpaar.', 'Starkes Überlappen schafft eine gemeinsame Grenze.', 'Späte Umkehr und früher Range-Lärm unterscheiden.'],
  },
  {
    number: 32, title: 'Fall 6.13: Kein Schatten ist nur im passenden Trend stark',
    summary: 'Ein Bar ohne Tails wirkt im Bärenspike anders als derselbe Bar in späterer Balance.',
    section: 'Chartfall 6.13', anchors: ['Abbildung 6.13 · shaved Bars', 'Bärenbar ohne Tails im Spike', 'Spätere Bars in Trading Range'],
    scenario: 'c06-case-13',
    paragraphs: [
      'Ein Bärenbar eröffnet nahe seinem Hoch, wird durchgehend verkauft und schließt nahe seinem Tief. Inmitten eines gerade entstehenden kräftigen Abwärtstrends kann diese Form starken Druck bis zum Schluss zeigen. Ein weiterer Rücklauf oder ein kurzer Pause-Bar bietet dann eher einen Short-Kontext.',
      'Später erscheinen ebenfalls Bars ohne einzelne Schatten, doch die Folge ist inzwischen stärker überlappt und zweiseitig. Aus der identischen Form folgt kein zweiter Bärenspike. Der Unterschied liegt in der umgebenden Preisfolge, nicht in einem Pixel am Kerzenende.',
      'Die vertiefte Betrachtung zeigt zudem, wie ein Sell-Climax nach einem frühen Spike zu Range-Verhalten führen kann. Selbst ein gutes erstes Pausensignal verdient dann kleinere Erwartungen. Prüfe, ob Käufer schon Gegentests und längere Rückläufe durchsetzen.',
    ], callout: 'Shaved beschreibt den Bar; Trenddruck entsteht aus der Folge.',
    diagramTitle: 'Shaved Bärenbar vor und nach der Verlangsamung',
    caption: 'Zwei eigens konstruierte Phasen zeigen schnelle Fortsetzung und spätere Überlappung.',
    observations: ['Früh fällt der Kurs ohne große Gegenbars.', 'Später handeln mehrere Bars denselben Preisraum.', 'Das gleiche Schattenmerkmal bekommt dadurch einen anderen Wert.'],
    prompt: 'Wann ist ein Bärenbar ohne Tails der bessere Fortsetzungs-Hinweis?',
    answers: [['Während eines schnellen, kaum überlappten Bärenspikes.', 'Richtig. Form und Trendverhalten passen zusammen.'], ['Nach zehn überlappenden Bars einer flachen Range.', 'Dort kann die Form bedeutungslos sein.'], ['Immer bei geringem Volumen unabhängig vom Preis.', 'Der Kurskontext bleibt wesentlich.']], correct: 0,
    takeaways: ['Ein Schluss am Tief zeigt momentanen Druck.', 'Schneller Spike verstärkt die Aussage.', 'Spätere Range-Überlappung kann sie entwerten.'],
  },
  {
    number: 33, title: 'Fall 6.14: Hammer gegen enge Range am Durchschnitt',
    summary: 'Ein optisch hübscher Umkehr-Bar bleibt schwach, wenn direkt darüber Verkäufer warten.',
    section: 'Chartfall 6.14 · erster Teil', anchors: ['Abbildung 6.14 · frühe Signal-Bars', 'Mehrere Dojis unter Durchschnitt', 'Zweiter Tief-Test mit bullischer Kontrolle'],
    scenario: 'c06-case-14',
    paragraphs: [
      'Ein einzelner Bar mit langem unteren Schatten kann an einen klassischen Hammer erinnern. Im Lehrfall steht er jedoch nach mehreren überlappenden Dojis direkt unter dem Durchschnitt. Käufer müssten praktisch sofort durch eine Zone, an der die letzten Vorstöße bereits stockten.',
      'Ein späterer bullischer Bar entsteht nach einem neuen Tief und dem zweiten Versuch, die untere Zone zurückzuweisen. Sein Körper und die anschließenden Bars zeigen mehr Kaufkontrolle. Der Gegenüberstellung entnimmt man keine feste Hammer-Regel, sondern die Bedeutung des zweiten Tests.',
      'Auch die Bargröße wirkt sich auf den Plan aus: Breite Bars erfordern eine größere Preisstrecke bis zur klaren Ungültigkeit. Ein Einstieg nahe dem Range-Deckel mit engem Ziel und großem Fehlpunkt ist trotz hübscher Kerze unattraktiv.',
    ], callout: 'Ein Kerzenname ersetzt weder Zielraum noch den Test der vorherigen Zone.',
    diagramTitle: 'Erster Doji und späterer bestätigter Tief-Test',
    caption: 'Das eigenständige Schema stellt einen Hammer unter Widerstand einer späteren Käuferreaktion gegenüber.',
    observations: ['Der erste Bar sitzt unter einer dichten Verkaufszone.', 'Der zweite Test entsteht tiefer und erhält Anschluss.', 'Signalform und verfügbare Strecke unterscheiden sich.'],
    prompt: 'Warum ist ein Hammer-Doji direkt unter einer mehrfach getesteten Range-Oberkante kein starker Long?',
    answers: [['Weil die Kerzenbezeichnung falsch übersetzt ist.', 'Der Name ist für die Entscheidung nicht ausschlaggebend.'], ['Weil wenig freier Raum und viel Überlappung bestehen.', 'Richtig. Der Kontext beschränkt den möglichen Anschluss.'], ['Weil ein Doji nie eine Umkehr begleiten kann.', 'Am passenden Rand kann er Teil eines Setups sein.']], correct: 1,
    takeaways: ['Ein schöner Einzelbar kann am falschen Ort schwach sein.', 'Zweiter Tief-Test und Anschluss ändern die Lage.', 'Bargröße beeinflusst den Fehlpunkt und den Zielraum.'],
  },
  {
    number: 34, title: 'Fall 6.14: Vom starken Hoch zum schwachen Gegenversuch',
    summary: 'Signalqualität wandelt sich, wenn Trenddruck, Klimax und spätere Range einander ablösen.',
    section: 'Chartfall 6.14 · zweiter Teil', anchors: ['Abbildung 6.14 · spätere Signal-Bars', 'Erster Doji nach starken Bull-Bars', 'Zweiter Short und spätere Range'],
    scenario: 'c06-case-14',
    paragraphs: [
      'Nach mehreren kräftigen Bullenbars ist der erste kleine bärische Doji am Hoch meist nur ein schwacher Gegenversuch. Die Trendseite hat noch keine ernsthafte Verkaufswelle gesehen. Wer sofort shortet, setzt gegen eine Folge höherer Schlüsse.',
      'Später hat der Markt einen tieferen Rücklauf zum Durchschnitt absolviert und testet erneut ein Hoch. Ein zweiter Verkaufsversuch mit deutlicherem bärischem Schluss und mehr strukturellem Kontext kann eine Korrektur wesentlich besser begründen.',
      'Wenn daraus eine Trading Range wird, wechselt erneut die Logik: Ein kleiner Doji am oberen Rand kann eine sinnvolle Verkaufsmarke sein, während derselbe Bar mitten im Tagesraum wenig bedeutet. Der ausführliche Buchfall zeigt genau diese Wandlung der Marktphase über viele Bars.',
    ], callout: 'Bewerte denselben Signaltyp erneut, sobald Trend, Korrektur und Range wechseln.',
    diagramTitle: 'Erster und zweiter Verkaufsversuch',
    caption: 'Das Lehrschema des Falls bleibt gleich; jetzt wird der spätere Teil seiner Marktphasen gelesen.',
    observations: ['Erster Doji widerspricht vielen starken Bull-Bars.', 'Nach Rücklauf und Retest gibt es mehr Verkaufsargumente.', 'In der Range wird der Ort am oberen Rand entscheidend.'],
    prompt: 'Was verbessert einen späteren Short nach einem vorher gescheiterten ersten Versuch am Hoch?',
    answers: [['Nur die Anzahl roter Kerzen im Screenshot.', 'Die Zahl ohne Verlauf erklärt nichts.'], ['Vorheriger tieferer Rücklauf, erneuter Hochtest und stärkere Verkäuferreaktion.', 'Richtig. Der zweite Versuch besitzt mehr Kontext.'], ['Dass der Markt nie mehr steigen darf.', 'Eine solche Sicherheit liefert kein Setup.']], correct: 1,
    takeaways: ['Der erste Gegensignal-Bar im starken Trend ist oft schwach.', 'Ein zweiter Test nach struktureller Änderung kann stärker sein.', 'In der Range gelten andere Einstiegsorte.'],
  },
  {
    number: 35, title: 'Fall 6.15: Bullischer Reversal-Bar als Bärenflag',
    summary: 'Im steilen Abverkauf werden frühe Käufer am falschen Rand gefangen.',
    section: 'Chartfall 6.15', anchors: ['Abbildung 6.15 · ein-Bars-Bärenflag', 'Erster Pullback im Bärenspike', 'Späterer Kanalbruch und neuer Long-Kontext'],
    scenario: 'c06-case-15',
    paragraphs: [
      'Ein bullischer Reversal-Bar sieht am Tief nach Entlastung aus. Im ungebrochenen Bärenspike ist er aber häufig nur die erste kleine Pause. Wird sein Hoch nicht überwunden und sein Tief bald unterschritten, verlassen frühe Käufer ihre Positionen und der Trend erhält zusätzlichen Verkaufsdruck.',
      'Auch mehrere Dojis nebeneinander können eine kleine seitliche Bärenflag bilden. Der zweite misslungene Anstieg aus dieser Zone macht einen Short unter der gesamten Pause nachvollziehbarer als einen Long wegen der einzelnen grünen Kerze.',
      'Erst nach einem deutlichen Bruch der fallenden Struktur und einem späteren höheren Tief wird eine bullische Gegenbewegung plausibler. Der Fall vereint somit zwei verschiedene Mikro-Doppel: eines im Verkaufs-Spike mit Fortsetzungsrolle und eines nach dem Strukturwechsel mit möglicher Umkehrrolle.',
    ], callout: 'Der erste Gegen-Bar im steilen Spike ist oft Teil der alten Richtung.',
    diagramTitle: 'Frühe Falle, späterer Strukturwechsel',
    caption: 'Eigene Folge: kleine bullische Pause im Bärenspike, dann erst deutlich später Kanalbruch und höheres Tief.',
    observations: ['Der erste grüne Bar löst oben nicht aus.', 'Unter der Pause verkaufen Trendseite und enttäuschte Käufer.', 'Nach Kanalbruch gelten neue Voraussetzungen.'],
    prompt: 'Ein bullischer Reversal-Bar entsteht nach mehreren großen Bärenbars und wird sofort unten gebrochen. Was ist die naheliegende Einordnung?',
    answers: [['Ein-Bars-Bärenflag mit gefangenen frühen Longs.', 'Richtig. Der Verkaufskontext blieb intakt.'], ['Bestätigter Bullenmarkt trotz Bruch unten.', 'Die Preisfolge widerspricht dem.'], ['Eine Gegenposition ist unabhängig vom Trend Pflicht.', 'Der Trendkontext verlangt gerade Zurückhaltung.']], correct: 0,
    takeaways: ['Bullische Form kann im Bärenspike Fortsetzung vorbereiten.', 'Mehrere Dojis können eine kleine Flag bilden.', 'Späterer Kanalbruch ändert die Rolle ähnlicher Tiefmuster.'],
  },
  {
    number: 36, title: 'Fall 6.16: Viele Setups, aber nicht jeder erste Versuch',
    summary: 'Ausbruch, Rücklauf und zweiter Versuch ordnen einen lebhaften Tageschart.',
    section: 'Chartfall 6.16 · erster Teil', anchors: ['Abbildung 6.16 · frühe Setups', 'Zwei-Bar-Boden und Follow-through', 'Dojis am Hoch und zweiter Short'],
    scenario: 'c06-case-16',
    paragraphs: [
      'Ein Zwei-Bar-Boden nach einem kurzzeitig neuen Tief ist ein möglicher Beginn einer Aufwärtsfolge. Ein kräftiger Anschlussbar macht die These besser. Der erste kleine Bärenbar am Durchschnitt kann dagegen nur der Pullback sein, aus dem Käufer den neuen Impuls fortsetzen.',
      'Später drängt der Markt an ein altes Hoch und mehrere Dojis erscheinen. Einer allein ist kein starker Short: In den Dojis handeln beide Seiten. Erst ein weiterer Versuch mit klarer bärischer Rücknahme und dem Bruch einer gemeinsamen Untergrenze macht eine Korrektur leichter zu begründen.',
      'Der tiefergehende Fall enthält gleichzeitig einen Kanal mit mehreren Aufwärtsschüben. Das erklärt, warum der spätere Short mehr Gewicht erhält als der erste Doji. Der Lernende sollte die Abfolge markieren, statt die vielen Signale gleichzeitig als gleichwertig zu behandeln.',
    ], callout: 'In einem vollen Chart gewinnt die Reihenfolge der Versuche über die Zahl der Muster.',
    diagramTitle: 'Boden, Anschluss, Hochtest und zweiter Short',
    caption: 'Eigenes Mehrphasen-Schema zum Lesen der frühen Entscheidungen des Falls.',
    observations: ['Der Boden erhält erst mit Anschluss Gewicht.', 'Am Hoch häufen sich schwache erste Gegenbars.', 'Der zweite Versuch zeigt klarere Untergrenzen.'],
    prompt: 'Am Ende eines kräftigen Aufwärtsschubs erscheinen drei überlappende Dojis. Was verbessert einen Short?',
    answers: [['Ein zweiter Versuch mit erkennbarem bärischem Bruch.', 'Richtig. Er liefert mehr als den ersten Doji.'], ['Ein beliebiger roter Pixel innerhalb des ersten Dojis.', 'Die kleine Farbänderung genügt nicht.'], ['Die Gewissheit, dass drei Dojis immer einen Crash auslösen.', 'Das folgt aus dem Muster nicht.']], correct: 0,
    takeaways: ['Anschluss bestätigt den ersten Boden besser.', 'Mehrere Dojis sind zunächst zweiseitig.', 'Ein weiterer klarer Bruch kann den späteren Gegenplan stützen.'],
  },
  {
    number: 37, title: 'Fall 6.16: Gescheiterte Ausbrüche ändern den Tagesplan',
    summary: 'Ein zu früher Gegen-Long, ein ioi und ein Range-Rand haben verschiedene Qualität.',
    section: 'Chartfall 6.16 · zweiter Teil', anchors: ['Abbildung 6.16 · spätere Setups', 'Gefangene Käufer nach kleinem Reversal', 'Zweiter Tief-Test und ioi'],
    scenario: 'c06-case-16',
    paragraphs: [
      'Nachdem die Aufwärtsfolge bricht, wirkt ein kleiner bullischer Reversal-Bar als schnelle Rettung. Käufer werden jedoch sofort in einem starken Gegenbar gefangen. Im bereits fallenden Markt wird der Ausstieg dieser frühen Longs selbst zu zusätzlichem Verkaufsdruck.',
      'Ein späterer Schub unter ein früheres Swingtief erhält ebenfalls keinen überzeugenden Anschluss. Jetzt steht der Kurs am unteren Rand eines Tagesraums und bietet einen zweiten Versuch mit ioi-Struktur. Dieselbe Gegenidee, die mitten im Abverkauf zu früh war, hat am getesteten Rand mehr Begründung.',
      'Der Fall erinnert zudem an die Gefahr großer überlappender Bars am Durchschnitt: Ein bullischer Bruch dort kann die nächste Falle sein. Bewerte jede neue Formation gegen den aktuellen Tageszustand, nicht gegen die Erinnerung an das erste Setup.',
    ], callout: 'Ein guter zweiter Test ist mehr als die Wiederholung des ersten kleinen Bars.',
    diagramTitle: 'Erster Long scheitert, späterer Randtest hält',
    caption: 'Das eigene Chartbild wird nun von der späteren Verkaufs- und Rückkehrphase aus gelesen.',
    observations: ['Der frühe bullische Bar wird sofort zurückgenommen.', 'Der spätere Tiefbruch hält nicht.', 'Am Range-Rand bekommt ioi einen anderen Ort.'],
    prompt: 'Warum kann ein späterer Long am zweiten Range-Tief sinnvoller sein als der erste Long mitten im Verkaufsbein?',
    answers: [['Weil der zweite Versuch eine getestete Außenzone und gescheiterten Verkaufsanschluss zeigt.', 'Richtig. Ort und Folge ändern die These.'], ['Weil ioi jeden Verlust ausschließt.', 'Das Muster garantiert nichts.'], ['Weil der erste Versuch rückwirkend richtig war.', 'Er war eine andere, gescheiterte Entscheidung.']], correct: 0,
    takeaways: ['Frühe Käufer können in starkem Gegenbar gefangen werden.', 'Der zweite Außentest liefert neue Evidenz.', 'Tagesphase und Lage verändern die Funktion von ioi.'],
  },
  {
    number: 38, title: 'Fall 6.17: Der Bärenbar wird zur Bullenflag',
    summary: 'Starker voriger Kaufdruck begrenzt die Aussage des ersten Verkaufsversuchs.',
    section: 'Chartfall 6.17', anchors: ['Abbildung 6.17 · Gegenbar im Bullenlauf', 'Kaufklimax und notwendiger Pullback', 'Späterer zweiter Long nach Bärenkanal'],
    scenario: 'c06-case-17',
    paragraphs: [
      'Nach mehreren aufeinanderfolgenden Bullenbars kann ein einzelner starker Bärenbar wie eine plötzliche Trendwende aussehen. Ohne vorherigen Bruch der Aufwärtsstruktur oder eine zweite Verkaufswelle ist er zunächst eher eine Pause, aus der Käufer wieder zugreifen können.',
      'Der konkrete Fall ist anspruchsvoller, weil der Bullenlauf spät parabolisch beschleunigt. Ein sofortiger weiterer Long direkt nach dem Klimax-Bar kann ebenfalls ungünstig sein. Das vernünftige Warten auf einen Rücklauf ist etwas anderes als der voreilige Short gegen den ersten starken Trend.',
      'Später nach einem echten Abwärtsabschnitt und mehreren Verkaufsschüben taucht eine zweite Kaufgelegenheit auf. Ein erster Gegenbar mit großem unteren Schatten zeigt Reaktion; ein höheres Tief oder zweiter bullischer Auslöser gibt ihr bessere Struktur. Auch dieser Long ist zunächst nur eine Gegenbewegung zu einem Bärenkanal.',
    ], callout: 'Weder ersten Gegenbar blind shorten noch späten Klimax blind kaufen.',
    diagramTitle: 'Klimax, Pullback und späterer Zweitversuch',
    caption: 'Eine selbst entworfene Folge trennt den frühen Bärenbar vom späteren strukturierten Long.',
    observations: ['Der erste Bärenbar folgt starker Kaufkontrolle.', 'Die Aufwärtsphase ist zugleich überdehnt.', 'Der spätere Long folgt einem neuen, eigenständigen Test.'],
    prompt: 'Fünf starke Bullenbars enden in einem großen Klimax-Bar; danach kommt der erste Bärenbar. Welche Haltung berücksichtigt beide Risiken?',
    answers: [['Auf einen geordneten Rücklauf und neue Evidenz warten.', 'Richtig. Der erste Short und der späte Long sind beide schwierig.'], ['Sofort Short mit Gewinngarantie.', 'Der erste Gegenbar hat noch wenig bärische Struktur.'], ['Jeden Preis kaufen, weil der Trend bisher stieg.', 'Der späte Klimax kann einen tieferen Rücklauf auslösen.']], correct: 0,
    takeaways: ['Der erste Bärenbar im starken Bullenlauf ist oft eine Flag.', 'Parabolischer Kaufdruck kann zugleich Korrekturrisiko erhöhen.', 'Spätere zweite Signale brauchen ihren eigenen Kontext.'],
  },
  {
    number: 39, title: 'Fall 6.18: Schwacher Reversal-Bar mit starkem Ort',
    summary: 'Ein kleiner Bar gewinnt durch gescheiterten Ausbruch und exakten Retest an Aussage.',
    section: 'Chartfall 6.18', anchors: ['Abbildung 6.18 · schwache Reversal-Bars', 'Fehlausbruch einer Flag', 'Erneuter Test einer alten Zone'],
    scenario: 'c06-case-18',
    paragraphs: [
      'Ein kleiner Bar nach einem großen Ausbruch sieht häufig zu schwach für eine Umkehr aus. Steht er jedoch am alten Tief, und scheitert der Ausbruch aus der vorherigen Flag, kommen zwei eigenständige Gründe hinzu: die zurückgewiesene Grenze und der erneute Test derselben Preiszone.',
      'Ein bullischer Folgebalken oder ein deutliches Gegenpaar kann aus der bloßen Möglichkeit ein besseres Setup machen. Der schwache Einzelbar ist nicht magisch stärker geworden; der Markt hat neben ihm weitere Information geliefert.',
      'Spiegelbildlich kann ein kleiner Bärenbar nach einem Ausbruch über eine enge Range eine Fehlausbruchsthese vorbereiten. Wird das alte Hoch wieder aufgegeben, gewinnen Verkäufer an Argumenten. Verwechsle dabei die beobachtete Rückkehr nicht mit der Behauptung, der gesamte Tag werde zwangsläufig bärisch.',
    ], callout: 'Schwache Kerze plus guter Ort kann besser sein als starke Kerze mitten im Nichts.',
    diagramTitle: 'Schwacher Bar an einer mehrfach geprüften Grenze',
    caption: 'Eigenes Schema: ein kleiner Gegenbar nach gescheitertem Range-Bruch und späterer Anschluss.',
    observations: ['Die alte Zone wird erneut erreicht.', 'Der Ausbruch hält nicht.', 'Der nächste Bar kann die kleine Gegenreaktion stützen.'],
    prompt: 'Warum kann ein kleiner Reversal-Bar nach einem Fehlausbruch interessant sein?',
    answers: [['Weil der Ort am alten Extrem und der gescheiterte Bruch zusätzliche Belege liefern.', 'Richtig. Die Form wird durch den Kontext ergänzt.'], ['Weil kleine Bars nie scheitern.', 'Ihre Größe bietet keine Garantie.'], ['Weil der ganze Handelstag schon bekannt ist.', 'Nur bisherige Bars dürfen die Entscheidung stützen.']], correct: 0,
    takeaways: ['Ein kleines Signal kann am richtigen Testort tragen.', 'Fehlausbruch und Gegenanschluss sind getrennte Beobachtungen.', 'Keine spätere Tagesentwicklung als frühe Gewissheit ausgeben.'],
  },
  {
    number: 40, title: 'Fall 6.19: Viele shaved Bars ohne Trend',
    summary: 'Wiederholte Schlusskurse an Extremen können in einer engen Range kaum Richtung liefern.',
    section: 'Chartfall 6.19', anchors: ['Abbildung 6.19 · gehäufte shaved Bars', 'Trend-Cluster gegenüber Range-Cluster', 'Fehlausbrüche aus enger Überlappung'],
    scenario: 'c06-case-19',
    paragraphs: [
      'Zuerst fallen mehrere Bars gerichtet und schließen nahe ihren Tiefs. Dort passt ein fehlender unterer Schatten zum allgemeinen Verkaufsdruck. Später häufen sich ebenfalls Bars mit exakten Extrem-Schlüssen, aber nun überlappen ihre Preisbereiche und die Richtung wechselt ständig.',
      'In dieser zweiten Phase beschreibt shaved nur die einzelnen Bars. Eine enge Range zieht Ausbrüche oft wieder in denselben Bereich zurück. Wer jeden schattenlosen Bar als neuen Trendstart nimmt, wird in beide Richtungen hintereinander gefangen.',
      'Der tiefere Chartfall zeigt außerdem, wie ein anfangs möglicher Eröffnungsausbruch mehrmals seine Richtung verliert. Die Qualität der Gegenbewegung lässt sich an Überlappung, großen Schatten und fehlendem Anschluss ablesen. Erst ein klar gehaltener Bruch der gemeinsamen Zone würde die Marktphase verändern.',
    ], callout: 'Der Wert eines Signal-Bars sinkt, wenn viele ähnliche Bars ohne Anschluss auftauchen.',
    diagramTitle: 'Gleiche Form, verschiedene Phase',
    caption: 'Die eigens konstruierte Doppelfolge stellt einen gerichteten shaved-Cluster einer seitlichen Häufung gegenüber.',
    observations: ['Früh passen die Schlüsse zur Trendrichtung.', 'Später überlappen die Bars und wechseln die Seite.', 'Ein Range-Ausbruch braucht Halten außerhalb der gemeinsamen Zone.'],
    prompt: 'Viele Bars ohne Schatten wechseln innerhalb einer engen Range zwischen bullisch und bärisch. Was verliert an Gewicht?',
    answers: [['Die isolierte Deutung eines einzelnen shaved Bars als Trendstärke.', 'Richtig. Häufung ohne Anschluss relativiert die Form.'], ['Die Bedeutung der äußeren Range-Grenzen.', 'Diese Grenzen bleiben relevant.'], ['Die Möglichkeit eines späteren echten Ausbruchs.', 'Ein solcher bleibt möglich, braucht aber Anschluss.']], correct: 0,
    takeaways: ['Shaved im Spike und shaved in Range sind nicht gleich.', 'Häufung ohne gerichteten Anschluss warnt vor Fallen.', 'Die gemeinsame Range-Grenze bleibt der nächste Test.'],
  },
];

export const chapterSixCaseLessons = drafts.map(chapterSixLesson);
