import { PRACTICE_TASK_SCHEMA_VERSION, type OrderTask } from '../practiceTaskTypes';

// C-04 (Teil 2): „Ordne die Schritte“. Die Reihenfolgen folgen ausdrücklich dem Ablauf, den die
// genannten Lektionen selbst vermitteln; eigene Formulierungen, keine Buchzitate.
// Status `approved`: von Robert fachlich freigegeben (siehe docs/C04_AUFGABEN.md).
const draft = { schemaVersion: PRACTICE_TASK_SCHEMA_VERSION, status: 'approved' } as const;

export const c04OrderTasks: OrderTask[] = [
  {
    ...draft,
    id: 'practice.c04.order.read-a-bar',
    title: 'Einen einzelnen Bar lesen',
    unitId: 'price-action-trends.chapter-02',
    lessonIds: ['price-action-trends.chapter-02.lesson-01'],
    prompt: 'Bringe die Schritte in die Reihenfolge, in der du einen einzelnen Bar sinnvoll einordnest.',
    steps: [
      { id: 'control', text: 'Fragen: Hat eine Seite den Preis vom Open bis zum Close durchgesetzt – oder wurde die Bewegung ausgeglichen?' },
      { id: 'body', text: 'Den Körper mit den Nachbarbars vergleichen.' },
      { id: 'tails', text: 'Tails und die Position des Schlusses als Zusatzzeichen prüfen.' },
      { id: 'name', text: 'Erst danach einen Namen für den Bar wählen.' },
    ],
    explanation: 'Die Lektion beginnt mit der Frage nach Kontrolle oder Balance, nicht mit dem Kerzennamen. Der Körper im Vergleich zur Umgebung liefert die erste Antwort, Tails und Schlussposition verfeinern sie, der Name kommt zuletzt.',
    sourceAnchors: ['Kapitel 2 · Trendbar oder Ein-Bar-Range'],
  },
  {
    ...draft,
    id: 'practice.c04.order.counter-spike',
    title: 'Einen Gegen-Spike einordnen',
    unitId: 'price-action-trends.chapter-02',
    lessonIds: ['price-action-trends.chapter-02.lesson-06'],
    prompt: 'Im Bullenmarkt fällt ein kräftiger bärischer Bar. Bringe die Schritte in die passende Reihenfolge.',
    steps: [
      { id: 'notice', text: 'Den kräftigen Gegen-Bar bemerken, ohne sofort auf seine Größe zu reagieren.' },
      { id: 'trend', text: 'Den übergeordneten Trend als Ausgangshypothese festhalten.' },
      { id: 'next', text: 'Den nächsten Bar prüfen: Schafft die Gegenseite Anschluss?' },
      { id: 'classify', text: 'Die Einordnung anpassen: ohne Anschluss eher Flag im alten Trend, mit Anschluss gewinnt die Umkehr an Gewicht.' },
    ],
    explanation: 'Nicht die Schockwirkung des ersten Gegenbars zählt. Erst der Anschluss im nächsten Bar zeigt, ob die neue Seite weiter Druck erzeugt; bis dahin bleibt der Trend die Ausgangshypothese.',
    sourceAnchors: ['Kapitel 2 · Follow-through entscheidet den Spike'],
  },
  {
    ...draft,
    id: 'practice.c04.order.climax-reversal',
    title: 'Vom Klimax zur möglichen Umkehr',
    unitId: 'price-action-trends.chapter-02',
    lessonIds: ['price-action-trends.chapter-02.lesson-08'],
    prompt: 'Auf eine schnelle einseitige Bewegung folgt eine mögliche Umkehr. Ordne die Schritte.',
    steps: [
      { id: 'climax', text: 'Die schnelle einseitige Bewegung (Klimax) erkennen.' },
      { id: 'pause', text: 'Die erste Pause abwarten: Doji, Inside-Bar, Gegenbar oder auffälliger Tail.' },
      { id: 'breakout', text: 'Prüfen, ob ein überzeugender Breakout der Gegenseite folgt.' },
      { id: 'thesis', text: 'Nur mit diesem Gegen-Breakout eine mögliche klimaktische Umkehr annehmen.' },
    ],
    explanation: 'Klimax plus Pause ergibt nur Balance. Erst der zusätzliche Breakout der Gegenseite macht daraus eine belastbare Umkehrthese.',
    sourceAnchors: ['Kapitel 2 · Klimax ist noch keine Umkehr'],
  },
  {
    ...draft,
    id: 'practice.c04.order.failed-breakout',
    title: 'Einen Ausbruch prüfen',
    unitId: 'price-action-trends.chapter-01',
    lessonIds: ['price-action-trends.chapter-01.lesson-07'],
    prompt: 'Der Markt eröffnet über einer wichtigen Grenze. Bringe die Prüfschritte in die richtige Reihenfolge.',
    steps: [
      { id: 'reference', text: 'Das Referenzniveau festhalten, zum Beispiel das Vortageshoch.' },
      { id: 'attempt', text: 'Den Ausbruch darüber als Versuch erkennen – noch nicht als Erfolg.' },
      { id: 'accept', text: 'Prüfen, ob Preise außerhalb der Grenze angenommen werden und Anschluss folgt.' },
      { id: 'reject', text: 'Kehrt der Markt schnell in den alten Bereich zurück, die Breakout-Hypothese schwächen.' },
    ],
    explanation: 'Ein Breakout zeigt einen Versuch. Erst Halten und Follow-through zeigen Erfolg; die schnelle Rückkehr unter die Grenze fängt späte Käufer ein und spricht gegen den Ausbruch.',
    sourceAnchors: ['Kapitel 1 · Fehlausbruch über dem Vortageshoch'],
  },
  {
    ...draft,
    id: 'practice.c04.order.trend-resumption',
    title: 'Die Trendwiederaufnahme',
    unitId: 'price-action-trends.chapter-01',
    lessonIds: ['price-action-trends.chapter-01.lesson-08'],
    prompt: 'Ein Tag entwickelt sich in vier Phasen. Ordne sie in der Reihenfolge, in der sie auftreten.',
    steps: [
      { id: 'impulse', text: 'Starker Trend direkt nach der Eröffnung (Impuls).' },
      { id: 'compression', text: 'Mehrstündige enge Range (Kompression).' },
      { id: 'trap', text: 'Ein kleiner Ausbruch gegen den frühen Trend scheitert sofort (Falle).' },
      { id: 'resumption', text: 'Der Markt nimmt die frühe Richtung mit Anschluss wieder auf.' },
    ],
    explanation: 'Nicht die Uhrzeit handelt, sondern die vollständige Abfolge: Impuls, Kompression, Falle, Wiederaufnahme. Fehlt ein Glied, fehlt auch die These.',
    sourceAnchors: ['Kapitel 1 · Die Falle vor der Trendwiederaufnahme'],
  },
  {
    ...draft,
    id: 'practice.c04.order.high-2',
    title: 'Die High-2-Zählung',
    unitId: 'price-action-trends.chapter-01',
    lessonIds: ['price-action-trends.chapter-01.lesson-06'],
    prompt: 'Im Bullenmarkt zählst du eine Abwärtskorrektur. Bringe die Ereignisse in die richtige Reihenfolge.',
    steps: [
      { id: 'leg1', text: 'Eine Abwärtskorrektur beginnt (erstes Bein).' },
      { id: 'h1', text: 'Ein Bar handelt über dem Hoch seines Vorgängerbars: High 1.' },
      { id: 'leg2', text: 'High 1 scheitert, es folgt ein zweites Abwärtsbein.' },
      { id: 'h2', text: 'Ein erneuter Bruch über ein Vorgängerhoch ist High 2.' },
    ],
    explanation: 'High und Low bezeichnen den Richtungsversuch, die Zahl seine Reihenfolge innerhalb der Korrektur. H2 gibt es erst, nachdem H1 gescheitert und ein zweites Bein entstanden ist.',
    sourceAnchors: ['Kapitel 1 · Beine zählen statt Buchstaben jonglieren'],
  },
  {
    ...draft,
    id: 'practice.c04.order.low-2',
    title: 'Vom Signal-Bar zum Low-2-Entry',
    unitId: 'price-action-trends.chapter-01',
    lessonIds: ['price-action-trends.chapter-01.lesson-06'],
    prompt: 'Ein Bärenkontext bereitet ein Low-2-Setup vor. Ordne die Schritte.',
    steps: [
      { id: 'context', text: 'Bärenkontext: eine Aufwärtskorrektur beginnt (erstes Bein).' },
      { id: 'leg2', text: 'Das erste Bein scheitert, ein zweites Aufwärtsbein entsteht.' },
      { id: 'signal', text: 'Ein bearischer Signal-Bar bereitet das Setup vor.' },
      { id: 'entry', text: 'Der folgende Bruch nach unten erzeugt den Entry-Bar.' },
    ],
    explanation: 'Der Signal-Bar bereitet vor, erst der Bruch nach unten löst aus – dann ist es der Entry-Bar des Low-2-Setups.',
    sourceAnchors: ['Kapitel 1 · Beine zählen statt Buchstaben jonglieren'],
  },
  {
    ...draft,
    id: 'practice.c04.order.trend-bar-quality',
    title: 'Die Qualität eines Trendbars prüfen',
    unitId: 'price-action-trends.chapter-02',
    lessonIds: ['price-action-trends.chapter-02.lesson-09'],
    prompt: 'Ein bullischer Trendbar erscheint. Bringe die Qualitätsprüfung in eine sinnvolle Reihenfolge.',
    steps: [
      { id: 'body', text: 'Den Körper mit den letzten fünf bis zehn Bars vergleichen.' },
      { id: 'shape', text: 'Open, Close und Tails prüfen.' },
      { id: 'position', text: 'Die Position im Trend beachten: Ein ungewöhnlich großer Bar spät im Trend warnt vor Erschöpfung.' },
      { id: 'follow', text: 'Auf gute Folgebars als Bestätigung warten.' },
    ],
    explanation: 'Größe und Form zeigen die Kontrolle im Bar, Trendposition und Folgeverhalten gehören ebenfalls zur Qualitätsprüfung. Mehrere gute Folgebars sind meist stärker als eine einzelne Rekordkerze.',
    sourceAnchors: ['Kapitel 2 · Der ideale Trendbar – und wann Größe warnt'],
  },
];
