import { PRACTICE_TASK_SCHEMA_VERSION, type OrderTask } from '../practiceTaskTypes';

// C-04 Teil 2 (Kapitel 3–10), „Ordne die Schritte“: Die Reihenfolgen folgen ausdrücklich dem Ablauf,
// den die genannten Lektionen selbst vermitteln; eigene Formulierungen, keine Buchzitate.
// Status `draft`: fachliche Freigabe steht aus (siehe docs/C04_AUFGABEN.md).
const draft = { schemaVersion: PRACTICE_TASK_SCHEMA_VERSION, status: 'draft' } as const;

export const c04OrderTasksPart2: OrderTask[] = [
  {
    ...draft,
    id: 'practice.c04.order.failed-breakdown',
    title: 'Vom Tiefbruch zum Spike nach oben',
    unitId: 'brooks-trends.chapter-03',
    lessonIds: ['brooks-trends.chapter-03.lesson-09'],
    prompt: 'Ein Tiefausbruch scheitert. Bringe die Ereignisse in die Reihenfolge, in der sie eintreten.',
    steps: [
      { id: 'break', text: 'Der Markt unterschreitet das Tief des Vortages und erzeugt ein neues Tief.' },
      { id: 'no-hold', text: 'Er kann die tieferen Preise nicht halten: Es fehlt die Akzeptanz.' },
      { id: 'flow', text: 'Bären reduzieren Verkäufe und decken Shorts ein, Bullen kaufen aggressiv.' },
      { id: 'spike', text: 'Ein bullischer Spike sucht anschließend einen neuen Gleichgewichtsbereich.' },
    ],
    explanation: 'Ein neues Extrem ist keine Bestätigung. Ohne Akzeptanz außerhalb der alten Grenze wird der Bruch zum Fehlausbruch; die Verschiebung des Orderstroms nach oben erzeugt den Spike.',
    sourceAnchors: ['Kapitel 3 · Chartfall 3.1: Der gescheiterte Tiefausbruch'],
  },
  {
    ...draft,
    id: 'practice.c04.order.ii-reading',
    title: 'Ein ii sauber lesen',
    unitId: 'brooks-trends.chapter-04',
    lessonIds: ['brooks-trends.chapter-04.lesson-11'],
    prompt: 'Zwei Inside-Bars folgen aufeinander. Bringe die Schritte der sauberen Lesart in die richtige Reihenfolge.',
    steps: [
      { id: 'compression', text: 'Die Kompression erkennen: Hochs und Tiefs rücken zusammen.' },
      { id: 'both', text: 'Beide Seiten planen: Ein Ausbruch ist nach oben und nach unten möglich.' },
      { id: 'context', text: 'Den Kontext gewichten: Trend oder Trading Range, Lage im Chart.' },
      { id: 'after', text: 'Erst nach Auslösung und Anschluss bewerten.' },
    ],
    explanation: 'ii und iii sagen sicher etwas über die schrumpfende Range, aber nichts Sicheres über die Ausbruchsrichtung. Deshalb: erkennen, beide Seiten planen, Kontext gewichten und erst nach Auslösung plus Anschluss urteilen.',
    sourceAnchors: ['Kapitel 4 · ii und iii verschachteln die Kompression'],
  },
  {
    ...draft,
    id: 'practice.c04.order.setup-signal-entry',
    title: 'Vom Setup-Bar zum Entry-Bar',
    unitId: 'brooks-trends.chapter-05',
    lessonIds: ['brooks-trends.chapter-05.lesson-05'],
    prompt: 'Nach einem tieferen Tief bildet sich ein bullischer Bar. Ordne die Schritte bis zur Bewertung des Einstiegs.',
    steps: [
      { id: 'setup', text: 'Der bullische Bar ist zunächst nur ein mögliches Setup, noch kein Signal.' },
      { id: 'plan', text: 'Vor dem Einstieg beide Fälle planen: guter Anschluss oder sofortige Rückkehr in die alte Struktur.' },
      { id: 'trigger', text: 'Der nächste Bar überschreitet die Schwelle, die Order wird ausgeführt: Der Vorbar wird rückblickend zum Signal-Bar.' },
      { id: 'entry', text: 'Den Entry-Bar beurteilen: Schließt er kräftig in Handelsrichtung?' },
    ],
    explanation: 'Form, Ausführung und Folgereaktion sind drei verschiedene Informationen. Erst die Ausführung macht den Vorbar zum Signal-Bar, und der Entry-Bar zeigt, ob danach Initiative folgt.',
    sourceAnchors: ['Kapitel 5 · Aus dem Setup wird erst nach Auslösung ein Signal'],
  },
  {
    ...draft,
    id: 'practice.c04.order.setup-trigger-room',
    title: 'Setup, Auslösung, Raum',
    unitId: 'brooks-trends.chapter-06',
    lessonIds: ['brooks-trends.chapter-06.lesson-01'],
    prompt: 'Ein Bar bereitet eine mögliche Gelegenheit vor. Bringe die drei Schritte in die richtige Reihenfolge.',
    steps: [
      { id: 'recognize', text: 'Das Setup erkennen: Der Bar bereitet eine Gelegenheit vor.' },
      { id: 'wait', text: 'Die Auslösung abwarten: Erst dann wird der Bar zum Signal-Bar.' },
      { id: 'room', text: 'Den Raum für Anschluss beurteilen: Marktphase, Widerstand, Zielraum.' },
    ],
    explanation: 'Die bloße Form einer Kerze erzeugt noch keinen gefüllten Trade, und selbst eine Auslösung sagt nichts darüber, ob sich der Einstieg lohnt. Deshalb: Setup erkennen, Auslösung abwarten, Raum für Anschluss beurteilen.',
    sourceAnchors: ['Kapitel 6 · Ein Signal-Bar entsteht erst durch die Auslösung'],
  },
  {
    ...draft,
    id: 'practice.c04.order.unclear-outside',
    title: 'Bei Unklarheit abwarten',
    unitId: 'brooks-trends.chapter-07',
    lessonIds: ['brooks-trends.chapter-07.lesson-11'],
    prompt: 'Ein großer Outside-Bar lässt die nächste Richtung offen. Ordne einen sauberen Arbeitsplan.',
    steps: [
      { id: 'name', text: 'Die Unklarheit ausdrücklich benennen.' },
      { id: 'notes', text: 'Grenzen und den nächsten aussagekräftigen Test notieren.' },
      { id: 'watch', text: 'Folgebars beobachten: gehaltener Bruch mit Anschluss oder schnelle Rückkehr?' },
      { id: 'act', text: 'Erst mit einer klaren These handeln – sonst ist kein Trade der Plan.' },
    ],
    explanation: 'Abwarten ist nicht passiv, wenn Grenzen und nächster Test notiert sind. Erst neue Kursinformation kann eine unklare Outside-Spanne ordnen, und ohne erkennbaren Vorteil ist kein Trade ein gültiger Plan.',
    sourceAnchors: ['Kapitel 7 · Bei Unklarheit weitere Bars abwarten'],
  },
  {
    ...draft,
    id: 'practice.c04.order.closed-bar-first',
    title: 'Erst den geschlossenen Bar beurteilen',
    unitId: 'brooks-trends.chapter-08',
    lessonIds: ['brooks-trends.chapter-08.lesson-01'],
    prompt: 'Ein Bar sieht kurz vor seinem Ende nach einem starken Signal aus. Bringe den Ablauf in eine sinnvolle Reihenfolge.',
    steps: [
      { id: 'plan', text: 'Den Einstieg als wiederholbaren Plan festlegen.' },
      { id: 'wait', text: 'Das Ende des Bars abwarten.' },
      { id: 'judge', text: 'Den geschlossenen Bar beurteilen: Schluss und Lage.' },
      { id: 'enter', text: 'Erst dann nach Plan einsteigen.' },
    ],
    explanation: 'Ein offener Schluss ist eine Vermutung. Wer Signal und endgültigen Schluss trennt und einem festen Ablauf folgt, entlastet die Entscheidung und vermeidet seltene, aber teure Fehlgriffe.',
    sourceAnchors: ['Kapitel 8 · Der fast fertige Bar kann noch kippen'],
  },
  {
    ...draft,
    id: 'practice.c04.order.warning-wait-failure',
    title: 'Warnung, Abwarten, Fehlschlag',
    unitId: 'brooks-trends.chapter-09',
    lessonIds: ['brooks-trends.chapter-09.lesson-05'],
    prompt: 'Eine vermeintliche Bullenflagge sieht uneindeutig aus. Ordne die Schritte, bevor eine Gegenthese gehandelt wird.',
    steps: [
      { id: 'pattern', text: 'Das uneindeutige Muster mit Warnzeichen erkennen.' },
      { id: 'wait', text: 'Nicht sofort handeln, sondern weitere Price Action abwarten.' },
      { id: 'failure', text: 'Den versuchten Ausbruch und die Reaktion danach beobachten.' },
      { id: 'trade', text: 'Erst dann die Gegenthese handeln – mit eigenem Auslöser und Schutzpunkt.' },
    ],
    explanation: 'Warnung und bestätigter Fehlschlag sind zwei verschiedene Dinge. Wer schon beim ersten Zweifel handelt, handelt einen Ablauf, der noch gar nicht stattgefunden hat.',
    sourceAnchors: ['Kapitel 9 · Erst der gescheiterte Ausbruch öffnet die Gegenthese'],
  },
  {
    ...draft,
    id: 'practice.c04.order.counter-trend-second-try',
    title: 'Gegen einen starken Trend: der zweite Versuch',
    unitId: 'brooks-trends.chapter-10',
    lessonIds: ['brooks-trends.chapter-10.lesson-05'],
    prompt: 'Nach mehreren kräftigen Bullenbars erscheint ein bärischer Reversal-Bar. Bringe den Ablauf in die richtige Reihenfolge.',
    steps: [
      { id: 'observe', text: 'Den ersten Gegenversuch als Beobachtung behandeln, keinen Gegentrend-Trade nehmen.' },
      { id: 'resume', text: 'Die Wiederaufnahme des Trends für ein oder zwei Bars ansehen.' },
      { id: 'second', text: 'Auf einen erneuten Umkehrversuch warten.' },
      { id: 'entry', text: 'Erst dann einen Entry erwägen – mit passendem Ort, Auslösung und begrenztem Schutz.' },
    ],
    explanation: 'Nicht der erste Gegenbar, sondern der zweite ernsthafte Versuch ist der Prüfpunkt. Entsteht kein zweites Signal, gibt es auch keinen Trade aus diesem Plan.',
    sourceAnchors: ['Kapitel 10 · Gegen starken Trend erst den erneuten Versuch prüfen'],
  },
];
