import { chapterEightLesson, type ChapterEightDraft } from './chapter-08-model';

// Die Diagramme hierzu sind neue Lehrschemata, keine Nachzeichnung von 8.1.
const drafts: ChapterEightDraft[] = [
  {
    number: 8, title: 'Fall 8.1: Zwei Zeitebenen, zwei verschiedene Risiken',
    summary: 'Kürzere Bars erlauben engere Stops, bringen aber mehr Auslösungen gegen die größere Struktur.',
    section: 'Chartfall 8.1 · Rahmen',
    anchors: ['Fall 8.1 · Drei- und Fünf-Minuten-Blick', 'Längerer Bärentrend mit größeren Pullbacks', 'Kleinerer Stop und häufigere Ausstopper'],
    scenario: 'c08-figure-context',
    paragraphs: [
      'Das Fallbeispiel zeigt eine Umkehrsituation nach einer längeren bärischen Phase. Neue Tiefs werden öfter gekauft, die Rückläufe nach oben werden größer. Eine fertige Bullenwende ist das noch nicht, aber die Vorgeschichte vor dem nächsten Tief-Test hat sich verändert.',
      'Eine kürzere Zeitebene zerlegt dieselbe Bewegung in mehr Bars. Oft bekommst du so einen näheren technischen Stop, siehst aber auch zusätzliche Gegenbars und Tiefstiche. Auf der längeren Arbeitszeitebene bleibt so ein Stich vielleicht noch innerhalb eines intakten Signalbereichs.',
      'Ein engerer Stop verkleinert den Verlust pro Einheit, kann aber auch öfter unnötig ausgestoppt werden. Mehr kurze Bars heißen außerdem mehr Signale, und wer zwischen ihnen hin und her springt, verpasst leicht genau den besten Einstieg. Die passende Zeitebene hängt also nicht nur von der Stop-Distanz ab, sondern auch davon, ob du deine Signale dort konsequent lesen kannst.',
    ],
    callout: 'Ein kleinerer Stop heißt nicht automatisch bessere Qualität.',
    diagramTitle: 'Eine Bewegung, unterschiedlich zerlegt',
    caption: 'Eigenes abstraktes Schema: Links mehr kurze Bars mit Zwischentief, rechts dieselbe Idee in größeren Bars und breiterer Struktur.',
    observations: ['Beide Ansichten können dieselbe Marktphase meinen.', 'Kürzere Bars liefern mehr einzelne Gegensignale.', 'Risikostrecke und Ausstopphäufigkeit zusammen betrachten.'],
    prompt: 'Was ist der mögliche Nachteil, wenn du für eine größere Umkehr nur wegen des kleineren Stops auf eine kürzere Zeitebene wechselst?',
    answers: [['Der Stop kann häufiger getroffen werden, obwohl die größere Struktur noch hält.', 'Richtig. Das kleinere Risiko je Trade kann mit mehr Fehlausstiegen einhergehen.'], ['Es gibt auf kürzeren Charts keine bullischen Signale.', 'Signale gibt es dort ebenfalls, aber ihre Zuverlässigkeit und Menge ändern sich.'], ['Die größere Zeitebene liefert dann keine Information mehr.', 'Sie bleibt für die ursprüngliche These relevant.']], correct: 0,
    takeaways: ['Zeitebene vor dem Trade festlegen.', 'Stop-Distanz und Trefferwahrscheinlichkeit gemeinsam sehen.', 'Änderung der Marktphase im größeren Kontext beachten.'],
  },
  {
    number: 9, title: 'Fall 8.1: Der Schutz gehört unter die Struktur',
    summary: 'Ein überzeugender zweiter Umkehrversuch darf einen größeren, sachlich begründeten Stop brauchen.',
    section: 'Chartfall 8.1 · zweiter Versuch',
    anchors: ['Fall 8.1 · Signal um Bar 11', 'Zweiter Versuch nach tieferem Tief', 'Struktureller Stop und kleinere Positionsgröße'],
    scenario: 'c08-figure-stop-distance',
    paragraphs: [
      'Im Beispiel ist Bar 11 gleich zweierlei: ein starker bullischer Reversal-Bar und eine Umkehr über zwei Bars. Ein früherer Versuch über ein ii nach Bar 10 scheiterte; der neue Tief-Test ist der dritte Abwärtsschub des Tages und kann einen möglichen Wedge-Boden abschließen. Erst diese Abfolge macht den zweiten Käuferversuch aussagekräftiger als eine einzelne hübsche Kerze. Das ii sind zwei Inside-Bars nacheinander; weder ii noch Wedge garantieren die Umkehr.',
      'Ein Long-Plan muss das Tief dieser Struktur als möglichen Ungültigkeitspunkt einplanen. Im historischen Fallbeispiel lag der Stop etwa drei E-mini-Punkte vom Einstieg entfernt, also mehr als die zuletzt oft ausreichenden zwei Punkte. Die Zahlen erklären die damalige Entscheidung und sind keine Vorgabe für heutige Stops. Ein willkürlich enger Stop macht die Umkehridee jedenfalls nicht besser.',
      'Willst du das Geldrisiko begrenzen, verkleinere lieber die Positionsgröße oder lass den Trade aus. Weniger Kontrakte ändern nichts an der Bedeutung des Tiefs, nur an der finanziellen Wirkung der Distanz.',
    ],
    callout: 'Den Schutzort aus der These ableiten, die Größe aus dem Risikobudget.',
    diagramTitle: 'Strukturtief und zu enger Zwischen-Stop',
    caption: 'Eigenes Schema zeigt zwei frei gewählte Schutzlinien unter einer bullischen Reaktion; nur eine liegt jenseits des relevanten Tiefs.',
    observations: ['Bar 11 verbindet zweiten Versuch, Zwei-Bar-Umkehr und dritten Abwärtsschub.', 'Ein enger Zwischen-Stop kann mitten in der Idee liegen.', 'Positionsgröße begrenzt Geldrisiko ohne Änderung der Struktur.'],
    prompt: 'Ein gutes Long-Setup benötigt einen weiter entfernten Stop unter dem wichtigen Tief. Was ist die saubere Anpassung bei gleichem Geldrisiko?',
    answers: [['Den Stop ohne Chartgrund näher heranrücken.', 'Damit wird der Schutzpunkt von der These abgekoppelt.'], ['Die Position verkleinern oder auslassen.', 'Richtig. Der strukturelle Stop bleibt dort, wo die Idee invalidiert wäre.'], ['Den Stop ganz entfernen.', 'Das würde das Risiko unbestimmt machen.']], correct: 1,
    takeaways: ['Mehrere Versuche verändern die Signalqualität.', 'Stop unter relevante Struktur statt unter zufälligen Mini-Bar.', 'Geldrisiko über Positionsgröße oder Verzicht steuern.'],
  },
  {
    number: 10, title: 'Fall 8.1: Nur der kürzere Chart stoppt aus',
    summary: 'Ein kräftiger Gegenbar auf der kleinen Zeitebene kann trotzdem noch zum größeren Long-Plan passen.',
    section: 'Chartfall 8.1 · Ausstopper',
    anchors: ['Fall 8.1 · Stop der Drei-Minuten-Ansicht', 'Fünf-Minuten-Tief bleibt bestehen', 'Konflikt der beiden Signale'],
    scenario: 'c08-figure-stopout',
    paragraphs: [
      'Nach dem Umkehrsignal entsteht im kürzeren Blick ein bärischer Bar mit starkem Schluss. Sein Tief löst den Schutz unter dem kleinen Entry-Bar aus. Auf dieser Zeitebene sieht das nach einer klaren Verkäuferreaktion aus.',
      'Die größere Arbeitszeitebene zeigt gleichzeitig ein anderes Bild: Ihr relevantes Signaltief bleibt unberührt. Wer wegen des größeren Setups eingestiegen ist, darf nicht heimlich den kleineren Stop und die kleinere Signalbewertung zum neuen Plan machen.',
      'Hinterher wirkt der kurze Stich offensichtlich. Während er passiert, lassen sich die widersprüchlichen Signale aber kaum sortieren. Mit vorher gewählter Zeitebene und Stop-Regel wechselst du mitten im schnellen Gegenbar nicht die Entscheidung.',
    ],
    callout: 'Nach dem Einstieg nicht heimlich die Zeitebene des Schutzplans tauschen.',
    diagramTitle: 'Kleiner Stop berührt, größeres Tief hält',
    caption: 'Zwei unabhängige Lehrschemata markieren jeweils den Schutzort der gewählten Zeitebene; nur die nähere Linie wird geschnitten.',
    observations: ['Ein bärischer Klein-Bar kann stark aussehen.', 'Der weiter entfernte Strukturpunkt bleibt unangetastet.', 'Das Mischen zweier Pläne verändert den Trade.'],
    prompt: 'Ein Long aus dem größeren Chart ist offen; nur der Stop unter einem Bar des kleineren Charts wird erreicht. Welche Aussage ist korrekt?',
    answers: [['Das größere Setup ist damit zwangsläufig ungültig.', 'Sein eigenes relevantes Tief wurde gerade nicht erreicht.'], ['Der kleinere Stich beweist eine sofortige Bärenphase.', 'Ein starker kurzer Gegenbar kann in einer größeren Bewegung aufgefangen werden.'], ['Die beiden Schutzpläne sind verschieden und müssen vorab getrennt werden.', 'Richtig. Ein kleiner Ausstopper invalidiert nicht automatisch die größere These.']], correct: 2,
    takeaways: ['Starke Gegensignale auf kleiner Ebene richtig einordnen.', 'Invalidation auf der geplanten Ebene prüfen.', 'Nicht nachträglich einen anderen Stop übernehmen.'],
  },
  {
    number: 11, title: 'Fall 8.1: Nach dem kurzen Stich übernehmen Käufer',
    summary: 'Ein zurückgekaufter Tiefbruch kann Ausgestoppte an der Rückkehr hindern.',
    section: 'Chartfall 8.1 · Rückeroberung',
    anchors: ['Fall 8.1 · bullischer Outside-Folgebar', 'Höheres Tief nach kurzzeitigem Stop-Lauf', 'Ein Chart als Arbeitsgrundlage'],
    scenario: 'c08-figure-recovery',
    paragraphs: [
      'Auf den starken kleinen Bärenbar folgt im Fallbeispiel eine energische Käuferreaktion. Der nächste Bar umfasst den vorherigen und schließt hoch. Das kurze Tief wird so Teil eines höheren Tiefbereichs, statt eine neue dauerhafte Abwärtsbewegung einzuleiten.',
      'Wer am engen Stop ausgestiegen ist, muss jetzt in kürzester Zeit einen Fehlausbruch erkennen und einen neuen Einstieg planen. Oft wartet man aus Vorsicht auf einen späteren Pullback, während die ursprüngliche Bewegung ohne die eigene Position weiterläuft.',
      'Das heißt nicht, dass du Stop-Läufe grundsätzlich kaufen sollst. Es zeigt nur, warum zwei gleichzeitig beobachtete Zeitebenen dich im schnellen Umschlag lahmlegen können. Ein fest gewählter Arbeitschart liefert dir die ruhigere Entscheidungsfolge.',
    ],
    callout: 'Ein zurückerobertes Tief ist neue Information, aber kein Beweis für jedes künftige Signal.',
    diagramTitle: 'Stich unter das Tief und bullische Rückkehr',
    caption: 'Eigenes Schema stellt den engen Ausstopper und die anschließende Outside-Up-Reaktion einem ruhigeren Blick auf den größeren Plan gegenüber.',
    observations: ['Der kurzfristige Bärenbar verliert sofort Anschluss.', 'Ein Outside-Up-Bar kann den Tiefbereich zurückerobern.', 'Ein Plan darf nicht bei jedem Gegensignal die Zeitebene wechseln.'],
    prompt: 'Warum ist ein Wiedereinstieg nach dem kurzen Ausstopper psychologisch und praktisch schwer?',
    answers: [['Weil ein einmaliger Stop jeden späteren Einstieg verbietet.', 'Eine erneute Entscheidung ist möglich, aber schwerer unter Zeitdruck.'], ['Weil der Trader einen starken kleinen Bärenbar und seine schnelle Rücknahme neu einordnen muss.', 'Richtig. Angst und widersprüchliche Zeitebenen können den Plan verzögern.'], ['Weil ein Outside-Bar immer eine Trading Range beendet.', 'Die Form allein sagt das nicht.']], correct: 1,
    takeaways: ['Gegenbar und seine Folgereaktion gemeinsam lesen.', 'Kurzer Tiefbruch kann Käufer anziehen.', 'Einen Arbeitschart und seinen Schutzplan konsistent nutzen.'],
  },
  {
    number: 12, title: 'Fall 8.1: Frühe Gegenbrüche scheitern noch',
    summary: 'Kleine Brüche einer fallenden Linie ändern den Trend nicht ohne Anschluss.',
    section: 'Chartfall 8.1 · vertiefter Rückblick',
    anchors: ['Fall 8.1 · vertiefte Diskussion', 'Frühe Brüche über fallende Trendlinie', 'Mit-Trend-Short nach ausbleibendem Anschluss'],
    scenario: 'c08-figure-failed-breaks',
    paragraphs: [
      'Vor der späteren bullischen Umkehr zeigt derselbe Chart frühere Versuche, eine fallende Trendlinie zu überwinden. Beide bleiben knapp oder kurz und bekommen keine tragfähige Käuferfolge. Ein Linienbruch allein kippt die bisherige Bärenstruktur nicht.',
      'Nach einem misslungenen Gegenbruch kann der Markt wieder in die alte Richtung drehen. Das bereitet einen Mit-Trend-Short vor, solange die weitere Folge den Abwärtstrend stützt. Erst später verändern größere Rückläufe, wiederholte Tief-Tests und stärkere Käuferreaktionen die Ausgangslage.',
      'Diese zeitliche Reihenfolge schützt dich vor dem Rückschaufehler: Du darfst die späte Umkehr nicht in frühere Bars hineinlesen. Am jeweiligen Bar-Schluss lagen nur die damaligen Informationen vor, die spätere Käuferstärke kannte niemand.',
    ],
    callout: 'Ein erster Gegenbruch ist ein Test; erst die Folge zeigt den Regimewechsel.',
    diagramTitle: 'Zwei kurze Brüche und die alte Richtung',
    caption: 'Ein frei konstruiertes Schema zeigt zwei nicht gehaltene Tests einer fallenden Referenzlinie; es bildet keinen echten Chart nach.',
    observations: ['Beide Hochstiche verlieren die neue Zone.', 'Die Bären erhalten danach erneut Schlusskontrolle.', 'Der spätere Umkehrfall darf nicht rückwirkend unterstellt werden.'],
    prompt: 'Warum war ein kurzer Bruch über die fallende Linie im früheren Abschnitt noch keine sichere Bullenwende?',
    answers: [['Weil der Bruch keinen tragfähigen bullischen Anschluss erhielt.', 'Richtig. Der Markt kehrte in die alte Richtung zurück.'], ['Weil Trendlinien nie Informationen liefern.', 'Sie zeigen einen Test, dessen Folge beurteilt werden muss.'], ['Weil die spätere Umkehr schon feststand.', 'Am früheren Entscheidungspunkt war sie nicht bekannt.']], correct: 0,
    takeaways: ['Linienbruch und Anschluss getrennt prüfen.', 'Frühere Entscheidungen nur mit damaligem Wissen beurteilen.', 'Der Bar-Schluss macht die Folge schrittweise sichtbar.'],
  },
];

export const chapterEightCaseLessons = drafts.map(chapterEightLesson);
