import { chapterTenLesson, type ChapterTenDraft } from './chapter-10-model';

// Vertiefte Besprechung von Fall 10.2 in aufbauender Reihenfolge.
const drafts: ChapterTenDraft[] = [
  {
    number: 14, title: 'Rückblick: Der Ausbruch aus dem alten Bärenkanal hielt nicht',
    summary: 'Ein Bruch der fallenden Begrenzung vor dem Beispieltag scheiterte am gleitenden Durchschnitt.',
    section: 'Fall 10.2 · vertiefter Rückblick',
    anchors: ['Fall 10.2 · Vortags-Schlussphase', 'Bruch über Bärenkanal', 'Scheitern am gleitenden Durchschnitt'],
    scenario: 'c10-deep-yesterday',
    paragraphs: [
      'Die vertiefte Erklärung beginnt noch vor dem eigentlichen Beispieltag: Gegen Ende des Vortags verließ der Kurs den fallenden Kanal nach oben. Ein erster Bruch der Kanalbegrenzung kann den Bärentrend schwächen, beweist aber noch keinen neuen Bullenmarkt.',
      'Die Bewegung traf auf den gleitenden Durchschnitt und verlor dort den Anschluss. Danach ergab sich wieder ein Short-Setup. Die Reihenfolge ist wichtig: erst der Gegenbruch, dann sein Test an einer Referenz, dann die Rückkehr der Verkäufer. Ein isolierter Linienbruch hätte die spätere Reaktion nicht vorweggenommen.',
      'Für Kapitel 10 ist dies die Ausgangslage vor den Intraday-Entries. Wer nur einen markierten Bar am Folgetag ansieht, übersieht die vorherige gescheiterte Käuferinitiative. Das Schema unten zeigt einen anderen frei erfundenen Marktpfad mit derselben Entscheidungsfolge.',
    ],
    callout: 'Kanalbruch und gescheiterter Anschluss sind zwei verschiedene Informationen.',
    diagramTitle: 'Gegenbruch trifft Widerstand',
    caption: 'Eigenes Lehrschema zeigt einen Ausbruch über eine fallende Begrenzung, einen Test einer Referenzzone und die Rückkehr nach unten.',
    observations: ['Der erste Linienbruch schwächt die alte Struktur.', 'Die Reaktion an der Referenz bleibt negativ.', 'Erst die Folge stützt wieder die Short-Seite.'],
    prompt: 'Was fehlte dem Ausbruch aus dem alten Bärenkanal?',
    answers: [['Ein tragfähiger Anschluss oberhalb des gleitenden Durchschnitts.', 'Richtig. Der Test dort scheiterte im beschriebenen Fall.'], ['Eine Eröffnung des nächsten Handelstages.', 'Der fehlende Anschluss war bereits am Vortag sichtbar.'], ['Ein numerisch perfektes Hoch.', 'Die Qualität wird an der Reaktion und nicht an einem perfekten Extrem gemessen.']], correct: 0,
    takeaways: ['Vortag als Kontext für neue Signale mitlesen.', 'Linienbruch nicht mit Trendwechsel gleichsetzen.', 'Fehlgeschlagener Test kann Mit-Trend-Short vorbereiten.'],
  },
  {
    number: 15, title: 'Das neue Tagestief wird zurückgenommen',
    summary: 'Der Bruch unter das Vortagestief scheitert an einer frühen bullischen Reaktion.',
    section: 'Fall 10.2 · früher Handel',
    anchors: ['Fall 10.2 · Bruch unter Vortagestief', 'Bullische Umkehr am vierten Tagesbar', 'Breakout-Pullback zu tieferem Tief'],
    scenario: 'c10-deep-low-failure',
    paragraphs: [
      'Am neuen Handelstag fällt der Markt zunächst unter das Tief des Vortags. Ein solcher Bruch könnte den alten Bärentrend bestätigen. Doch schon am vierten Bar kehrt der Preis nach oben zurück. Das tiefere Niveau hält vorerst nicht.',
      'Diese Folge lässt sich auch als Breakout-Pullback zu einem tieferen Tief beschreiben: Nach einem frühen Gegenbruch über einen kleinen Bärenkanal testet der Markt unten erneut. Die neue Tiefmarke und die Rückeroberung gehören als ein Ablauf zusammen, nicht als zwei widersprüchliche Einzel-Signale.',
      'Der gescheiterte Tiefbruch eröffnet eine bullische Gegenthese. Er garantiert keine Trendwende, denn weitere Hochs müssen erst entstehen. Beurteile also den Test und die nächste Kaufreaktion, bevor du aus einem einzelnen frühen Bar einen dauerhaften Richtungswechsel ableitest.',
    ],
    callout: 'Ein neues Tief wird erst dann zum Bärensignal, wenn es auch angenommen wird.',
    diagramTitle: 'Unter das Vortagestief und wieder zurück',
    caption: 'Frei erfundene Folge mit einer markierten Vor-Tief-Linie und einer bullischen Rückkehr nach einem kurzzeitigen Bruch.',
    observations: ['Das Tief wird kurz unterschritten.', 'Der nächste Kaufversuch holt die Zone zurück.', 'Die Folge entscheidet, ob der Bruch Bestand hat.'],
    prompt: 'Was verändert die frühe bullische Rückkehr nach dem neuen Tagestief?',
    answers: [['Sie beweist automatisch einen Bullen-Trendtag.', 'Eine Rückkehr allein beweist die spätere Tagesstruktur nicht.'], ['Sie stellt die bärische Breakout-These infrage und eröffnet einen erneuten Test.', 'Richtig. Der Tiefbruch wurde nicht gehalten.'], ['Sie löscht das Vortagestief aus dem Chart.', 'Die Referenz bleibt vorhanden und wichtig.']], correct: 1,
    takeaways: ['Breakout und anschließende Akzeptanz unterscheiden.', 'Tief-Test im Kontext früher Gegenbrüche lesen.', 'Neues Tief kann auch scheitern.'],
  },
  {
    number: 16, title: 'Das höhere Hoch bleibt aus: Bar 6 als Doppeltest',
    summary: 'Ohne Bruch über das letzte tiefere Hoch setzt sich die Bärenstruktur fort.',
    section: 'Fall 10.2 · Bar 6 und Struktur',
    anchors: ['Fall 10.2 · kein Higher High', 'Bar 6 am Doppel-Hoch-Bereich', 'Fortgesetzte Folge tieferer Hochs und Tiefs'],
    scenario: 'c10-deep-double-top',
    paragraphs: [
      'Die frühe bullische Reaktion hätte ein höheres Hoch gebraucht, um die fallende Struktur deutlicher zu verändern. Im Fallbeispiel bleibt sie jedoch unter einem vorherigen tieferen Hoch stehen. Die Verkäufer erhalten damit eine weitere Chance, den Tag wieder nach unten zu lenken.',
      'Bei Bar 6 entsteht in dieser Zone ein enger Doppel-Hoch-Test. Darunter bietet sich ein Short gegen den gescheiterten Versuch an, aus der Eröffnungserholung einen neuen Trend zu machen. Die tiefere Hochfolge ist hier wichtiger als ein hübscher Mustername.',
      'Wer die beiden bisherigen Seiten trennt, erkennt die Verschiebung: Der Tiefbruch scheiterte zuerst, aber danach scheiterte auch die Käufererholung am Hoch. Ein erneuter Short hat deshalb andere Gründe als ein ungeduldiger Verkauf direkt am ersten Tagesbar.',
    ],
    callout: 'Ein gescheitertes Tief allein reicht nicht, wenn die Erholung kein höheres Hoch schafft.',
    diagramTitle: 'Erholung bleibt unter dem letzten Hoch',
    caption: 'Eigenes Schema markiert einen wiederholten Hochtest unter einer früheren Hochzone und den erneuten fallenden Abschnitt.',
    observations: ['Die Käufer überbieten das relevante Hoch nicht.', 'Ein zweiter Hochtest scheitert nahe der Zone.', 'Die Folge tieferer Hochs kann weiterlaufen.'],
    prompt: 'Weshalb wird unter dem Bar-6-Bereich ein Short prüfbar?',
    answers: [['Weil jeder Doppeltest automatisch zur Trendwende führt.', 'Der Marktort und die tiefere Hochfolge sind hier ausschlaggebend.'], ['Weil der frühe Tiefbruch jede Kaufidee dauerhaft verbietet.', 'Der Tiefbruch war zunächst sogar gescheitert.'], ['Weil die Erholung kein höheres Hoch erreichte und die Bärenstruktur sich erneut zeigte.', 'Richtig. Der zweite Hochtest bekam keinen bullischen Anschluss.']], correct: 2,
    takeaways: ['Höhere und tiefere Hochs als Struktur lesen.', 'Gescheiterten Käufertrend von isoliertem Bar trennen.', 'Short-Trigger unter der relevanten Zone prüfen.'],
  },
  {
    number: 17, title: 'Low 4 und der anschließende Bärenimpuls',
    summary: 'Ein mehrfacher Verkaufsversuch aus einem Pullback löst eine kräftige Abwärtsphase aus.',
    section: 'Fall 10.2 · Low 4 und Spike',
    anchors: ['Fall 10.2 · Pullback nach Bärenspike', 'Low-4-Short um 9:35 PST im Fallbeispiel', 'Vier-Bar-Bärenspike ab Bar 6'],
    scenario: 'c10-deep-low4',
    paragraphs: [
      'Nach dem ersten Bärenspike erholt sich der Markt. Innerhalb dieses Pullbacks zählt man weitere Versuche, die alte Abwärtsrichtung wieder aufzunehmen. Der vierte Verkaufseinstieg in dieser Zählung ist der Low 4; er ist kein vierter Bar des Tages und keine allgemeine Erfolgsgarantie.',
      'Im historischen Beispielchart wird dieser Short um 9:35 Uhr PST mit einem kräftigen Bärenbar ausgelöst. Danach wächst die Bewegung zu einem Abschnitt aus vier bärischen Bars, dessen Beginn bei Bar 6 liegt. Zählung, Auslösung und Anschluss sind drei getrennte Beobachtungen.',
      'Wichtiger als die Uhrzeit ist die Struktur: Pullback nach einem Abwärtsimpuls, wiederholter Verkaufsversuch, dann tatsächlich starker Bruch. Wer den Count erst im Nachhinein auf jeden beliebigen Rücklauf klebt, verpasst die Entscheidungsstelle vor der Auslösung.',
    ],
    callout: 'Low 4 benennt die Verkaufszählung, nicht das Ergebnis des Trades.',
    diagramTitle: 'Mehrfacher Verkaufsversuch nach einem Pullback',
    caption: 'Eigenes abstrahiertes Schema zeigt einen Bärenimpuls, mehrere Pullback-Stufen und den erneuten Abwärtsbruch, ohne historische Bars zu kopieren.',
    observations: ['Der Count liegt im Pullback nach Abwärtsdruck.', 'Ein starker Auslösungsbar bringt neue Information.', 'Der spätere Spike zeigt Anschluss.'],
    prompt: 'Welche Bedeutung hat „Low 4“ hier?',
    answers: [['Der vierte gezählte Versuch, einen Pullback nach unten fortzusetzen.', 'Richtig. Es geht um die Folge von Verkaufsversuchen.'], ['Der vierte Bar nach der Börseneröffnung.', 'Die Bar-Nummer des Tages ist eine andere Zählung.'], ['Ein fester Stop von vier Ticks.', 'Der Count legt keinen solchen Geld- oder Tick-Stop fest.']], correct: 0,
    takeaways: ['Low-Count als Pullback-Folge verstehen.', 'Auslösung und Follow-through gesondert prüfen.', 'Historische Uhrzeit nicht als Regel übertragen.'],
  },
  {
    number: 18, title: 'Bar 5 ist ein High 2 gegen zu viel Bärendruck',
    summary: 'Ein formal vorhandener zweiter Kaufversuch kann direkt nach vier Bärenbars schlecht sein.',
    section: 'Fall 10.2 · High 2 bei Bar 5',
    anchors: ['Fall 10.2 · Bar 5 als High 2', 'Vier Bären-Trendbars unmittelbar davor', 'Count gegen Momentum'],
    scenario: 'c10-deep-high2',
    paragraphs: [
      'Bar 5 zählt als High 2, also als zweiter möglicher Kaufversuch innerhalb eines Rücklaufs. Nach der Zählung klingt das nach der bevorzugten zweiten Gelegenheit. Doch direkt davor stehen vier starke Bärenbars.',
      'Die sichtbare Abwärtskraft wiegt in diesem Fall schwerer als das formal passende Etikett. Käufer haben noch nicht gezeigt, dass sie einen vernünftigen Gegenstoß und einen hohen Schluss halten können. Ein Long gegen die vier Bars würde die wichtigste Information des Charts ignorieren.',
      'Damit löst das Kapitel einen möglichen Widerspruch auf: „Zweiter Entry“ bedeutet nicht „immer handeln“. Die Zählung sagt, was für ein Versuch vorliegt; die Trendstärke sagt, ob dieser Versuch überhaupt eine Chance verdient. Im Fallbeispiel wird dieser High 2 ausgelassen.',
    ],
    callout: 'High 2 zählt den Versuch; vier starke Bärenbars beurteilen seine Qualität.',
    diagramTitle: 'Formaler High 2 unter Bärendruck',
    caption: 'Eigenes Zwei-Panel-Lehrschema zeigt eine wiederholte bullische Auslösung nach starken Bärenbars und die fehlende Käuferfolge.',
    observations: ['Der zweite Kaufversuch ist zählbar.', 'Die vorherigen Bars fallen kräftig.', 'Ein Count allein ändert das Momentum nicht.'],
    prompt: 'Warum wird der High 2 bei Bar 5 im Fallbeispiel nicht gekauft?',
    answers: [['Weil ein High 2 grundsätzlich ein Verkaufssignal ist.', 'High 2 bezeichnet hier einen möglichen Kaufversuch.'], ['Weil vier kräftige Bärenbars die Gegenidee deutlich schwächen.', 'Richtig. Der Kontext dominiert die formale Zählung.'], ['Weil ein zweiter Versuch nie nach einem Tief auftreten darf.', 'Gerade an Tiefs gibt es oft wiederholte Kaufversuche.']], correct: 1,
    takeaways: ['Count und Momentum getrennt auswerten.', 'Starke Vorbars nicht wegen eines Musternamens übergehen.', 'Ein zweiter Entry darf ausgelassen werden.'],
  },
  {
    number: 19, title: 'Bar 7: Eine enge ii-Pause kann die letzte Flagge sein',
    summary: 'Nach dem vier Bar langen Bärenspike folgt eine enge Pause und noch ein Abwärtsschub.',
    section: 'Fall 10.2 · Spike und ii',
    anchors: ['Fall 10.2 · Spike ab Bar 6', 'Bar 7 als ii und mögliche Final Flag', 'Zwei-Bar-Bärenspike nach der Pause'],
    scenario: 'c10-deep-final-flag',
    paragraphs: [
      'Der Abwärtsimpuls ab Bar 6 umfasst im Fallbeispiel vier bärische Bars. Anschließend entsteht bei Bar 7 ein ii: zwei nacheinander enger werdende Inside-Bars. Eine solche Pause wirkt zunächst wie eine kleine Fortsetzungsflagge, weil der vorangehende Druck noch sichtbar ist.',
      'Sie gilt zugleich als mögliche Final Flag, also eine späte Pause vor einem letzten Schub der laufenden Richtung. Tatsächlich folgt ein weiterer, diesmal zwei Bars umfassender Bärenspike. Erst sein Verlauf und die folgende Reaktion zeigen, ob die Verkäufer noch effizient weiterkommen.',
      '„Mögliche letzte Flagge“ ist eine Arbeitshypothese, keine Prognose, dass der nächste Bar sofort steigt. Das Schema zeigt die Abfolge Spike, ii-Pause und erneuter Spike mit frei gewählten Bars. Die spätere Umkehr wird erst in der nächsten Lektion behandelt.',
    ],
    callout: 'Die späte ii-Pause kann noch einen Bärenschub einleiten, bevor Käufer reagieren.',
    diagramTitle: 'Bärenspike, enge ii-Pause, weiterer Schub',
    caption: 'Synthetische Folge mit einem Abwärtsimpuls, zwei verschachtelten Innenbars und einem neuen zweibarsigen Abwärtsschub.',
    observations: ['Die ii-Pause komprimiert die Spanne.', 'Der Ausbruch läuft zunächst in Trendrichtung.', 'Ob die Flagge die letzte war, zeigt sich erst danach.'],
    prompt: 'Warum ist „Final Flag“ an Bar 7 noch keine sichere Long-Auslösung?',
    answers: [['Weil die Pause zuerst einen weiteren Bärenschub hervorbringen kann.', 'Richtig. Das Beispiel zeigt gerade die Fortsetzung vor der Erholung.'], ['Weil Inside-Bars grundsätzlich nie ausbrechen.', 'Eine enge Pause kann durchaus in Trendrichtung aufgelöst werden.'], ['Weil die spätere Käuferreaktion schon bekannt sein muss.', 'Am Bar 7 ist sie noch nicht beobachtbar.']], correct: 0,
    takeaways: ['ii als zwei verschachtelte Innenbars erkennen.', 'Späte Flagge und tatsächliche Umkehr zeitlich trennen.', 'Auch ein letzter Bärenschub kann zunächst kräftig aussehen.'],
  },
  {
    number: 20, title: 'Wiederholte Verkaufsklimaxe erhöhen die Chance auf Erholung',
    summary: 'Nach drei beschleunigten Abwärtsschüben wird ein mindestens zweibeiniger Rücklauf plausibler.',
    section: 'Fall 10.2 · aufeinanderfolgende Klimaxe',
    anchors: ['Fall 10.2 · Kanal nach Low 4', 'Drei Bärenspikes als Verkaufsklimaxe', 'Erwartung einer mindestens zweibeinigen Rally'],
    scenario: 'c10-deep-three-climaxes',
    paragraphs: [
      'Seit dem Low-4-Short folgen im Beispielchart mehrere neue bärische Beschleunigungen. Drei Spikes innerhalb dieses abwärts gerichteten Abschnitts zählen als aufeinanderfolgende Verkaufsklimaxe. Jeder weitere Schub lockt Verkäufer an, kann aber zugleich die Bewegung überdehnen.',
      'Nach dem dritten hält er eine Erholung mit mindestens zwei Aufwärtsbeinen für wahrscheinlicher. Ein „Bein“ ist ein Abschnitt in einer Richtung, der durch einen Rücklauf getrennt werden kann. Die Erwartung entsteht aus der wiederholten Überdehnung und dem späten Marktort, nicht aus einer magischen Zahl drei.',
      'Für eine Long-Entscheidung wartet man dennoch auf einen konkreten Käuferversuch und dessen Auslösung. Ein Klimax-Count rechtfertigt nicht, ohne Schutz vor die nächste starke Bärenkerze zu kaufen. Im Fall liefert erst das spätere Mikro-Doppeltief eine prüfbare Struktur.',
    ],
    callout: 'Drei überdehnte Schübe machen Erholung plausibel, aber noch nicht handelbar.',
    diagramTitle: 'Dritter Schub und möglicher zweibeiniger Rücklauf',
    caption: 'Eigene abstrakte Folge markiert drei zunehmend späte Abwärtsabschnitte und eine nur als Möglichkeit eingezeichnete zweiteilige Erholung.',
    observations: ['Wiederholte Beschleunigung kann erschöpfen.', 'Zwei Beine brauchen einen Zwischenrücklauf.', 'Erwartung und Entry-Signal sind verschieden.'],
    prompt: 'Was folgt im Beispiel aus den drei Verkaufsklimaxen?',
    answers: [['Ein garantierter sofortiger Bullenmarkt.', 'Eine Erholung wird wahrscheinlicher, nicht gewiss.'], ['Eine erhöhte Erwartung für mindestens zwei Aufwärtsbeine, sofern Käufer auslösen.', 'Richtig. Die Struktur begünstigt einen Rücklauf, braucht aber ein Setup.'], ['Die Verpflichtung, jeden neuen Tiefbruch blind zu kaufen.', 'Das wäre ein ungeschützter Gegentrend-Trade.']], correct: 1,
    takeaways: ['Klimaxe in ihrer zeitlichen Folge zählen.', 'Wahrscheinlichkeit von konkreter Auslösung trennen.', 'Zweiteilige Erholung als Szenario, nicht als Versprechen lesen.'],
  },
  {
    number: 21, title: 'Bar 8 und 9: Zweiter Tieftest nach dem langen Rückgang',
    summary: 'Ein Mikro-Doppeltief und bullischer Reversal-Bar geben der Erholung eine handelbare Struktur.',
    section: 'Fall 10.2 · Bars 8 und 9',
    anchors: ['Fall 10.2 · Bar 8 Mikro-Doppeltief', 'Vergleich mit Tief zwei Bars früher', 'Long bei Bar 9 nach Reversal-Bar'],
    scenario: 'c10-deep-micro-bottom',
    paragraphs: [
      'Bar 8 markiert im Beispielchart einen erneuten Tiefversuch nahe dem Rückgang von zwei Bars zuvor. Die kleine Folge lässt sich als Mikro-Doppeltief lesen. Zugleich zeigt Bar 8 eine Käuferreaktion aus dem Tief. Nach den späten Verkaufsschüben bekommt die Erholung damit einen konkreten Standort.',
      'Ein Long bei Bar 9 folgt erst nach diesem Reversal-Bar. Die These lautet nicht „das Tief kann nie mehr fallen“, sondern „nach der langen Bärenphase und dem erneuten Test könnte ein Rücklauf mit zwei Beinen entstehen“. Der Einstieg muss zur möglichen Risikostrecke unter dem Signalbereich passen.',
      'Wer hier nur das Musterwort liest, verliert den Grund für seine Wirkung: zuvor mehrere Verkaufsklimaxe, dann ein zweiter Tieftest und ein sichtbarer Kaufversuch. Ohne diese Vorgeschichte wäre derselbe kleine Doppeltest weniger überzeugend.',
    ],
    callout: 'Das Mikro-Doppeltief erhält seine Bedeutung aus der späten Bärenphase davor.',
    diagramTitle: 'Zweiter Tieftest vor der Erholung',
    caption: 'Eigenes Lehrschema zeigt zwei nahe Tiefbereiche, einen bullischen Gegenbar und einen späteren Entry-Punkt, ohne echte Kurse nachzuzeichnen.',
    observations: ['Der Markt prüft den Tiefbereich erneut.', 'Ein Reversal-Bar zeigt Käuferreaktion.', 'Der Long folgt der Auslösung, nicht der Vorahnung.'],
    prompt: 'Welche Kombination begründet den Long nach Bar 8 im Fallbeispiel?',
    answers: [['Nur die Zahl acht auf dem Chart.', 'Die Barnummer ist kein Handelsgrund.'], ['Ein einzelner grüner Bar ohne Vorgeschichte.', 'Die wiederholten Verkaufsschübe und der Tief-Test sind wesentlich.'], ['Späte Verkaufsklimaxe, erneuter Tief-Test und sichtbare bullische Reaktion.', 'Richtig. Erst die gesamte Folge stützt den Versuch.']], correct: 2,
    takeaways: ['Mikro-Doppeltief als zweiten Test verstehen.', 'Bar 9 als Entry nach der Reaktion lesen.', 'Risikopunkt aus der Struktur ableiten.'],
  },
  {
    number: 22, title: 'Bar 10: Low 1 gegen zu viel Käuferkraft',
    summary: 'Ein erstes Verkaufssignal in der jungen Rally muss nicht die erwartete Fortsetzung des Bärentrends sein.',
    section: 'Fall 10.2 · Bar 10',
    anchors: ['Fall 10.2 · Bar 10 als Low 1', 'Starke bullische Erholung davor', 'Higher-Low-Long oder Test des Aufwärts-Hochs'],
    scenario: 'c10-deep-low1',
    paragraphs: [
      'Nach dem Kaufversuch bei Bar 9 zieht der Markt im Beispielchart kräftig an. Bar 10 lässt sich zwar als Low 1 bezeichnen, also als erster Versuch, einen Rücklauf nach unten fortzusetzen. Doch die neuen Bullenbars zeigen bereits zu viel Stärke für einen bequemen Short.',
      'Deshalb richtet sich der Blick eher auf einen Long nach einem höheren Tief. Denkbar ist auch ein vorausgeplanter Kauf bei einem begrenzten Rücklauf. Solche Limit-Ideen setzen eine bewusst gewählte Struktur und einen Schutzpunkt voraus; ein anfängerfreundlicher Plan kann stattdessen auf ein klar sichtbares neues Signal warten.',
      'Die Erholung hat mit der vorliegenden Stärke gute Chancen, wenigstens ihr voriges Aufwärtshoch noch einmal zu testen. Das ist eine Erwartung im damaligen Chart, keine Garantie. Der Count „Low 1“ muss gegen die nun sichtbare Käuferseite beurteilt werden.',
    ],
    callout: 'Ein erstes Short-Signal kann nach starkem Käuferanschluss die falsche Seite sein.',
    diagramTitle: 'Low 1 in einer kräftigen Erholung',
    caption: 'Frei erfundene Aufwärtsfolge mit einem kleinen Rücklauf und einer möglichen Higher-Low-Zone; keine historische Bar-Abbildung.',
    observations: ['Der Aufwärtsimpuls bleibt kräftig.', 'Low 1 ist zunächst nur der erste Gegenversuch.', 'Ein höheres Tief kann zur Long-These passen.'],
    prompt: 'Warum ist Bar 10 trotz Low-1-Zählung kein überzeugender Short?',
    answers: [['Weil die davor beobachtete Käuferstärke einen weiteren Hochtest plausibel macht.', 'Richtig. Der Kontext spricht gegen das isolierte Short-Etikett.'], ['Weil Low 1 immer ein Long-Muster ist.', 'Low 1 ist ein möglicher erster Verkaufsversuch.'], ['Weil ein Markt nach Bar 9 nicht mehr fallen kann.', 'Der Rücklauf bleibt möglich, nur seine Einordnung ändert sich.']], correct: 0,
    takeaways: ['Count nach aktueller Marktstärke beurteilen.', 'Höheres Tief als mögliche Long-Struktur erkennen.', 'Erwarteten Hochtest nicht als Sicherheit verkaufen.'],
  },
  {
    number: 23, title: 'Bar 11: Klimax, Gewinnmitnahme und höhere Tiefs',
    summary: 'Ein zweiter Short an einer Widerstandszone kann nur einen Rücklauf auslösen.',
    section: 'Fall 10.2 · Bar 11 und Ausblick',
    anchors: ['Fall 10.2 · Doji-Reversal-Bar 11', 'Kaufklimax und Doppel-Hoch-Bärenflagge', 'Gewinnmitnahme, MA-Test und mögliches höheres Tief'],
    scenario: 'c10-deep-bar11',
    paragraphs: [
      'Bar 11 ist im Beispielchart ein Doji mit Umkehrcharakter nach einem großen bullischen Trendbar. Die Rally hatte zuvor über mehrere Bars viel Käuferdruck aufgebaut. Ein besonders großer später Bullenbar kann eine Kaufklimax markieren; danach sind grob zehn oder mehr seitliche bis fallende Bars möglich, bevor Käufer wieder übernehmen. Das ist eine Erwartung im Chartfall, keine feste Zeitregel.',
      'Der Bereich liegt zudem nahe dem letzten tieferen Hoch des vorigen Bärentrends. Damit kann die Erholung als Doppel-Hoch-Bärenflagge gelesen werden. Long-Trader können dort Gewinne sichern; aggressive Bären können einen begrenzten Short-Rücklauf in Richtung des gleitenden Durchschnitts versuchen. Das sind unterschiedliche Absichten am selben Preisort.',
      'Wegen der vorherigen starken Käuferreaktion rechnet man gleichzeitig mit der Möglichkeit eines höheren Tiefs, bevor Käufer erneut erscheinen. Bar 11 beendet den Bullenversuch also nicht zwingend. Bei der Lektüre trenne Einstieg für einen kleinen Gegen-Trade, Gewinnmitnahme eines Longs und Prognose des nächsten größeren Trends.',
    ],
    callout: 'Ein zweiter Short kann einen Rücklauf begründen, ohne den ganzen Käuferimpuls auszulöschen.',
    diagramTitle: 'Klimax am alten Hoch und möglicher Rücklauf',
    caption: 'Eigenes Zwei-Panel-Schema markiert eine späte bullische Beschleunigung am Widerstand und einen Rücklauf zu einem noch höheren Tief.',
    observations: ['Der späte große Bullenbar kann Erschöpfung anzeigen.', 'Altes tieferes Hoch dient als Testzone.', 'Eine Korrektur kann über dem letzten Tief enden.'],
    prompt: 'Welche Aussage hält die beiden Seiten bei Bar 11 auseinander?',
    answers: [['Ein kleiner Short-Rücklauf und ein späteres höheres Tief können beide zum Chart passen.', 'Richtig. Die Gegenbewegung muss den Käuferimpuls nicht vollständig umkehren.'], ['Ein Doji beweist einen neuen dauerhaften Bärentrend.', 'Form und Ort allein garantieren keinen Trendwechsel.'], ['Gewinnmitnahme eines Longs und neuer Short sind dieselbe Position.', 'Sie sind verschiedene Entscheidungen mit verschiedenen Risiken.']], correct: 0,
    takeaways: ['Klimax und Trendwechsel unterscheiden.', 'Profit-taking und neuer Gegentrend-Entry trennen.', 'Höheres Tief nach starkem Käuferlauf als Möglichkeit offenlassen.'],
  },
];

export const chapterTenDeepDiveLessons = drafts.map(chapterTenLesson);
