import { chapterTenLesson, type ChapterTenDraft } from './chapter-10-model';

const drafts: ChapterTenDraft[] = [
  {
    number: 10, title: 'Fall 10.2: Den ersten Short bei Bar 1 auslassen',
    summary: 'Nach fünf starken Bullenbars bekommt der zweite Short-Versuch bei Bar 2 mehr Gewicht.',
    section: 'Fall 10.2 · Bars 1 und 2',
    anchors: ['Fall 10.2 · Bar 1 nach fünf Bullenbars', 'Ersten Short-Versuch beobachten', 'Bar 2 als zweiter Versuch'],
    scenario: 'c10-102-first-short',
    paragraphs: [
      'Im Beispielchart kommt Bar 1 nach fünf aufeinanderfolgenden bullischen Trendbars. Ein erster Short direkt gegen diese Folge trifft auf Käufer, die gerade mehrfach stark geschlossen haben. Auch ein auffälliger Gegenbar muss diese Vorgeschichte erst überwinden.',
      'Du wartest ab, ob die Käufer nach dem ersten Rücklauf noch einmal nach oben kommen und dann erneut scheitern. Beim zweiten Short-Versuch um Bar 2 liegt genau diese zusätzliche Reaktion vor. Deshalb beurteilst du ihn anders als das schnelle Raten eines Tops bei Bar 1.',
      'Das Lehrschema zeigt keinen identischen historischen Kursverlauf. Es macht den Entscheidungsunterschied sichtbar: Ohne zweiten gescheiterten Anstieg fehlt die neue Information. Und auch ein zweiter Versuch hängt noch vom späteren Bruch und der Verkäuferfolge ab.',
    ],
    callout: 'Fünf starke Bullenbars sind ein Grund, den ersten Short nicht vorwegzunehmen.',
    diagramTitle: 'Erster und zweiter Short nach Bullenstärke',
    caption: 'Eigene schematische Folge: Nach kräftigem Anstieg wird der erste Rücklauf gekauft; erst der erneute Hochversuch scheitert.',
    observations: ['Mehrere Bullenbars schaffen Momentum.', 'Der erste Short steht gegen diese Stärke.', 'Der zweite Versuch enthält einen gescheiterten Käufer-Test.'],
    prompt: 'Was ist gegenüber Bar 1 beim Short um Bar 2 hinzugekommen?',
    answers: [['Ein weiterer Versuch der Bullen nach dem ersten Rücklauf und dessen Scheitern.', 'Richtig. Das ist die neue Information des zweiten Entries.'], ['Die Gewissheit eines vollständigen Bärenmarktes.', 'Ein zweiter Entry garantiert keinen großen Trend.'], ['Ein identischer Preis in allen Zeitebenen.', 'Das ist weder nötig noch Aussage des Charts.']], correct: 0,
    takeaways: ['Vor Bar 1 die fünf Bullenbars beachten.', 'Gegenbewegung und erneuten Hochversuch abwarten.', 'Bar 2 als zweite Gelegenheit im Kontext lesen.'],
  },
  {
    number: 11, title: 'Fall 10.2: Bar 3 ist noch kein überzeugender Boden',
    summary: 'Nach einer langen Folge ohne bullischen Schluss bekommt der Long bei Bar 4 zusätzliche Bestätigung.',
    section: 'Fall 10.2 · Bars 3 und 4',
    anchors: ['Fall 10.2 · neues Tagestief bei Bar 3', 'Sechs Bars ohne bullischen Schluss', 'Bar 4 als zweiter Long-Versuch'],
    scenario: 'c10-102-second-long',
    paragraphs: [
      'Bar 3 bietet im Fallbeispiel nach einem neuen Tagestief einen ersten Long-Versuch. Doch die sechs Bars davor brachten keinen überzeugenden bullischen Schluss. Die Verkäufer haben also eine längere, gut sichtbare Kontrolle aufgebaut.',
      'Bei Bar 4 entsteht später ein zweiter Long-Versuch. Zwischen den beiden Punkten konnte der Markt zeigen, wie er auf das neue Tief und den ersten Kauf reagiert. Das macht den zweiten Einstieg besser prüfbar, auch wenn die vorherige Abwärtskraft nicht einfach verschwindet.',
      'Wer nur die tiefe Lage sieht, hält Bar 3 vielleicht voreilig für ein Schnäppchen. Die Lektion dreht die Reihenfolge um: Zuerst die sechs schwachen Schlüsse zählen, dann den ersten Versuch beobachten und erst beim erneuten Signal überlegen, ob sich die Käufer wirklich durchsetzen.',
    ],
    callout: 'Ein neues Tief nach sechs schwachen Bars verlangt mehr als einen ersten Long-Bar.',
    diagramTitle: 'Neues Tief, erster und zweiter Kaufversuch',
    caption: 'Ein erfundener Bärenimpuls zeigt erst einen schwachen ersten Gegenversuch und danach einen zweiten Test mit stärkerer Käuferreaktion.',
    observations: ['Der Verkaufsdruck reicht bis zum ersten Versuch.', 'Der zweite Versuch kommt nach einer Reaktion.', 'Der Long benötigt trotzdem sichtbaren Anschluss.'],
    prompt: 'Weshalb ist im Fallbeispiel Bar 4 als Long eher prüfbar als Bar 3?',
    answers: [['Weil Bar 3 immer ein Verlusttrade sein muss.', 'Das Ergebnis folgt nicht allein aus der Nummer.'], ['Weil nach der langen Serie schwacher Schlüsse erst eine weitere Käuferreaktion sichtbar wurde.', 'Richtig. Der zweite Versuch enthält mehr Information.'], ['Weil der zweite Entry ohne Stop gehandelt werden darf.', 'Ein begrenzter Schutz bleibt erforderlich.']], correct: 1,
    takeaways: ['Sechs Bars ohne bullischen Schluss als Kontext mitlesen.', 'Neues Tief nicht automatisch als Boden werten.', 'Die Reaktion zwischen den Entries prüfen.'],
  },
  {
    number: 12, title: 'Fall 10.2: Bei Bar 5 kommt kein zweiter Long',
    summary: 'Vier Bärenbars warnen vor dem ersten Kauf; ohne Folgesignal bleibst du draußen.',
    section: 'Fall 10.2 · Bar 5',
    anchors: ['Fall 10.2 · Bar 5 nach vier Bärenbars', 'Ersten Long auslassen', 'Kein zweiter Kaufversuch entwickelt sich'],
    scenario: 'c10-102-no-second',
    paragraphs: [
      'Vor Bar 5 stehen im Chart vier bärische Trendbars. Der erste mögliche Long geht damit direkt gegen eine kräftige Verkaufsphase. Das Setup sieht vielleicht verlockend aus, aber seine Vorgeschichte spricht gegen den sofortigen Gegentrend-Einstieg.',
      'Hier zeigt sich der Nutzen der Warte-Regel besonders klar: Danach bildet sich kein zweiter Long-Versuch. Die bevorzugte Bedingung tritt also nicht ein. Wer den Plan ernst nimmt, muss sich keinen Ersatz-Entry aus irgendeinem späteren Bar zurechtbasteln.',
      'Das Auslassen erspart dir im beschriebenen Fall einen Verlust. Wichtiger als dieses nachträglich bekannte Ergebnis ist aber die Regel, die vorher schon ausführbar war: bei starkem Abwärtsdruck den ersten Gegenversuch auslassen und nur bei einem echten erneuten Setup neu entscheiden.',
    ],
    callout: 'Erscheint der zweite Versuch nicht, ist „kein Trade“ die vollständige Entscheidung.',
    diagramTitle: 'Erster Long ohne erneuten Versuch',
    caption: 'Zwei eigene Lehrpanels trennen den ersten bullischen Versuch nach starken Bärenbars von einer Folge ohne zweiten Long-Trigger.',
    observations: ['Vier Bärenbars prägen die Ausgangslage.', 'Der erste Gegenversuch bleibt unbeantwortet.', 'Die Bedingung für den geplanten zweiten Entry fehlt.'],
    prompt: 'Was tust du im beschriebenen Fallbeispiel, wenn nach Bar 5 kein zweites Long-Setup entsteht?',
    answers: [['Den ersten Versuch im Nachhinein zum zweiten umbenennen.', 'Das würde die festgelegte Bedingung aufweichen.'], ['Trotzdem kaufen, weil jeder Trend enden muss.', 'Das Ende eines Trends ist nicht durch diesen Bar bewiesen.'], ['Den Gegentrend-Trade aus diesem Plan auslassen.', 'Richtig. Eine nicht entstandene Gelegenheit wird nicht erzwungen.']], correct: 2,
    takeaways: ['Vier Trendbars vor dem Signal berücksichtigen.', 'Abwarten darf in einem Auslassen enden.', 'Keine zweite Gelegenheit erfinden.'],
  },
  {
    number: 13, title: 'Fall 10.2: Bar 11 folgt erst nach einem zweiten Test',
    summary: 'Vor dem Short bei Bar 10 steigt der Markt zu beständig; Bar 11 liefert eine erneute Verkaufsmöglichkeit.',
    section: 'Fall 10.2 · Bars 10 und 11',
    anchors: ['Fall 10.2 · sechs Bars mit höheren Tiefs', 'Bar 10 als früher Short', 'Bar 11 als zweiter Short-Versuch'],
    scenario: 'c10-102-second-short',
    paragraphs: [
      'Bis Bar 10 hat der Beispielchart sechs Bars mit steigenden Tiefs. Nur zwei Bars haben kleine bärische Körper. Das ist etwas anderes als eine müde, überlappende Erholung: Die Käufer verteidigen Rückläufe und schieben die Tiefs Stufe für Stufe nach oben.',
      'Ein Short bei Bar 10 wäre ein früher Versuch gegen diesen Aufwärtsdruck. Erst der spätere bärische Reversal-Bar bei Bar 11 bietet eine zweite Gelegenheit. Durch die zusätzliche Preisfolge kannst du Verkäuferreaktion und die Grenze der Käuferstärke neu einordnen.',
      'Auch Bar 11 darfst du nicht ohne den größeren Kontext lesen. Der Chart hat vorher einen Bärentrend und danach eine kräftige Erholung gezeigt. Ein zweiter Short kann einen Rücklauf auslösen, ohne dass er die ganze Käuferbewegung zwingend rückgängig macht.',
    ],
    callout: 'Höhere Tiefs vor einem Short sind Momentum, das erst überwunden werden muss.',
    diagramTitle: 'Steigende Tiefs vor dem zweiten Short',
    caption: 'Eigene Folge mit höheren Tiefs und zwei getrennten Verkaufsversuchen; der erneute Test kommt erst nach weiterem Käuferdruck.',
    observations: ['Höhere Tiefs zeigen wiederholte Verteidigung.', 'Bar 10 liegt gegen diese Stärke.', 'Bar 11 ist eine neue, aber begrenzte Gegenthese.'],
    prompt: 'Was spricht im Fallbeispiel gegen einen vorschnellen Short bei Bar 10?',
    answers: [['Die vorangehende Reihe höherer Tiefs und wenige schwache Bärenkörper.', 'Richtig. Die Käuferseite ist unmittelbar davor kräftig.'], ['Die absolute Nummer 10.', 'Eine Barnummer hat ohne Marktstruktur keine Bedeutung.'], ['Dass Bar 11 zwingend ein neues Allzeithoch bringen wird.', 'Der zweite Short ist ein Gegenversuch, kein solcher Beweis.']], correct: 0,
    takeaways: ['Höhere Tiefs als bullische Stärke erkennen.', 'Ersten und zweiten Short zeitlich trennen.', 'Zweiten Entry nicht mit großem Trendwechsel gleichsetzen.'],
  },
];

export const chapterTenFigure102Lessons = drafts.map(chapterTenLesson);
