import { chapterSevenLesson, type ChapterSevenDraft } from './chapter-07-model';

// Independent teaching prose and schematics, following the chapter's argument.
const drafts: ChapterSevenDraft[] = [
  {
    number: 1, title: 'Ein Outside-Bar umfasst seinen Vorgänger',
    summary: 'Die äußeren Grenzen zeigen, dass beide Seiten innerhalb kurzer Zeit aktiv waren.',
    section: 'Outside-Bar und Überlappung',
    anchors: ['Outside Bars · Definition', 'Hoch über und Tief unter dem Vorbar', 'Überlappung als kurze Trading Range'],
    scenario: 'c07-boundaries',
    paragraphs: [
      'Ein Outside-Bar hat ein höheres Hoch und ein tieferes Tief als der unmittelbar vorherige Bar. Entscheidend sind beide äußeren Grenzen; ein Bar mit nur einem neuen Hoch ist noch keiner. Der Schluss kann irgendwo innerhalb dieser erweiterten Spanne liegen.',
      'Die große Spanne verrät, dass Käufer und Verkäufer zeitweise energisch waren. Schließt der Bar nahe seiner Mitte, bleibt von der Expansion wenig gerichtete Kontrolle übrig. Zusammen mit dem komplett überdeckten Vorbar ergibt er schon eine kleine zweiseitige Zone.',
      'Du kannst die Form deshalb nicht in einen festen Kauf- oder Verkaufshinweis übersetzen. Erst die Stellung in Trend, Pullback oder Trading Range und die nächsten Bars zeigen, ob aus der Expansion ein Trendversuch, eine Umkehr oder weitere Balance wird.',
    ],
    callout: 'Außen heißt größere Spanne – noch keine festgelegte Richtung.',
    diagramTitle: 'Zwei Grenzen müssen überschritten sein',
    caption: 'Eigenes Schema: Ein großer Bar umschließt das Hoch und Tief des vorherigen Bars; ein einseitiger Hochbruch dient als Gegenbild.',
    observations: ['Links sind beide alten Extreme überschritten.', 'Der Schluss liegt nicht zwingend am neuen Hoch.', 'Rechts fehlt das neue Tief und damit die Outside-Form.'],
    prompt: 'Ein neuer Bar übersteigt das Hoch des Vorbars, hält dessen Tief aber. Wie ist er einzuordnen?',
    answers: [['Als Outside-Bar, weil ein neues Hoch genügt.', 'Beide Extreme müssen überschritten werden.'], ['Als möglicher Ausbruch, aber nicht als Outside-Bar.', 'Richtig. Die zweite äußere Grenze fehlt.'], ['Als zwingende Umkehr nach unten.', 'Die Richtung folgt daraus nicht.']], correct: 1,
    takeaways: ['Höheres Hoch und tieferes Tief sind beide nötig.', 'Überlappung macht die Folge zweiseitig.', 'Marktort und Schluss geben der Form erst Bedeutung.'],
  },
  {
    number: 2, title: 'Die gleiche Form kann drei Rollen spielen',
    summary: 'Outside-Bars erscheinen als kurze Range, Umkehr- oder Trendbar.',
    section: 'Rolle im Kontext',
    anchors: ['Outside Bars · Kontext', 'Range-, Reversal- und Trend-Bar', 'Schluss und Anschluss'],
    scenario: 'c07-three-roles',
    paragraphs: [
      'Mitten in einer Folge überlappender Bars bestätigt ein Outside-Bar oft nur, dass beide Seiten handeln. Sein Schluss in der Mitte und eine sofortige Rückkehr in die alte Zone sprechen gegen einen klaren Gewinner.',
      'An einem überdehnten Extrem kann dieselbe äußere Form eine Abweisung zeigen: zuerst neuer Preis in Trendrichtung, dann ein kräftiger Gegenschluss. Nach einem glaubwürdigen Wechsel kann ein Outside-Bar dagegen als starker Trend-Bar der neuen Richtung wirken.',
      'Schau deshalb auf die Bars vor dem Signal und seine Schlusslage. Frag dann, ob der Kurs außerhalb der wichtigen Grenze bleibt. Eine Formbezeichnung ersetzt weder diese Reihenfolge noch die Prüfung des Folgebars.',
    ],
    callout: 'Range, Umkehr und Trend sind Rollen in einer Folge, keine Eigenschaften des Namens.',
    diagramTitle: 'Seitliche Expansion und gerichteter Wechsel',
    caption: 'Zwei selbst konstruierte Spannen zeigen einmal einen mittigen Schluss und einmal einen kräftigen Gegenschluss nach einem Extremtest.',
    observations: ['Überlappung setzt links die Range fort.', 'Rechts wird ein alter Extrempreis deutlich verlassen.', 'Ein Folgetest entscheidet, ob die neue Seite hält.'],
    prompt: 'Was ist nach einem großen Outside-Bar in einer engen, mehrbarigen Range die vorsichtige Ausgangsannahme?',
    answers: [['Ein sicherer Trendstart.', 'Große Spanne allein beendet die Balance nicht.'], ['Automatisch eine Trendwende.', 'Der alte Trendstatus ist hier nicht einmal geklärt.'], ['Weitere zweiseitige Bewegung, bis Anschluss sichtbar wird.', 'Richtig. Das Umfeld bleibt zunächst eine Range.']], correct: 2,
    takeaways: ['Die Vorgeschichte bestimmt die wahrscheinliche Rolle.', 'Schluss und Anschluss unterscheiden die Fälle.', 'Die Form allein ist kein Handelsplan.'],
  },
  {
    number: 3, title: 'Ein großer Outside-Bar macht den Ausbruch teuer',
    summary: 'Ein Einstieg jenseits der ganzen Spanne kann ein ungünstig großes Risiko erzeugen.',
    section: 'Ausbruchsrisiko',
    anchors: ['Outside Bars · Ausbruch über Bargrenze', 'Weite Schutzdistanz', 'Risiko und Positionsgröße'],
    scenario: 'c07-breakout-risk',
    paragraphs: [
      'Wer erst über dem Hoch eines großen Outside-Bars kauft und den Schutz unter seinem Tief plant, muss eine breite Strecke tragen. Spiegelbildlich gilt das für einen Short unter der gesamten Spanne. Ein kurzer Ausbruch in einer Range kann dieses Verhältnis zusätzlich verschlechtern.',
      'Die bekannte Idee, vorsorglich auf beiden Seiten Stop-Orders zu platzieren, wird dadurch unzuverlässig. Nach einem Fill kann auch die Gegenrichtung kurz auslösen. Gerade bei einer großen Fünf-Minuten-Spanne ist oft ein früheres, besser begründetes Signal oder das Abwarten eines kleineren Pullbacks sinnvoller.',
      'Rechtfertigt die Marktstruktur einen Einstieg trotzdem, gehören Schutzort und Positionsgröße zur Entscheidung. Der größere Bar darf nicht unbemerkt ein größeres Geldrisiko erzeugen. Eine engere Geldgrenze wiederum ersetzt keinen sachlichen Grund, warum der Trade noch gültig sein sollte.',
    ],
    callout: 'Prüf vor dem Trigger die gesamte Strecke bis zur sinnvollen Ungültigkeit.',
    diagramTitle: 'Breite Bar, weiter Schutzpunkt',
    caption: 'Das Lehrschema vergleicht einen Ausbruch jenseits einer großen Outside-Spanne mit einem früheren, kleineren Signal.',
    observations: ['Der späte Trigger liegt weit von der Gegenseite.', 'Eine Range kann den kurzen Bruch sofort zurückholen.', 'Ein kleineres Setup verändert die Risikostrecke.'],
    prompt: 'Ein sehr großer Outside-Bar steht in der Range-Mitte. Was muss vor einem Buy-Stop über seinem Hoch geklärt sein?',
    answers: [['Nur ob der Stop ein Tick über dem Hoch liegt.', 'Die technische Marke sagt nichts über Zielraum und Risiko.'], ['Ob Zielraum, Schutzdistanz und Positionsgröße zusammenpassen.', 'Richtig. Die weite Spanne ist ein wesentlicher Teil des Plans.'], ['Ob gleichzeitig ein doppelt großer Short-Stop bereitsteht.', 'Eine Gegenorder löst das Grundproblem nicht.']], correct: 1,
    takeaways: ['Der Barumfang vergrößert oft die Schutzdistanz.', 'Ein kurzer Range-Bruch kann beide Seiten täuschen.', 'Risiko ist vor der Auslösung zu beurteilen.'],
  },
  {
    number: 4, title: 'Outside als Entry-Bar statt als Breakout-Setup',
    summary: 'Ein guter Vorbar kann die Long-These tragen, während der nächste Bar beide Extreme durchläuft.',
    section: 'Signal-Bar und Entry-Bar',
    anchors: ['Outside Bars · vorheriger Signal-Bar', 'Long-Auslösung am Hoch des Vorbars', 'Outside-Bar als Entry-Bar'],
    scenario: 'c07-prior-signal',
    paragraphs: [
      'Stell dir einen klaren bullischen Signal-Bar an einem getesteten Tief vor. Der nächste Bar handelt zunächst darunter. Bleibt der übergeordnete Kaufgrund bestehen, kann ein geplanter Einstieg über dem Hoch des Signal-Bars weiterhin sinnvoll sein.',
      'Dreht dieser zweite Bar stark nach oben und löst den Einstieg aus, wird er erst während seiner Entstehung zum Outside-Bar. Der Kauf erfolgt am Hoch des ursprünglichen Signal-Bars, nicht erst über der jetzt viel größeren Spanne des Outside-Bars. Diese beiden Preise und Risiken darfst du nicht verwechseln.',
      'Ohne brauchbaren Vorbar oder tragfähigen Umkehrkontext wäre dieselbe Bewegung im Bar nur unruhig. Die Qualität des vorherigen Signals und die sichtbare Reaktion der Gegenseite begründen den Plan; die neue Form ist das Ergebnis der Auslösung.',
    ],
    callout: 'Signal im Vorbar, Auslösung im Outside-Bar: zwei verschiedene Aufgaben.',
    diagramTitle: 'Erst unten, dann über das Signalhoch',
    caption: 'Eigenes Zwei-Panel-Beispiel: Ein bullischer Vorbar setzt den Long-Trigger; der Folgebalken berührt erst das Tief und dann das Hoch.',
    observations: ['Das ursprüngliche Signal entsteht vor der Expansion.', 'Der Folgebalken löst am alten Hoch aus.', 'Seine spätere Outside-Spanne ist nicht der ursprüngliche Trigger.'],
    prompt: 'Ein guter bullischer Vorbar wird kurz unterboten, dann durchbricht der nächste Bar sein Hoch. Welcher Bar war das Signal?',
    answers: [['Der bullische Vorbar; der Outside-Bar ist der Entry-Bar.', 'Richtig. Die Rollen liegen zeitlich auseinander.'], ['Nur der nun größere Outside-Bar.', 'Er kann Einstieg sein, aber der Plan kam aus dem Vorbar.'], ['Keiner, weil ein Tiefbruch jeden Long grundsätzlich verbietet.', 'Die Kontextthese kann trotz eines kurzen Tiefbruchs bestehen.']], correct: 0,
    takeaways: ['Signal und Einstieg zeitlich trennen.', 'Der Vorbar muss für sich brauchbar sein.', 'Nicht automatisch über die gesamte Outside-Spanne einsteigen.'],
  },
  {
    number: 5, title: 'Ein zweiter Umkehrversuch kann die Expansion tragen',
    summary: 'Nach Trendlinienbruch und erneutem Test des Extrems kann ein Outside-Bar eine echte Käuferreaktion zeigen.',
    section: 'Zweiter Einstieg an einem Extrem',
    anchors: ['Outside Bars · zweiter Einstieg', 'Trendkanal-Überschuss und zweiter Tief-Test', 'Käufer übernehmen nach Short-Fehlversuch'],
    scenario: 'c07-second-entry',
    paragraphs: [
      'Ein starker Bärentrend endet selten mit der ersten grünen Kerze. Interessanter wird ein späterer zweiter Tiefversuch, wenn der fallende Kanal schon verletzt wurde und der neue Ausbruch nach unten keine Fortsetzung mehr findet.',
      'Dort kann der nächste Bar zuerst unter den Vorbar fallen und Verkäufer anziehen, dann dessen Hoch übersteigen und als Outside-Up-Bar schließen. Ein vorher geplanter Einstieg über dem Vorbar wird jetzt ausgelöst. Die neue Richtung wird durch den gescheiterten zweiten Verkaufsversuch gestützt.',
      'Das ist ein anderer Fall als ein zufälliger Outside-Bar mitten in einer Range. Hier liefern zeitliche Reihenfolge, Kanaltest und zweite Chance Gründe für einen größeren Gegenmove. Ob daraus ein neuer Trend wird, musst du an weiteren Bars prüfen.',
    ],
    callout: 'Das zweite Signal bekommt sein Gewicht aus dem gescheiterten Trendversuch.',
    diagramTitle: 'Zweiter Tief-Test nach Kanalbruch',
    caption: 'Das unabhängige Schema setzt einen frühen, schwachen Gegenversuch neben einen späteren Test mit Outside-Up-Einstieg.',
    observations: ['Der erste Gegenbar steht noch im Abwärtstrend.', 'Später verliert der erneute Tiefbruch an Wirkung.', 'Der Schluss oberhalb des Vorbars bestätigt zunächst Käuferdruck.'],
    prompt: 'Wodurch unterscheidet sich ein Outside-Up-Bar nach zweitem Tief-Test von einem im ersten Bärenspike?',
    answers: [['Nur durch seine Farbe.', 'Die Form kann gleich aussehen.'], ['Durch die zusätzliche Struktur aus Kanalbruch und fehlender neuer Verkaufsfortsetzung.', 'Richtig. Sie verändert die Ausgangslage.'], ['Weil danach kein weiterer Rücklauf möglich ist.', 'Die Zukunft bleibt offen.']], correct: 1,
    takeaways: ['Ein zweiter Test liefert neue Information.', 'Outside kann hier Entry-Bar einer Umkehr sein.', 'Die Folge muss den Wechsel weiter bestätigen.'],
  },
  {
    number: 6, title: 'In der Range-Mitte ist Ausweitung kein Vorteil',
    summary: 'Ein Outside-Bar kann die bestehende Balance bestätigen, statt sie zu beenden.',
    section: 'Outside-Bar in der Range',
    anchors: ['Outside Bars · Mitte einer Trading Range', 'Ausbrüche ohne Folge', 'Kleine nächste Bar am äußeren Rand'],
    scenario: 'c07-range-middle',
    paragraphs: [
      'Mehrere Bars pendeln schon zwischen ähnlichen Grenzen. Ein größerer Bar, der seinen Vorgänger ganz umschließt, zeigt in dieser Mitte vor allem, dass beide Seiten zum Handeln bereit sind. Wer über seinem Hoch kauft, kann nahe am oberen Rand der ganzen Range landen.',
      'Nach einem schnellen Bruch über oder unter die große Spanne kehrt der Kurs oft zurück. Das ist kein Befehl, jeden Bruch blind dagegenzuhalten. Du kannst stattdessen auf eine kleine Folgekerze nahe einem äußeren Rand, einen erkennbaren Fehlausbruch oder einen späteren Pullback warten.',
      'Erst wenn der Markt außerhalb der bisherigen Zone bleibt und neue Bars Anschluss schaffen, verdient die Ausbruchsthese mehr Gewicht. Bis dahin ist Abwarten eine vollwertige Entscheidung; dass eine große Kerze auftaucht, verpflichtet dich zu nichts.',
    ],
    callout: 'Range-Mitte plus große Outside-Spanne bietet oft wenig klaren Zielraum.',
    diagramTitle: 'Großer Bar mitten im alten Bereich',
    caption: 'Ein selbst konstruierter Range-Cluster hält den Outside-Bar in der Mitte; rechts folgt ein kleiner Bar am Rand.',
    observations: ['Die alte Zone bleibt auf beiden Seiten bestehen.', 'Der große Bar verbessert die Lage nicht.', 'Ein späteres kleines Signal am Rand kann die Entscheidung präzisieren.'],
    prompt: 'Ein Outside-Bar umschließt seinen Vorbar mitten in einer engen Range. Was ist zunächst gerechtfertigt?',
    answers: [['Sofort beide Ausbruchsseiten handeln.', 'Die Spanne ist groß und der Zielraum unklar.'], ['Warten auf Randtest, Fehlausbruch oder gehaltenen Bruch.', 'Richtig. Erst neue Struktur verbessert den Plan.'], ['Aus dem Namen eine Trendrichtung ableiten.', 'Outside beschreibt nur die Extreme.']], correct: 1,
    takeaways: ['In der Mitte bestätigt der Bar oft Balance.', 'Ein kurzer Bruch kann wieder eingefangen werden.', 'Abwarten ist ein legitimer Plan.'],
  },
  {
    number: 7, title: 'ioi braucht einen sinnvollen Ausbruchsraum',
    summary: 'Innen–außen–innen liefert eine Grenze, aber der Ort des letzten Bars entscheidet mit.',
    section: 'ioi und Zielraum',
    anchors: ['Outside Bars · ioi', 'Inside-Bar nach Outside-Bar', 'Lage, Größe und Ausbruchsraum'],
    scenario: 'c07-ioi-context',
    paragraphs: [
      'Auf einen Inside-Bar folgt ein Outside-Bar und danach wieder ein Inside-Bar: Diese Abfolge heißt ioi. Der letzte Bar liefert eine enge Auslösungsgrenze, aber seine Lage innerhalb der größeren Outside-Spanne kann sehr unterschiedlich sein.',
      'Ein kleiner bärischer Inside-Bar nahe einem neuen Swinghoch kann nach einem gescheiterten Hochversuch einen nachvollziehbaren Short vorbereiten. Liegt der letzte Bar groß und zentral in einer engen, mehrfach überlappten Zone, wäre der Bruch nach unten oft nur ein Verkauf nahe der Range-Unterkante.',
      'Prüfe deshalb nicht nur die drei Buchstaben. Wie weit ist die gegenüberliegende Grenze entfernt? Hat der Ausbruch Platz bis zu einem vernünftigen Ziel? Bleibt der Kurs nach dem Trigger draußen? Ohne diese Antworten ist das Muster bloß eine Beschreibung.',
    ],
    callout: 'ioi benennt die Reihenfolge; Marktort und verfügbare Strecke entscheiden über den Nutzen.',
    diagramTitle: 'Kleiner Inside-Bar am Rand gegen großen in der Mitte',
    caption: 'Zwei unabhängige ioi-Folgen haben dieselbe Reihenfolge, aber unterschiedlichen Abstand zu ihrer nächsten Range-Grenze.',
    observations: ['Die Abfolge innen–außen–innen ist beidseits gleich.', 'Am Rand ist der nächste Zielraum größer.', 'In der Mitte bleibt der Bruch innerhalb einer größeren Balance.'],
    prompt: 'Welcher ioi-Short hat einen verständlicheren Ausgangspunkt?',
    answers: [['Ein kleiner bärischer Inside-Bar am oberen Rand nach einem fehlgeschlagenen Hochtest.', 'Richtig. Ort und Raum helfen der These.'], ['Ein großer Inside-Doji in der Mitte einer engen Range.', 'Der Short läge nahe an einem möglichen Range-Tief.'], ['Jeder ioi-Short unabhängig von Vorbars und Ziel.', 'Die Buchstaben allein reichen nicht.']], correct: 0,
    takeaways: ['ioi ist eine Folge von Spannen.', 'Die Position des letzten Bars zählt.', 'Ein Ausbruch braucht Raum und Bestätigung.'],
  },
  {
    number: 8, title: 'Ein Outside-Bar kann zum Trend-Bar werden',
    summary: 'Nach einem glaubwürdigen Richtungswechsel verliert die Range-Lesart manchmal ihre Vorherrschaft.',
    section: 'Außenbar im neuen Trend',
    anchors: ['Outside Bars · mit neuer Trendrichtung', 'Frühes Bein nach Umkehr', 'Starker Schluss und Folgebars'],
    scenario: 'c07-trend-outside',
    paragraphs: [
      'Nach einer deutlichen Käuferreaktion und einem höheren Tief versuchen Verkäufer oft noch einmal, den alten Bärentrend fortzusetzen. Wird dieser kurze Tiefbruch sofort zurückgenommen und der Bar steigt über das vorige Hoch, entsteht ein Outside-Up-Bar.',
      'In diesem besonderen Zusammenhang kann er wie ein kräftiger Bullen-Trendbar wirken. Die Käufer setzen sich gegen den alten Short-Plan durch, der Schluss ist hoch, und weitere Bars laufen aufwärts. Dass er zwischendurch nach unten ausgeweitet hat, macht ihn nicht automatisch zur Range.',
      'Für diese Lesart brauchst du die neue Struktur vor dem Bar und den Anschluss danach. Schließt derselbe Bar neutral und folgen weitere überlappende Bars, liegt die vorsichtigere Range-These weiterhin näher.',
    ],
    callout: 'Außenform und Trendwirkung können gleichzeitig vorkommen – im passenden Verlauf.',
    diagramTitle: 'Scheiternder Tiefbruch, hoher Schluss',
    caption: 'Ein eigener Kursweg zeigt ein höheres Tief, eine kurz ausgelöste Short-Seite und den starken Outside-Up-Schluss.',
    observations: ['Ein früher Käuferimpuls liegt bereits vor.', 'Das alte Tief wird nur kurz unterschritten.', 'Hoher Schluss und Anschluss stützen die neue Richtung.'],
    prompt: 'Wann lässt sich ein Outside-Up-Bar eher als Trend-Bar der neuen Richtung lesen?',
    answers: [['Wenn er in der Range-Mitte als Doji schließt.', 'Das bestätigt eher Balance.'], ['Wenn er nach höherem Tief den Short-Bruch zurückweist und stark aufwärts anschließt.', 'Richtig. Struktur und Folge tragen die Lesart.'], ['Immer sobald beide Extreme des Vorbars überschritten wurden.', 'Die Definition legt seine Wirkung nicht fest.']], correct: 1,
    takeaways: ['Der alte Trendversuch kann im Bar scheitern.', 'Starker Schluss und Anschluss zählen.', 'Die Range-Lesart ist kein Automatismus.'],
  },
  {
    number: 9, title: 'Das höhere Tief kann der Beginn des neuen Beins sein',
    summary: 'Für die funktionale Bein-Zählung zählt der Moment, in dem der Kontrollwechsel erkennbar wird.',
    section: 'Beine nach Outside-Umkehr',
    anchors: ['Outside Bars · Ursprung des Aufwärtsbeins', 'Höheres Tief nach altem Bärentief', 'Zwei funktionale Beine und späterer Test'],
    scenario: 'c07-leg-origin',
    paragraphs: [
      'Ein Chart zeigt vielleicht schon einen ersten Anstieg vom absoluten Bärentief. Nach einem Rücklauf entsteht ein höheres Tief; erst dort scheitert ein neuer Short, und ein kräftiger Outside-Up-Bar lässt die Käuferseite sichtbar übernehmen.',
      'Zählst du ab dem optischen Tief, kann die spätere Bewegung wie drei Aufwärtsschübe aussehen. Für die Entscheidung in diesem Fall ist aber das höhere Tief der wichtigere Start: Erst hier wird der Wechsel breit akzeptiert. Von diesem Punkt aus lässt sich ein späterer Pullback und ein weiterer Schub als zweite funktionale Bewegung lesen.',
      'Das ist eine Deutung der Marktstruktur, kein Trick, um jedes Chartmuster umzubenennen. Markiere, wann Käufer und Verkäufer ihr Verhalten tatsächlich ändern. Nach einem starken ersten Schub wird dessen Ursprung oft noch einmal getestet, bevor die Fortsetzung klar wird.',
    ],
    callout: 'Zähl nicht nur optische Zacken; such den nachweisbaren Kontrollwechsel.',
    diagramTitle: 'Optisches Tief und funktionales Starttief',
    caption: 'Zwei Markierungen im eigenen Schema trennen das absolute Tief vom späteren höheren Tief mit Outside-Up-Umkehr.',
    observations: ['Vom absoluten Tief gibt es bereits eine Gegenbewegung.', 'Am höheren Tief scheitert der alte Short-Plan.', 'Ab dort gewinnt die neue Bein-Zählung Bedeutung.'],
    prompt: 'Warum kann das höhere Tief nach einem Bärentief für die neue Aufwärtszählung wichtiger sein?',
    answers: [['Weil erst dort die erneute Verkaufsfortsetzung scheitert und Käufer deutlich übernehmen.', 'Richtig. Das ist der erkennbare Strukturwechsel.'], ['Weil das absolute Tief nie zum Chart gehört.', 'Es bleibt ein sichtbares und relevantes Extrem.'], ['Weil jedes höhere Tief garantiert zwei weitere Schübe bringt.', 'Eine Garantie folgt daraus nicht.']], correct: 0,
    takeaways: ['Optischer und funktionaler Ursprung können abweichen.', 'Der gescheiterte Short-Versuch begründet den Wechsel.', 'Ein späterer Test prüft die neue Käuferstruktur.'],
  },
  {
    number: 10, title: 'Gefangene Shorts können flache Pullbacks erklären',
    summary: 'Ausstiege der alten Seite und nachlaufende Käufer können denselben Schub antreiben.',
    section: 'Positionsdruck nach Umkehr',
    anchors: ['Outside Bars · fehlgeschlagene Bärenflag', 'Short-Eindeckung und verpasste Longs', 'Kleine Rückläufe im neuen Schub'],
    scenario: 'c07-trapped-orders',
    paragraphs: [
      'Ein Tiefbruch unter eine vermeintliche Bärenflag füllt neue Shorts. Schießt derselbe Bar danach nach oben, müssen diese Verkäufer ihre alte Annahme prüfen. Käufer, die auf einen ruhigen Rücklauf warteten, sehen den Einstieg gleichzeitig davonlaufen.',
      'Beide Gruppen würden einen tieferen Rücklauf begrüßen: die einen für einen günstigeren Ausstieg, die anderen für einen günstigeren Einstieg. Werden aber schon kleine Rücksetzer gekauft, kann eine mehrbarige Korrektur lange ausbleiben, und der erste Aufwärtsschub läuft weit.',
      'Das ist eine Erklärung für möglichen Positionsdruck, keine Kenntnis einzelner Marktteilnehmer und keine Gewissheit über die nächste Kerze. Du beobachtest den gescheiterten Tiefbruch, den kräftigen Schluss und weitere flache Pullbacks; erst diese sichtbare Folge stützt die These.',
    ],
    callout: 'Ein Fehlausbruch kann Ausstiege und neue Käufe in dieselbe Richtung bündeln.',
    diagramTitle: 'Short-Falle und flache Rückläufe',
    caption: 'Eigenes Lehrschema zeigt einen zuerst ausgelösten Short, seine Rücknahme und mehrere kleine Rücksetzer im Aufwärtsschub.',
    observations: ['Der Short-Trigger wird zuerst berührt.', 'Der Outside-Schluss widerspricht dem Plan.', 'Spätere Rückläufe bleiben klein, solange Kaufdruck anhält.'],
    prompt: 'Was lässt sich aus einem schnellen Short-Fehlschlag und danach mehrfach gekauften Mini-Rückläufen ableiten?',
    answers: [['Dass der nächste Bar zwangsläufig steigt.', 'Eine Folge erhöht Plausibilität, liefert aber keine Garantie.'], ['Dass nur eine einzige Händlergruppe aktiv sein kann.', 'Ausstiege und neue Käufe können zusammentreffen.'], ['Dass mehrere Gruppen denselben Aufwärtsschub unterstützen könnten.', 'Richtig. Das ist eine mögliche Erklärung der sichtbaren Folge.']], correct: 2,
    takeaways: ['Fehlversuche ändern die Positionslage.', 'Flache Pullbacks sind ein sichtbarer Hinweis.', 'Motive bleiben Hypothesen, keine beobachteten Orders.'],
  },
  {
    number: 11, title: 'Bei Unklarheit weitere Bars abwarten',
    summary: 'Nicht jeder Outside-Bar verdient eine Vorhersage oder eine Order.',
    section: 'Entscheidung bei Unsicherheit',
    anchors: ['Outside Bars · Unsicherheit', 'Warten auf Follow-through', 'Range- und Trendhypothese neu prüfen'],
    scenario: 'c07-wait',
    paragraphs: [
      'Outside-Bars können in wenigen Minuten erst die eine Seite locken und dann die andere. Besonders bei großen Schatten, mittigem Schluss und wiederholter Überlappung lässt sich die nächste Richtung schwer aus der einzelnen Kerze ablesen.',
      'Ein sauberer Arbeitsplan nennt die Alternative: Ein gehaltener Bruch mit Anschluss stärkt die Trendthese; die schnelle Rückkehr und ein kleiner Gegenbar am Rand stärken die Range- oder Fehlausbruchsthese. Solange weder das eine noch das andere vorliegt, musst du keine Position eröffnen.',
      'Abwarten ist nicht passiv, wenn du die Grenzen und den nächsten aussagekräftigen Test notierst. So verhinderst du, dass der Name einer Formation statt des sichtbaren Marktes die Entscheidung trifft.',
    ],
    callout: 'Erst neue Kursinformation kann eine unklare Outside-Spanne ordnen.',
    diagramTitle: 'Zwei mögliche Fortsetzungen nach demselben Bar',
    caption: 'Ein eigener großer Outside-Bar erhält einmal bestätigten Anschluss und einmal eine schnelle Rückkehr in die alte Range.',
    observations: ['Die Ausgangskerze bleibt in beiden Fällen gleich.', 'Anschluss verschiebt die Beweislast.', 'Rückkehr in die Zone spricht für erneute Balance.'],
    prompt: 'Outside-Bar mit langen Schatten schließt mittig. Die Vorbars überlappen stark. Was ist eine vollständige Entscheidung?',
    answers: [['Sofort den ersten Tick über dem Bar kaufen.', 'Ein kurzer Tick-Bruch beweist keinen Trend.'], ['Grenzen notieren und auf einen aussagekräftigen Folgetest warten.', 'Richtig. Die Ausgangslage ist unklar.'], ['Automatisch beide Seiten gleichzeitig eröffnen.', 'Das vergrößert das Risiko ohne bessere Evidenz.']], correct: 1,
    takeaways: ['Unsicherheit darf ausdrücklich benannt werden.', 'Folgebars unterscheiden Ausbruch und Rückkehr.', 'Kein Trade ist bei fehlendem Vorteil ein Plan.'],
  },
];

export const chapterSevenFoundationLessons = drafts.map(chapterSevenLesson);
