import { makeChapterFiveLesson, type ReversalLessonDraft } from './chapter-05-model';

export const chapterFiveCaseLessons = ([
  {
    number: 18,
    title: 'Chartfall 5.1: Der bullische Bar dreht keine Range',
    summary: 'Eine schöne Form entwerten, wenn vier überlappende Bars schon zweiseitigen Handel zeigen.',
    sourceUnit: 'Kapitel 5 · Chartfall 5.1 · Überlappender Bullen-Bar',
    sourceAnchors: ['Bullische Umkehrform nach engem Bärenkanal', 'Überlappung mit mehreren Vorbars', 'Long nahe der Oberkante ohne klaren alten Verkaufsüberschuss'],
    durationMinutes: 13,
    teachingTitle: 'Beginne beim Bereich um den Bar, nicht beim Bar selbst',
    paragraphs: [
      'In der ersten Szene des Chartfalls wirkt der bullische Bar für sich genommen einladend. Markierst du aber die Spanne der vier Bars davor, siehst du viel gemeinsamen Handel. Der neue Bar bleibt größtenteils in dieser Zone.',
      'Die Verkäufer hatten unmittelbar davor keinen klaren neuen Preisbereich erobert, den die Käufer jetzt zurücknehmen könnten. Wer über der bullischen Kerze kauft, steigt womöglich am oberen Rand des gerade entstandenen Seitwärtsbereichs ein.',
      'Der frühere Abwärtskanal bleibt als Hintergrund wichtig. Ein erster Ausbruch aus einem engen Kanal kann eine neue Struktur vorbereiten, aber ein einzelner überlappender Bar liefert noch keine eindeutige Entscheidung zwischen erneuter Erholung und Wiederaufnahme des Falls.',
      'Für die eigene Übung reicht ein schematischer Chart: Umrahme die letzten Bars, markiere das mögliche Entry-Level und schreib auf, an welcher Stelle die These echten Anschluss bekommen müsste. Die Darstellung nutzt absichtlich keine Originalkurse.',
    ],
    callout: 'Liegt der Signal-Bar fast ganz in den alten Bars, ist die gemeinsame Range deine erste Information.',
    scenario: 'reversal-case-51-overlap',
    chartTitle: 'Chartfall 5.1: Bullische Form innerhalb der gemeinsamen Spanne',
    caption: 'Eigenes Schema zum Lernpunkt des Fallbeispiels: Eine bullische Kerze überlappt vier frühere Bars und bietet am oberen Rand wenig freien Raum.',
    observations: ['Der Bar verlässt die gemeinsame Spanne nicht deutlich.', 'Ein Long oberhalb des Bars läge nahe der Oberkante.', 'Die nächste Bewegung muss erst zeigen, ob überhaupt Käufer außerhalb der Range bleiben.'],
    questionTitle: 'Weshalb ist der Long schwach?',
    prompt: 'Der bullische Bar überlappt vier Vorbars und erreicht deren obere Grenze. Was ist der wichtigste Einwand gegen einen sofortigen Long?',
    choices: ['Er hat einen unteren Schatten.', 'Die Käufer hätten nahe der Range-Oberkante noch keinen nachhaltigen Ausbruch belegt.', 'Es gab zuvor irgendwann einen Bärenbar.'],
    explanations: ['Ein unterer Schatten kann je nach Ort sogar hilfreich sein.', 'Richtig. Die Lage im gemeinsamen Handelsbereich ist hier die Schwäche.', 'Ein einzelner früherer Bärenbar ist nicht der entscheidende Einwand.'],
    correct: 1,
    takeaways: ['Der Chartfall beginnt mit einer überlappenden Zone.', 'Ein schönes Einzelbar-Signal kann innerhalb der Range schwach sein.', 'Der nächste Ausbruch und sein Anschluss bleiben offen.'],
  },
  {
    number: 19,
    title: 'Chartfall 5.1: Gescheiterte Käufer helfen dem Short',
    summary: 'Wie eine bärische Reaktion nach einem schwachen Kaufausbruch zusätzlichen Verkaufsdruck erzeugen kann.',
    sourceUnit: 'Kapitel 5 · Chartfall 5.1 · Gescheiterter Ausbruch',
    sourceAnchors: ['Kaufausbruch über früheres bullisches Signal scheitert', 'Bärische Reversal-Bar an oberer Bereichsgrenze', 'Ausstiege enttäuschter Käufer und neue Shorts'],
    durationMinutes: 14,
    teachingTitle: 'Der zweite Bar verändert die Geschichte des ersten',
    paragraphs: [
      'Im nächsten Abschnitt des Chartfalls überschreitet der Preis den möglichen Kaufeinstieg, findet aber keinen dauerhaften Anschluss. Ein späterer bärischer Bar nimmt diesen Versuch zurück. Die ersten Käufer sehen ihre Annahme sofort widerlegt.',
      'Fällt der Markt unter die bärische Signalzone, können zwei Gruppen gleichzeitig verkaufen: frühe Longs, die ihren Trade beenden, und Trader, die einen neuen Short auf den Fehlausbruch planen. Das erklärt möglichen kurzfristigen Druck, garantiert aber keine große Abwärtsbewegung.',
      'Die Lage nahe dem oberen Rand einer Range und ein fehlgeschlagener Ausbruch wiegen mehr als die reine Farbe des bärischen Bars. Ohne diese Vorgeschichte wäre derselbe Short-Bar nur eine weitere Kerze im zweiseitigen Handel.',
      'Plane bei der Fallanalyse auch das Gegenteil ein: Wird der bärische Bar sofort überschritten und halten die Käufer außerhalb der Range, ist die Short-These geschwächt. Leg die Grenze fest, bevor du eine Ausführung simulierst.',
    ],
    callout: 'Ein Fehlausbruch schafft neue Information: Der alte Long-Plan scheitert, und ein möglicher Short bekommt Kontext.',
    scenario: 'reversal-case-51-failure',
    chartTitle: 'Chartfall 5.1: Long-Ausbruch, Rückkehr und Short-Trigger',
    caption: 'Eigenes Schema: Der Kurs kehrt nach dem Versuch über der Range zurück; das Unterschreiten des bärischen Bars prüft die neue Verkaufsseite.',
    observations: ['Die Long-Auslösung bekommt keinen tragfähigen Anschluss.', 'Ein bärischer Bar nimmt den Ausbruch zurück.', 'Ausstiege und neue Shorts können unter seiner Tiefzone zusammentreffen.'],
    questionTitle: 'Was trägt zum Verkaufsdruck bei?',
    prompt: 'Ein Kaufausbruch aus einer Range fällt sofort zurück und unterschreitet einen bärischen Signal-Bar. Welche Erklärung passt am besten?',
    choices: ['Nur neue Leerverkäufer können den Preis bewegen.', 'Das Muster beweist einen vollständigen Trendtag nach unten.', 'Enttäuschte Longs können aussteigen, während neue Shorts denselben Bereich nutzen.'],
    explanations: ['Auch das Schließen bestehender Longs erzeugt Verkaufsorders.', 'Der weitere Tagesverlauf bleibt ungewiss.', 'Richtig. Beide Ordermotive können in dieselbe Richtung wirken.'],
    correct: 2,
    takeaways: ['Ein Fehlausbruch verändert die Bewertung des ersten Signals.', 'Ausstiege bestehender Longs können neue Shorts ergänzen.', 'Auch die Short-These braucht einen klaren Fehlpunkt.'],
  },
  {
    number: 20,
    title: 'Chartfall 5.2: Das unterschrittene Tief wird zurückerobert',
    summary: 'Einen langen unteren Schatten nach einem echten Test eines Extrems anders lesen als eine bloße Range-Kerze.',
    sourceUnit: 'Kapitel 5 · Chartfall 5.2 · Neuer Tief-Ausbruch',
    sourceAnchors: ['Test unter früheres wichtiges Tief', 'Rückkehr über die alte Tiefzone', 'Vorheriger Abverkauf und anschließende Käuferreaktion'],
    durationMinutes: 13,
    teachingTitle: 'Hier wurde ein konkreter Verkaufsversuch widerlegt',
    paragraphs: [
      'Die erste Szene des zweiten Chartfalls beginnt mit starkem Verkaufsdruck und einem Vorstoß unter ein vorher sichtbares Tief. Dort bleiben weitere Verkäufe zunächst aus, und der Preis kehrt in den alten Bereich zurück. Der untere Schatten fasst diese Abfolge im Bar zusammen.',
      'Der wichtige Unterschied zur bloß überlappenden Kerze ist die geprüfte Grenze: Die Verkäufer wollten unter dem alten Tief Anschluss finden. Ihr Versuch wird zeitnah zurückgenommen. Deshalb können auch Short-Positionen zum Rückkauf gezwungen sein.',
      'Der lange Schatten beweist noch keinen neuen Bullenmarkt. Ein Händler beobachtet, ob der nächste Bar das Tief hält, ob die Käufer höhere Schlusskurse schaffen und wo die Idee bei erneuter Schwäche scheitert.',
      'Leg in einer Übung drei Linien fest: das alte Tief, das Tief des Test-Bars und das geplante Entry-Level. So trennst du Hoffnung und Invalidierung, bevor ein Trade überhaupt ausgelöst würde.',
    ],
    callout: 'Ein Schatten bekommt sein Gewicht dadurch, dass ein bestimmter Ausbruch unter eine wichtige Marke scheitert.',
    scenario: 'reversal-case-52-break',
    chartTitle: 'Chartfall 5.2: Test unter der alten Tiefmarke',
    caption: 'Eigenes Schema zum Fallbeispiel: Ein neues Tief hält nicht; die Rückkehr über das Referenzniveau verändert die Lage.',
    observations: ['Die alte Tiefzone ist vor dem Test sichtbar.', 'Der Bar handelt kurz darunter und kehrt zurück.', 'Die spätere Käuferfolge entscheidet, ob mehr als ein kurzfristiger Rückkauf entsteht.'],
    questionTitle: 'Was macht diesen Schatten besonders?',
    prompt: 'Der Markt unterschreitet ein klar markiertes Swing-Tief und schließt wieder darüber. Warum ist das informativer als ein langer Schatten innerhalb einer Range?',
    choices: ['Ein konkreter Ausbruch nach unten wurde getestet und zurückgenommen.', 'Jeder lange Schatten garantiert zehn steigende Bars.', 'Range-Grenzen spielen grundsätzlich keine Rolle.'],
    explanations: ['Richtig. Hier wurde ein vorher bekannter Referenzpreis sichtbar verteidigt.', 'Eine solche Dauer ist weder garantiert noch aus dem Schatten allein ableitbar.', 'Gerade die Grenze macht den Unterschied.'],
    correct: 0,
    takeaways: ['Der alte Tiefpreis macht den Verkaufsversuch messbar.', 'Rückkehr über die Zone kann den Ausbruch widerlegen.', 'Anschluss und Fehlpunkt bleiben nötig.'],
  },
  {
    number: 21,
    title: 'Chartfall 5.2: Die ähnliche Kerze ohne Tief-Test',
    summary: 'Die zweite Silhouette mit großem Schatten als zweiseitigen Handel einordnen.',
    sourceUnit: 'Kapitel 5 · Chartfall 5.2 · Überlappende Alternative',
    sourceAnchors: ['Großer Schatten mit kleinem Körper an einem anderen Tag', 'Kein Durchstoß unter ein relevantes altes Tief', 'Überlappung mit mehreren früheren Bars'],
    durationMinutes: 12,
    teachingTitle: 'Gleiche Form, aber kein gescheiterter Ausbruch',
    paragraphs: [
      'Der zweite Bar in diesem Vergleich sieht dem ersten auffallend ähnlich: tiefer Ausflug, kräftige Rückkehr, relativ kleiner Körper. Er bleibt aber in einem Bereich, den schon mehrere frühere Bars gehandelt haben. Eine neue Verkaufsgrenze wurde nicht geprüft.',
      'Auf einer kleineren Zeitebene kann die ganze Kerze wie ein gewöhnlicher Seitwärtsabschnitt wirken. Ein Kauf über ihrem Hoch wäre dann ein Einstieg am oberen Rand dieser kleineren Range, während ein neuer Ausflug nach unten weiter plausibel bleibt.',
      'Warte auf zusätzliche Preisaktion, wenn du eine Umkehr handeln willst: einen echten Ausbruch aus dem Bereich mit Anschluss, einen erneuten tieferen Test mit sofortiger Rückkehr oder eine andere klar beschreibbare Veränderung.',
      'Vergleich in beiden Szenen ausdrücklich den alten Referenzpreis. Der Schatten fällt optisch sofort auf; die fehlende Grenze musst du aktiv suchen. Genau das ist der Lernpunkt dieses Doppelbeispiels.',
    ],
    callout: 'Die Silhouette kann gleich sein; ohne getestete Grenze fehlt der konkrete Fehlausbruch.',
    scenario: 'reversal-case-52-inside',
    chartTitle: 'Chartfall 5.2: Ähnliche Form innerhalb alter Spannen',
    caption: 'Eigenes Schema: Der lange Schatten bleibt innerhalb des zuvor gehandelten Bereichs; zusätzliche Evidenz wird gebraucht.',
    observations: ['Vorbars überlappen die neue Kerze stark.', 'Der Preis hat kein relevantes Tief zurückerobert.', 'Ein Long am Hoch würde nahe der Bereichsoberkante entstehen.'],
    questionTitle: 'Was fehlt gegenüber Fall 5.2A?',
    prompt: 'Der zweite Bar hat einen langen unteren Schatten, aber er bleibt innerhalb der letzten Bars. Welche wichtige Beobachtung fehlt?',
    choices: ['Ein bestimmter Wochentag.', 'Ein gescheiterter Ausbruch unter eine zuvor erkennbare Tiefmarke.', 'Ein möglichst symmetrischer oberer Schatten.'],
    explanations: ['Der Wochentag erklärt diesen Strukturunterschied nicht.', 'Richtig. Ohne diesen Test kann der Bar nur Teil einer Range sein.', 'Symmetrie ist kein Ersatz für die fehlende Referenz.'],
    correct: 1,
    takeaways: ['Langer Schatten allein unterscheidet die zwei Szenen nicht.', 'Die getestete Grenze gibt der ersten Szene ihre Bedeutung.', 'In der überlappenden Szene ist Abwarten eine begründete Entscheidung.'],
  },
  {
    number: 22,
    title: 'Chartfall 5.3: Die unkonventionelle bärische Umkehr',
    summary: 'Ein großer Abwärtsbar nimmt viele frühere Schlusskurse zurück, obwohl er kein klassisches Umkehrmuster mit Tail oben ist.',
    sourceUnit: 'Kapitel 5 · Chartfall 5.3 · Unkonventioneller Reversal-Bar',
    sourceAnchors: ['Kräftiger Bärenbar nach bullischem Abschnitt', 'Schluss unter mehreren früheren Schlüssen und Tiefs', 'Belastung zuvor eingegangener Long-Positionen'],
    durationMinutes: 14,
    teachingTitle: 'Die Bewegung zurück durch alte Preise zählt mehr als eine Pin-Bar-Form',
    paragraphs: [
      'Im dritten Chartfall steigt der Markt zunächst. Dann fällt ein breiter Bärenbar durch mehrere vorher gehaltene Preisniveaus und schließt tief. Dafür muss er nicht erst über das Hoch des Vorbars steigen. Sein Schluss kehrt trotzdem einen beträchtlichen Teil der jüngsten Aufwärtsphase um.',
      'Käufer aus dem vorherigen Abschnitt sind damit in einer neuen Lage: Ihre Positionen verlieren, und eine Erholung könnte eher als Gelegenheit zum Ausstieg gesehen werden. Zusätzliche Verkäufe können einen späteren Rücklauf begrenzen.',
      'Ein starker Einzelbar kann gleichzeitig mehrere Rollen haben: Er stößt durch eine Range-Grenze, dreht einen vorherigen Anstieg und kann die Grundlage eines folgenden Shorts sein. Welcher Name gerade nützlich ist, hängt von der Entscheidung ab, um die es geht.',
      'Trotz seiner Stärke ist auch dieser Bar kein Auftrag, blind am Tief zu verkaufen. Stell den möglichen Einstieg, den Fehlpunkt über einer passenden Struktur und die nächste Gegenreaktion nebeneinander.',
    ],
    callout: 'Ein ungewöhnlicher Bar kann eine echte Veränderung zeigen, wenn sein Schluss viele alte Entscheidungen überschreitet.',
    scenario: 'reversal-case-53-unconventional',
    chartTitle: 'Chartfall 5.3: Ein Schluss unter vielen früheren Preisen',
    caption: 'Eigenes Schema zum Fallbeispiel: Der Abwärtsbar braucht keinen klassischen oberen Schatten, um mehrere Long-Referenzen zu brechen.',
    observations: ['Der Schluss liegt unter mehreren früheren Schlüssen.', 'Zuvor profitable Longs können unter Druck geraten.', 'Der Bar kann zugleich Ausbruch und Umkehr einer älteren Bewegung sein.'],
    questionTitle: 'Warum ist der Bar trotzdem eine Umkehr?',
    prompt: 'Ein starker Bärenbar steigt nie über das Hoch des Vorbars, schließt aber deutlich unter mehreren früheren Schlüssen. Was begründet seine Reversal-Funktion?',
    choices: ['Ein langes oberes Dochtmuster ist immer Pflicht.', 'Nur der Kalenderzeitpunkt macht ihn bärisch.', 'Er nimmt den vorherigen Aufwärtsfortschritt durch seinen tiefen Schluss zurück.'],
    explanations: ['Eine klassische Schattenform ist nicht zwingend.', 'Die sichtbare Preisänderung ist die relevante Information.', 'Richtig. Der Schluss verändert mehrere frühere Preisentscheidungen.'],
    correct: 2,
    takeaways: ['Reversal ist nicht auf eine Pin-Bar-Silhouette beschränkt.', 'Ein Schluss durch mehrere alte Niveaus kann starke Information liefern.', 'Ausbruch, Umkehr und mögliches Signal können im selben Bar zusammentreffen.'],
  },
  {
    number: 23,
    title: 'Chartfall 5.3: Ein Doji nach dem Signal bremst den Impuls',
    summary: 'Die erste Folgereaktion bei starkem und bei schwachem Setup unterschiedlich bewerten.',
    sourceUnit: 'Kapitel 5 · Chartfall 5.3 · Schwacher Entry-Bar',
    sourceAnchors: ['Doji oder Inside-Bar nach bullischem Signal', 'Fehlender unmittelbarer Anschluss', 'Unterschied zwischen starkem Setup und schwacher Auslösung'],
    durationMinutes: 14,
    teachingTitle: 'Der Markt berührt die Schwelle, läuft aber noch nicht los',
    paragraphs: [
      'In mehreren Situationen des dritten Chartfalls folgt auf ein mögliches Kaufsignal nur ein Doji oder ein enger Inside-Bar. Ein Einstieg kann schon ausgelöst sein; der Markt zeigt trotzdem keine Dringlichkeit, höhere Preise zu akzeptieren.',
      'Nach einem schwachen Signal ist ein schwacher Entry-Bar ein besonders ernstes Warnzeichen. Wer keinen guten Grund für den Trade hat, kann einen geordneten Ausstieg nahe dem Einstand prüfen, statt aus Hoffnung immer weiter auf Anschluss zu warten.',
      'Nach einem wirklich starken Setup muss ein einzelner Doji nicht sofort den ganzen Plan zerstören. Ein vorher festgelegter Stop unter dem Signalbereich kann sinnvoll bleiben, solange das Grundszenario intakt ist und deine Positionsgröße dieses Risiko trägt.',
      'Zieh den Stop nicht reflexhaft direkt hinter den engen Doji. Ein gewöhnlicher Rücktest kann ihn auslösen, ohne die größere These zu widerlegen. Die Alternative: den Trade bewusst verkleinern oder beenden, wenn der fehlende Anschluss die ursprüngliche Idee deutlich schwächt.',
    ],
    callout: 'Ein schwacher Entry-Bar ist neue Information; was sie bedeutet, hängt von der Qualität des vorherigen Setups ab.',
    scenario: 'reversal-case-53-doji-entry',
    chartTitle: 'Chartfall 5.3: Signal, Auslösung und zögernder Entry-Bar',
    caption: 'Eigenes Schema: Die Einstiegsschwelle wird berührt, doch der nächste enge Bar bleibt ohne klare Fortsetzung.',
    observations: ['Der Einstieg kann trotz fehlendem Momentum ausgelöst sein.', 'Schwaches Setup und schwacher Entry-Bar verschärfen einander.', 'Ein Stop direkt am Doji kann normalen Rücklauf mit echter Invalidierung verwechseln.'],
    questionTitle: 'Wie reagierst du auf den Doji?',
    prompt: 'Ein eher schwaches Long-Setup wird ausgelöst, der Entry-Bar ist jedoch nur ein Doji. Welche Einordnung ist vernünftig?',
    choices: ['Fehlenden Anschluss als Warnung werten und einen vorher geplanten Ausstieg prüfen.', 'Den Trade ohne neue Begründung vergrößern.', 'Annehmen, dass jeder Doji einen weiteren Trend garantiert.'],
    explanations: ['Richtig. Die Reaktion muss sich nach ursprünglicher Qualität und Risikoplan richten.', 'Das würde ein schwaches Setup ohne zusätzliche Evidenz vergrößern.', 'Ein Doji zeigt gerade wenig unmittelbaren Fortschritt.'],
    correct: 0,
    takeaways: ['Auslösung und kräftiger Anschluss sind verschiedene Ereignisse.', 'Schwaches Setup plus schwacher Entry-Bar verlangt besondere Vorsicht.', 'Stop und Ausstieg orientieren sich an der eigentlichen These.'],
  },
  {
    number: 24,
    title: 'Chartfall 5.3: Überlappende Flag und aufgestauter Druck',
    summary: 'Warum ein starker Einzelbar im falschen Bereich zum Fehlsignal werden kann.',
    sourceUnit: 'Kapitel 5 · Chartfall 5.3 · Flag, Falle und kumulativer Druck',
    sourceAnchors: ['Mehrere große überlappende Bars in einer Flag', 'Scheinbar starker bullischer Reversal-Bar am oberen Rand', 'Vorangegangene bärische Körper als kumulativer Verkaufsdruck'],
    durationMinutes: 14,
    teachingTitle: 'Eine einzelne starke Kerze kann die alte Range nicht ausradieren',
    paragraphs: [
      'Ein weiterer Abschnitt des dritten Chartfalls zeigt eine enge Folge großer, stark überlappender Bars. Ein bullischer Bar darin sieht für sich nach Umkehr aus. Im Gesamtbild läge der Kauf aber nahe am oberen Rand einer Flag statt am Anfang einer frisch bestätigten Aufwärtsbewegung.',
      'Dazu kommt der Druck der vorherigen Bärenkörper: Sie zeigen, dass die Verkäufer mehrfach Schlusskurse auf ihrer Seite hatten. Dieser wiederholte Druck verschwindet nicht, nur weil eine einzelne Kerze einmal grün schließt.',
      'Wird der Kauf über der Flag ausgelöst und fällt sofort zurück, wechseln frühere Käufer womöglich von Hoffen zu Aussteigen. Ein Rückfall kann damit die ursprüngliche Verkaufsrichtung wieder sichtbar machen.',
      'Trenne zwei Fragen: Hat die bullische Kerze einen guten Körper? Und hat der Markt den überlappenden Bereich mit Anschluss verlassen? Die zweite Frage entscheidet, ob die Form in diesem Kontext nützlich war.',
    ],
    callout: 'Kumulativer Druck und Range-Ränder können einen perfekten Einzelbar überstimmen.',
    scenario: 'reversal-case-53-flag',
    chartTitle: 'Chartfall 5.3: Starker Bar am oberen Rand einer Flag',
    caption: 'Eigenes Schema: Mehrere überlappende Bars und wiederholte bärische Schlüsse bilden den Kontext für eine mögliche Kauf-Falle.',
    observations: ['Mehrere Bars teilen denselben Preisraum.', 'Vorherige Bärenkörper zeigen wiederholten Verkaufsdruck.', 'Ein Kauf am oberen Rand braucht einen echten Ausbruch mit Anschluss.'],
    questionTitle: 'Welche Information wird leicht übersehen?',
    prompt: 'Ein großer bullischer Bar steht nach drei stark überlappenden Bars mit mehreren bärischen Schlüssen. Welcher Einwand ist am wichtigsten?',
    choices: ['Der bullische Körper ist zu groß, um jemals zu handeln.', 'Die Flag-Oberkante und der zuvor aufgebaute Verkaufsdruck bleiben relevant.', 'Die Farbe der ersten Kerze des Tages ist unbekannt.'],
    explanations: ['Größe allein ist kein generelles Ausschlusskriterium.', 'Richtig. Ein einzelner Bar löscht die ältere Struktur nicht.', 'Diese Information entscheidet das Setup hier nicht.'],
    correct: 1,
    takeaways: ['Betrachte die letzten Bars gemeinsam statt einen Bar isoliert.', 'Wiederholte bärische Schlüsse können Verkaufsdruck aufbauen.', 'Ein Range-Ausbruch braucht Anschluss außerhalb der alten Spanne.'],
  },
  {
    number: 25,
    title: 'Drei Reversal-Bars, drei Entscheidungen',
    summary: 'Kapitel 5 als Ablauf anwenden: Struktur, Signalqualität, Auslösung und Konsequenz.',
    sourceUnit: 'Kapitel 5 · Synthese und Transfer',
    sourceAnchors: ['Figur 5.1 als überlappende Range und Fehlausbruch', 'Figur 5.2 als echter oder fehlender Extremtest', 'Figur 5.3 als unkonventioneller Kontrollwechsel mit Folgereaktion'],
    durationMinutes: 15,
    teachingTitle: 'Sag zuerst, was der Bar im Chart verändert',
    paragraphs: [
      'Bei der ersten Übung steht ein bullischer Reversal-Bar mitten in mehreren überlappenden Bars. Die Entscheidung kann schlicht Abwarten heißen: Es gibt noch keinen klaren Ausbruch aus dem zweiseitigen Handel. Ein späteres bärisches Fehlsignal ist eine neue, getrennte Situation.',
      'In der zweiten Übung unterschreitet ein Bar ein altes Tief und kehrt darüber zurück. Jetzt lässt sich ein konkreter Verkaufsversuch benennen, aber du prüfst Auslösung und nächsten Schluss. Für die optisch ähnliche Kerze ohne diesen Tief-Test gilt dieselbe Begründung nicht.',
      'In der dritten Übung schließt ein kräftiger Bärenbar unter mehreren vorherigen Preisen. Auch ohne klassischen Umkehr-Tail kann er Käufer unter Druck setzen. Ein späterer Doji als Entry-Bar kann die neue These bremsen; ein Rückfall in die alte Flag kann sie widerlegen.',
      'Formuliere für jeden Fall vier Sätze: Wo liegt der Markt? Was wurde getestet oder zurückgenommen? Was müsste der nächste Bar tun? Bei welchem Preis oder Ereignis ist die Idee falsch? Erst dann ergibt ein Entry-Plan Sinn.',
    ],
    callout: 'Reversal lesen heißt: Kontext → Test → Schluss → Auslösung → Anschluss → Fehlpunkt.',
    scenario: 'reversal-three-decisions',
    chartTitle: 'Drei eigenständige Situationen im Vergleich',
    caption: 'Eigenes Transferdiagramm zu den drei Fallbeispielen: überlappende Range, gescheiterter Tief-Ausbruch und tiefer Schluss durch frühere Long-Niveaus.',
    observations: ['Die gleiche Kerzenkategorie führt nicht zur gleichen Entscheidung.', 'Ein getesteter Referenzpreis verändert den Informationswert.', 'Ein Trade-Plan braucht sowohl Anschluss als auch Invalidierung.'],
    questionTitle: 'Welche Reihenfolge ist tragfähig?',
    prompt: 'Du siehst einen Reversal-Bar in einem unbekannten Chart. Welche Prüf-Reihenfolge macht die wenigsten Annahmen?',
    choices: ['Erst Kerzenname, dann sofort kaufen, später einen Stop suchen.', 'Nur den Schatten messen und die Folgebars ignorieren.', 'Kontext und getestete Grenze prüfen, Schluss und Auslösung beobachten, Fehlpunkt planen.'],
    explanations: ['So werden Lage und Risiko erst nach dem Einstieg bedacht.', 'Die Schattenlänge ersetzt weder Auslösung noch Kontext.', 'Richtig. Jeder Schritt fügt eine beobachtbare Information hinzu.'],
    correct: 2,
    takeaways: ['Fall 5.1 zeigt die Gefahr des überlappenden Bereichs.', 'Fall 5.2 zeigt den Wert eines echten, gescheiterten Extremtests.', 'Fall 5.3 zeigt Umkehr ohne klassische Form und die Bedeutung der Folgebars.', 'Kontext, Auslösung und Fehlpunkt gehören zu jeder Entscheidung.'],
    comparison: {
      title: 'Welches Ereignis hat stattgefunden?',
      positive: { title: 'Sichtbar verändert', points: ['altes Tief zurückerobert oder frühere Schlüsse gebrochen', 'Folgebars bestätigen den neuen Preisbereich', 'Fehlpunkt lässt sich benennen'] },
      warning: { title: 'Nur schöne Form', points: ['Bar bleibt in der alten Range', 'kein relevantes Niveau wurde getestet', 'Auslösung ohne Folgedruck'] },
    },
  },
] satisfies ReversalLessonDraft[]).map(makeChapterFiveLesson);
