import { chapterTenLesson, type ChapterTenDraft } from './chapter-10-model';

const drafts: ChapterTenDraft[] = [
  {
    number: 6, title: 'Fall 10.1: Die meisten zweiten Entries kosten Preis',
    summary: 'Im Beispielchart bringen fast alle erneuten Auslösungen keinen günstigen Rabatt.',
    section: 'Fall 10.1 · Überblick',
    anchors: ['Fall 10.1 · Tagesübersicht', 'Mehrere zweite Entries', 'Auslösung meist gleich oder ungünstiger'],
    scenario: 'c10-101-price-map',
    paragraphs: [
      'Im Beispiel (Fall 10.1) sind über einen ganzen Handelstag viele zweite Einstiegsmöglichkeiten markiert. Es kommt nicht darauf an, ob jede markierte Stelle später Gewinn brachte. Zuerst vergleichst du, welchen Preis die Wartenden gegenüber dem ersten Versuch bekamen.',
      'In diesem historischen Chart liegt fast jeder zweite Auslösungspreis für die jeweilige Richtung auf demselben Niveau oder etwas ungünstiger. Das passt zur Idee, dass mehr Bestätigung meistens etwas Preis kostet. Den einen abweichenden Kaufversuch schauen wir im nächsten Schritt gesondert an.',
      'Zeichne beim Nacharbeiten für jeden Kandidaten Versuch eins, Reaktion und Versuch zwei ein. Trenn Longs und Shorts: Für Long ist höher ungünstiger, für Short tiefer. So prüfst du die zentrale Beobachtung des Fallbeispiels, ohne aus einer pauschalen Regel ein Handelssignal zu machen.',
    ],
    callout: 'Erst die zwei Auslösungspreise vergleichen, dann die Marktstärke beurteilen.',
    diagramTitle: 'Zweite Auslösung ohne Rabatt',
    caption: 'Eigenes Preisschema mit zwei frei erfundenen Kaufversuchen auf ähnlichem oder etwas höherem Niveau; keine echte Kursreihe.',
    observations: ['Zwei Versuche haben zwei Auslösungspunkte.', 'Mehr Information kann einen späteren Preis erfordern.', 'Der Vergleich sagt allein noch nichts über den Gewinn.'],
    prompt: 'Welche Preisbeziehung zeigt sich in Fall 10.1 bei den meisten zweiten Entries?',
    answers: [['Der zweite Entry liegt für die jeweilige Seite gleich oder etwas ungünstiger.', 'Richtig. Der auffällig billigere Long ist die Ausnahme, die er untersucht.'], ['Alle zweiten Longs werden deutlich unter dem ersten ausgeführt.', 'Das entspricht gerade nicht seiner Beobachtung in diesem Chart.'], ['Der Ausführungspreis ist für die Fallbesprechung bedeutungslos.', 'Der Preisvergleich ist das Ausgangsthema des Falls.']], correct: 0,
    takeaways: ['Long und Short beim Preisvergleich spiegeln.', 'Auslösung und späteres Ergebnis nicht vermischen.', 'Abweichungen vom Muster eigens prüfen.'],
  },
  {
    number: 7, title: 'Fall 10.1: Der Long bei Bar 10 wirkt zu billig',
    summary: 'Ein Tick Vorteil gegenüber Bar 9 ist im engen Bärenkanal ein Warnzeichen.',
    section: 'Fall 10.1 · Bars 9 und 10',
    anchors: ['Fall 10.1 · Long bei Bar 9', 'Bar 10 · ein Tick günstigerer Versuch', 'Enger Bärenkanal ab Bar 8'],
    scenario: 'c10-101-bargain-trap',
    paragraphs: [
      'Im Beispiel folgt auf den Long bei Bar 9 ein erneuter Kaufversuch bei Bar 10. Dieser zweite Versuch bietet sogar einen Tick besseren Preis. Das klingt attraktiv, obwohl ein späterer Trader sonst für zusätzliche Bestätigung mehr bezahlt.',
      'Der Chart drumherum liefert den Gegenbeweis zur Schnäppchen-Idee: Seit Bar 8 läuft ein enger Bärenkanal abwärts. Die Verkäufer machen laufend neue Tiefs, die Gegenversuche sind klein. Das günstigere Angebot gibt es also, weil die Kaufkraft fehlt, und nicht, weil der Einstieg plötzlich großzügig geworden wäre.',
      'Der Preisvorteil ist hier der Anlass, die Long-These zu stoppen und den Druck neu zu lesen. Das heißt nicht, dass jeder billigere zweite Entry verliert. Im konkreten Kontext wäre ein sofortiger Gegentrend-Kauf trotz des Tick-Vorteils aber eine schwache Entscheidung.',
    ],
    callout: 'Dem billigen zweiten Long solltest du misstrauen, solange der Bärenkanal eng bleibt.',
    diagramTitle: 'Billigerer Kauf innerhalb des Bärendrucks',
    caption: 'Ein eigener schematischer Abwärtspfad zeigt zwei markierte Kaufversuche; der spätere liegt tiefer, während der Kanal nicht gebrochen ist.',
    observations: ['Der zweite Kaufpunkt liegt etwas tiefer.', 'Die fallende Folge bleibt eng.', 'Der Rabatt kann aus anhaltendem Verkaufsdruck stammen.'],
    prompt: 'Was macht Bar 10 trotz seines günstigeren Long-Preises problematisch?',
    answers: [['Der Long liegt deutlich über dem ersten Auslösungspreis.', 'Im Beispiel liegt er gerade etwas tiefer; das Problem ist der anhaltende Verkaufsdruck.'], ['Der enge Bärenkanal zeigt weiterhin zu viel Verkaufsdruck.', 'Richtig. Der Preisvorteil passt zur Schwäche der Gegenseite.'], ['Ein zweiter Entry darf nie tiefer liegen.', 'Er kann tiefer liegen, muss dann aber besonders kritisch gelesen werden.']], correct: 1,
    takeaways: ['Bar 9 und 10 nur mit dem vorangehenden Kanal vergleichen.', 'Ein Tick Preisvorteil beweist keine bessere Qualität.', 'Gegentrend nur bei erkennbarer Gegenkraft erwägen.'],
  },
  {
    number: 8, title: 'Fall 10.1: Vor dem Long Käuferkraft suchen',
    summary: 'Einzelne minimale Hochstiche reichen nicht als Beleg für eine Umkehr gegen den Bärenkanal.',
    section: 'Fall 10.1 · Vorbedingungen',
    anchors: ['Fall 10.1 · Erläuterung zu Bar 10', 'Mehrere Bars vor dem Signal', 'Ausmaß bullischer Gegenbewegungen'],
    scenario: 'c10-101-bull-evidence',
    paragraphs: [
      'Bevor du einen Kauf gegen den Bärenkanal erwägst, schau ein paar Bars zurück. Konnten die Käufer die Hochs der Vorgängerbars überhaupt deutlich überwinden? Kleine Stiche von wenigen Ticks, die sofort wieder verkauft werden, sind noch keine tragfähige Gegenbewegung.',
      'So unterscheidest du einen echten zweiten Versuch von einer bloßen neuen Zahl auf einer weiter fallenden Kurve. In einem engen Kanal kann ein „High 2“ formal erkennbar sein, während die Käufer weder Raum noch Folgebars gewinnen. Ein sauberer Name fürs Muster nimmt den Druck nicht weg.',
      'Die Übung ist konkret: Markiere bei den Bars vor deinem geplanten Long, wie weit die Aufwärtsversuche kamen und ob sie oben schlossen. Bleiben sie winzig und ohne Anschluss, kannst du Abwarten oder Auslassen besser begründen als den Kauf eines scheinbar billigen Signals.',
    ],
    callout: 'Vor einem zweiten Long muss die Gegenseite im Chart schon etwas erreicht haben.',
    diagramTitle: 'Schwache Hochstiche und tragfähige Gegenbewegung',
    caption: 'Zwei selbst konstruierte Abwärtsfolgen zeigen links nur winzige bullische Stiche und rechts einen sichtbaren Gegenstoß vor einem erneuten Tief-Test.',
    observations: ['Kleine Hochstiche ändern den Bärendruck kaum.', 'Ein Gegenstoß zeigt erstmals Raum für Käufer.', 'Die letzten Bars zählen mehr als das Etikett „zweiter“.'],
    prompt: 'Welche Beobachtung würde einen zweiten Long gegen einen engen Bärenkanal eher stützen?',
    answers: [['Dass der Einstieg einen Tick billiger geworden ist.', 'Der Preisvorteil kann aus weiterem Verkaufsdruck stammen.'], ['Dass kein Bar der letzten Folge über sein Vorhoch kam.', 'Dann fehlt sichtbare Käuferkraft.'], ['Dass einige vorangehende Bars bereits deutlich über vorherige Hochs vorstießen.', 'Richtig. Das wäre konkrete bullische Gegenreaktion.']], correct: 2,
    takeaways: ['Vorbars auf echte Gegenbewegung prüfen.', 'Formale Zählung nicht über Momentum stellen.', 'Fehlende Stärke kann ein Auslassen begründen.'],
  },
  {
    number: 9, title: 'Fall 10.1: Kleine Doppeltests markieren Umkehrversuche',
    summary: 'Die Nähe zweier Hochs oder Tiefs kann den zweiten Angriff sichtbar machen.',
    section: 'Fall 10.1 · Mikro-Doppel',
    anchors: ['Fall 10.1 · Bar 1 und früherer Reversal-Bar', 'Bar 18 und Tief vor Bar 17', 'Mikro-Doppeltop und Mikro-Doppeltief'],
    scenario: 'c10-101-micro-doubles',
    paragraphs: [
      'Im oberen Bereich des Beispielcharts kannst du Bar 1 zusammen mit dem bärischen Reversal-Bar zwei Bars davor als engen zweiten Hochtest lesen. Das nennt man Mikro-Doppeltop. Die Bars müssen weder direkt nebeneinanderliegen noch exakt dasselbe Hoch erreichen.',
      'Weiter unten bildet Bar 18 mit dem Tief des Bars direkt vor Bar 17 eine entsprechende zweite Prüfung der Käuferseite: ein Mikro-Doppeltief. Diese kurzen Muster zeigen, wie erneute Versuche auf kleinem Raum entstehen, auch ohne große, perfekte Doppel-Formation.',
      'Ausführlicher kommen wir in einem späteren Kursteil darauf zurück. Hier reicht die Grundfunktion: Zwei nahe Extremtests können einen zweiten Entry vorbereiten. Ob er trägt, zeigen erst die Richtung der Auslösung und die Folgebars.',
    ],
    callout: 'Zwei nahe Extremtests deuten auf einen erneuten Versuch hin, sind aber kein Umkehrbeweis.',
    diagramTitle: 'Mikro-Doppeltop und Mikro-Doppeltief',
    caption: 'Zwei frei erfundene kleine Folgen zeigen einen wiederholten Hochtest und einen wiederholten Tieftest; keine Nachzeichnung eines echten Charts.',
    observations: ['Die Extremzonen liegen nahe beieinander.', 'Ein Zwischenbar kann die zwei Tests trennen.', 'Die Folge nach dem zweiten Test entscheidet.'],
    prompt: 'Was haben Bar 1 und Bar 18 im Kapitel gemeinsam?',
    answers: [['Sie dienen jeweils als Beispiel für einen zweiten Test einer nahen Extremzone.', 'Richtig. Oben entsteht ein Mikro-Doppeltop, unten ein Mikro-Doppeltief.'], ['Beide müssen exakt denselben absoluten Kurs erreichen.', 'Eine nahe Zone reicht für die strukturelle Deutung.'], ['Beide sind sichere Signale in die gleiche Richtung.', 'Die Richtungen sind verschieden und beide Muster können scheitern.']], correct: 0,
    takeaways: ['Zweite Hoch- und Tieftests auch auf engem Raum erkennen.', 'Form und Auslösung voneinander trennen.', 'Keine Details aus anderen Kursteilen voraussetzen.'],
  },
];

export const chapterTenFigure101Lessons = drafts.map(chapterTenLesson);
