import { makeChapterFiveLesson, type ReversalLessonDraft } from './chapter-05-model';

export const chapterFiveContextLessons = ([
  {
    number: 9,
    title: 'Viel Überlappung kann eine Range statt einer Umkehr sein',
    summary: 'Warum ein hübscher Reversal-Bar mitten in überlappenden Bars kaum jemanden in die Enge treibt.',
    sourceUnit: 'Kapitel 5 · Überlappung und Trading Range',
    sourceAnchors: ['Überlappung mehrerer Bars', 'Zweiseitiger Handel ohne klaren alten Trend', 'Fehlender Anschluss nach scheinbar starkem Signal'],
    durationMinutes: 13,
    teachingTitle: 'Eine Umkehr braucht eine Bewegung, die umgekehrt werden kann',
    paragraphs: [
      'Durchlaufen mehrere Bars nahezu denselben Preisraum, wird schon auf beiden Seiten gehandelt. Ein Reversal-Bar, dessen Spanne fast komplett in diesen Bereich fällt, verändert wenig. Er markiert vielleicht nur den nächsten Ausschlag einer Trading Range.',
      'Ein Long über einem solchen Bar kauft womöglich nahe am oberen Rand des gemeinsamen Bereichs. Dort können kurzfristige Käufer Gewinne mitnehmen, und frühere Käufer warten auf einen Rücklauf zum Einstand. Die Kerze sieht stark aus, aber niemand wird zwingend zu einer größeren Neubewertung gedrängt.',
      'Zeichne dir gedanklich ein Rechteck um die letzten drei bis vier Bars. Liegt der neue Bar überwiegend darin, bewerte zuerst die Range und ihre Ränder. Frag dann, ob der nächste Ausbruch den Bereich wirklich verlässt und außerhalb davon angenommen wird.',
      'Das gilt besonders streng für Umkehrideen gegen den Trend. In einem kräftigen Trend darf ein Pullback-Signal stärker überlappen und trotzdem eine Fortsetzung einleiten. Die bestehende Trendrichtung gibt dort einen anderen Kontext.',
    ],
    callout: 'Überlappung zeigt oft Aushandeln – keinen klaren Sieg einer neuen Seite.',
    scenario: 'reversal-overlap-range',
    chartTitle: 'Der schöne Bar bleibt innerhalb der vorigen Handelsspanne',
    caption: 'Die markierte Zone umfasst mehrere Bars; das vermeintliche Long-Signal entsteht nahe ihrer Oberkante.',
    observations: ['Die alten Bars und der neue Bar teilen denselben Preisraum.', 'Oberhalb des Signals wartet bereits die Range-Oberkante.', 'Erst Ausbruch und Anschluss können das Gleichgewicht verändern.'],
    questionTitle: 'Welche Diagnose kommt zuerst?',
    prompt: 'Vier große Bars überlappen stark; der fünfte schließt bullisch innerhalb derselben Spanne. Was prüfst du zuerst?',
    choices: ['Ob alle Bars dieselbe Kerzenfarbe besitzen.', 'Ob der Markt eine Range bildet und der Einstieg am ungünstigen Rand läge.', 'Wie schön der untere Schatten isoliert aussieht.'],
    explanations: ['Die gemeinsame Spanne ist wichtiger als identische Farben.', 'Richtig. Die Lage in der Range kann das vermeintliche Signal entwerten.', 'Der Schatten ohne Struktur beantwortet die Trade-Frage nicht.'],
    correct: 1,
    takeaways: ['Starke Überlappung spricht für zweiseitigen Handel.', 'Eine Range-Kerze kehrt keinen klaren Trend um.', 'Trendrichtung und Lage zu den Rändern verändern die Bewertung.'],
  },
  {
    number: 10,
    title: 'Die Bar-Mitte als Warnhilfe bei Überlappung',
    summary: 'Eine praktische Sichtprüfung nutzen, ohne daraus eine mechanische Einstiegsregel zu machen.',
    sourceUnit: 'Kapitel 5 · Stärke der Überschneidung',
    sourceAnchors: ['Mitte des bullischen Bars relativ zum vorherigen Tief', 'Spiegelbildliche Prüfung beim bärischen Bar', 'Heuristik je nach Mit-Trend- oder Gegen-Trend-Lage'],
    durationMinutes: 11,
    teachingTitle: 'Wie viel der alten Spanne bleibt erhalten?',
    paragraphs: [
      'Bei einem möglichen bullischen Reversal kann die Mitte des neuen Bars über dem Tief des Vorbars liegen. Dann überlappen sich beide Bars stark. Statt eines klaren neuen Tiefs mit kräftiger Rückeroberung siehst du womöglich nur zwei Seiten desselben kleinen Handelsbereichs.',
      'Für ein bärisches Signal kannst du die Beobachtung spiegeln: Liegt die Mitte des neuen Bars noch unter dem Hoch des Vorbars, könnte auch hier ein großer gemeinsamer Preisraum bestehen. Zeichne die zwei Spannen übereinander, statt eine feste Zahl auswendig zu lernen.',
      'Diese Mitte ist ein Warnhinweis und kein statistisch gesicherter Schalter. In einem starken Trend kann eine überlappende Reaktion mit dem Trend funktionieren, während derselbe Grad an Überlappung einen Einstieg gegen den Trend unattraktiv macht.',
      'Frag zusätzlich: Hat der neue Bar eine frühere Grenze verlassen, und wie schließt der Bar danach? Ein isolierter Vergleich der Mitte kann fehlenden Chartkontext nicht ersetzen.',
    ],
    callout: 'Die Mitte hilft dir, die Überschneidung zu sehen; einen Trade entscheidet sie nicht allein.',
    scenario: 'reversal-midpoint-overlap',
    chartTitle: 'Zwei Spannen und ihre gemeinsame Mitte',
    caption: 'Die Mitte des neuen Bars liegt noch im Bereich des alten Bars – eine visuelle Warnung vor zu viel Überlappung.',
    observations: ['Beide Bars nutzen viele derselben Preise.', 'Es fehlt ein deutlich abgesetzter neuer Bereich.', 'Bei Gegen-Trend-Ideen ist diese Warnung besonders wichtig.'],
    questionTitle: 'Wie verwendest du die Mitte?',
    prompt: 'Die Mitte eines bullischen Reversal-Bars liegt deutlich innerhalb der Spanne des Vorbars. Was folgt daraus?',
    choices: ['Ein Long ist mathematisch ausgeschlossen.', 'Der Bar muss am nächsten Tag gewinnen.', 'Die starke Überlappung ist ein Warnhinweis; Trend und Folgebars bleiben zu prüfen.'],
    explanations: ['Die Mitte ist eine Heuristik, keine Ausschlussformel.', 'Aus einem geometrischen Verhältnis folgt keine solche Prognose.', 'Richtig. Sie lenkt den Blick auf den gemeinsamen Handelsbereich.'],
    correct: 2,
    takeaways: ['Vergleiche Spannen und Bar-Mitte als Sichtprüfung.', 'Spiegele die Logik für bärische Signale.', 'Behandle die Grenze als Warnhilfe, nicht als starre Regel.'],
  },
  {
    number: 11,
    title: 'Ein großer Doji ist eine kleine Range',
    summary: 'Warum ein großer Bar mit kleinem Körper oft mehr Unentschlossenheit zeigt als eine Trendwende.',
    sourceUnit: 'Kapitel 5 · Große Dojis als schwache Signale',
    sourceAnchors: ['Große Gesamtspanne bei kleinem Körper', 'Käufe am Hoch einer Ein-Bar-Range', 'Warten auf ein zweites klares Signal'],
    durationMinutes: 12,
    teachingTitle: 'Große Bewegung innerhalb des Bars, wenig Fortschritt bis zum Schluss',
    paragraphs: [
      'Ein großer Doji durchläuft viel Preisraum, endet aber nahe seiner Eröffnung. Beide Seiten waren aktiv, keine hat den gewonnenen Boden bis zum Ende gehalten. Das ähnelt einer Trading Range, die in einem einzigen Bar zusammengefasst ist.',
      'Wer nach einem starken Bärentrend knapp über dem Hoch dieses Dojis kauft, steigt möglicherweise am oberen Rand dieser Ein-Bar-Range ein. Ohne einen weiteren bullischen Schluss kann der Kurs sofort wieder in den alten Bereich fallen.',
      'Die bessere Lernentscheidung lautet oft: weitere Preisaktion abwarten. Ein zweiter Versuch, ein deutlicher Ausbruch oder ein Pullback mit erneutem bullischem Schluss zeigt mehr über die neue Richtung als die erste Doji-Spanne.',
      'Die Größe des Bar-Körpers musst du deshalb im Verhältnis zur gesamten Spanne lesen. Ein kleiner Bar mit kleinem Körper und ein riesiger Bar mit kleinem Körper bedeuten unterschiedliche Risiken und eine andere Platzierung von Stop und Entry.',
    ],
    callout: 'Ein weiter Doji zeigt Kampf, aber noch keine Seite, die den Schluss kontrolliert.',
    scenario: 'reversal-large-doji',
    chartTitle: 'Ein großer Doji als Ein-Bar-Range',
    caption: 'Die weite Spanne lockt am oberen Rand zum Kauf, doch der Schluss hält keinen nennenswerten Aufwärtsfortschritt fest.',
    observations: ['Hohe und tiefe Preise wurden innerhalb desselben Bars gehandelt.', 'Der kleine Körper lässt die Entscheidung offen.', 'Ein zweites Signal kann die Richtung klären.'],
    questionTitle: 'Was ist der bessere erste Schluss?',
    prompt: 'Nach starkem Rückgang entsteht ein großer Doji mit langen Schatten auf beiden Seiten. Du suchst einen Gegen-Trend-Long. Was ist die robustere Lesart?',
    choices: ['Den Doji als Ein-Bar-Range behandeln und auf weitere bullische Evidenz warten.', 'Den oberen Schatten als sicheren Kaufdruck werten.', 'Das Hoch ohne Risikoplan kaufen, weil die Spanne groß ist.'],
    explanations: ['Richtig. Die große Spanne bei kleinem Körper zeigt noch keine eindeutige Kontrolle.', 'Ein oberer Schatten zeigt gerade, dass ein Hoch wieder abgegeben wurde.', 'Größe allein begründet keinen solchen Einstieg.'],
    correct: 0,
    takeaways: ['Großer Doji bedeutet große Spanne und wenig Nettofortschritt.', 'Ein Einstieg am Rand dieses Bars kann am Range-Rand erfolgen.', 'Ein zweites Signal kann die Lage besser klären.'],
  },
  {
    number: 12,
    title: 'Der Schatten am falschen Ende schwächt das Signal',
    summary: 'Einen bullischen oberen und einen bärischen unteren Schatten als Abgabe vor dem Schluss lesen.',
    sourceUnit: 'Kapitel 5 · Warnzeichen an Schatten und Körper',
    sourceAnchors: ['Oberer Schatten am bullischen Reversal-Bar', 'Unterer Schatten am bärischen Reversal-Bar', 'Starker Körper und zusätzlicher Kontext als mögliche Gegenargumente'],
    durationMinutes: 12,
    teachingTitle: 'Wer gab seinen Vorsprung vor dem Schluss wieder her?',
    paragraphs: [
      'Ein bullischer Bar mit langem oberen Schatten wurde gegen Ende wieder verkauft. Die Käufer hatten zwischendurch mehr erreicht, als sie bis zum Schluss halten konnten. Für einen Gegen-Trend-Long ist das ein anderes Signal als ein Schluss dicht am Hoch.',
      'Beim bärischen Reversal-Bar ist es umgekehrt: Ein langer unterer Schatten zeigt, dass die Verkäufer ein tieferes Niveau nicht bis zum Schluss halten konnten. Der Bar kann trotzdem bärisch sein, zeigt aber zusätzliche Gegenwehr.',
      'Beurteile Schatten nie allein. Ein breiter Körper in Richtung des geplanten Trades und ein zweiter erfolgloser Versuch der Gegenseite können das Gesamtbild verbessern. Ohne diese Unterstützung verlangt der schwache Schluss mehr Geduld.',
      'Skizziere dir vor der Entscheidung die Abfolge: erst Hoch oder Tief, dann Rückgabe, schließlich Schluss. So liest du den tatsächlichen Preisverlauf statt nur eine Kerzenkategorie.',
    ],
    callout: 'Der letzte Teil des Bars zählt: Dort zeigt sich, ob die neue Seite ihren Vorsprung halten konnte.',
    scenario: 'reversal-wrong-end-tail',
    chartTitle: 'Hoher Schluss gegen abgegebenes Hoch',
    caption: 'Der rechte bullische Bar verliert kurz vor dem Schluss einen großen Teil des anfänglichen Fortschritts.',
    observations: ['Gleicher unterer Test kann mit ganz anderem Schluss enden.', 'Ein langer oberer Schatten zeigt Abgabe durch Käufer.', 'Ein kräftiger Körper und ein zweiter Versuch können die Schwäche relativieren.'],
    questionTitle: 'Welcher Schatten ist beim Short verdächtig?',
    prompt: 'Du erwägst einen bärischen Gegen-Trend-Einstieg. Welches Merkmal warnt besonders vor nachlassender Verkaufsinitiative?',
    choices: ['Ein kurzer oberer Schatten.', 'Ein langer unterer Schatten bis zum Bar-Schluss.', 'Ein Schluss unter mehreren früheren Tiefs.'],
    explanations: ['Ein kurzer oberer Schatten ist für sich kein klares Warnzeichen.', 'Richtig. Käufer haben einen Teil des Verkaufsdrucks wieder aufgefangen.', 'Ein solcher Schluss könnte sogar die bärische Evidenz verstärken.'],
    correct: 1,
    takeaways: ['Bullisch mit langem oberem Schatten: Käufer gaben Hochs ab.', 'Bärisch mit langem unterem Schatten: Verkäufer gaben Tiefs ab.', 'Körper, Lage und zweiter Versuch können das Gesamtbild verändern.'],
  },
  {
    number: 13,
    title: 'Ein kleiner Bar senkt das Risiko nicht automatisch',
    summary: 'Eine enge Spanne als mögliche Chance und als Hinweis auf fehlende Gegenkraft auseinanderhalten.',
    sourceUnit: 'Kapitel 5 · Kleine Reversal-Bars',
    sourceAnchors: ['Kleiner Bar im Verhältnis zu früheren Bars', 'Kleiner Körper als schwaches Gegen-Trend-Signal', 'Enge Distanz zum anfänglichen Stop bei passendem Kontext'],
    durationMinutes: 12,
    teachingTitle: 'Ein enger Stop hilft nur, wenn die Idee selbst trägt',
    paragraphs: [
      'Nach mehreren kräftigen Bärenbars kann ein winziger bullischer Bar auftauchen. Dass er klein ist, heißt nicht, dass die Käufer schon stark geworden wären. Gerade mit kleinem Körper kann er nur eine kurze Atempause vor dem nächsten Abwärtsschub sein.',
      'Gleichzeitig erlaubt eine kleine Spanne bei gutem Kontext einen engeren technischen Fehlpunkt. Wer über dem Bar einsteigt und einen Stop unter seiner Tiefzone plant, hat eine klarere Distanz als bei einem riesigen Signal-Bar.',
      'Beide Aussagen gehören zusammen: Kleineres Risiko pro Kontrakt kann mit einer geringeren Chance auf tragfähigen Anschluss einhergehen. Kosten, Slippage und die Platzierung im Gesamtchart bleiben wichtig.',
      'Ein starker Körper an einem schon getesteten Niveau ist etwas anderes als ein winziger Doji mitten im Bärenkanal. Entscheide nach Verlauf und Lage, nicht nach der angenehmen Zahl zwischen Entry und Stop.',
    ],
    callout: 'Eine kurze Stop-Distanz macht ein schwaches Setup nicht automatisch gut.',
    scenario: 'reversal-small-bar',
    chartTitle: 'Zwei kleine Bars, zwei unterschiedliche Situationen',
    caption: 'Im intakten Trend wirkt die Mini-Kerze nur als Pause; am getesteten Tief kann ein kleiner entschlossener Schluss mehr bedeuten.',
    observations: ['Größe allein zeigt keine neue Kontrolle.', 'Ein klarer kleiner Bar kann einen nahen technischen Fehlpunkt bieten.', 'Der alte Trend und die getestete Zone entscheiden über die Qualität.'],
    questionTitle: 'Welche Schlussfolgerung ist unzulässig?',
    prompt: 'Ein bullischer Reversal-Bar ist sehr klein. Sein Stop läge nur wenige Ticks entfernt. Welche Folgerung ist falsch?',
    choices: ['Die Positionsgröße muss zum tatsächlichen Verlustrisiko passen.', 'Die Chartlage und der Bar-Körper bleiben zu prüfen.', 'Der Trade ist allein wegen des engen Stops wahrscheinlich profitabel.'],
    explanations: ['Das gehört zum Risikoplan und ist daher keine falsche Folgerung.', 'Diese Prüfung bleibt nötig und ist daher keine falsche Folgerung.', 'Richtig: Diese Folgerung ist falsch. Der Stop-Abstand sagt nichts über die Erfolgswahrscheinlichkeit allein.'],
    correct: 2,
    takeaways: ['Kleine Bars können nur eine Pause des alten Trends sein.', 'Ein kleiner starker Bar am passenden Ort kann das Risiko begrenzen.', 'Enge Stop-Distanz und guter Erwartungswert sind nicht gleichbedeutend.'],
  },
  {
    number: 14,
    title: 'Eine entstehende Reversal-Bar kann vor Schluss kippen',
    summary: 'Die Gefahr verstehen, einen unfertigen Schatten wie einen fertigen Schluss zu handeln.',
    sourceUnit: 'Kapitel 5 · Unfertige Bars im starken Trend',
    sourceAnchors: ['Vorläufiger Reversal-Eindruck während des Bars', 'Späte Rückkehr des alten Trends vor Schluss', 'Gefangene frühe Gegen-Trend-Einstiege'],
    durationMinutes: 12,
    teachingTitle: 'Während der Bar läuft, ist seine Kerzenform noch veränderlich',
    paragraphs: [
      'Ein fallender Markt bricht kurz unter eine Kanalgrenze und dreht während des laufenden Bars kräftig nach oben. Auf dem Bildschirm sieht das aus wie ein bullischer Reversal-Bar. Bis zum endgültigen Schluss kann der Preis aber wieder fallen.',
      'Schließt der Bar am Tief, hat sich die Geschichte gedreht: Statt einer bestätigten bullischen Abweisung steht dort ein starker Bärenbar. Früh eingestiegene Käufer sitzen jetzt gegen die alte Trendrichtung und müssen ihre Entscheidung neu bewerten.',
      'Eine im Voraus geplante Ausnahme für einen frühen Einstieg kann es geben, sie braucht aber eigene Regeln und ein definiertes Risiko. Wer eigentlich den Bar-Schluss handeln wollte, sollte nicht heimlich während der Entstehung die Regel wechseln.',
      'In der Übung hilft eine einfache Pause: Deck die letzten Sekunden oder den noch offenen Bar ab und entscheide erst nach seinem endgültigen Schluss. Vergleiche dann deine Erwartung mit der tatsächlich abgeschlossenen Kerze.',
    ],
    callout: 'Ein Schatten vor dem Schluss ist eine Möglichkeit; der Schluss kann eine andere Geschichte erzählen.',
    scenario: 'reversal-forming-trap',
    chartTitle: 'Derselbe laufende Bar in zwei Momenten',
    caption: 'Zuerst scheint der Rücklauf stark. Ein später Verkaufsstoß verwandelt das vorläufige Signal in einen Bärenbar.',
    observations: ['Die vorläufige Kerze existiert nur bis zum nächsten Tick.', 'Der endgültige Schluss gibt der Form erst ihren Stand.', 'Frühe Gegen-Trend-Einstiege können bei Rückfall den alten Trend verstärken.'],
    questionTitle: 'Was hat sich wirklich geändert?',
    prompt: 'Ein Bar sieht 30 Sekunden vor Schluss bullisch aus, endet aber am Tief. Welche Information zählt für eine Strategie, die auf abgeschlossene Bars wartet?',
    choices: ['Der bullische Zwischenstand.', 'Der bärische endgültige Schluss.', 'Nur das Tagestief von gestern.'],
    explanations: ['Der Zwischenstand ist kein abgeschlossener Signal-Bar.', 'Richtig. Er widerspricht der vorherigen Umkehrvermutung.', 'Der alte Referenzpreis kann Kontext liefern, ersetzt aber den Bar-Schluss nicht.'],
    correct: 1,
    takeaways: ['Offene Bars können ihre Form bis zum Schluss ändern.', 'Ein später Rückfall kann frühe Gegen-Trend-Trader fangen.', 'Handle nach der Zeitebene und den Regeln deines Plans.'],
  },
  {
    number: 15,
    title: 'Ein großer Schatten mit kleinem Körper braucht Kontext',
    summary: 'Warum dieselbe Silhouette nach einem Tief-Ausbruch und innerhalb einer Range Gegensätzliches bedeutet.',
    sourceUnit: 'Kapitel 5 · Kontext eines langen Schattens',
    sourceAnchors: ['Langer unterer Schatten mit kleinem Körper', 'Ausbruch unter altes Extrem als mögliche Rückweisung', 'Überlappung als Hinweis auf kleinere Range'],
    durationMinutes: 13,
    teachingTitle: 'Wurde ein neues Extrem zurückgenommen oder nur die alte Spanne durchlaufen?',
    paragraphs: [
      'Ein langer unterer Schatten mit kleinem Körper sieht oft nach starken Käufern aus. Tatsächlich zeigt er nur, dass tiefer gehandelt und später höher geschlossen wurde. Ob daraus ein Vorteil wird, hängt vom vorher getesteten Preis ab.',
      'Unterschreitet der Bar ein altes, gut sichtbares Tief und springt rasch darüber zurück, hat der Markt einen echten Verkaufsversuch widerlegt. Besonders nach einem überdehnten Rückgang kann das ein Anlass sein, ein mögliches Aufwärtsbein aufmerksam zu verfolgen.',
      'Liegt derselbe Bar dagegen fast komplett in den Spannen der vorherigen Bars, zeigt sein Schatten womöglich nur eine kleine Range auf der niedrigeren Zeitebene. Ein Kauf nahe seinem Hoch wäre dann ein Kauf am Rand dieser Range.',
      'Leg in beiden Fällen die alte Tiefmarke, den Schluss und den nächsten Bar nebeneinander. Du brauchst keine perfekte Kerzenbezeichnung, sondern eine konkrete Antwort auf die Frage, welcher Verkaufsversuch gescheitert sein soll.',
    ],
    callout: 'Gleiche Silhouette, verschiedene Aussage: Entscheidend ist der Test einer Grenze außerhalb der bisherigen Überlappung.',
    scenario: 'reversal-tail-context',
    chartTitle: 'Neues Tief zurückgewiesen oder nur innen gependelt?',
    caption: 'Links unterschreitet der Bar eine echte Referenz und kehrt zurück; rechts bleibt er innerhalb einer überlappenden Zone.',
    observations: ['Nur links wurde ein klarer Tief-Ausbruch getestet.', 'Rechts gab es keinen vergleichbaren neuen Verkaufsversuch.', 'Der nächste Bar muss zeigen, ob Käufer Anschluss finden.'],
    questionTitle: 'Wo steckt die zusätzliche Information?',
    prompt: 'Zwei Bars haben denselben langen unteren Schatten. Welcher Kontext gibt dem bullischen Versuch mehr Gewicht?',
    choices: ['Der Bar, der das alte Swing-Tief kurz unterschreitet und darüber zurückkehrt.', 'Der Bar, der vollständig innerhalb der letzten vier Bars bleibt.', 'Beide, weil Schattenlängen allein die Qualität bestimmen.'],
    explanations: ['Richtig. Hier ist ein bestimmter Ausbruch nach unten gescheitert.', 'Das kann lediglich ein Ausschlag innerhalb einer Range sein.', 'Der Ort des Bars ist entscheidend.'],
    correct: 0,
    takeaways: ['Ein langer Schatten ist zunächst nur ein beobachteter Weg.', 'Ein gescheiterter Ausbruch über eine Referenz ist informativer.', 'Bei starker Überlappung kann dieselbe Form nur Range-Handel sein.'],
    comparison: {
      title: 'Die Preisgrenze macht den Unterschied',
      positive: { title: 'Außerhalb getestet', points: ['altes Tief klar erkennbar', 'Verkaufsversuch kehrt in den Bereich zurück', 'anschließende Käuferreaktion prüfen'] },
      warning: { title: 'Innerhalb überlappt', points: ['kein neues Extrem durchbrochen', 'lange Schatten auf beiden Seiten möglich', 'Kauf nahe der Range-Oberkante riskant'] },
    },
  },
  {
    number: 16,
    title: 'Auf anderen Zeitebenen ändert sich die Kerzenform',
    summary: 'Das Setup als Preisablauf verstehen, statt für dieselbe Bewegung die perfekte Kerze zu suchen.',
    sourceUnit: 'Kapitel 5 · Zeitrahmen und Bar-Darstellung',
    sourceAnchors: ['Derselbe Verlauf auf Zeit- und Tick-Charts', 'Reversal aus mehreren Bars statt einem idealen Einzelbar', 'Handelsplan in einer festgelegten Zeitebene'],
    durationMinutes: 12,
    teachingTitle: 'Das Ereignis bleibt, während die Darstellung wechselt',
    paragraphs: [
      'Ein Fünf-Minuten-Bar kann wie ein sauberer Reversal-Bar aussehen. Auf dem Ein-Minuten-Chart besteht dieselbe Bewegung aus mehreren fallenden, pausierenden und steigenden Bars. Auf einem Tick-Chart ergeben sich wieder andere Grenzen zwischen den Bars.',
      'Daraus folgt: Die präzise Ein-Bar-Form ist nicht das Ereignis selbst. Das Ereignis ist zum Beispiel das Unterschreiten des alten Tiefs, das Zurückkehren über diese Zone und später ein bestätigender Anstieg.',
      'Wechselst du hinterher so lange die Zeitebene, bis eine perfekte Kerze erscheint, passt du das Bild an deine Wunschidee an. Dabei verlierst du Zeit für die eigentlich wichtige Prüfung von Lage, Risiko und Folgereaktion.',
      'Wähle für eine Übung einen Plan-Zeitrahmen. Beschreibe zuerst die Preisfolge in einfachen Worten; zoome nur dann hinaus oder hinein, wenn eine konkrete Frage zur Struktur offen ist.',
    ],
    callout: 'Beschreibe die Preisfolge und halte die Zeitebene fest, in der du entscheidest.',
    scenario: 'reversal-timeframe-zoom',
    chartTitle: 'Ein Bar links, mehrere Schritte rechts',
    caption: 'Die Rückweisung eines Tiefs ist derselbe Vorgang, obwohl die kleineren Bars keine einzelne perfekte Kerze bilden.',
    observations: ['Bargrenzen verändern die Silhouette.', 'Alter Tief-Test und anschließende Rückkehr bleiben beobachtbar.', 'Plan und Risiko dürfen nicht unbemerkt mit der Zeitebene wandern.'],
    questionTitle: 'Wie vermeidest du Musterjagd?',
    prompt: 'Ein Setup erscheint im Fünf-Minuten-Chart plausibel, aber nicht als klassische Reversal-Bar im Ein-Minuten-Chart. Was ist der bessere nächste Schritt?',
    choices: ['Noch zehn Charttypen durchsuchen, bis eine Idealform auftaucht.', 'Alle Tief-Tests ignorieren, wenn keine perfekte Ein-Bar-Kerze existiert.', 'Preisablauf und Risikopunkt im gewählten Plan-Zeitrahmen prüfen.'],
    explanations: ['Das ist Anpassung des Bildes an eine Wunschthese.', 'Viele Umkehrversuche entwickeln sich über mehrere Bars.', 'Richtig. Die beobachtete Struktur ist wichtiger als eine perfekte Form in jedem Chart.'],
    correct: 2,
    takeaways: ['Eine Bewegung erzeugt je nach Bar-Einteilung andere Formen.', 'Ein mehrbariger Test kann dieselbe Umkehrinformation tragen.', 'Die Plan-Zeitebene verhindert nachträgliche Musterwahl.'],
  },
  {
    number: 17,
    title: 'Ein Tages-Reversal kann aus vielen Intraday-Abschnitten bestehen',
    summary: 'Tageskerze und inneren Verlauf auseinanderhalten und den Schluss nicht vorwegnehmen.',
    sourceUnit: 'Kapitel 5 · Reversal-Bars auf höherer Zeitebene',
    sourceAnchors: ['Tagesbar als verdichteter Intraday-Verlauf', 'Gestufte Ranges oder klimaktische Gegenbewegung', 'Tagesform erst zum Ende bekannt'],
    durationMinutes: 11,
    teachingTitle: 'Die Tageskerze zeigt das Ergebnis, nicht den ganzen Weg',
    paragraphs: [
      'Ein Tagesbar mit langem unteren Schatten erzählt im Rückblick von tieferen Preisen und einer Erholung bis zum Schluss. Intraday kann dieser Weg aus mehreren Ranges mit kurzen Ausbrüchen bestehen oder aus einem heftigen Fall und einer schnellen Gegenbewegung.',
      'Die spätere Tagesform war am Vormittag noch nicht bekannt. Eine starke Intraday-Erholung kann am Nachmittag wieder verkauft werden. Deshalb taugt die noch offene Tageskerze nicht als sichere Rechtfertigung für einen vorzeitigen Long.',
      'Wer Intraday handelt, braucht einen Plan in seinem eigenen Zeitrahmen: Wo wurde ein Tief getestet, wo kam Anschluss, wo wäre die These falsch? Die Tagesebene kann den Rahmen zeigen, ersetzt aber nicht die tatsächliche Ausführung.',
      'Beim Rückblick hilft die Frage, welche kleineren Abschnitte die Tageskerze gebaut haben. Dann wird aus dem abstrakten Schatten eine Folge von Auktionen, die du überprüfen kannst.',
    ],
    callout: 'Ein fertiger Tagesbar ist die Zusammenfassung eines Tages – kein Signal, das schon am Morgen bekannt wäre.',
    scenario: 'reversal-daily-compression',
    chartTitle: 'Viele Intraday-Bars ergeben eine Tageskerze',
    caption: 'Die kleine Zeitebene zeigt den Weg vom Abverkauf über Seitwärtsphasen zur Erholung, den der Tagesbar verdichtet.',
    observations: ['Der Tagesbar verbirgt Zwischenrückläufe und Pausen.', 'Seine endgültige Form entsteht erst am Tagesende.', 'Intraday-Risiko braucht eigene Referenzpreise.'],
    questionTitle: 'Was weißt du um 11 Uhr?',
    prompt: 'Um 11 Uhr hat der Tag einen langen unteren Schatten, doch der Handelstag läuft weiter. Welche Aussage ist sauber?',
    choices: ['Der Tages-Reversal-Bar ist bereits endgültig bestätigt.', 'Der Zwischenstand zeigt eine Erholung; die Tageskerze kann sich noch ändern.', 'Intraday-Bars sind deshalb grundsätzlich wertlos.'],
    explanations: ['Der Tagesbar ist erst mit dem Tagesschluss fertig.', 'Richtig. Die weitere Handelssitzung kann die Form noch verändern.', 'Der kleinere Verlauf ist gerade für einen Intraday-Plan relevant.'],
    correct: 1,
    takeaways: ['Tagesbars verdichten viele Handelsabschnitte.', 'Der laufende Tagesbar kann seine Form noch ändern.', 'Ausführung und Fehlpunkt müssen zum eigenen Zeitrahmen passen.'],
  },
] satisfies ReversalLessonDraft[]).map(makeChapterFiveLesson);
