import { chapterSixLesson, type ChapterSixDraft } from './chapter-06-model';

// Original teaching text, following the source's opening sections. Diagrams
// are independent sketches rather than redrawings of the book's figures.
const drafts: ChapterSixDraft[] = [
  {
    number: 1, title: 'Ein Signal-Bar entsteht erst durch die Auslösung',
    summary: 'Ein attraktiver Setup-Bar und ein sinnvoller Trade sind zwei verschiedene Dinge.',
    section: 'Einführung', anchors: ['Signal-Bar und Setup-Bar', 'Auslösung jenseits des Bars', 'Kontext und erreichbares Ziel'],
    scenario: 'c06-signal-context',
    paragraphs: [
      'Ein Bar kann eine mögliche Gelegenheit vorbereiten. Zum Signal-Bar wird er erst, wenn der folgende Kurs den vorgesehenen Einstieg tatsächlich auslöst. Die bloße Form einer Kerze erzeugt noch keinen gefüllten Trade.',
      'Auch eine Auslösung sagt noch nicht, ob sich der Einstieg gelohnt hat. Liegt direkt dahinter der Rand einer engen Trading Range, kann der Kurs zwar kurz über den Signal-Bar hinauslaufen, aber ohne genug Raum für ein sinnvolles Ziel wieder zurückkehren.',
      'Prüfe vor dem Bar drei Ebenen: Welche Marktphase liegt vor, wo befindet sich der Bar darin, und wie wahrscheinlich ist ein tragfähiger Anschluss? Erst dann wird die Einstiegsmarke wichtig. Ein übersehener Widerstand macht eine technisch korrekt ausgelöste Order nicht zu einer guten Entscheidung.',
    ], callout: 'Setup erkennen, Auslösung abwarten, Raum für den Anschluss beurteilen.',
    diagramTitle: 'Gleicher Einstieg, anderer Platz im Markt',
    caption: 'Eigene Schemata: Ein Ausbruch aus einem Trend-Pullback hat anderen Raum als ein Ausbruch mitten in enger Überlappung.',
    observations: ['Links ist eine Richtung bereits erkennbar.', 'Rechts begrenzt die Range den freien Raum.', 'Die Auslösung allein beseitigt den Unterschied nicht.'],
    prompt: 'Ein Buy-Stop oberhalb eines Bars wird gefüllt, während die letzten acht Bars eng überlappen. Was ist die wichtigste offene Frage?',
    answers: [['Ob das Kerzenmuster einen besonderen Namen hat.', 'Der Mustername ersetzt keine Einschätzung des verfügbaren Raums.'], ['Ob ein Anschluss weit genug über die Range hinaus plausibel ist.', 'Richtig. Auslösung und tragfähiger Folgemove sind verschiedene Fragen.'], ['Ob ein früherer Bar eine identische Körperlänge hatte.', 'Gleiche Körpergrößen ersetzen keine Einschätzung des Zielraums.']], correct: 1,
    takeaways: ['Ein Setup-Bar ist zunächst eine Möglichkeit.', 'Signal-Bar setzt eine tatsächliche Auslösung voraus.', 'Marktphase und Zielraum entscheiden mit.'],
  },
  {
    number: 2, title: 'Starke Trendbars im Spike',
    summary: 'Warum ein kräftiger Schluss im frischen Ausbruch einen direkten Einstieg mit dem Trend begründen kann.',
    section: 'Starker Trend-Bar', anchors: ['Strong Trend Bar', 'Spike-Phase', 'Schluss und Folgekauf'],
    scenario: 'c06-strong-spike',
    paragraphs: [
      'Nach einem deutlichen Bruch einer wichtigen Zone können mehrere große Bars mit Schlusskursen nahe ihren Hochs entstehen. Wer den neuen Aufwärtsimpuls ernst nimmt, wartet nicht immer auf einen idealen Pullback: Ein starker Schluss kann selbst der Ausgangspunkt der nächsten Kaufentscheidung sein.',
      'Der Grund ist der Zeitdruck auf beiden Seiten. Späte Käufer wollen einsteigen, während vorher falsch positionierte Verkäufer ihre Positionen eindecken. Kaufen beide Gruppen beim kleinsten Rücklauf, können sich die starken Bars zu einem Spike verdichten.',
      'Das gilt nicht für jeden großen grünen Bar. Ein später Bar in einer alten Range kann ein Ausbruchsversuch mit schlechtem Anschluss sein. Entscheidend sind die neue Marktphase, die Lage zur gebrochenen Grenze und die Reaktion der nächsten Bars.',
    ], callout: 'Dringlichkeit im frischen Spike ist eine Beobachtung zum Kontext, kein Freibrief für jeden großen Bar.',
    diagramTitle: 'Vom Ausbruch zur Folge starker Bars',
    caption: 'Nach dem Bruch einer Grenze schließen mehrere eigene Bars hoch; ein später Range-Ausbruch dient als Gegenbild.',
    observations: ['Die ersten Bars verlassen die frühere Zone.', 'Kleine Rückläufe werden sofort aufgefangen.', 'Ein isolierter großer Bar kann denselben Eindruck nur vortäuschen.'],
    prompt: 'Wann hat ein starker bullischer Schluss als Signal-Bar die bessere Grundlage?',
    answers: [['Im frischen, bestätigten Aufwärtsspike nach einem wichtigen Bruch.', 'Richtig. Trendphase und weitere Käufer geben dem Schluss Gewicht.'], ['Mitten in vier stark überlappenden Bars einer Range.', 'Hier fehlt eine klare Richtung und oft freier Raum.'], ['Nur wenn der Bar exakt doppelt so groß wie sein Vorgänger ist.', 'Eine feste Größenformel ersetzt den Kontext nicht.']], correct: 0,
    takeaways: ['Ein starker Trend-Bar kann selbst einen Einstieg vorbereiten.', 'Dringlichkeit zeigt sich in der Folge mehrerer Bars.', 'Ein großer Bar in einer Range ist kein gleichwertiges Signal.'],
  },
  {
    number: 3, title: 'Gegen den Trend brauchst du mehr Belege',
    summary: 'Warum ein schwacher Pullback-Bar mit dem Trend besser sein kann als ein schöner Bar gegen ihn.',
    section: 'Reversal-Muster', anchors: ['Beweislast gegen einen starken Trend', 'Schwache Mit-Trend-Signalbars', 'Pullback und Trendwiederaufnahme'],
    scenario: 'c06-trend-asymmetry',
    paragraphs: [
      'Ein starker Trend setzt sich oft trotz optisch unsauberer Einstiegskerzen fort. Am Ende eines geordneten Pullbacks kann ein kleiner oder sogar gegenläufiger Bar eine Order mit dem Trend vorbereiten, weil viele Marktteilnehmer genau auf eine günstigere Einstiegslage gewartet haben.',
      'Für eine echte Wende gegen den Trend braucht es mehr. Die bisherige Seite hat zahlreiche Positionen und verteidigt Pullbacks. Ein einzelner hübscher Reversal-Bar gegen diesen Druck kann nur die erste Pause vor einer neuen Fortsetzung sein.',
      'Frag dich deshalb bei einem Short gegen den Bullenmarkt nach einem erkennbaren Bruch, einem erneuten Test und wirklicher Verkaufskraft. Bei einem Long nach einem Bullen-Pullback kann der schon starke übergeordnete Trend einen viel kleineren Signal-Bar tragen.',
    ], callout: 'Die Richtung des bestehenden Trends bestimmt, wie viel Beweis ein Signal braucht.',
    diagramTitle: 'Schwacher Mit-Trend-Bar oder starker Gegen-Bar?',
    caption: 'Zwei eigene Bewegungsfolgen zeigen den Unterschied zwischen Pullback-Ende und erstem Umkehrversuch.',
    observations: ['Links bleibt die vorherige Aufwärtsstruktur intakt.', 'Rechts widerspricht ein einzelner Bar vielen Trendbars.', 'Eine Umkehr braucht meist weitere strukturelle Hinweise.'],
    prompt: 'Ein Aufwärtstrend hat einen ruhigen zweibeinigen Pullback. Warum kann ein kleiner bullischer Signal-Bar genügen?',
    answers: [['Weil kleine Bars immer verlässlicher sind.', 'Die Größe allein macht kein Signal verlässlich.'], ['Weil der bestehende Trend und der abgeschlossene Pullback die These tragen.', 'Richtig. Die Kerze ist nur ein Teil des Mit-Trend-Setups.'], ['Weil alle Gegen-Trend-Signale verboten sind.', 'Gegen-Trend-Handel ist möglich, verlangt aber andere Belege.']], correct: 1,
    takeaways: ['Mit-Trend-Pullbacks benötigen oft keine perfekte Kerze.', 'Der erste Gegen-Bar bestätigt keine Wende.', 'Beurteile Signalstärke relativ zur bisherigen Marktphase.'],
  },
  {
    number: 4, title: 'Zwei Bars können zusammen umkehren',
    summary: 'Ein Impuls in alter Richtung und ein Gegenschub bilden ein gemeinsames Setup.',
    section: 'Two-Bar Reversal', anchors: ['Zwei-Bar-Reversal', 'Gegengerichtete Trendbars', 'Zusammenfassung auf höherer Zeitebene'],
    scenario: 'c06-two-bar',
    paragraphs: [
      'Bei einer Zwei-Bar-Umkehr folgt auf einen gerichteten Bar ein deutlicher Bar in Gegenrichtung. Zusammen zeigen sie, dass die zuerst dominante Seite ihren Fortschritt nicht halten konnte. Der zweite Bar muss mehr liefern als einen zufälligen Farbwechsel.',
      'Die beiden Bars können auf einer größeren Zeitebene wie eine einzige Umkehrkerze wirken. Ob ihre Zeitgrenzen dort genau zusammenfallen, ist weniger wichtig als die Abfolge: Vorstoß, Gegenkontrolle und eine plausible Stelle für den Richtungswechsel.',
      'Nicht jedes gegengerichtete Paar verdient einen Trade. Nach einem starken Abwärtsspike kann ein kleiner bullischer zweiter Bar nur eine Ein-Bar-Pause sein. An einem verteidigten Tief nach einer auslaufenden Bewegung kann dieselbe Paarform deutlich mehr bedeuten.',
    ], callout: 'Lies das Paar als gemeinsame Veränderung der Kontrolle, nicht als zwei einzelne Farben.',
    diagramTitle: 'Erster Impuls, zweite Gegeninitiative',
    caption: 'Eigene Paare vergleichen eine echte Rücknahme mit einer kurzen Pause im starken Trend.',
    observations: ['Die Form entsteht über zwei Bars.', 'Der Schluss des zweiten Bars zeigt die Stärke des Gegenschubs.', 'Die vorangehende Struktur entscheidet über Umkehr oder Pause.'],
    prompt: 'Ein großer Bärenbar wird unmittelbar von einem starken Bullenbar zurückgenommen. Was prüfst du als Nächstes?',
    answers: [['Die Stelle im Markt und die Auslösung über dem gesamten Setup.', 'Richtig. Das Paar ist erst im Kontext handelbar.'], ['Nur, ob die Bars verschiedene Farben haben.', 'Ein Farbwechsel allein ist kein vollständiges Setup.'], ['Ob auf jedem höheren Zeitrahmen dieselbe Kerze sichtbar ist.', 'Die exakte Bündelung ist nicht entscheidend.']], correct: 0,
    takeaways: ['Eine Zwei-Bar-Umkehr zeigt eine Abfolge von Kontrolle und Gegenkontrolle.', 'Höhere Zeitrahmen können dieselbe Folge zusammenfassen.', 'Ort und Anschluss bleiben wichtiger als der Name.'],
  },
  {
    number: 5, title: 'Bei großer Überlappung zählt die ganze Paar-Range',
    summary: 'Der Ausbruch nur über den zweiten Bar kann in einer Zwei-Bar-Range zur Falle werden.',
    section: 'Two-Bar Reversal', anchors: ['Stark überlappende Bars', 'Auslösung jenseits beider Extreme', 'Ein-Tick-Fehlausbruch'],
    scenario: 'c06-pair-boundary',
    paragraphs: [
      'Überlappt der zweite Bar den ersten fast komplett, bilden beide zusammen eine kleine Trading Range. Eine Order knapp jenseits des zweiten Bars kann ausgelöst werden, obwohl der Kurs das Extrem des ersten Bars noch gar nicht durchbrochen hat.',
      'Bei einem Short nach einem bullischen und einem bärischen Bar entsteht so eine Falle: Der Markt fällt kurz unter den zweiten Bar, hält aber über dem ersten Tief und dreht wieder nach oben. Wer nur die zweite Kerze sah, hat die gemeinsame Range übersehen.',
      'Markiere deshalb das tiefere Tief bzw. das höhere Hoch beider Bars. Prüfe außerdem, ob ein Einstieg jenseits des ganzen Paars noch Platz bis zur nächsten Unterstützung oder zum nächsten Widerstand hat. Ein sicherer Auslöser ist nicht automatisch ein günstiger Preis.',
    ], callout: 'Bei überlappenden Bars zählt die gemeinsame Grenze mehr als das Extrem der letzten Kerze.',
    diagramTitle: 'Zwei Grenzen, nur eine liegt außerhalb der Range',
    caption: 'Im eigenen Schema wird die zweite Kerze kurz unterschritten, während das Paar-Tief hält.',
    observations: ['Das Tief des zweiten Bars liegt innerhalb der Paar-Range.', 'Ein kurzer Bruch dort verlässt die gemeinsame Range nicht.', 'Erst das tiefere der beiden Tiefs ist die äußere Grenze.'],
    prompt: 'Zwei Bars überlappen fast vollständig. Der zweite Bärenbar endet knapp über dem Tief des ersten. Wo liegt die klare äußere Short-Schwelle?',
    answers: [['Am Tief des zweiten Bars.', 'Das wäre noch innerhalb der gemeinsamen Range.'], ['Jenseits des tieferen Tiefs beider Bars.', 'Richtig. Erst dort verlässt der Preis das ganze Paar.'], ['Immer am Schluss des zweiten Bars.', 'Der Schluss beantwortet die Grenzfrage nicht.']], correct: 1,
    takeaways: ['Große Überlappung macht aus dem Paar eine kleine Range.', 'Ein Bruch nur des zweiten Bars kann sofort scheitern.', 'Die äußere Paargrenze und das nachfolgende Risiko zusammen prüfen.'],
  },
  {
    number: 6, title: 'Mehrere große Bars am Durchschnitt sind oft eine Range',
    summary: 'Warum ein perfektes Zwei-Bar-Muster in dichter Überlappung wenig wert sein kann.',
    section: 'Two-Bar Reversal', anchors: ['Drei oder mehr überlappende Bars', 'Gleitender Durchschnitt', 'Fehlender Trenddruck'],
    scenario: 'c06-overlap-ma',
    paragraphs: [
      'Handeln drei oder vier relativ große Bars am gleitenden Durchschnitt auf ähnlichen Preisen, entsteht eine kleine Balancezone. Darin kann ein scheinbar starkes Zwei-Bar-Kaufsignal auftauchen, obwohl der Kurs nur an den oberen Rand der Zone zurückkehrt.',
      'Ohne kräftigen übergeordneten Trend ist ein Kauf über dem Paar oft ein Kauf auf der ungünstigen Seite dieser Mini-Range. Verkäufer sehen denselben Bereich als Widerstand. Die Form des Paars hebt die vielen vorher gescheiterten Ausbrüche nicht auf.',
      'Prüfe zuerst die Überlappung aller beteiligten Bars. In einem wirklich starken Trend kann der Markt auch aus so einer Pause weiterlaufen; dann trägt der Trend den Einstieg. In unklarer Lage ist Abwarten eine begründete Entscheidung.',
    ], callout: 'Mehrere überlappende Bars schlagen ein einzeln schönes Muster.',
    diagramTitle: 'Signalpaar im gemeinsamen Handelsraum',
    caption: 'Das eigene Schema zeigt ein bullisches Paar unmittelbar unter dem oberen Rand einer mehrteiligen Range.',
    observations: ['Mehrere frühere Bars handeln dieselben Preise.', 'Das Kaufsignal liegt am oberen Range-Rand.', 'Ein starker Trend wäre ein separater Grund für Fortsetzung.'],
    prompt: 'Ein schönes bullisches Zwei-Bar-Paar bildet sich innerhalb von vier großen, überlappenden Bars am flachen Durchschnitt. Welche Lesart ist vernünftig?',
    answers: [['Die gemeinsame Range und den fehlenden Raum zuerst prüfen.', 'Richtig. Die übrigen Bars gehören zum Setup-Kontext.'], ['Das Paar isoliert als sicheren Long nehmen.', 'Die isolierte Paarform blendet die Balancezone aus.'], ['Jedes Zwei-Bar-Paar ignorieren, auch im starken Trend.', 'Ein starker Trend kann die Lage verändern.']], correct: 0,
    takeaways: ['Drei oder mehr überlappende Bars bilden eine kleine Range.', 'Ein Muster am ungünstigen Rand kann scheitern.', 'Trendstärke kann die Balanceeinschätzung verändern.'],
  },
  {
    number: 7, title: 'Drei Bars: Richtungswechsel mit einer Pause dazwischen',
    summary: 'Der mittlere Bar darf unscheinbar sein; die zeitliche Bündelung ist nur ein Zusatzhinweis.',
    section: 'Three-Bar Reversals', anchors: ['Drei-Bar-Umkehr', 'Kleiner Mittelbar', 'Fünf- und Fünfzehn-Minuten-Bündelung'],
    scenario: 'c06-three-bar',
    paragraphs: [
      'Eine Drei-Bar-Umkehr beginnt mit einem kräftigen Bar in der bisherigen Richtung. Ein kleiner mittlerer Bar unterbricht die Bewegung, bevor ein dritter Bar deutlich in Gegenrichtung handelt. Die Pause macht den Wechsel sichtbar, trägt die Entscheidung aber nicht selbst.',
      'Drei Fünf-Minuten-Bars können auf dem Fünfzehn-Minuten-Chart wie eine einzige Umkehr wirken. Das hängt davon ab, wann die größere Kerze schließt. Ein passender Schluss kann zusätzliche Marktteilnehmer aufmerksam machen; eine unpassende Zeitgrenze entwertet den sichtbaren Fünf-Minuten-Wechsel aber nicht automatisch.',
      'Such nicht zwanghaft nach einer perfekten Drei-Bar-Form. Entscheidend ist, ob die Bewegung wirklich die Kontrolle wechselt und ob Auslösung und Ort passen. Die größere Zeitebene liefert Kontext, keine Pflichtbestätigung.',
    ], callout: 'Drei Bars beschreiben dieselbe Umkehrlogik mit einer kurzen Pause in der Mitte.',
    diagramTitle: 'Gegenschub nach einem kleinen Mittelbar',
    caption: 'Eine schematische Dreierfolge wird als kleinere und größere Zeiteinheit betrachtet.',
    observations: ['Der erste Bar setzt den bisherigen Impuls fort.', 'Der mittlere Bar zeigt eine Pause.', 'Der dritte Bar übernimmt die Gegenrichtung.'],
    prompt: 'Eine überzeugende Dreierfolge endet nicht genau mit dem Fünfzehn-Minuten-Schluss. Was folgt daraus?',
    answers: [['Der Fünf-Minuten-Wechsel ist dadurch wertlos.', 'Die Zeitgrenze ist nur ein Zusatzhinweis.'], ['Die Folge muss auf dem kleineren Chart und im Kontext beurteilt werden.', 'Richtig. Der Handelsschluss einer größeren Kerze ist nicht das Muster selbst.'], ['Man muss eine andere Chartart finden, bis es perfekt aussieht.', 'Das wäre rückblickende Mustersuche statt Entscheidung.']], correct: 1,
    takeaways: ['Die mittlere Kerze muss nicht stark sein.', 'Zeitliche Bündelung kann die Wirkung ergänzen.', 'Verliere die sichtbare Umkehr und den Ort nicht aus dem Blick.'],
  },
  {
    number: 8, title: 'Kleine Inside-Bars: Größe, Körper und Ort',
    summary: 'Warum ein kleiner Bar am Range-Rand anders wirkt als ein großer Doji in ihrer Mitte.',
    section: 'Small Bars', anchors: ['Inside-Bar und Gleichstand der Extreme', 'Körper in Einstiegsrichtung', 'Großer Doji als Ein-Bar-Range'],
    scenario: 'c06-small-inside',
    paragraphs: [
      'Ein Inside-Bar bleibt mit Hoch und Tief innerhalb oder genau auf den Grenzen seines Vorgängers. Seine geringe Ausdehnung verrät, dass beide Seiten kurz weniger weit kamen. Welche Seite danach gewinnt, sagt das allein noch nicht.',
      'Ein kleiner Inside-Bar mit Körper in der geplanten Richtung ist leichter zu lesen als ein großer Doji. Der Doji zeigt Kauf und Verkauf im selben Bar und verhält sich eher wie eine kleine Trading Range. Gerade in ihrer Mitte wird ein Stop-Einstieg leicht hin und her geschlagen.',
      'Am Ende eines Pullbacks im starken Trend oder am Rand einer größeren Range kann ein unscheinbarer Inside-Bar trotzdem nützlich sein. Markiere die äußere Struktur und den nächsten sinnvollen Preisbereich; erst dann lohnt der Blick auf seine Farbe.',
    ], callout: 'Klein heißt Pause. Lage und Schluss bestimmen, was aus der Pause werden könnte.',
    diagramTitle: 'Kleiner Inside-Bar an drei Stellen',
    caption: 'Die eigene Skizze verschiebt denselben kleinen Bar zwischen Trend-Pullback und Range-Mitte.',
    observations: ['Die äußeren Grenzen des Vorbars bleiben erhalten.', 'Ein gerichteter Körper zeigt eine Seite im Schluss.', 'In der Mitte einer Range fehlt häufig ein Vorteil.'],
    prompt: 'Welcher Inside-Bar spricht eher für einen Long?',
    answers: [['Ein großer Doji mitten in breiter Überlappung.', 'Hier ist zweiseitiger Handel besonders sichtbar.'], ['Ein kleiner bullischer Bar am Ende eines Pullbacks im starken Bullenmarkt.', 'Richtig. Ort und Richtung passen zusammen.'], ['Jeder Inside-Bar unabhängig vom Umfeld.', 'Die Definition allein ergibt keinen Vorteil.']], correct: 1,
    takeaways: ['Inside erlaubt auch identische Grenzen.', 'Kleiner gerichteter Körper hilft bei der Einordnung.', 'Ein großer Doji ist häufig eine kleine Range.'],
  },
  {
    number: 9, title: 'ii und iii: wiederholte Kompression',
    summary: 'Zwei oder drei ineinanderliegende Bars und ihre möglichen Ausbrüche.',
    section: 'Small Bars', anchors: ['ii und iii', 'Kompression nach ausgedehnter Bewegung', 'Gegenseite und Fehlausbruch'],
    scenario: 'c06-ii-iii',
    paragraphs: [
      'Beim ii-Muster liegt ein Inside-Bar in einem weiteren Inside-Bar; bei iii setzt sich die Verschachtelung noch einmal fort. Der Preis verengt seinen sichtbaren Raum. Auf einem kleineren Zeitrahmen kann dieselbe Pause aus mehreren Tests oder einer kleinen Umkehr bestehen.',
      'Nach einem reifen Trend ist ein Ausbruch in Trendrichtung nicht automatisch der Start einer langen Fortsetzung. Er kann der letzte Schub einer Flag sein und schnell in die Kompressionszone zurückfallen. Ein Ausbruch gegen den Trend kann dagegen den Beginn einer größeren Gegenbewegung anzeigen, besonders nach einem vorherigen Strukturbruch.',
      'Beziehe bei Stop und Erwartung die ganze Kompressionsstruktur ein. Schaust du nur auf das Extrem des letzten winzigen Bars, kann ein normaler Test der äußeren Grenzen fälschlich wie endgültiges Scheitern wirken. Auf die Reaktion nach dem ersten Ausbruch zu warten ist oft klarer.',
    ], callout: 'ii beschreibt engeren Preisraum, nicht die künftige Richtung.',
    diagramTitle: 'Verschachtelte Grenzen und zwei Ausbruchswege',
    caption: 'Eigenes Schema: Ein letzter Trend-Ausbruch und ein Gegen-Ausbruch starten aus derselben Kompression.',
    observations: ['Jeder Inside-Bar verengt den vorherigen Bereich.', 'Beide Außengrenzen bleiben relevant.', 'Der Trendkontext verändert die Erwartung an den Ausbruch.'],
    prompt: 'Ein ii bildet sich nach einem lange laufenden Bullenkanal. Ein winziger Aufwärtsausbruch erscheint. Was ist offen?',
    answers: [['Ob er nur eine letzte Flag ist und zurückfällt.', 'Richtig. Nach reifen Bewegungen sind Fehlausbrüche möglich.'], ['Ob ii definitionsgemäß nur nach unten ausbrechen darf.', 'Das Muster legt keine Richtung fest.'], ['Ob alle früheren Grenzen gelöscht werden.', 'Die äußeren Grenzen bleiben wichtig.']], correct: 0,
    takeaways: ['ii/iii sind verschachtelte Inside-Strukturen.', 'Kompression bietet beide Richtungen an.', 'Reifer Trend und Ausbruchsreaktion entscheiden über die Qualität.'],
  },
  {
    number: 10, title: 'ioi und Outside-Bar nicht isoliert lesen',
    summary: 'Kompression, Expansion und erneute Kompression verlangen eine Richtungsentscheidung.',
    section: 'Small Bars / Outside Bar', anchors: ['Inside–Outside–Inside', 'Ausbruch aus zweitem Inside-Bar', 'Outside-Bar als Expansion'],
    scenario: 'c06-ioi-outside',
    paragraphs: [
      'Bei ioi steht zwischen zwei Inside-Bars ein Outside-Bar, dessen Spanne beide Seiten erweitert. Danach verengt der zweite Inside-Bar den Raum wieder. Diese Folge baut Druck für einen späteren Ausbruch auf, ohne die Richtung allein festzulegen.',
      'Ein Outside-Bar sagt zunächst nur, dass beide Seiten der Vorgängerspanne gehandelt wurden. Er kann kraftvolle Initiative zeigen, aber auch hektischen zweiseitigen Handel. Sein Schluss und die Marktphase entscheiden, ob er eher Fortsetzung oder Unsicherheit ausdrückt.',
      'Ist der Kontext offen, hilft dir ein Plan für beide Ausbruchsrichtungen mit klarer Ungültigkeitsgrenze mehr als eine Vorhersage aus dem Musternamen. Werden beide Seiten nacheinander überschritten, ist das kein Beweis für zwei gute Trades, sondern ein Warnzeichen für Whipsaw.',
    ], callout: 'ioi ist ein Entscheidungspunkt: erst Expansion, dann erneute Verengung.',
    diagramTitle: 'Inside–Outside–Inside als Folge',
    caption: 'Die drei eigenen Bars zeigen die wechselnden Spannengrenzen ohne vorweggenommene Ausbruchsrichtung.',
    observations: ['Der Mittelbar erweitert Hoch und Tief.', 'Der letzte Bar verengt die Spanne erneut.', 'Erst der spätere Kurs zeigt, welche Seite die Initiative hält.'],
    prompt: 'Was sagt eine ioi-Folge vor dem Ausbruch sicher aus?',
    answers: [['Ein Long ist bestätigt.', 'Die Richtung ist noch offen.'], ['Kompression, Expansion und erneute Kompression sind sichtbar.', 'Richtig. Das Muster beschreibt den Ablauf, nicht den Gewinner.'], ['Ein Outside-Bar bedeutet immer Trendstärke.', 'Er kann auch zweiseitiges Handeln zeigen.']], correct: 1,
    takeaways: ['Outside erweitert die vorige Spanne.', 'ioi endet in einer neuen engen Entscheidungslage.', 'Fehlausbrüche auf beiden Seiten sind möglich.'],
  },
  {
    number: 11, title: 'Mikro-Doppeltop und -boden wechseln ihre Rolle',
    summary: 'Dieselben nahen Hochs oder Tiefs können Flag oder Umkehr sein.',
    section: 'Micro Double Bottom / Top', anchors: ['Nahezu gleiche Extrempunkte', 'Fortsetzungsflag im Spike', 'Umkehr außerhalb starker Spikes'],
    scenario: 'c06-micro-double',
    paragraphs: [
      'Zwei direkt benachbarte Bars können fast dasselbe Tief oder Hoch testen. Das ist eine sehr kleine Doppelstruktur. Sie ist keine automatische Wette auf die Gegenrichtung, denn ein starker Spike behandelt kurze Gegenreaktionen oft nur als Pause.',
      'Nach einem steilen Verkaufsimpuls kann ein kurzes Paar gleicher Tiefs mit kleinem bullischem Zwischenbar eine Ein-Bar-Bärenflag sein. Unter den gemeinsamen Tiefs treffen dann neue Verkäufer auf Käufer, die ihre frühe Umkehrthese aufgeben müssen. Im starken Aufwärtsimpuls gilt für gleiche Hochs spiegelbildlich eine mögliche Bullenflag.',
      'Anders ist ein Doppeltest nach abgeflautem Druck und mehreren Anzeichen für eine Wende. Dann kann die gescheiterte Fortsetzung selbst den Gegenplan tragen. Frag immer zuerst nach Spike oder auslaufender Bewegung, danach nach der kleinen Doppelform.',
    ], callout: 'Der Ort entscheidet, ob ein Mikro-Doppel eine Flag oder eine Gegenreaktion ist.',
    diagramTitle: 'Gleiche Tiefs, zwei unterschiedliche Marktphasen',
    caption: 'Ein Doppeltest im steilen Abwärtsspike wird einer späteren Stabilisierung gegenübergestellt.',
    observations: ['Die Extrempunkte liegen fast gleich.', 'Im Spike dominiert noch die alte Richtung.', 'Nach sichtbarem Druckverlust wird eine Umkehr plausibler.'],
    prompt: 'Ein kleines Doppeltief bildet sich in einem kaum unterbrochenen Bärenspike. Welche Deutung muss zuerst geprüft werden?',
    answers: [['Sicherer Beginn eines Bullenmarkts.', 'Der starke vorherige Verkaufsdruck widerspricht einer sicheren Wende.'], ['Kurze Bärenflag mit möglicher Fortsetzung unter den Tiefs.', 'Richtig. Das ist in diesem Kontext eine naheliegende Lesart.'], ['Mikro-Doppel sind nie relevant.', 'Die kleine Struktur kann gerade an einem Auslöser wichtig sein.']], correct: 1,
    takeaways: ['Nahezu gleiche Hochs/Tiefs definieren die Mikrostruktur.', 'Im Spike kann sie die alte Richtung fortsetzen.', 'Bei schwächerem Druck kann dieselbe Form Teil einer Umkehr sein.'],
  },
  {
    number: 12, title: 'Wenn der Reversal-Bar auf der falschen Seite bricht',
    summary: 'Ein gescheiterter Umkehrversuch kann die bisherige Trendseite stärken.',
    section: 'Reversal Bar Failure', anchors: ['Nicht ausgelöster Reversal-Bar', 'Bruch der Gegenseite', 'Positionsausstieg als Zusatzdruck'],
    scenario: 'c06-failed-reversal',
    paragraphs: [
      'Ein bullischer Reversal-Bar im Bärentrend bleibt zunächst nur eine Einladung an Käufer. Steigt der nächste Bar nicht über sein Hoch, entsteht kein planmäßig ausgelöster Long. Fällt der Kurs stattdessen unter sein Tief, ist die mögliche Umkehr gescheitert.',
      'Wer schon vor der Auslösung gekauft hat, muss jetzt oft raus. Sein Verkauf trifft auf neue Shorts. So kann ein optisch bullischer Bar im Rückblick zur Ein-Bar-Flag im Bärentrend werden. Spiegelbildlich kann ein bärischer Reversal-Bar im Bullenmarkt über seinem Hoch scheitern.',
      'Der Fehlschlag ist nur dann interessant, wenn die ursprüngliche Trendseite weiterhin eine überzeugende Struktur hat. In einer engen Range kann ein Bruch beider Seiten schlicht mehr Überlappung bedeuten. Trenne früher Einstieg, gültigen Auslöser und Folgedruck sauber.',
    ], callout: 'Die nicht erreichte Signal-Schwelle ist selbst eine wichtige Information.',
    diagramTitle: 'Die angekündigte Wende löst nie aus',
    caption: 'Ein eigener bullischer Umkehr-Bar wird unterboten, bevor sein Hoch überschritten wird.',
    observations: ['Der Long-Auslöser wurde nicht erreicht.', 'Der Kurs verlässt die Gegenseite des Bars.', 'Frühe Gegen-Trend-Positionen geraten unter Druck.'],
    prompt: 'Ein bullischer Reversal-Bar im Bärentrend wird am nächsten Bar unten gebrochen, ohne oben auszulösen. Welche Aussage ist korrekt?',
    answers: [['Ein Long war durch die Barfarbe bereits bestätigt.', 'Ohne Auslösung ist die geplante Long-Order ungefüllt.'], ['Die Umkehrthese scheiterte; eine Fortsetzungsflag ist möglich.', 'Richtig. Die falsche Seite und der Trendkontext zählen.'], ['Der nächste Bar muss einen neuen Bullenmarkt beginnen.', 'Dafür gibt es keinen Beleg.']], correct: 1,
    takeaways: ['Ein Reversal-Bar allein ist kein Entry.', 'Der Bruch seiner Gegenseite zeigt ein Scheitern.', 'Im Trend kann daraus eine Fortsetzungsflag werden.'],
  },
  {
    number: 13, title: 'Shaved-Bar: kein Schatten, trotzdem Kontext nötig',
    summary: 'Ein Schluss am Extrem kann Trenddruck zeigen oder in einer ruhigen Range bedeutungslos sein.',
    section: 'Shaved Bar', anchors: ['Kein oberer oder unterer Schatten', 'Schlussdruck im Trend', 'Häufung in ruhiger Trading Range'],
    scenario: 'c06-shaved',
    paragraphs: [
      'Ein Bar ohne sichtbaren Schatten an einem Ende heißt shaved. Im kräftigen Bullenlauf ist ein Schluss exakt am Hoch ein Zeichen, dass die Käufer bis zuletzt aktiv waren. Im Bärenlauf gilt ein Schluss am Tief entsprechend für die Verkäufer.',
      'Ein fehlender Schatten an der Eröffnungsseite sagt zeitlich etwas anderes als ein fehlender Schatten am Schlussende. Wer nur auf die Silhouette schaut, übersieht, ob die Stärke bis zur letzten Sekunde des Bars anhielt.',
      'In einer ruhigen, seitlichen Phase können viele Bars zufällig ohne Schatten enden. Treten sie abwechselnd in beide Richtungen auf und überlappen die Kursbereiche, leitest du daraus keinen neuen Trend ab. Such nach einer Folge gerichteter Bars und einer klaren Marktphase.',
    ], callout: 'Ein Schluss am Extrem zählt nur zusammen mit Trend, Tempo und Folgebars.',
    diagramTitle: 'Shaved-Bar im Trend und in der Range',
    caption: 'Zwei eigene Folgen zeigen denselben fehlenden Schatten mit unterschiedlichen Nachbarbars.',
    observations: ['Im Trend folgen weitere gerichtete Bars.', 'In der Range wechseln die Schlussseiten.', 'Der fehlende Schatten allein trennt beides nicht.'],
    prompt: 'Mehrere Bars in einer engen Range schließen abwechselnd exakt am Hoch und am Tief. Wie deutest du das?',
    answers: [['Als bewiesene Stärke in beide Richtungen.', 'Zwei widersprüchliche Richtungen sind kein klarer Trend.'], ['Als mögliches Merkmal ruhigen zweiseitigen Handels.', 'Richtig. Die Häufung in der Range mindert den Einzelwert.'], ['Jeden shaved Bar sofort als Stop-Einstieg.', 'Die Form ohne Kontext produziert Fehlentscheidungen.']], correct: 1,
    takeaways: ['Kein Schatten am Schlussende kann Druck ausdrücken.', 'Die Trendphase verstärkt diese Aussage.', 'In ruhiger Überlappung wird die Form schnell bedeutungslos.'],
  },
  {
    number: 14, title: 'Ein ungewöhnlich großer Trend-Bar kann erschöpfen',
    summary: 'Der letzte starke Schub ist nicht immer der Anfang weiterer Beschleunigung.',
    section: 'Exhaustion Bar', anchors: ['Ungewöhnliche Größe spät im Trend', 'Klimax und Pause', 'Folgebars entscheiden'],
    scenario: 'c06-exhaustion',
    paragraphs: [
      'Ein großer Bar in Trendrichtung ist zunächst ein sichtbarer Ausbruch. Wird er erst nach vielen vorherigen Trendbars ungewöhnlich groß, kann er zugleich der Höhepunkt der Bewegung sein: Späte Teilnehmer drängen hinein, während die Gegenseiten ihre Verluste schließen.',
      'Aus „groß“ folgt keine sofortige Trendwende. Oft kommt zuerst eine seitliche oder zweibeinige Korrektur. Für einen Einstieg gegen den Trend zählen dann eine erkennbare Gegeninitiative, die Lage an einer Zielzone und ein nachvollziehbarer Auslöser mehr als der Klimax-Bar allein.',
      'Vergleiche deshalb relative Größe und Phase: Ein früher großer Bar nach einer Range kann einen neuen Spike eröffnen; derselbe relative Größenanstieg nach langem Lauf erhöht eher die Wachsamkeit für Erschöpfung. Beobachte, ob weitere Bars den Ausbruch halten.',
    ], callout: 'Ausbruch und mögliche Erschöpfung können dieselbe Kerze beschreiben.',
    diagramTitle: 'Früher Ausbruchsbar gegen späten Klimax-Bar',
    caption: 'Die beiden schematischen Folgen unterscheiden den Anfang eines neuen Trends vom überdehnten Spätschub.',
    observations: ['Die relative Größe nimmt spät stark zu.', 'Ein später Klimax braucht keine sofortige Umkehr.', 'Die nächste Barfolge zeigt, ob der Bruch getragen wird.'],
    prompt: 'Nach vielen fallenden Bars erscheint ein außergewöhnlich großer Bärenbar. Was ist eine vorsichtige Folgerung?',
    answers: [['Der Kurs muss sofort steigen.', 'Ein Klimax kann noch fortgesetzt werden.'], ['Der Bar zeigt Druck und mögliches Erschöpfungsrisiko; die Reaktion abwarten.', 'Richtig. Beide Eigenschaften können gleichzeitig gelten.'], ['Es handelt sich sicher um den Beginn des Bärentrends.', 'Die lange Vorphase spricht gegen eine solche Gewissheit.']], correct: 1,
    takeaways: ['Größe ist relativ zur vorigen Bewegung zu lesen.', 'Später Trenddruck kann ein Klimax sein.', 'Gegen-Trend-Handel braucht zusätzliche Bestätigung.'],
  },
  {
    number: 15, title: 'Trendbars als Signal in Trend und Range',
    summary: 'Ein gerichteter Bar kann eine Korrektur beenden oder am Rand einer Range erschöpft sein.',
    section: 'Trend Bars', anchors: ['Mit-Trend-Einstieg nach Pullback', 'Korrektur am gleitenden Durchschnitt', 'Range-Extrem und Gegenrichtung'],
    scenario: 'c06-trend-range',
    paragraphs: [
      'Ein Trend-Bar dient im starken Trend oft als Signal mit dem Trend. Aber auch ein gegenläufiger kleiner Bar am Ende eines geordneten Pullbacks kann den Übergang zur Wiederaufnahme anzeigen, wenn Käufer im Aufwärtstrend den unteren Bereich verteidigen.',
      'In einer klaren Trading Range kann ein kräftiger Aufwärtsbar am oberen Rand dagegen der letzte Schub eines fehlenden Ausbruchs sein. Dort lautet die nächste Frage nicht, ob der Bar grün ist, sondern ob der Markt über der bekannten Obergrenze Akzeptanz findet.',
      'Denk in Bewegungsabschnitten statt in festen Kerzenregeln. Was ist in diesem Markt normal: Fortsetzung nach kleiner Pause oder Rückkehr zur Mitte nach einem Randtest? Vergleiche die neue Kerze mit diesem Ausgangszustand.',
    ], callout: 'Ein Trend-Bar hat keine feste Rolle; Trend und Range geben ihm die Aufgabe.',
    diagramTitle: 'Gerichteter Bar an zwei Orten',
    caption: 'Ein eigener Impuls beendet links einen Pullback und testet rechts nur die Oberkante einer Range.',
    observations: ['Links ist der Bar Teil einer bestehenden Richtung.', 'Rechts trifft er auf einen bekannten Rand.', 'Anschluss oder Zurückweisung trennen die Fälle.'],
    prompt: 'Ein kräftiger Bullenbar schließt direkt am oberen Rand einer seitlichen Tagesrange. Welche Frage ist vorrangig?',
    answers: [['Ob der Markt oberhalb der Range weitere Käufer findet.', 'Richtig. Erst der Anschluss trennt echten Bruch vom Randtest.'], ['Ob der Bar einen Kerzenmusternamen erfüllt.', 'Der Name verrät die Folge nicht.'], ['Ob grüne Bars unabhängig vom Ort gekauft werden müssen.', 'Das blendet die Range aus.']], correct: 0,
    takeaways: ['Trendbars können sowohl Fortsetzung als auch Erschöpfung zeigen.', 'Pullback-Ende und Range-Rand sind verschiedene Kontexte.', 'Die Reaktion nach dem Bar entscheidet über die These.'],
  },
  {
    number: 16, title: 'Im Kanal werden viele Bars in beide Richtungen gehandelt',
    summary: 'Limit- und Stop-Orders erklären, warum die einzelne Signalform dort weniger eindeutig ist.',
    section: 'All Bars in a Channel', anchors: ['Limit-Orders an Bar-Extremen', 'Stop-Orders an Pullbacks', 'Zweiseitige Aktivität im Kanal'],
    scenario: 'c06-channel-orders',
    paragraphs: [
      'Ein Kanal bewegt sich gerichtet, enthält aber viele kleine Rückläufe. In einem Bullenkanal kaufen Trendteilnehmer oft unter vorherigen Tiefs oder über den Hochs kleiner Pullback-Bars. Andere verkaufen nahe neuen Hochs, weil sie einen weiteren Rücklauf erwarten.',
      'Dadurch kann derselbe kleine Bar gleichzeitig ein Kauf- und ein Verkaufsszenario enthalten. Der Kanal ist weder eine reine Gerade noch automatisch eine Range. Seine Steilheit, die Tiefe der Pullbacks und der Ort zum letzten Swing entscheiden, welcher Plan gerade plausibler ist.',
      'Zeichne die zuletzt verteidigten Bar-Hochs und -Tiefs ein und beschreibe, wer beim Bruch einer Seite unter Druck gerät. Einen Long im starken Kanal und einen frühen Short am oberen Rand musst du unterschiedlich bewerten, obwohl sie dieselbe Kerze betrachten.',
    ], callout: 'In einem Kanal sind Bar-Extreme zugleich Einstiegs- und Ausstiegspunkte verschiedener Gruppen.',
    diagramTitle: 'Orders um die Bars eines Bullenkanals',
    caption: 'Das eigene Schema markiert Pullback-Tief und neues Hoch als konkurrierende Entscheidungen.',
    observations: ['Der Trend steigt trotz einzelner Gegenbars.', 'Rückläufe schaffen Mit-Trend-Einstiege.', 'Gegenpositionen am oberen Rand brauchen eine eigene Begründung.'],
    prompt: 'Ein kleiner Bärenbar bildet sich im intakten Bullenkanal. Ist er automatisch ein Short-Signal?',
    answers: [['Ja, weil die Barfarbe wechselt.', 'Die Kanalstruktur bleibt möglicherweise intakt.'], ['Nein; er kann auch der Pullback für einen Long sein.', 'Richtig. Beide Seiten sehen das Extrem unterschiedlich.'], ['Ja, wenn der Bar einen Schatten hat.', 'Ein Schatten allein legt die Richtung nicht fest.']], correct: 1,
    takeaways: ['Kanäle zeigen gerichteten, aber zweiseitigen Handel.', 'Trendteilnehmer nutzen kleine Rückläufe.', 'Ein einzelner Gegenbar ändert die Kanalstruktur nicht zwangsläufig.'],
  },
  {
    number: 17, title: 'Inside-Bar nach einem Ausbruch: Pause oder Fehlschlag?',
    summary: 'Farbe und Schluss der Pause verändern die Ausbruchsthese.',
    section: 'All Bars in a Channel', anchors: ['Inside-Bar nach großem Ausbruch', 'Mit- oder gegenläufiger Körper', 'Beide Ausbruchsrichtungen und Risiko'],
    scenario: 'c06-breakout-pause',
    paragraphs: [
      'Auf einen großen Ausbruchsbar folgt manchmal ein kleiner Inside-Bar. Schließt er in Ausbruchsrichtung, kann das eine kurze Pause vor dem nächsten Impuls sein. Schließt er kräftig dagegen, meldet er womöglich nachlassende Bereitschaft und einen Fehlausbruch.',
      'In der ersten Minute nach dieser Pause sind beide Wege denkbar. Ein Breakout über die obere Grenze und ein Rückfall unter die untere Grenze belasten unterschiedliche Positionen. Gerade an einem vorher seitlichen Tag kann die erste ausgelöste Richtung wieder scheitern.',
      'Komplexe Gegenorders und automatische Umkehrungen sind kein Muss. Wechseln die ersten Bars zu schnell und bleibt der Kontext unklar, ist der sauberste Plan, auf mehr Preisverhalten zu warten. Einen späten, klaren Retest wertest du oft leichter aus.',
    ], callout: 'Ein Inside-Bar nach dem Bruch verlangt einen Plan für die Reaktion, nicht reflexhaft zwei Trades.',
    diagramTitle: 'Die Pause nach dem Range-Ausbruch',
    caption: 'Eigene Schemata: Eine kleine Fortsetzungspause und ein rascher Rückfall in die alte Zone.',
    observations: ['Der große Bar überschreitet eine Grenze.', 'Der Inside-Bar hält zunächst in seiner Spanne.', 'Der nächste Bruch zeigt Akzeptanz oder Fehlschlag.'],
    prompt: 'Nach einem Ausbruch wechseln die Bars schnell und schlagen beide Inside-Grenzen an. Was ist eine vernünftige Reaktion?',
    answers: [['Die Zahl der gleichzeitig offenen Orders erhöhen.', 'Komplexität behebt die unklare Marktlage nicht.'], ['Abwarten und einen späteren klareren Test beurteilen.', 'Richtig. Zweiseitiger Whipsaw ist selbst Information.'], ['Den ersten Bruch als endgültig erklären.', 'Der sofortige Gegenschlag widerlegt diese Gewissheit.']], correct: 1,
    takeaways: ['Mitläufige Pause und gegenläufiger Warnbar unterscheiden.', 'Die Reaktion auf den ersten Bruch prüfen.', 'Unklare schnelle Wechsel dürfen zum Abwarten führen.'],
  },
  {
    number: 18, title: 'ii nach langem Trend kann die letzte Flag sein',
    summary: 'Ein Trend-Ausbruch aus enger Balance wird nach einer reifen Bewegung anfälliger.',
    section: 'All Bars in a Channel', anchors: ['ii nach ausgedehntem Swing', 'Final-Flag-Risiko', 'Gegenrichtung nach Fehlausbruch'],
    scenario: 'c06-final-flag',
    paragraphs: [
      'Ein langer Trend kann sich zum Schluss in zwei sehr kleinen Inside-Bars beruhigen. Das wirkt wie eine ordentliche Fortsetzungsflag. Gerade die plötzliche Balance kann aber zeigen, dass die vorher schwächere Seite aufholt.',
      'Bricht der Markt noch einmal in Trendrichtung aus und wird gleich zurück in die enge Zone gezogen, geraten späte Trendfolger unter Druck. Der Gegen-Ausbruch aus der Kompression kann dann weiter tragen als der letzte Trendversuch. Das ist eine mögliche Final-Flag-Folge, keine automatische Vorhersage aus ii.',
      'Verknüpfe den ii mit Trendlinienbruch, Reife des Swings und Anschluss nach dem ersten Bruch. Die gesamte äußere Spanne bleibt eine sinnvolle Referenz für den Fehlpunkt. Ein Muster in der Tagesmitte ohne klare Richtung verdient vorsichtigere Erwartungen.',
    ], callout: 'Das Risiko der letzten Flag entsteht aus Trendalter und gescheitertem Anschluss.',
    diagramTitle: 'Ein letzter Schub und Rückkehr in den ii',
    caption: 'Die eigenständige Folge zeigt Ausbruch, Rückkehr und mögliche Gegeninitiative.',
    observations: ['Der Trend hat bereits mehrere Schübe hinter sich.', 'Der erste Ausbruch hält nicht außerhalb des ii.', 'Zurückkehrende Positionen verstärken die Gegenseite.'],
    prompt: 'Ein reifer Trend bricht aus einem ii in Trendrichtung aus und fällt sofort zurück. Welches Risiko ist gestiegen?',
    answers: [['Dass der ii eine letzte Flag vor einer Gegenbewegung war.', 'Richtig. Der gescheiterte Anschluss ist der entscheidende Zusatz.'], ['Dass jeder ii einen neuen Trend garantiert.', 'Der Fehlschlag spricht dagegen.'], ['Dass die äußere ii-Grenze keine Rolle mehr spielt.', 'Sie bleibt eine wichtige Referenz.']], correct: 0,
    takeaways: ['ii kann nach langem Trend Balance anzeigen.', 'Ein nicht gehaltener Ausbruch macht die Gegenseite interessant.', 'Trendalter und Folgehandel sind wichtiger als das Kürzel.'],
  },
  {
    number: 19, title: 'Kleine Bars nur am passenden Ort handeln',
    summary: 'Range-Rand, Swingpunkt und zweiter Versuch verbessern oder verschlechtern dasselbe Signal.',
    section: 'All Bars in a Channel', anchors: ['Small Bar am Swing-Extrem', 'Doji am gleitenden Durchschnitt', 'Zweiter Einstieg'],
    scenario: 'c06-small-location',
    paragraphs: [
      'Kleine Bars sind nicht automatisch günstige Stop-Distanzen. In der Mitte einer Range oder direkt an einem flachen gleitenden Durchschnitt kann ein körperloser Doji nur wiederholte Unentschlossenheit zeigen. Ein kurzer Ausbruch wird dann schnell zurückgenommen.',
      'Am unteren Range-Rand oder nach einem getesteten Swingtief kann derselbe kleine Bar eine konkrete Zone verteidigen. Ein Körper in der geplanten Richtung und ein zweiter erfolgloser Gegenversuch geben der Entscheidung zusätzliche Struktur.',
      'Im intakten Trend ist ein kleiner Pullback-Bar oft eher ein Signal mit dem Trend. Am Range-Rand suchst du dagegen nach einer Abweisung des Extrembereichs. Wo weder Ort noch Folgedruck passen, ist „kein Trade“ eine echte Auswertung des Charts.',
    ], callout: 'Kleine Bar-Ranges ersetzen weder eine gute Lage noch einen zweiten Blick auf die Struktur.',
    diagramTitle: 'Kleiner Doji in Mitte und am Rand',
    caption: 'Die selbst entworfenen Panels setzen die gleiche Barform in zwei verschiedene Preiszonen.',
    observations: ['In der Mitte handeln beide Seiten auf ähnlichen Preisen.', 'Am Rand ist ein konkreter Test erkennbar.', 'Ein weiterer Versuch kann die These stärken oder widerlegen.'],
    prompt: 'Wo ist ein kleiner Doji eher als Umkehr-Signal zu prüfen?',
    answers: [['Mitten zwischen den Grenzen einer engen Range.', 'Dort fehlt ein sinnvoller Test einer äußeren Zone.'], ['Nach einem zweiten Test des Range-Tiefs mit erkennbarer Käuferreaktion.', 'Richtig. Ort und Folge geben der kleinen Form Bedeutung.'], ['An jeder Berührung eines flachen Durchschnitts.', 'Allein die Berührung schafft noch keinen Vorteil.']], correct: 1,
    takeaways: ['Kleine Bars sind ohne Kontext zweiseitig.', 'Range-Ränder und Swingtests geben Orientierung.', 'Ein zweiter Versuch kann mehr aussagen als die erste Kerze.'],
  },
];

export const chapterSixFoundationLessons = drafts.map(chapterSixLesson);
