import { makeChapterFiveLesson, type ReversalLessonDraft } from './chapter-05-model';

export const chapterFiveFoundationLessons = ([
  {
    number: 1,
    title: 'Eine Reversal-Bar ist ein Versuch, keine Trendwende',
    summary: 'Was ein einzelner Bar sichtbar zurücknimmt und warum der nächste Handelsschritt offenbleibt.',
    sourceUnit: 'Kapitel 5 · Funktion einer Reversal-Bar',
    sourceAnchors: ['Bar kehrt eine Eigenschaft der vorangegangenen Bewegung um', 'Richtungswechsel im kleineren Zeitrahmen', 'Form und spätere Trendwende sind verschiedene Dinge'],
    durationMinutes: 12,
    teachingTitle: 'Frage zuerst: Was genau wurde umgekehrt?',
    paragraphs: [
      'Ein Reversal-Bar verändert mindestens ein Merkmal der vorherigen Bewegung. Nach mehreren fallenden Bars kann ein bullischer Schluss zeigen, dass Käufer den letzten Verkaufsdruck zurückgedrängt haben. Das ist eine Beobachtung innerhalb dieses Bars, noch keine bestätigte neue Aufwärtsphase.',
      'Zoomst du in denselben Zeitraum hinein, siehst du meist zwei Abschnitte: erst Bewegung in der alten Richtung, dann eine Gegenbewegung. Ein einzelner großer Bar fasst diese Abfolge nur zusammen. Seine Form sagt wenig darüber, ob Käufer oder Verkäufer auch die nächsten Bars beherrschen.',
      'Prüfe deshalb drei Fragen getrennt: Kam der Bar an einer sinnvollen Stelle? Hat er die vorherige Bewegung deutlich zurückgenommen? Zeigt der Markt nach dem Bar weitere Bereitschaft in der neuen Richtung? Schon die erste Frage kann einen optisch schönen Bar entwerten.',
      'Ein Bullen-Reversal mitten in einem engen Seitwärtsmarkt kehrt womöglich gar keinen Trend um. Ein unscheinbarer Bar an einem getesteten Tief kann dagegen ein wichtiger Teil einer größeren Umkehrsequenz sein.',
    ],
    callout: 'Die Form beschreibt den Bar. Eine handelbare Umkehr entsteht erst aus Lage, Auslösung und Anschluss.',
    scenario: 'reversal-meaning',
    chartTitle: 'Alte Richtung, Gegenreaktion und offener Ausgang',
    caption: 'Der farblich markierte Bar nimmt den letzten Rückgang zurück; rechts bleiben Fortsetzung und Fehlschlag als mögliche Wege sichtbar.',
    observations: ['Der erste Richtungswechsel ist auf einen Bar begrenzt.', 'Die Lage im vorangegangenen Verlauf entscheidet über seine Bedeutung.', 'Ohne Folgebars bleibt die These einer neuen Richtung unbestätigt.'],
    questionTitle: 'Was ist tatsächlich belegt?',
    prompt: 'Nach einem Verkaufsbein schließt ein Bar über seiner Eröffnung. Welche Aussage ist unmittelbar gerechtfertigt?',
    choices: ['Ein neuer Bullenmarkt ist bestätigt.', 'Käufer haben diesen Bar teilweise oder deutlich zurückgewonnen; der nächste Bar bleibt offen.', 'Ein Long kann nicht mehr verlieren.'],
    explanations: ['Ein einzelner Schluss in Gegenrichtung bestätigt noch keinen Trendwechsel.', 'Richtig. Der Bar zeigt eine Reaktion, deren Fortsetzung erst beobachtet werden muss.', 'Aus einer Barform ergibt sich keine Gewinngarantie.'],
    correct: 1,
    takeaways: ['Reversal meint zunächst eine Umkehr eines sichtbaren Merkmals.', 'Kleinere Zeitrahmen zeigen die Bewegung innerhalb des Bars.', 'Lage und nächste Bars geben der Form ihre Bedeutung.'],
  },
  {
    number: 2,
    title: 'Der bullische Bar: Rückweisung und Schluss',
    summary: 'Körper, unteren Schatten, oberen Schatten und Schluss im Verhältnis zu früheren Bars lesen.',
    sourceUnit: 'Kapitel 5 · Eigenschaften bullischer Reversal-Bars',
    sourceAnchors: ['Bullischer Körper oder Schluss über der Barmitte', 'Unterer Schatten als sichtbare Zurückweisung', 'Geringer oberer Schatten und Schluss relativ zu Vorbars'],
    durationMinutes: 13,
    teachingTitle: 'Verkäufer erreichen ein Tief, Käufer erobern den Schluss',
    paragraphs: [
      'Ein bullischer Reversal-Bar kann nach einem tieferen Handel wieder deutlich höher schließen. Sein unterer Schatten zeigt den Weg zum Tief und zurück; ein Schluss weit oben im Bar zeigt, dass die Käufer bis zum Ende aktiv blieben. Ein bullischer Körper oder wenigstens ein Schluss über der Barmitte ist eine brauchbare Mindestbeschreibung.',
      'Ein Schatten allein ist keine Kauforder. Achte darauf, ob der Schluss über dem Schluss des Vorbars liegt und ob der Bar einen jüngsten Bereich wirklich zurückerobert. Ein Schluss nahe dem Hoch bei kleinem oberen Schatten wirkt entschlossener als ein Rückfall kurz vor Schluss.',
      'Die Länge des unteren Schattens bekommt erst durch den Ort Bedeutung. Unter einem früheren Tief kann sie einen gescheiterten Verkaufsversuch sichtbar machen. Mitten in mehreren überlappenden Bars ist dieselbe Silhouette oft nur ein weiterer Ausschlag in einer Range.',
      'Merk dir keine perfekte Proportion als Pflicht. Der Bar darf weniger klassisch aussehen, wenn der Gesamtverlauf klar für die Käufer spricht. Umgekehrt rettet eine Bilderbuchkerze keinen schlechten Einstieg gegen den Trend.',
    ],
    callout: 'Lies den Schluss zusammen mit dem getesteten Preis und dem vorherigen Druck.',
    scenario: 'bull-reversal-anatomy',
    chartTitle: 'Zwei bullische Silhouetten mit unterschiedlicher Aussage',
    caption: 'Links verteidigen Käufer ein neues Tief bis zum Schluss. Rechts schließt der Bar nach anfänglicher Erholung wieder tiefer.',
    observations: ['Der untere Schatten markiert eine zurückgewiesene Tiefzone.', 'Ein Schluss weit oben stärkt den Eindruck aktiver Käufer.', 'Ein großer oberer Schatten schwächt die Aussage des Schlusses.'],
    questionTitle: 'Welche Form zeigt mehr Kontrolle?',
    prompt: 'Zwei Bars haben denselben langen unteren Schatten. A schließt fast am Hoch, B gibt die Hälfte der Erholung wieder ab. Welcher zeigt in diesem Moment mehr Kaufdruck?',
    choices: ['B, weil sein oberer Schatten größer ist.', 'Beide beweisen dieselbe Stärke.', 'A, weil Käufer die Erholung bis zum Schluss besser gehalten haben.'],
    explanations: ['Ein großer oberer Schatten zeigt nachlassende Kaufkontrolle.', 'Der identische untere Schatten beschreibt nur den ersten Teil des Bars.', 'Richtig. Der stärkere Schluss ist zusätzliche Evidenz, kein Erfolgsversprechen.'],
    correct: 2,
    takeaways: ['Bullischer Körper oder Schluss oberhalb der Mitte ist ein Ausgangspunkt.', 'Unterer Schatten plus hoher Schluss beschreibt eine stärkere Rückeroberung.', 'Die Lage zum alten Tief bleibt wichtiger als eine ideale Kerzenform.'],
  },
  {
    number: 3,
    title: 'Der bärische Bar ist das Spiegelbild',
    summary: 'Wie ein getestetes Hoch, ein oberer Schatten und ein tiefer Schluss zusammenspielen.',
    sourceUnit: 'Kapitel 5 · Eigenschaften bärischer Reversal-Bars',
    sourceAnchors: ['Bärischer Körper oder Schluss unter der Barmitte', 'Oberer Schatten nach gescheitertem Hoch', 'Tiefer Schluss und geringer unterer Schatten'],
    durationMinutes: 12,
    teachingTitle: 'Der Preis steigt zuerst und wird dann zurückgedrückt',
    paragraphs: [
      'Ein bärischer Reversal-Bar zeigt oft: Käufer erreichen ein Hoch, aber Verkäufer nehmen den Anstieg bis zum Schluss wieder zurück. Ein oberer Schatten macht diese Abweisung sichtbar; ein Schluss nahe dem Tief deutet auf Verkaufsdruck bis zum letzten Moment hin.',
      'Prüfe, ob der Bar unter seiner Eröffnung oder wenigstens unter seiner Mitte schließt. Noch aussagekräftiger ist es, wenn er auch unter frühere Schlusskurse fällt. Der tiefe Schluss trennt entschlossenes Verkaufen von einem bloßen Rücksetzer in einem starken Aufwärtstrend.',
      'Ein langer unterer Schatten passt nicht zum Bild einer durchgehend starken Verkäuferseite: Auch Käufer haben vor dem Schluss wieder reagiert. Das macht einen Short nicht automatisch falsch, erhöht aber die Bedeutung des nächsten Bars und des Orts im Chart.',
      'An einer mehrfach getesteten Range-Oberkante kann derselbe Bar etwas anderes bedeuten als nach dem ersten kurzen Pullback eines starken Bullenkanals. Form und Kontext müssen zusammenpassen.',
    ],
    callout: 'Ein bärischer Reversal-Bar zeigt Abgabe bis zum Schluss; der Short braucht trotzdem einen tragfähigen Kontext.',
    scenario: 'bear-reversal-anatomy',
    chartTitle: 'Hoch zurückgewiesen oder nur kurz pausiert?',
    caption: 'Die eine Variante schließt nach dem Test des Hochs tief, die andere wird unten sofort wieder gekauft.',
    observations: ['Der obere Schatten zeigt den abgewiesenen Hochtest.', 'Der tiefe Schluss trägt mehr Gewicht als ein kurzzeitiges Zurückfallen.', 'Ein langer unterer Schatten verrät Gegenwehr durch Käufer.'],
    questionTitle: 'Was schwächt einen bärischen Schluss?',
    prompt: 'Ein Bar steigt über ein altes Hoch, fällt, schließt aber mit langem unteren Schatten und kleinem Körper. Was fehlt gegenüber einem starken bärischen Reversal-Bar?',
    choices: ['Verkaufsdruck bis in den Schluss.', 'Ein hoher Umsatzwert aus dem Orderbuch.', 'Eine bestimmte Uhrzeit.'],
    explanations: ['Richtig. Käufer haben einen Teil des Rückgangs vor dem Schluss wieder aufgefangen.', 'Der sichtbare Bar lässt sich ohne Orderbuchdaten lesen.', 'Die Uhrzeit allein entscheidet hier nicht über die Form.'],
    correct: 0,
    takeaways: ['Bärischer Körper oder Schluss unter der Mitte ist die Grundform.', 'Oberer Schatten plus tiefer Schluss zeigt Zurückweisung.', 'Unterer Schatten und Lage können die Verkaufsbotschaft abschwächen.'],
  },
  {
    number: 4,
    title: 'Ein Schluss durch mehrere Bars wiegt mehr',
    summary: 'Den Kontrollwechsel an früheren Schlusskursen und an Hochs oder Tiefs messen.',
    sourceUnit: 'Kapitel 5 · Stärke über mehrere frühere Bars',
    sourceAnchors: ['Schluss relativ zu den Schlüssen mehrerer Vorbars', 'Überschreiten vorheriger Hochs oder Unterschreiten vorheriger Tiefs', 'Stärkerer Gegenimpuls ohne perfekte Schattenform'],
    durationMinutes: 12,
    teachingTitle: 'Zähle zurück, wie viel Boden wirklich zurückgewonnen wurde',
    paragraphs: [
      'Zwei Bars können gleich groß sein und denselben unteren Schatten haben. Schließt der eine nur über dem letzten Schluss und der andere zusätzlich über mehreren früheren Schlusskursen und Hochs, hat der zweite einen größeren Teil des Rückgangs zurückgenommen.',
      'Nach einem Anstieg gilt das spiegelbildlich: Ein kräftiger bärischer Bar kann mehrere frühere Schlusskurse und Tiefs unterschreiten, obwohl sein Hoch das Hoch des Vorbars nie überschritten hat. Weil die klassische Pin-Bar-Form fehlt, ist der Kontrollwechsel trotzdem nicht unsichtbar.',
      'Vergleiche nicht nach festen Stückzahlen wie bei einer Zauberformel. Wichtig ist, ob der Schluss in einer relevanten Preiszone liegt und ob dadurch bestehende Positionen unter Druck geraten. In einer breiten Range wechseln solche Grenzen oft ohne nachhaltige Wirkung.',
      'Markiere vor der Entscheidung die letzten zwei bis drei wichtigen Schlusskurse und Swingpunkte. So siehst du, ob der neue Bar tatsächlich etwas rückgängig macht oder nur im bisherigen Handelsraum pendelt.',
    ],
    callout: 'Ein Schluss durch mehrere frühere Entscheidungen liefert mehr Information als ein einzelner auffälliger Schatten.',
    scenario: 'reversal-many-closes',
    chartTitle: 'Ein Schluss überschreitet mehrere frühere Schlüsse',
    caption: 'Die markierten Vergleichsniveaus machen sichtbar, wie weit der neue Bar den vorangegangenen Rückgang aufhebt.',
    observations: ['Mehrere vorherige Schlüsse werden übertroffen.', 'Der neue Schluss dringt in einen zuvor verteidigten Bereich vor.', 'Geringe Überlappung macht die Änderung besser sichtbar.'],
    questionTitle: 'Welcher Bar verändert mehr?',
    prompt: 'Bar A endet knapp über dem letzten Schluss. Bar B endet nach derselben Abwärtsphase oberhalb der letzten drei Schlüsse. Bei sonst ähnlichem Kontext: Welcher zeigt die stärkere Rückeroberung?',
    choices: ['A, weil ein kleinerer Schritt immer sicherer ist.', 'B, weil er mehr der vorangegangenen Bewegung aufhebt.', 'Die Zahl der Schlüsse hat grundsätzlich keine Bedeutung.'],
    explanations: ['Ein kleiner Schritt kann sinnvoll sein, nimmt aber weniger der alten Bewegung zurück.', 'Richtig. Der Vergleich der früheren Schlüsse zeigt die größere Veränderung.', 'Frühere Schlüsse sind ein nützlicher Teil der Evidenz, wenn auch kein starres Handelssignal.'],
    correct: 1,
    takeaways: ['Vergleiche den Schluss mit mehr als nur einem Vorbar.', 'Auch frühere Hochs oder Tiefs können betroffen sein.', 'Kontext entscheidet, ob die Überschreitung bestehen bleibt.'],
  },
  {
    number: 5,
    title: 'Aus dem Setup wird erst nach Auslösung ein Signal',
    summary: 'Die Barform zeitlich sauber von Entry-Bar und Follow-through trennen.',
    sourceUnit: 'Kapitel 5 · Signal, Auslösung und Folgebar',
    sourceAnchors: ['Möglicher Setup-Bar vor dem Einstieg', 'Signal-Bar nach ausgeführter Order', 'Starker oder schwacher Entry-Bar als neue Information'],
    durationMinutes: 11,
    teachingTitle: 'Ein interessantes Bild führt noch keinen Trade aus',
    paragraphs: [
      'Nach einem tieferen Tief bildet sich ein bullischer Bar. Solange der geplante Einstieg über seinem Hoch nicht ausgelöst ist, bleibt er ein möglicher Setup-Bar. Die Form allein zwingt dich zu keiner Position.',
      'Überschreitet der nächste Bar deine gewählte Einstiegsschwelle und wird die Order ausgeführt, wird der vorherige Bar rückblickend zum Signal-Bar. Der auslösende Bar ist der Entry-Bar. Schließt er kräftig in Handelsrichtung, bestätigt er mehr als ein kurzes Antippen des Levels.',
      'Ein enger Doji als Entry-Bar sagt dagegen: Der Markt hat die Schwelle erreicht, aber bisher keine entschlossene Fortsetzung geliefert. Je schwächer das ursprüngliche Setup war, desto weniger Grund gibt es, schwachen Anschluss großzügig zu übergehen.',
      'Vor dem Einstieg solltest du deshalb zwei Fälle planen: Was tue ich bei gutem Anschluss, und was bei sofortiger Rückkehr in die alte Struktur? Stop, Größe und möglicher Ausstieg müssen zum jeweiligen Risiko passen.',
    ],
    callout: 'Trenne Form, Ausführung und Folgereaktion – es sind drei verschiedene Informationen.',
    scenario: 'reversal-entry-chain',
    chartTitle: 'Setup, ausgelöster Einstieg und offener Anschluss',
    caption: 'Der Signal-Bar wird erst nach Auslösung so benannt; danach prüfst du die Qualität des Entry-Bars.',
    observations: ['Die Einstiegsschwelle liegt jenseits des Setup-Bars.', 'Das Erreichen der Schwelle ist nicht dasselbe wie ein starker Schluss.', 'Der nächste Bar kann die These stützen oder sofort in Frage stellen.'],
    questionTitle: 'Wann ändert sich die Rolle?',
    prompt: 'Du planst einen Buy-Stop über einem bullischen Reversal-Bar. Der nächste Bar erreicht die Schwelle nicht. Welche Rolle hat der erste Bar?',
    choices: ['Bereits ein ausgeführter Entry-Bar.', 'Automatisch ein bestätigter Signal-Bar.', 'Ein potenzieller Setup-Bar ohne ausgelösten Trade.'],
    explanations: ['Der Entry-Bar wäre der Bar einer tatsächlichen Ausführung.', 'Ohne Auslösung bleibt die Bezeichnung Signal-Bar für diesen Trade verfrüht.', 'Richtig. Die Orderidee ist noch kein Einstieg.'],
    correct: 2,
    takeaways: ['Eine Reversal-Form ist zunächst ein mögliches Setup.', 'Ausführung macht den vorherigen Bar zum Signal-Bar.', 'Der Entry-Bar zeigt, ob nach Auslösung Initiative folgt.'],
  },
  {
    number: 6,
    title: 'Im starken Trend darf das Mit-Trend-Signal einfacher sein',
    summary: 'Warum ein Pullback-Long andere Anforderungen hat als ein Short gegen denselben Trend.',
    sourceUnit: 'Kapitel 5 · Mit-Trend- und Gegentrend-Signale',
    sourceAnchors: ['Starke Trendrichtung als Kontextvorteil', 'Weniger perfekte Mit-Trend-Signal-Bar nötig', 'Gegentrend-Signal unter höherer Beweislast'],
    durationMinutes: 13,
    teachingTitle: 'Die übergeordnete Richtung verändert die Beweislast',
    paragraphs: [
      'In einem starken Bullenmarkt laufen Rücksetzer oft in die alte Richtung zurück. Ein Long nach einer Pause braucht deshalb nicht immer den schönsten bullischen Bar. Der bestehende Trend liefert einen Teil des Kontexts.',
      'Ein Short an derselben Stelle ist eine andere Behauptung: Er verlangt, dass die bisher erfolgreichen Käufer die Kontrolle verlieren. Ein hübscher bärischer Bar während eines kleinen Rücklaufs kann nur das Ende der Pause markieren und als Short schnell scheitern.',
      'Das ist keine Aufforderung, beliebige Bars im Trend zu kaufen. Prüf trotzdem, wo das Setup liegt, wie weit der Stop entfernt ist und ob die mögliche Bewegung das Risiko rechtfertigt. Ein starker Trend ersetzt keinen Plan.',
      'Vergleiche dieselbe Kerze bei zwei Fragen: Unterstützt sie eine Fortsetzung nach einem Pullback, oder soll sie einen etablierten Trend kippen? Die zweite Aufgabe braucht deutlich mehr unabhängige Hinweise.',
    ],
    callout: 'Die Gegenrichtung muss erst beweisen, dass der alte Trend seine Kontrolle verliert.',
    scenario: 'reversal-with-trend',
    chartTitle: 'Dieselbe Schwäche als Pullback und als Short-Idee',
    caption: 'Im Bullenkanal ist ein fallender Bar für Käufer eine mögliche Pause; für Verkäufer reicht er allein kaum als Umkehrbeweis.',
    observations: ['Mehrere frühere Bars stützen die Trendrichtung.', 'Der Gegen-Bar kann nur ein kleiner Pullback sein.', 'Mit-Trend-Einstieg und Gegentrend-Einstieg haben unterschiedliche Voraussetzungen.'],
    questionTitle: 'Welcher Trade verlangt mehr Evidenz?',
    prompt: 'Nach einem flachen Rücklauf in einem starken Bullenkanal planst du entweder Long mit dem Trend oder Short gegen ihn. Welcher Plan braucht stärkere Umkehrhinweise?',
    choices: ['Der Short gegen den etablierten Trend.', 'Der Long nach dem Rücklauf.', 'Beide erfordern unabhängig vom Kontext exakt dieselbe Barform.'],
    explanations: ['Richtig. Er setzt einen echten Wechsel der bisherigen Käuferkontrolle voraus.', 'Der Long arbeitet zunächst mit der vorhandenen Trendrichtung.', 'Die Stärke des bestehenden Trends verändert die Anforderungen.'],
    correct: 0,
    takeaways: ['Trendrichtung ist Teil der Setup-Qualität.', 'Ein Mit-Trend-Signal kann bei starkem Trend unperfekt sein.', 'Gegentrend-Handel fordert stärkere Belege und durchdachtes Risiko.'],
    comparison: {
      title: 'Gleicher Chart, verschiedene Ansprüche',
      positive: { title: 'Mit Trend nach Pullback', points: ['alte Richtung ist bereits belegt', 'Signal zeigt Ende der Pause', 'Risiko und Lage bleiben zu prüfen'] },
      warning: { title: 'Gegen Trend', points: ['alter Trend muss an Kraft verlieren', 'ein einzelner Schatten genügt selten', 'Fehlschlag kann sofort die Fortsetzung speisen'] },
    },
  },
  {
    number: 7,
    title: 'Gegen den Trend zählt die Struktur vor der Kerze',
    summary: 'Trendlinienbruch, Test und starkes Signal als Abfolge für vorsichtige Umkehrideen.',
    sourceUnit: 'Kapitel 5 · Gegen-Trend-Umkehr',
    sourceAnchors: ['Trendbruch vor größerer Gegen-Trend-These', 'Erneuter Test des Extrembereichs', 'Starker Reversal-Bar am Test'],
    durationMinutes: 13,
    teachingTitle: 'Erst ein Bruch, dann ein Test, dann ein neues Signal',
    paragraphs: [
      'Im starken Abwärtstrend scheitern Versuche, das absolute Tief mit nur einem kleinen bullischen Bar zu erwischen, oft. Der Kurs kann kurz hochspringen und trotzdem den nächsten Abwärtsschub beginnen. Die alte Struktur ist noch intakt.',
      'Eine tragfähigere Umkehrgeschichte hat mehrere Schritte: Der Markt verlässt zuerst seinen engen Abwärtsverlauf, kehrt in den Tiefbereich zurück und zeigt dort erneut Käufer. Der zweite Test beantwortet, ob Verkäufer noch einmal nachhaltig tiefer handeln können.',
      'Ein kräftiger bullischer Schluss am Test verbessert die These, beweist sie aber weiterhin nicht. Scheitert der Ausbruch nach oben oder unterschreitet der Markt das Testtief, war die Umkehridee falsch, und du musst das Risiko begrenzen.',
      'Gerade im sehr kleinen Zeitrahmen tauchen ständig optische Reversal-Bars auf. Wähle eine feste Plan-Zeitebene und bewerte die größere Struktur, statt jeden Mini-Schatten als Beginn eines neuen Trends zu behandeln.',
    ],
    callout: 'Ein Bar am zweiten Test hat eine andere Grundlage als derselbe Bar beim ersten Antippen des Tiefs.',
    scenario: 'reversal-break-retest',
    chartTitle: 'Alter Abwärtskanal, Bruch und zweiter Tief-Test',
    caption: 'Die Gegen-Trend-Idee gewinnt Kontext, sobald nach dem Kanalbruch ein erneuter Verkaufsversuch scheitert.',
    observations: ['Der Kanalbruch schwächt die alte Struktur zunächst nur ab.', 'Am zweiten Tief-Test fehlt ein nachhaltiger Durchbruch.', 'Der Reversal-Bar ist Teil einer mehrbarigen Sequenz.'],
    questionTitle: 'Welcher Verlauf liefert mehr Kontext?',
    prompt: 'A: erster bullischer Schatten in einem intakten engen Bärenkanal. B: Bruch des Kanals, erneuter Test des Tiefs und bullischer Schluss. Welche Long-Idee hat die bessere strukturelle Grundlage?',
    choices: ['A, weil sie früher kommt.', 'B, weil der alte Verlauf bereits getestet und zurückgewiesen wurde.', 'Beide sind allein wegen des Schattens gleichwertig.'],
    explanations: ['Frühe Einstiege erhalten weniger strukturelle Bestätigung.', 'Richtig. Bruch und Test zeigen mehr als die isolierte Kerzenform.', 'Die Abfolge vor dem Bar macht einen wesentlichen Unterschied.'],
    correct: 1,
    takeaways: ['Im starken Trend sind isolierte Gegen-Bars anfällig.', 'Ein Strukturbruch und ein erneuter Test liefern zusätzliche Evidenz.', 'Auch eine bessere Sequenz braucht einen klaren Fehlpunkt.'],
  },
  {
    number: 8,
    title: 'Der zweite gescheiterte Tief-Test verändert die Lage',
    summary: 'Warum ein erneuter Versuch am alten Extrem mehr Information liefert als das erste Abprallen.',
    sourceUnit: 'Kapitel 5 · Test des alten Extrems',
    sourceAnchors: ['Erster Kaufimpuls aus einem Tief', 'Rückkehr in die Zone des alten Tiefs', 'Gescheiterter zweiter Verkaufsversuch'],
    durationMinutes: 12,
    teachingTitle: 'Der Markt fragt dieselbe Preiszone ein zweites Mal ab',
    paragraphs: [
      'Nach einem ersten Abprallen vom Tief ist offen, ob wirklich dauerhaft Käufer bereitstehen. Verkäufer können beim nächsten Rücklauf noch einmal versuchen, den Preis unter das alte Tief zu drücken. Dieser Versuch ist ein aussagekräftigerer Test als der erste kurze Sprung.',
      'Hält die Zone beim zweiten Besuch oder wird ein kleines Unterschreiten rasch zurückgenommen, verlieren die Verkäufer einen Teil ihrer Argumente. Ein bullischer Reversal-Bar dort kann den gescheiterten Versuch sichtbar zusammenfassen.',
      'Ein doppelter Test ist keine automatische Long-Regel. Vergleiche Tiefe, Tempo, Schluss und Folgebars. Ein kräftiger Ausbruch unter beide Tiefs würde das Kauf-Szenario widerlegen und könnte den alten Trend bestätigen.',
      'Denk in beobachtbaren Ereignissen: erstes Tief, Erholung, erneuter Verkaufsversuch, Ergebnis. Ob das Muster am Ende Double Bottom heißt, ist zweitrangig gegenüber diesen vier Schritten.',
    ],
    callout: 'Zwei gescheiterte Versuche an einer Zone liefern mehr Information als ein einzelner Schatten.',
    scenario: 'reversal-second-test',
    chartTitle: 'Erster Abprall und zweiter Verkaufsversuch',
    caption: 'Die entscheidende Frage ist, ob unter dem alten Tief weitere Verkäufer folgen oder der Kurs schnell zurückkehrt.',
    observations: ['Der erste Kaufimpuls schafft einen beobachtbaren Referenzpreis.', 'Der Rücklauf testet, ob die Zone erneut Käufer anzieht.', 'Das Ergebnis des zweiten Versuchs bestimmt die nächste Hypothese.'],
    questionTitle: 'Was widerlegt die Long-Idee?',
    prompt: 'Nach einer Erholung testet der Markt das alte Tief erneut. Welche Beobachtung schwächt die Umkehrthese am deutlichsten?',
    choices: ['Ein kurzes Unterschreiten mit sofortiger Rückkehr.', 'Ein zweiter bullischer Schluss nach dem Test.', 'Ein kräftiger Abwärtsausbruch unter beide Tiefs mit Anschluss.'],
    explanations: ['Ein rasch gescheiterter Durchbruch kann Käufer sogar stützen.', 'Er stärkt die These, sofern der nächste Verlauf passt.', 'Richtig. Der Verkaufsversuch erhält diesmal nachhaltigen Anschluss.'],
    correct: 2,
    takeaways: ['Ein erneuter Test prüft die Verteidigung der alten Zone.', 'Gescheiterter Durchbruch und nachhaltiger Ausbruch sind Gegensätze.', 'Der Name des Musters ersetzt die Beobachtung der Folgebars nicht.'],
  },
] satisfies ReversalLessonDraft[]).map(makeChapterFiveLesson);
