import { chapterNineLesson, type ChapterNineDraft } from './chapter-09-model';

// Absatzfolge des Buchkapitels. Beispiele und Schaubilder sind eigenständig.
const drafts: ChapterNineDraft[] = [
  {
    number: 1, title: 'Eine andere Darstellung kann ein Muster klären',
    summary: 'Bars, Schlusslinie und andere Einteilungen zeigen verschiedene Details derselben Bewegung.',
    section: 'Absatz 1 · Chartdarstellung',
    anchors: ['Kapitel 9 · Absatz 1', 'Bar- und Linienchart', 'Zeit-, Tick- und Volumenbars sowie Ausdruck'],
    scenario: 'c09-view-choice',
    paragraphs: [
      'Wenn eine Formation im gewohnten Chart schwer zu lesen ist, hilft manchmal ein Wechsel der Darstellung. Ein Bar-Chart zeigt Hoch, Tief, Eröffnung und Schluss. Eine Linie aus Schlusskursen blendet die Zwischenbewegung aus und macht sichtbar, ob die Endpreise wirklich in eine Richtung wandern.',
      'Man kann dieselbe Handelsphase auch in Zeit-, Tick- oder Volumenbars betrachten oder auf einer höheren beziehungsweise niedrigeren Zeitebene ansehen. Diese Ansichten setzen neue Grenzen zwischen Bars; dadurch kann eine Pause anders aussehen. Ein Ausdruck schafft Abstand zum laufenden Bildschirm und kann die große Struktur leichter erkennbar machen.',
      'Der Vergleich liefert keine zusätzliche Zukunftsinformation. Vor allem darf ein hübscheres Muster in einer zweiten Ansicht einen schwachen Standort oder fehlenden Anschluss im eigenen Handelschart nicht ersetzen. Kläre erst, welche konkrete Frage der Wechsel beantworten soll.',
    ],
    callout: 'Der Ansichtswechsel ist ein Prüfwerkzeug, kein neues Handelssignal.',
    diagramTitle: 'Bars und Schlusslinie derselben erfundenen Folge',
    caption: 'Eigenes Schema: Links Bars mit Extremstichen; rechts verbindet eine Linie nur deren Schlusswerte.',
    observations: ['Die Linie verbirgt Hoch und Tief innerhalb eines Bars.', 'Die Reihenfolge der Schlüsse bleibt gleich.', 'Ein anderer Blick verändert nicht die bereits gehandelten Preise.'],
    prompt: 'Was kann ein Schlusslinienchart zusätzlich zu deinem Bar-Chart klären?',
    answers: [['Ob die Folge der Endpreise das vermutete Muster stützt.', 'Richtig. Die Linie verdichtet jeden Bar auf seinen Schluss.'], ['Welche Position als Nächstes sicher gewinnt.', 'Eine andere Darstellung liefert keine Gewissheit über kommende Bars.'], ['Ob die Intrabar-Hochs auf einmal nicht mehr existieren.', 'Sie bleiben Teil des Marktes, sind in dieser Ansicht nur verborgen.']], correct: 0,
    takeaways: ['Zwischenbewegung und Endpreise bewusst unterscheiden.', 'Andere Bar-Einteilungen verändern die optische Struktur.', 'Mit einer konkreten Frage zwischen Ansichten wechseln.'],
  },
  {
    number: 2, title: 'SPY als zweiter Blick auf den Emini',
    summary: 'Ein eng verwandter ETF kann dieselbe Marktbewegung lesbarer zeigen.',
    section: 'Absatz 1 · Verwandtes Instrument',
    anchors: ['Kapitel 9 · Absatz 1', 'Emini und SPY im Vergleich', 'Klarere Price Action in der zweiten Ansicht'],
    scenario: 'c09-spy-context',
    paragraphs: [
      'Als Beispielmarkt dient häufig der S&P-500-Emini. Als ergänzende Ansicht dient SPY, einen börsengehandelten Fonds auf den S&P 500. Beide reagieren gewöhnlich auf die Bewegung desselben Aktienmarktes, auch wenn sie verschiedene Instrumente und verschiedene Preisniveaus sind.',
      'Auf dem einen Chart kann eine kleine Kerze unentschieden wirken, während der andere die Abfolge der Schlüsse oder einen Test einer Preiszone etwas deutlicher zeigt. Im historischen Beispiel ist der feinere Preisschritt des SPY ein Grund für die besser lesbaren Einzelbars. Das ist eine Hilfe beim Einordnen, keine Aussage, dass beide Kursreihen identisch sind.',
      'Lies zuerst dein gehandeltes Instrument und nutze SPY nur für eine offene Frage: War der Rücklauf wirklich schwach, wurde ein Tief klar zurückgekauft oder schlossen die Bars weiter in Trendrichtung? Stop, Auftrag und Ausführung bleiben an das Instrument gebunden, das du tatsächlich handelst.',
    ],
    callout: 'Ähnliche Bewegung heißt nicht gleicher Preis, Tick oder Auftrag.',
    diagramTitle: 'Ähnlicher Verlauf auf zwei eigenen Skalen',
    caption: 'Zwei frei konstruierte Kursfolgen vergleichen ein futuresähnliches Instrument mit einem ETF, jeweils auf einer eigenen normierten Skala.',
    observations: ['Die Richtung der Abschnitte ähnelt sich.', 'Die Einzelbars müssen nicht genau gleich aussehen.', 'Ein Preisniveau aus SPY ist kein Emini-Stop.'],
    prompt: 'Der SPY-Chart zeigt einen Tief-Test etwas klarer als dein Emini-Chart. Was darfst du daraus schließen?',
    answers: [['Der SPY-Preis ist direkt dein Stop im Future.', 'Beide Instrumente haben unterschiedliche Preisniveaus und Kontraktregeln.'], ['Der zweite Blick kann die Deutung des Musters prüfen; gehandelt wird nach dem eigenen Plan.', 'Richtig. Er verbessert die Lesbarkeit, ersetzt nicht die Ausführungsregeln.'], ['Der Future muss nun exakt dieselben Kerzen bilden.', 'Ähnliche Marktbewegung bedeutet keine identischen Bars.']], correct: 1,
    takeaways: ['SPY ist hier ein ergänzender Chart für den Emini.', 'Ähnliche Verläufe auf getrennten Preisachsen beurteilen.', 'Handelsregeln am eigenen Instrument verankern.'],
  },
  {
    number: 3, title: 'SDS zeigt die Gegenrichtung',
    summary: 'Die inverse ETF-Perspektive kann eine übersehene Verkäuferidee sichtbar machen.',
    section: 'Absatz 2 · Inverse Ansicht',
    anchors: ['Kapitel 9 · Absatz 2', 'SDS als inverse Perspektive', 'Hebel und unterschiedliche Kursachsen'],
    scenario: 'c09-inverse-view',
    paragraphs: [
      'Ein Chart in der Gegenrichtung kann die eigene Deutung auf die Probe stellen. Hierfür dient im historischen Beispiel SDS: einen inversen, zweifach gehebelten ETF zum S&P-500-Umfeld. Bei fallendem SPY wirkt SDS typischerweise stärker; die genaue Barform ist dennoch nicht einfach ein umgedrehter SPY-Chart.',
      'Angenommen, ein Anstieg des Emini sieht nach einer Pause vor weiterem Anstieg aus. Im inversen Blick könnte derselbe Zeitraum wie ein sich rundender Boden aussehen. Die Käuferthese ist dann weniger eindeutig, als die erste Ansicht vermuten ließ.',
      'Die inverse Ansicht ist ein Widerspruchstest, kein eigenständiger Beweis für einen Short. Unterschiedliche Preisachsen, Hebel und Produktmechanik verbieten es, aus dem SDS-Chart ein Emini-Preisziel oder einen Stop abzulesen. Frage nur, ob die andere Richtung ein ernstzunehmendes Muster bildet.',
    ],
    callout: 'Die Gegenansicht stellt deine erste Lesart infrage; sie ersetzt sie nicht.',
    diagramTitle: 'Zwei Richtungen, zwei Preisachsen',
    caption: 'Eigenes schematisches Gegenpaar: Ein normierter Marktverlauf und eine gegenläufige ETF-Ansicht, ohne behauptete punktgenaue Spiegelung.',
    observations: ['Ein Anstieg in der einen Ansicht steht einer Abwärtsphase gegenüber.', 'Die Gegenbewegung kann eine neue Struktur zeigen.', 'Die Skalen sind absichtlich nicht austauschbar.'],
    prompt: 'Welche Aufgabe erfüllt SDS in diesem Beispiel?',
    answers: [['Den exakten Emini-Stoppreis liefern.', 'Preisniveaus der Produkte sind nicht austauschbar.'], ['Jeden bullischen Bar automatisch widerlegen.', 'Die zweite Ansicht regt zum Prüfen an, sie beweist keine Umkehr.'], ['Eine bullische Deutung aus der Gegenperspektive prüfen.', 'Richtig. Ein inverses Muster kann eine blinde Stelle im ersten Chart aufdecken.']], correct: 2,
    takeaways: ['Inverse Ansichten können eine Gegenthese sichtbar machen.', 'SDS als historisches Beispiel einordnen.', 'Keine Preisniveaus zwischen ETF und Future übertragen.'],
  },
  {
    number: 4, title: 'Die scheinbare Bullenflagge und der runde Boden',
    summary: 'Eine freundliche Pause im Long-Chart kann im Gegenchart wie aufkommende Kaufkraft wirken.',
    section: 'Absatz 2 · Mustervergleich',
    anchors: ['Kapitel 9 · Absatz 2', 'Bull Flag im Emini oder SPY', 'Rundender Boden der SDS-Gegenansicht'],
    scenario: 'c09-flag-or-bottom',
    paragraphs: [
      'Eine Bullenflagge ist eine Unterbrechung innerhalb einer vorherigen Aufwärtsbewegung. Sie kann eine Trendfortsetzung vorbereiten, aber ihre Form allein garantiert keinen Ausbruch. Gerade nach einem stärkeren Anstieg kann der Blick auf die kurze Pause zu optimistisch sein.',
      'Es gibt einen Fall, in dem die vermeintliche Flagge im Emini beziehungsweise SPY aus der inversen SDS-Sicht eher einem rundenden Boden entspricht. Dort verlieren die Verkäufer der Gegenansicht allmählich an Kontrolle und Käufer werden stärker. Übersetzt auf den ursprünglichen Markt ist das ein Warnsignal gegen den sofortigen Long.',
      'Beide Bilder können gleichzeitig plausibel sein, weil Muster interpretationsabhängig sind. Entscheidend ist die nächste tatsächlich gehandelte Folge: Wird die Oberseite der Flagge überzeugend überwunden, oder bricht der Versuch ab? Das schematische Bild zeigt nur die Logik, keine Kopie echter Charts.',
    ],
    callout: 'Wenn die Gegenansicht ein tragfähiges Muster zeigt, braucht die erste These mehr Bestätigung.',
    diagramTitle: 'Flaggenidee gegen Bodenidee',
    caption: 'Zwei frei erfundene Verläufe: Links lässt sich eine Pause bullisch lesen; rechts wirkt die Gegenbewegung zunehmend stabil.',
    observations: ['Eine Flagge ist vor ihrem Ausbruch nur eine Möglichkeit.', 'Eine Rundung im Gegenchart ist eine Warnung, kein Short-Signal.', 'Die nächste Preisreaktion entscheidet zwischen den Lesarten.'],
    prompt: 'Der Long-Chart sieht nach Bullenflagge aus, SDS nach einem rundenden Boden. Was ist die vorsichtigste Folgerung?',
    answers: [['Den Long sofort verdoppeln, weil zwei Charts dasselbe zeigen.', 'Die Ansichten liefern hier gerade widersprechende Deutungen.'], ['Den geplanten Long hinterfragen und die nächste Preisfolge abwarten.', 'Richtig. Die Gegenansicht ist ein Hinweis auf Unklarheit.'], ['SDS ohne weiteres Signal sofort kaufen.', 'Ein mögliches Muster ist noch keine bestätigte Auslösung.']], correct: 1,
    takeaways: ['Flagge und Boden als konkurrierende Deutungen lesen.', 'Muster vor Auslösung nicht als Ergebnis behandeln.', 'Widerspruch führt zu mehr Beobachtung, nicht zu mehr Sicherheit.'],
  },
  {
    number: 5, title: 'Erst der gescheiterte Ausbruch öffnet die Gegenthese',
    summary: 'Nicht das Warnbild allein, sondern der Fehlschlag einer Fortsetzung macht einen Short prüfbar.',
    section: 'Absatz 2 · Entscheidung',
    anchors: ['Kapitel 9 · Absatz 2', 'Auf Ausbruch der möglichen Flagge warten', 'Short-Idee erst nach Fehlschlag des Ausbruchs'],
    scenario: 'c09-failed-breakout',
    paragraphs: [
      'Die SDS-Rundung führt im Beispiel dazu, die vermeintliche Bullenflagge nicht sofort zu kaufen. Man wartet auf weitere Price Action. Das ist eine aktive Entscheidung: Man lässt den Markt zeigen, ob die Käufer die erwartete Fortsetzung tatsächlich durchsetzen.',
      'Bricht der Emini später nach oben aus und fällt wieder zurück, verändert dieser Fehlschlag die Lage. Ein mögliches Short-Setup entsteht erst durch den beobachteten gescheiterten Ausbruch und die anschließende Verkäuferreaktion. Wenn der Ausbruch hält, hat die ursprüngliche Warnung keinen Vorrang vor der neuen Stärke.',
      'Für den Übungsplan trenne drei Zeitpunkte: das uneindeutige Muster, den versuchten Ausbruch und die Reaktion danach. Wer schon beim ersten Zweifel shortet, handelt einen Ablauf, den das Kapitel gerade nicht beschreibt. Ein tatsächlicher Einstieg braucht zusätzlich seinen eigenen Auslöser und Schutzpunkt.',
    ],
    callout: 'Warnung → abwarten → Fehlschlag prüfen; die Reihenfolge zählt.',
    diagramTitle: 'Ausbruch halten oder scheitern',
    caption: 'Eigenes Entscheidungsschema zeigt zwei mögliche Folgeverläufe nach derselben unklaren Pause; nur einer fällt in die alte Zone zurück.',
    observations: ['Vor dem Ausbruch besteht ein offener Konflikt.', 'Ein gehaltener Ausbruch entkräftet die Warnung.', 'Erst die Rückkehr nach dem Ausbruch stützt eine Gegenthese.'],
    prompt: 'Wann wird im beschriebenen Beispiel aus der Warnung eine prüfbare Short-Idee?',
    answers: [['Sobald SDS einen möglichen Boden andeutet.', 'Das war der Anlass zu warten, noch nicht der Auslöser für einen Short.'], ['Schon beim ersten Bar einer möglichen Bullenflagge.', 'Eine Flagge kann weiterhin nach oben fortgesetzt werden.'], ['Wenn der Aufwärtsausbruch des ursprünglichen Marktes scheitert.', 'Richtig. Die gescheiterte Fortsetzung liefert zusätzliche Information.']], correct: 2,
    takeaways: ['Warnung und bestätigten Fehlschlag unterscheiden.', 'Auch ein stark gehaltener Ausbruch ist ein mögliches Ergebnis.', 'Die Gegenthese erst nach beobachteter Folge handeln.'],
  },
  {
    number: 6, title: 'Andere Indizes sind nur gelegentlich hilfreich',
    summary: 'Nasdaq-Future, QQQ und QID sind weitere Blicke, aber keine Pflichtfenster.',
    section: 'Absatz 2 · Zusätzliche Märkte',
    anchors: ['Kapitel 9 · Absatz 2', 'Emini Nasdaq-100 und QQQ', 'QID als inverse Zusatzansicht und Fokus'],
    scenario: 'c09-extra-markets',
    paragraphs: [
      'Als weitere mögliche Vergleichsansichten kommen der Emini Nasdaq-100, der dazugehörige ETF QQQ und der zweifach inverse QID infrage. Ein Muster kann dort klarer wirken als im zuerst beobachteten Index. Diese Instrumente bilden jedoch andere Produkte beziehungsweise einen anderen Index ab.',
      'Mehr Charts sind nicht automatisch mehr Klarheit. Zusätzliche Preisskalen und leicht unterschiedliche Muster erhöhen die Zahl möglicher Deutungen. Während der Markt weiterläuft, kann das ständige Umschalten die Entscheidung sogar verzögern.',
      'Seine praktische Gewichtung in diesem Kapitel ist sparsam: beim Emini bleiben, gelegentlich SDS als Gegenprobe ansehen und die übrigen Märkte nur mit gutem Grund hinzuziehen. Für eine Lernübung reicht ein konkret formulierter Vergleich; ein ungerichtetes Suchen nach dem schönsten Muster hilft nicht.',
    ],
    callout: 'Ein Vergleichschart soll eine offene Frage beantworten, nicht neue Fragen stapeln.',
    diagramTitle: 'Gezielter Vergleich statt Chart-Sammlung',
    caption: 'Eigenes Schema vergleicht zwei frei erfundene Indexverläufe und markiert, dass ein ähnlicher Abschnitt unterschiedlich geformt sein kann.',
    observations: ['Eine zweite Indexfamilie ist kein identischer Markt.', 'Ein klareres Einzelbild kann den Arbeitschart ergänzen.', 'Der Fokus zählt mehr als beliebig viele Zusatzansichten.'],
    prompt: 'Wie ist die ständige Beobachtung von Nasdaq-100, QQQ und QID zusätzlich zum Emini zu bewerten?',
    answers: [['Meist ist der zusätzliche Aufwand kaum lohnend; Fokus auf den Emini ist sinnvoll.', 'Richtig. Er nennt die Charts als Möglichkeit, empfiehlt aber keinen Dauerwechsel.'], ['Sie sind für jeden Trade eine zwingende Bestätigung.', 'Das steht so nicht im Kapitel.'], ['Ihre Preisniveaus können direkt als Emini-Stop dienen.', 'Ein anderes Produkt ist keine gemeinsame Preisachse.']], correct: 0,
    takeaways: ['Nasdaq-100, QQQ und QID als optionale Vergleiche kennen.', 'Unterschiedliche Indizes nicht gleichsetzen.', 'Wenige, gezielte Prüfblicke bevorzugen.'],
  },
  {
    number: 7, title: 'ETF und Future können verschieden eröffnen',
    summary: 'Anpassungen und Fondskosten verhindern eine vollständig deckungsgleiche Kursreihe.',
    section: 'Absatz 3 · Produktunterschiede',
    anchors: ['Kapitel 9 · Absatz 3', 'Kosten und Anpassungen eines ETF', 'Dreifacher Verfall und abweichende Eröffnungslücke'],
    scenario: 'c09-adjustments',
    paragraphs: [
      'Ein ETF ist ein Fonds mit eigenen Kosten und einer eigenen Preisreihe. Sein Chart muss daher nicht jede Bewegung eines verwandten Futures pixelgenau wiederholen. Ein sichtbarer Unterschied ist zuerst eine Frage an das Produkt und den Zeitpunkt, nicht automatisch ein neues Trading-Signal.',
      'Im historischen Beispiel geht es um Tage mit dreifachem Verfall: SPY zeigt nach einer Preisanpassung zur Eröffnung mitunter eine deutlich größere Lücke als der Emini. Wer nur die beiden Gap-Größen vergleicht, könnte fälschlich glauben, der eine Markt bestätige eine andere Richtung.',
      'Nach dieser Eröffnungsabweichung zeigt das Beispiel einen weitgehend gemeinsamen Intraday-Rhythmus. Prüfe deshalb ab der Eröffnung die neue Bewegung und den jeweiligen Bar-Kontext auf dem eigenen Chart. Die Lücke aus dem Beispiel ist keine feste Vorschrift dafür, wie heutige Produkte an jedem Verfallstag eröffnen.',
    ],
    callout: 'Ein unterschiedlicher Startpunkt sagt noch wenig über die folgende Kursbewegung.',
    diagramTitle: 'Verschiedene Lücke, ähnlicher weiterer Weg',
    caption: 'Eigenes normiertes Schema: Der ETF beginnt nach einem größeren symbolischen Versatz; ab Handelsbeginn ähnelt die Richtung des weiteren Verlaufs dem Future.',
    observations: ['Die Startlücke ist in den Ansichten verschieden.', 'Der spätere Rhythmus kann dennoch ähnlich sein.', 'Keine exakten Preiswerte von einer Skala auf die andere übertragen.'],
    prompt: 'SPY zeigt am im Beispiel beschriebenen Verfallstag eine größere Eröffnungslücke als der Emini. Was prüfst du zuerst?',
    answers: [['Ob die Differenz mit einer ETF-Anpassung zusammenhängt und wie beide danach handeln.', 'Richtig. Ein einmaliger Versatz beweist keine andere laufende Marktrichtung.'], ['Ob das größere Gap jeden Long im Emini zwingend macht.', 'Die Gap-Größe des ETF ist kein automatischer Future-Einstieg.'], ['Ob du die SPY-Preise eins zu eins als Future-Preise eintragen kannst.', 'Die Produkte haben eigene Preisachsen.']], correct: 0,
    takeaways: ['ETF-Kosten und Anpassungen als mögliche Unterschiede beachten.', 'Gap-Größe nicht mit Intraday-Richtung verwechseln.', 'Den laufenden Preisverlauf nach der Eröffnung lesen.'],
  },
];

export const chapterNineFoundationLessons = drafts.map(chapterNineLesson);
