import { chapterEightLesson, type ChapterEightDraft } from './chapter-08-model';

// Eigenständige Lerntexte in der Argumentreihenfolge des Buchkapitels.
const drafts: ChapterEightDraft[] = [
  {
    number: 1, title: 'Der fast fertige Bar kann noch kippen',
    summary: 'Ein erwarteter Schluss ist noch kein beobachteter Schluss.',
    section: 'Vorzeitiger Einstieg',
    anchors: ['Kapitel 8 · erster Absatz', 'Einstieg vor dem Bar-Schluss', 'Kleiner Preisvorteil gegen Fehlsignalrisiko'],
    scenario: 'c08-early-entry',
    paragraphs: [
      'Ein Fünf-Minuten-Bar kann lange nach einer starken bullischen Kerze aussehen. Wer schon vor seinem Ende kauft, bekommt manchmal einen etwas besseren Preis. Dafür handelt er aber etwas, das der Markt noch gar nicht fertig gesagt hat.',
      'Dem möglichen Vorteil eines frühen Einstiegs von etwa einem Tick steht im Beispiel ein Verlust von acht Ticks aus einem misslungenen vorläufigen Signal gegenüber. Rein rechnerisch müssten acht erfolgreiche Preisvorteile so einen Fehlgriff ausgleichen, und Kosten oder weitere Fehltrades sind da noch gar nicht drin. Das ist ein Rechenbeispiel, keine feste Regel für heutige Märkte oder jeden Trade.',
      'In einem sehr starken Trend darf man einen frühen Mit-Trend-Einstieg vielleicht anders bewerten. Als Zusatzentscheidung auf jedem Bar frisst er aber Aufmerksamkeit, die du für Marktort, Stop und die nächsten Setups brauchst. Ein fester Ablauf nimmt dir die Entscheidung ab.',
    ],
    callout: 'Erst den geschlossenen Bar beurteilen; ein offener Schluss ist nur eine Vermutung.',
    diagramTitle: 'Erwarteter und wirklicher Schluss',
    caption: 'Eigenes Schema: Derselbe entstehende Bar wirkt zunächst bullisch; die letzte Bewegung kann seinen Schluss deutlich verändern.',
    observations: ['Vor dem Schluss ist der Körper nur vorläufig.', 'Viele kleine Tick-Vorteile können durch ein einziges Fehlsignal aufgebraucht werden.', 'Die Entscheidung braucht einen vorher festgelegten Ablauf.'],
    prompt: 'Ein laufender Bar sieht eine Minute vor Ende wie ein starkes Kaufsignal aus. Was ist noch unbekannt?',
    answers: [['Nur die exakte Größe des Gewinnziels.', 'Auch die Qualität des Signal-Bars selbst ist noch offen.'], ['Sein endgültiger Schluss und damit die Signalqualität.', 'Richtig. Der sichtbare Zwischenstand ist nicht die fertige Kerze.'], ['Ob die alte Marktrichtung jemals existiert hat.', 'Die Vorgeschichte ist sichtbar; der Schluss des aktuellen Bars noch nicht.']], correct: 1,
    takeaways: ['Kleine frühe Vorteile gegen seltene größere Fehlgriffe rechnen.', 'Signal und endgültigen Schluss trennen.', 'Den Einstieg als wiederholbaren Plan behandeln.'],
  },
  {
    number: 2, title: 'Auch die Tageskerze verändert noch ihre Aussage',
    summary: 'Ein Tageshoch während der Sitzung ist nicht automatisch ein starker Tages-Schluss.',
    section: 'Zeitebenen und Schluss',
    anchors: ['Kapitel 8 · zweiter Absatz', 'Tagesbar während seiner Bildung', 'Letzter Preis und Schlusslage'],
    scenario: 'c08-daily-close',
    paragraphs: [
      'Der Unterschied zwischen laufendem und geschlossenem Bar gilt nicht nur für kurze Zeitebenen. Ein Tagesbar, der zwischendurch nahe am Hoch steht, kann bis Handelsende wieder in die Mitte seiner Spanne zurückfallen.',
      'Wer am Zwischenhoch nur wegen des scheinbar starken Tageskörpers kauft, sitzt am Abend womöglich in einer Position, die auf einem Signal beruht, das im fertigen Chart gar nicht steht. Der Schluss kann dieselbe Spanne in eine viel ausgeglichenere Aussage verwandeln.',
      'Für einen Handel vor Tagesende brauchst du deshalb einen eigenen Intraday-Plan. Eine noch offene Tageskerze darfst du nicht behandeln, als wäre ihr Schluss schon bekannt.',
    ],
    callout: 'Die gewählte Zeitebene bestimmt, wann ihr Signal vollständig ist.',
    diagramTitle: 'Zwischenhoch und Tagesende',
    caption: 'Zwei selbst konstruierte Zustände derselben Tagesbewegung zeigen ein zeitweilig starkes Hoch und einen späteren mittigen Schluss.',
    observations: ['Das Tageshoch kann früh erreicht werden.', 'Der fertige Körper kann deutlich kleiner sein.', 'Ein Intraday-Einstieg braucht einen eigenen Grund.'],
    prompt: 'Warum kann ein Kauf nahe dem aktuellen Tageshoch nicht allein mit einem „starken Tages-Bar“ begründet werden?',
    answers: [['Weil Tagescharts grundsätzlich unbrauchbar sind.', 'Sie sind brauchbar, aber ihre Bar-Form steht erst zum Schluss fest.'], ['Weil das Hoch nach dem Tagesende verschwindet.', 'Das Hoch bleibt, die Schlusslage kann sich ändern.'], ['Weil der Tages-Schluss und damit die Bar-Stärke noch offen sind.', 'Richtig. Der Zwischenstand kann einen anderen Eindruck vermitteln.']], correct: 2,
    takeaways: ['Zeitebenen nicht während ihrer Bildung als abgeschlossen behandeln.', 'Hoch und Schlusslage gesondert lesen.', 'Vorzeitige Trades brauchen einen unabhängigen Plan.'],
  },
  {
    number: 3, title: 'Ein scheinbarer Boden kann am Ende verschwinden',
    summary: 'Das letzte Stück eines Bars kann eine bullische Gegenthese im Bärentrend entkräften.',
    section: 'Späte Umkehr des laufenden Bars',
    anchors: ['Kapitel 8 · erster häufiger Fehler', 'Vorläufige bullische Reversal-Bar', 'Starker Verkauf bis zum Schluss'],
    scenario: 'c08-false-bull-reversal',
    paragraphs: [
      'Nach einem fallenden Markt und einem neuen Tief warten viele auf einen bullischen Reversal-Bar. Steht der laufende Bar ein paar Minuten nahe seinem Hoch, wirkt der Gegenversuch überzeugend. Der vorherige Abwärtstrend ist aber noch nicht durch einen fertigen Schluss widerlegt.',
      'Fällt der Preis kurz vor Ablauf wieder zum Tief, bleibt statt des erhofften bullischen Signals nur ein schwacher Schluss. Ein früher Long hat dann seine Begründung verloren und riskiert trotz des vermeintlich besseren Einstiegs deutlich mehr.',
      'Die Lage am Tief, ein möglicher Kanalüberschuss und ein vorheriger Strukturbruch erklären, warum man auf eine Umkehr hofft. Sie ersetzen aber nicht die Beobachtung, ob die Käufer die Schlussphase wirklich halten.',
    ],
    callout: 'Eine mögliche Umkehr ist noch keine bestätigte Käuferkontrolle.',
    diagramTitle: 'Vom Gegenversuch zum schwachen Schluss',
    caption: 'Eigenes Zwei-Panel-Lehrschema: Ein Tief-Test steht zunächst hoch im Bar; der spätere Schluss fällt wieder in die Nähe des Tiefs.',
    observations: ['Der frühe Hochstand verlockt zum Gegentrend-Kauf.', 'Der endgültige Schluss entkräftet das vorläufige Signal.', 'Marktort und Schluss müssen gemeinsam stimmen.'],
    prompt: 'Ein bullischer Gegentrend-Bar in einem starken Abwärtstrend schließt am Ende nahe seinem Tief. Was ändert sich?',
    answers: [['Die frühe bullische Bar-These ist geschwächt und muss neu geprüft werden.', 'Richtig. Der tatsächliche Schluss widerspricht der erwarteten Zurückweisung.'], ['Der frühe Long wird dadurch automatisch sicherer.', 'Ein schwacher Schluss stärkt die Umkehrthese nicht.'], ['Der vorangehende Trend wird rückwirkend ausgelöscht.', 'Die Vorgeschichte bleibt bestehen; nur die neue Information ändert sich.']], correct: 0,
    takeaways: ['Vorläufige Umkehrform nicht vor Schluss handeln müssen.', 'Ein später Tiefschluss verändert die These.', 'Gegentrend-Ideen brauchen besonders klare Belege.'],
  },
  {
    number: 4, title: 'Ein bärisches Signal kann noch an Schärfe verlieren',
    summary: 'Ein später Rücksprung vom Tief ändert die Qualität eines geplanten Shorts.',
    section: 'Schlusslage eines Signal-Bars',
    anchors: ['Kapitel 8 · erster häufiger Fehler', 'Bärischer Signal-Bar kurz vor Schluss', 'Rücksprung vom Tief'],
    scenario: 'c08-bear-signal-weakens',
    paragraphs: [
      'Auch die Gegenseite kann zu früh auf eine fast fertige Form vertrauen. Ein Bar, der kurz vor Ende direkt am Tief handelt, sieht nach einem kräftigen bärischen Signal aus, und ein geplanter Short unter seiner Grenze wirkt dann einfach.',
      'Schon ein kleiner Rücksprung in den letzten Sekunden holt den Schluss vom Tief weg. Die Verkäuferkontrolle überzeugt dann weniger, obwohl Hoch und Tief des Bars gleich bleiben. Wer den Plan blind durchzieht, stützt sich noch auf den früheren Zwischenstand.',
      'Das heißt nicht, dass jeder Short mit unterem Schatten tabu ist. Du musst nur die tatsächliche Qualität des geschlossenen Signal-Bars und den Trend oder Range-Ort drumherum noch mal neu beurteilen.',
    ],
    callout: 'Ein paar späte Ticks können die Aussage des Schlusses ändern.',
    diagramTitle: 'Gleiche Spanne, schwächerer Bärenschluss',
    caption: 'Zwei schematische Schlusszustände teilen Hoch und Tief; der spätere Schluss liegt weiter vom Tief entfernt.',
    observations: ['Ein unterer Schatten zeigt Rückkauf vom Extrem.', 'Die Verkaufsstärke wird am geschlossenen Körper gemessen.', 'Der Kontext entscheidet, ob der Plan trotzdem trägt.'],
    prompt: 'Der letzte Preis springt kurz vor Ende vom Tief des möglichen Short-Signals weg. Welche Reaktion ist sinnvoll?',
    answers: [['Den Bar weiterhin nach seinem früheren Zwischenstand beurteilen.', 'Der Zwischenstand ist kein Schlusskurs.'], ['Die geplante Auslösung und die Signalqualität mit dem fertigen Bar neu prüfen.', 'Richtig. Die Schlusslage ist Teil der Begründung.'], ['Jeden bärischen Plan für den Rest des Tages verbieten.', 'Ein schwächeres Signal bedeutet kein pauschales Handelsverbot.']], correct: 1,
    takeaways: ['Schlusslage kann sich ohne neues Hoch oder Tief ändern.', 'Signalstärke nach dem fertigen Bar beurteilen.', 'Kein starres Urteil aus wenigen Ticks allein ableiten.'],
  },
  {
    number: 5, title: 'Ein vorschnell enger Stop kann einen guten Trade beenden',
    summary: 'Offener Gewinn und ein unfertiger Gegenbar sind kein Ersatz für den ursprünglichen Schutzplan.',
    section: 'Zu früher Ausstieg',
    anchors: ['Kapitel 8 · zweiter häufiger Fehler', 'Vorzeitig nachgezogener Schutz-Stop', 'Später Rücksprung des Gegenbars'],
    scenario: 'c08-premature-stop',
    paragraphs: [
      'Ein Einstieg läuft ein paar Ticks ins Plus, erreicht ein kleines Teilziel aber noch nicht. Gleichzeitig sieht der aktuelle Bar kurz vor Schluss nach einer Gegenbewegung aus. Da wächst die Versuchung, den Schutz knapp unter diesen noch laufenden Bar zu ziehen.',
      'Ein kurzer Abwärtsstich kann den engen Stop auslösen. Schließt der Bar danach höher und steigt der nächste weiter, hat nicht der Einstieg versagt, sondern die spontane Änderung des ursprünglichen Plans. Den größeren strukturellen Schutz hätte der Stich vielleicht nie erreicht.',
      'Einen Stop darfst du anpassen, wenn dein Plan dafür vorher eine klare Bedingung nennt. Der unfertige Eindruck eines Gegenbars kurz vor Ende ist aber keine verlässliche Bedingung. Beurteile zuerst den Schluss und die ganze Marktstruktur.',
    ],
    callout: 'Ein laufender Gegenbar rechtfertigt nicht automatisch einen neuen Stop.',
    diagramTitle: 'Enger Zwischen-Stop und ursprünglicher Schutz',
    caption: 'Das Lehrschema zeigt einen kurz berührten engen Stop neben einem weiter entfernten, strukturell begründeten Schutzpunkt.',
    observations: ['Offener Gewinn kann zu hektischem Nachziehen verleiten.', 'Ein kurzer Stich ändert nicht zwangsläufig den fertigen Bar.', 'Der ursprüngliche Schutz bleibt eine bewusste Planentscheidung.'],
    prompt: 'Warum kann ein Stop direkt unter einem noch laufenden Gegenbar problematisch sein?',
    answers: [['Weil Stops grundsätzlich nie verändert werden dürfen.', 'Es geht um eine unbegründete spontane Änderung, nicht um ein allgemeines Verbot.'], ['Weil ein Zwischenstich den Trade beenden kann, obwohl das fertige Signal anders aussieht.', 'Richtig. Der unfertige Bar kann die geplante Struktur noch nicht ersetzen.'], ['Weil ein enger Stop immer einen höheren Gewinn erzeugt.', 'Ein enger Stop erhöht auch das Risiko eines unnötigen Ausstiegs.']], correct: 1,
    takeaways: ['Stop-Regel vor dem Trade festlegen.', 'Laufenden Gegenbar nicht als fertige Umkehr lesen.', 'Guten Einstieg nicht aus Nervosität heraus aufgeben.'],
  },
  {
    number: 6, title: 'Die ersten Schlüsse verändern den Halteplan',
    summary: 'Entry-Bar und Folgebars zeigen, ob eher ein kleiner Gewinn oder ein größerer Swing plausibel wird.',
    section: 'Entry-Bar und Anschluss',
    anchors: ['Kapitel 8 · Schluss des Entry-Bars', 'Stärkerer Körper bis zum Schluss', 'Anschluss in den nächsten Bars'],
    scenario: 'c08-entry-followthrough',
    paragraphs: [
      'Nach der Auslösung hört das Beobachten nicht auf. Ein Entry-Bar kann sich in den letzten Sekunden von einem schwachen zu einem deutlich stärkeren Körper entwickeln. Der Schluss zeigt dann mehr Kontrolle der Einstiegsseite, als vorher zu sehen war.',
      'Schließen auch die nächsten ein oder zwei Bars überzeugend in dieselbe Richtung, kannst du eher einen Teil der Position für eine größere Bewegung halten. Schwache Schlüsse, breite Überlappung und fehlender Anschluss sprechen dagegen für vorsichtigeres Management.',
      'Dabei geht es um den vorher festgelegten Umgang mit Teilgewinnen und Restposition, nicht um die Gewissheit einer Fortsetzung. Positionsgröße, Stop und Ziel müssen zu beiden Varianten passen.',
    ],
    callout: 'Nicht nur der Signal-Bar zählt: Auch die ersten Folgeschlüsse gehören dazu.',
    diagramTitle: 'Starker und schwacher Anschluss',
    caption: 'Zwei selbst entworfene Folgen vergleichen hoch schließende Entry- und Folgebars mit überlappenden Bars und schwachen Schlüssen.',
    observations: ['Ein wachsender Körper kann die Position stärken.', 'Mehrere Schlüsse liefern mehr Evidenz als ein einzelner Bar.', 'Halten bleibt eine Risikowahl, keine Prognose.'],
    prompt: 'Ein Long-Entry-Bar und zwei Folgebars schließen jeweils stark. Was ändert sich am ehesten?',
    answers: [['Man darf den Schutzpunkt vollständig weglassen.', 'Starke Schlüsse ersetzen keinen Schutzplan.'], ['Jede Teilposition muss sofort verkauft werden.', 'Mehr Anschluss kann gerade das Halten eines Teils stützen.'], ['Ein geplanter Swing-Anteil wird plausibler, sofern das Risiko passt.', 'Richtig. Die Schlussfolge verbessert die Evidenz für eine Fortsetzung.']], correct: 2,
    takeaways: ['Entry-Schluss und frühe Folgeschlüsse gesondert prüfen.', 'Management auf sichtbare Stärke abstimmen.', 'Risiko bleibt auch bei gutem Anschluss bestehen.'],
  },
  {
    number: 7, title: 'Der Schluss ist auch außerhalb des Kerzencharts sichtbar',
    summary: 'Schlussbasierte Liniencharts verdichten jeden Bar auf genau einen Preis.',
    section: 'Schluss als gemeinsamer Bezug',
    anchors: ['Kapitel 8 · Schlusskurs in Liniencharts', 'Schlussbasierte Darstellung', 'Institutionelle Betrachtung von Wert und Preis'],
    scenario: 'c08-close-line',
    paragraphs: [
      'Nicht jeder liest Kerzen mit Hoch, Tief und Körper. Ein einfacher Linienchart verbindet nur die Schlusswerte der Bars. Ein langer Schatten kann dort unsichtbar bleiben, während ein neuer Schlussbereich sofort in die Linie eingeht.',
      'Dazu kommen institutionelle Entscheidungen, bei denen der Schluss als beobachteter Preis Gewicht hat. Daraus folgt nicht, dass alle Großen gleich handeln. Für dein Chartlesen erklärt es aber, warum viele Methoden das Ende eines Bars gemeinsam im Blick haben.',
      'Nimm den Linienblick als Ergänzung: Er zeigt, welche Bewegung in den Schlüssen wirklich fortgesetzt wurde. Die Kerze verrät dir weiterhin, wie der Weg dorthin aussah und wo der Markt an Extremen zurückgewiesen wurde.',
    ],
    callout: 'Schatten zeigen den Weg; der Schluss markiert den Endpunkt dieses Bars.',
    diagramTitle: 'Kerzen mit Schatten und Linie der Schlüsse',
    caption: 'Eigenes Vergleichsschema: Dieselben frei erfundenen Bars als OHLC-Folge und als verbundene Schlusswerte.',
    observations: ['Ein Linienchart enthält keine Hoch- und Tiefschatten.', 'Mehrere starke Schlüsse bilden dort einen klaren Verlauf.', 'Beide Darstellungen ergänzen sich.'],
    prompt: 'Welche Information geht verloren, wenn ein Chart nur die Schlüsse verbindet?',
    answers: [['Die Reihenfolge der Schlüsse.', 'Gerade diese Folge bildet die Linie.'], ['Die innerhalb der Bars erreichten Hochs und Tiefs.', 'Richtig. Der Linienchart zeigt nur die Endpunkte.'], ['Jede Information über die Richtung.', 'Die Folge der Schlüsse zeigt weiterhin Richtung.']], correct: 1,
    takeaways: ['Schlusskurse können eine eigene Trendfolge zeigen.', 'Kerzenschwänze bleiben für Extremtests wichtig.', 'Keine einheitliche Absicht aller Marktteilnehmer unterstellen.'],
  },
];

export const chapterEightFoundationLessons = drafts.map(chapterEightLesson);
