import { chapterTenLesson, type ChapterTenDraft } from './chapter-10-model';

// Reihenfolge der einleitenden Argumente im Buchkapitel; frei formuliert.
const drafts: ChapterTenDraft[] = [
  {
    number: 1, title: 'Warum ein zweiter Versuch Gewicht hat',
    summary: 'Nach einem misslungenen ersten Umkehrversuch kann ein erneuter Test mehr Trader überzeugen.',
    section: 'Grundidee · Hoch und Tief',
    anchors: ['Kapitel 10 · erster Absatz', 'Zweiter Umkehrversuch am Tief', 'Gleiches Prinzip an einem Hoch'],
    scenario: 'c10-second-at-extremes',
    paragraphs: [
      'Ein erster Versuch, ein fallendes Marktstück zu drehen, trifft oft noch auf Verkäufer. Hält das Tief aber und wagen Käufer nach einem Rücklauf einen zweiten Anlauf, liegt mehr beobachtete Information vor: Der Markt hat das alte Preisgebiet noch einmal geprüft.',
      'Diese Logik gilt für beide Seiten. Ein zweiter Kaufversuch an einem Boden und ein zweiter Verkaufsversuch nahe einem Hoch können mehr Überzeugung auslösen als der jeweilige erste. „Zweiter Entry“ beschreibt die erneute Handelsgelegenheit, nicht bloß den zweiten Bar einer beliebigen Folge.',
      'Die Wiederholung allein reicht nicht. Ort, Stärke des vorangehenden Trends, Qualität des Signal-Bars und Reaktion nach der Auslösung bestimmen, ob der erneute Versuch überhaupt sinnvoll ist. Im Schaubild werden nur die beiden Entscheidungsstellen markiert, keine Trefferquote versprochen.',
    ],
    callout: 'Erster Versuch, Rücklauf, erneuter Versuch: Lies die ganze Folge.',
    diagramTitle: 'Zwei Versuche am Hoch und am Tief',
    caption: 'Eigene schematische Gegenüberstellung: links zwei Kaufversuche nach einem Tief, rechts zwei Verkaufsversuche nach einem Hoch.',
    observations: ['Der zweite Versuch folgt einer sichtbaren ersten Reaktion.', 'Hoch und Tief funktionieren spiegelbildlich.', 'Ein zweites Signal braucht weiterhin Anschluss.'],
    prompt: 'Was macht aus einer bloßen Kerze einen zweiten Umkehrversuch?',
    answers: [['Ein erster Versuch, eine Zwischenreaktion und ein erneuter Versuch am relevanten Bereich.', 'Richtig. Die Abfolge und ihr Marktort machen die zweite Gelegenheit aus.'], ['Dass genau zwei Minuten vergangen sind.', 'Die Zeit allein definiert keinen zweiten Entry.'], ['Dass der zweite Bar zwangsläufig profitabel wird.', 'Auch ein zweites Signal kann scheitern.']], correct: 0,
    takeaways: ['Zweiten Entry als Abfolge statt isolierten Bar lesen.', 'Käufer und Verkäufer spiegelbildlich prüfen.', 'Ort und Folgereaktion bleiben entscheidend.'],
  },
  {
    number: 2, title: 'Mehr Bestätigung ist keine Garantie',
    summary: 'Zweite Entries werden häufig gegenüber ersten bevorzugt, aber das Umfeld entscheidet.',
    section: 'Grundidee · Wahrscheinlichkeit',
    anchors: ['Kapitel 10 · erster Absatz', 'Vergleich erster und zweiter Entry', 'Wahrscheinlichkeit statt Gewissheit'],
    scenario: 'c10-first-second',
    paragraphs: [
      'Wer den ersten Umkehrversuch nimmt, handelt gegen die noch bestehende Trägheit des Marktes. Beim zweiten sieht er bereits, wie der erste endete und ob die bisherige Richtung bei einem erneuten Schub noch dieselbe Kraft zeigt. Diese Zusatzinformation kann den Versuch besser machen.',
      'Zweite Einstiege gelten im Allgemeinen als chancenreicher als erste. Das ist eine qualitative Einordnung, keine feste Prozentzahl. Ein zweites Signal in einem engen Kanal mit starkem Druck gegen den eigenen Trade kann weiterhin sehr schlecht sein.',
      'Vergleiche deshalb zwei Fragen getrennt: Ist dies tatsächlich der erneute Versuch? Und hat sich die Kräfteverteilung seit dem ersten Versuch verbessert? Erst aus beidem entsteht eine begründete Entscheidung; ein bloßes „Nummer zwei“ ersetzt keine Chartlektüre.',
    ],
    callout: 'Zählen hilft, aber die Stärke der Gegenseite bleibt wichtiger.',
    diagramTitle: 'Erster Versuch gegen anhaltenden Druck',
    caption: 'Zwei frei erfundene Folgen zeigen ein isoliertes erstes Signal und einen erneuten Versuch nach einer sichtbaren Schwächung der alten Richtung.',
    observations: ['Beim ersten Versuch dominiert die alte Richtung noch.', 'Beim zweiten ist eine weitere Reaktion bekannt.', 'Der Trend kann trotzdem fortgesetzt werden.'],
    prompt: 'Was bedeutet „zweite Entries sind oft besser“ in diesem Zusammenhang?',
    answers: [['Jede zweite Kerze muss gekauft oder verkauft werden.', 'Die Zahl allein erzeugt kein Setup.'], ['Zusätzliche Reaktion kann helfen; Momentum und Kontext bleiben zu prüfen.', 'Richtig. Der Vorteil ist bedingt, nicht automatisch.'], ['Der zweite Einstieg hat immer einen kleineren Stop.', 'Seine Stop-Distanz ergibt sich aus der Struktur und kann auch größer sein.']], correct: 1,
    takeaways: ['Zusätzliche Information gegenüber dem ersten Versuch nutzen.', 'Keine feste Erfolgsquote aus der Reihenfolge ableiten.', 'Gegendruck und Signalqualität gemeinsam bewerten.'],
  },
  {
    number: 3, title: 'Ein auffällig günstiger zweiter Preis warnt',
    summary: 'Ein guter zweiter Entry kostet oft mindestens so viel wie der erste.',
    section: 'Einstiegspreis · Warnsignal',
    anchors: ['Kapitel 10 · zweiter Absatz', 'Gleicher oder ungünstigerer zweiter Preis', 'Besserer Preis als mögliche Falle'],
    scenario: 'c10-better-price',
    paragraphs: [
      'Ein Trader wartet, um nach dem ersten Versuch mehr Sicherheit zu bekommen. Wenn die Käufer tatsächlich stärker werden, erhält der spätere Käufer den Einstieg gewöhnlich nicht billiger als die Frühen. Für einen Short gilt die umgekehrte Preisrichtung: ein späterer Verkäufer bekommt häufig keinen höheren Verkaufspreis.',
      'Bietet der Markt beim zweiten Long-Versuch dennoch einen tieferen Preis, fragt man nach dem Grund. Vielleicht ist der Rücklauf stärker als gedacht und das angeblich verbesserte Signal steckt mitten in weiterem Verkaufsdruck. Der günstigere Fill ist dann ein Hinweis auf eine übersehene Schwäche.',
      'Das ist eine Warnheuristik, kein Verbot jedes tieferen Kaufs. Prüfe die Bars vor dem Signal und den Ort des Stops. Wenn sie nicht zur Umkehrthese passen, lässt du den vermeintlichen Rabatt aus, statt die bessere Zahl als Beweis für Qualität zu nehmen.',
    ],
    callout: 'Ein günstiger Preis kann aus einem stärkeren Gegentrend stammen.',
    diagramTitle: 'Zweiter Long: gleicher, teurer oder billiger?',
    caption: 'Eigenes Vergleichsschema markiert zwei Kaufversuche; im rechten Feld liegt der zweite Auslösungspreis auffällig tiefer.',
    observations: ['Bestätigung kostet bei echter Stärke oft etwas Preis.', 'Billiger kann mehr Abwärtsdruck bedeuten.', 'Preisqualität und Signalqualität sind verschieden.'],
    prompt: 'Warum ist ein billigerer zweiter Long nach einem ersten Versuch verdächtig?',
    answers: [['Weil ein kleiner Preis stets mehr Risiko in Euro erzeugt.', 'Das folgt nicht allein aus dem Preis.'], ['Weil es mathematisch keinen zweiten Entry unter dem ersten geben kann.', 'Es kann ihn geben; Die Lektion mahnt zur Prüfung.'], ['Weil die Verkäufer offenbar noch genügend Kraft für einen tieferen Rücklauf haben könnten.', 'Richtig. Der günstige Fill kann eine schwache Umkehrthese verraten.']], correct: 2,
    takeaways: ['Long- und Short-Preisrichtung sauber spiegeln.', 'Günstigen Fill nicht mit gutem Setup verwechseln.', 'Vorgeschichte vor einer zweiten Auslösung erneut lesen.'],
  },
  {
    number: 4, title: 'Kürzere Charts sind oft schon früher dabei',
    summary: 'Die Fünf-Minuten-Entry ist nicht zwingend die erste Teilnahme des Marktes.',
    section: 'Einstiegspreis · Zeitebenen',
    anchors: ['Kapitel 10 · dritter Absatz', 'Frühere Entries auf kleinerer Zeitebene', 'Späterer Einstieg im Fünf-Minuten-Chart'],
    scenario: 'c10-smaller-timeframe',
    paragraphs: [
      'Ein Signal auf dem Fünf-Minuten-Chart kann für dort Wartende neu sein, während andere auf kleineren Zeitebenen den zweiten Versuch schon vorher sehen und handeln. Dadurch bewegen frühe Orders den Preis gelegentlich bereits in die erwartete Richtung.',
      'Wenn die spätere Fünf-Minuten-Order ausgeführt wird, fühlt sich ein schlechterer Kaufpreis zunächst ärgerlich an. Er ist häufig mit tatsächlich vorhandener Nachfrage vereinbar. Ein überraschend leichter, billiger Fill kann dagegen anzeigen, dass die erwartete Käuferreaktion ausgeblieben ist.',
      'Daraus folgt kein Auftrag, zwischen Zeitebenen hektisch hin und her zu springen. Nutze den Arbeitschart konsistent und verstehe nur, dass andere Trader früher beteiligt sein können. Aus einem Fill allein lässt sich das Ergebnis eines Trades nicht sicher ableiten.',
    ],
    callout: 'Ein späterer Preis kann der Preis für zusätzliche beobachtete Stärke sein.',
    diagramTitle: 'Kleinerer Chart, früherer Versuch',
    caption: 'Synthetische Gegenüberstellung einer feineren und einer zusammengefassten Barfolge; frühe Reaktionen sind links bereits sichtbar.',
    observations: ['Mehr kurze Bars zeigen Zwischenversuche.', 'Der größere Bar fasst sie später zusammen.', 'Ein Fill ist ein Kontextsignal, keine Prognose.'],
    prompt: 'Warum kann der Einstieg auf dem Fünf-Minuten-Chart etwas ungünstiger ausfallen?',
    answers: [['Andere Trader haben die gleiche Idee auf kleineren Bars bereits gehandelt.', 'Richtig. Die Bewegung kann vor dem späteren Signal begonnen haben.'], ['Weil Fünf-Minuten-Bars nie Hochs und Tiefs zeigen.', 'Sie enthalten weiterhin Hoch, Tief, Eröffnung und Schluss.'], ['Weil ein schlechterer Fill immer zu einem Verlust führt.', 'Die Lektion beschreibt gerade die gegenteilige Möglichkeit.']], correct: 0,
    takeaways: ['Eine Zeitebene ist nicht die ganze Marktteilnahme.', 'Schlechterer Fill kann mit stärkerem Signal einhergehen.', 'Den eigenen Ausführungsplan beibehalten.'],
  },
  {
    number: 5, title: 'Gegen starken Trend erst den erneuten Versuch prüfen',
    summary: 'Der erste Umkehrversuch nach kräftigen Trendbars ist oft verfrüht.',
    section: 'Gegentrend · Geduld',
    anchors: ['Kapitel 10 · vierter Absatz', 'Mehrere kräftige Trendbars vor Gegen-Entry', 'Ersten Versuch auslassen und zweiten abwarten'],
    scenario: 'c10-countertrend-wait',
    paragraphs: [
      'Nach mehreren kräftigen Bullenbars ist ein erster bärischer Reversal-Bar noch kein Beweis für einen neuen Abwärtstrend. Die Käufer haben gerade sichtbar gedrückt. Als Beispiele für zu viel Momentum gegen einen frühen Short gelten etwa vier aufeinanderfolgende bullische Trendbars oder wenige besonders große Bars.',
      'Sein Ablauf ist präzise: Den ersten Gegenversuch als Beobachtung behandeln, keinen Gegentrend-Trade nehmen, die Wiederaufnahme des Trends für ein oder zwei Bars ansehen und erst bei einem erneuten Umkehrversuch einen Entry erwägen. Bei stark fallenden Märkten gilt dieselbe Logik für einen frühen Long.',
      'Entsteht kein zweites Signal, gibt es keinen Trade aus diesem Plan. Die Geduld schützt vor dem Reflex, jede erste Gegenkerze als Trendende zu behandeln. Selbst das zweite Signal benötigt einen passenden Ort, eine Auslösung und einen begrenzten Schutz.',
    ],
    callout: 'Nicht der erste Gegenbar, sondern der zweite ernsthafte Versuch ist der Prüfpunkt.',
    diagramTitle: 'Trenddruck, erste Pause und zweiter Versuch',
    caption: 'Zwei eigenständige schematische Richtungen zeigen zunächst mehrere Trendbars und danach einen ersten und zweiten Gegentrend-Versuch.',
    observations: ['Trendbars machen die erste Umkehr riskant.', 'Die alte Richtung wird dazwischen noch einmal getestet.', 'Fehlt Versuch zwei, bleibt der Plan ohne Einstieg.'],
    prompt: 'Ein starker Bullenlauf zeigt den ersten Bärenbar. Was ist hier das sinnvolle Vorgehen?',
    answers: [['Sofort short, weil der erste Bärenbar den Trend beendet.', 'Nach starkem Momentum ist das frühe Gegensignal besonders fragil.'], ['Ersten Versuch auslassen, Trendreaktion und erneute Umkehr abwarten.', 'Richtig. Die beobachtete zweite Chance ist der Prüfpunkt.'], ['Jeden späteren Short für immer ausschließen.', 'Ein zweiter Versuch kann nach neuer Information sinnvoll werden.']], correct: 1,
    takeaways: ['Momentum vor einem Gegentrend-Entry beurteilen.', 'Erste Umkehr als Information statt Zwangseinstieg nutzen.', 'Ohne zweiten Versuch auch keinen zweiten Entry erfinden.'],
  },
];

export const chapterTenFoundationLessons = drafts.map(chapterTenLesson);
